Check if memory is zeroed before creating empty_span in region init
pmem/pmemstream pull request #104
Opened 2022-02-01 11:44 UTC by igchor

Situation when data is non-zero can only happen if there was a crash,
which should be unlikely situation. Because of that, it makes sense
to first check the data - read bandwith for Persistent Memory is
higher than write bandwidth.

2022-02-01 15:52 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/region.c, line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/104#-MupyQVTCJRuE093_raj:-MupyQVTCJRuE093_rak:b-2dkj8b) ([raw file](https://github.com/pmem/pmemstream/blob/44f65bd52385929a95ee776efb3ab658bd5df186/src/region.c#L251)):*
> ```C
> 
> 	if (!util_is_zeroed(pmemstream_offset_to_ptr(stream, tail), remaining_size)) {
> 		span_create_empty(stream, tail, remaining_size - SPAN_EMPTY_METADATA_SIZE);
> ```

hmm did you check if this really speeds up things? and the span_create_empty is not called?

What I think is that perhaps we should check `_is_zeroed` from `tail + SPAN_EMPTY_METADATA_SIZE`, because if we have already an empty span it won't be all zeroes.

Anyway, we require an empty span to exist (e.g. in region_allocate), so shouldn't we create it here...?


<!-- Sent from Reviewable.io -->

2022-02-01 16:25 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[src/region.c, line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/104#-MupyQVTCJRuE093_raj:-Muq3N-w4GRn8fpadKmA:b-cmip27) ([raw file](https://github.com/pmem/pmemstream/blob/44f65bd52385929a95ee776efb3ab658bd5df186/src/region.c#L251)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm did you check if this really speeds up things? and the span_create_empty is not called?

What I think is that perhaps we should check `_is_zeroed` from `tail + SPAN_EMPTY_METADATA_SIZE`, because if we have already an empty span it won't be all zeroes.

Anyway, we require an empty span to exist (e.g. in region_allocate), so shouldn't we create it here...?
</blockquote></details>

@karczex could you benchmark this? ;d

Also, right now empty_span is equal to 8 zeroed-out bytes. so checking util_is_zero also check if there is empty span right after the last entry.


<!-- Sent from Reviewable.io -->

2022-02-01 16:38 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[src/region.c, line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/104#-MupyQVTCJRuE093_raj:-Muq8Tbe67hhArrwvQHX:b-yjf8r2) ([raw file](https://github.com/pmem/pmemstream/blob/44f65bd52385929a95ee776efb3ab658bd5df186/src/region.c#L251)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

@karczex could you benchmark this? ;d

Also, right now empty_span is equal to 8 zeroed-out bytes. so checking util_is_zero also check if there is empty span right after the last entry.
</blockquote></details>

you can just assert/print something in here :wink: but benchmarks, of course, would be nice

`span_create_empty` sets the size of the span, so it's not just 0's, I guess


<!-- Sent from Reviewable.io -->

2022-02-01 16:55 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex and @lukaszstolarczuk)

___
*[src/region.c, line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/104#-MupyQVTCJRuE093_raj:-MuqCgdWDfqFwInf-YWF:b-qu6n94) ([raw file](https://github.com/pmem/pmemstream/blob/44f65bd52385929a95ee776efb3ab658bd5df186/src/region.c#L251)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can just assert/print something in here :wink: but benchmarks, of course, would be nice

`span_create_empty` sets the size of the span, so it's not just 0's, I guess
</blockquote></details>

Good point. Done.


<!-- Sent from Reviewable.io -->

2022-02-02 07:52 UTC, karczex commented
___
*[src/region.c, line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/104#-MupyQVTCJRuE093_raj:-MutPs-IEYbQbdlPrEVI:bobgl6g) ([raw file](https://github.com/pmem/pmemstream/blob/44f65bd52385929a95ee776efb3ab658bd5df186/src/region.c#L251)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Good point. Done.
</blockquote></details>

@igchor I could, but not today.


<!-- Sent from Reviewable.io -->

2022-02-02 08:03 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/common/util.h, line 38 at r2](https://reviewable.io/reviews/pmem/pmemstream/104#-MutQAnnDd1YQg6c1Utx:-MutQAnnDd1YQg6c1Uty:b9dfcp3) ([raw file](https://github.com/pmem/pmemstream/blob/9c30e448bce44adfd5aca002bfe4dbc31c35cd54/src/common/util.h#L38)):*
> ```objc
> }
> 
> static inline int util_is_zeroed(const void *addr, size_t len)
> ```

I get convention of this file, but name `util_is_zeroed()` suggests, you want to check if... well... util is zeroed (whatever it means) :) 

maybe something like: 
`util_memory_chunk_is_zeroed()`
`util_memory_is_zeroed()`


<!-- Sent from Reviewable.io -->

2022-02-02 16:09 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/104)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/common/util.h, line 38 at r2](https://reviewable.io/reviews/pmem/pmemstream/104#-MutQAnnDd1YQg6c1Utx:-MuvBJdH0acGFeKx8Eaq:bictfqb) ([raw file](https://github.com/pmem/pmemstream/blob/9c30e448bce44adfd5aca002bfe4dbc31c35cd54/src/common/util.h#L38)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I get convention of this file, but name `util_is_zeroed()` suggests, you want to check if... well... util is zeroed (whatever it means) :) 

maybe something like: 
`util_memory_chunk_is_zeroed()`
`util_memory_is_zeroed()`
</blockquote></details>

I gues we should talk about what strategy we want to have regarding utils. Should we just copy the code from PDMK in unchanged form or should we refactor it if we want?

I think that until we have this code on dev-utils-kit it would be better to not modify it - so there's less work on figuring out which version is the latest.


<!-- Sent from Reviewable.io -->

2022-02-23 14:06 UTC, closed without merging