Check if stream is not NULL and offset is not above stream_size
pmem/pmemstream pull request #122
Opened 2022-02-14 12:59 UTC by Karolina002

in pmemstream_offset_to_ptr

Fixes segmentation fault in pmemstream_offset_to_ptr
and assertion fault in span_get_entry_runtime and span_get_region_runtime

Fixes: #98 #99 #100

2022-02-14 13:06 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/122)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/122#-MvsKcvS9qRW9h5QF01C):*
one commit should rather fix one issue (of course if it's possible to split them)


<!-- Sent from Reviewable.io -->

2022-02-15 10:05 UTC, karczex requested changes
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/122)* status: 3 of 11 files reviewed, 5 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[src/region.c, line 243 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-MvwaPgA6W0B3x8i7AKv:-MvwaPgA6W0B3x8i7AKw:bmbxou6) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/region.c#L243)):*
> ```C
> 	struct span_runtime *region_rt;
> 	if (span_get_region_runtime(stream, region.offset, &region_rt) == -1) {
> 		return;
> ```

This function is called in `region_runtime_initialize_clear_locked()`. If it fail silently, you would end up with region runtime in dirty state while `region_runtime_initialize_clear_locked()` succeed. 
___
*[src/span.c, line 92 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-Mvwp4bCE5yTALqO5xl4:-MvwgMhG9ZftIGWQHOWl:boxljsb) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/span.c#L92)):*
> ```C
> 		return -1;
> 
> 	struct span_runtime *srt = (struct span_runtime *)calloc(1, sizeof(*srt));
> ```

1. I didn't check very deeply, but it's probably memory leak. Do you ever free this memory? 

1. `calloc()` may fail
```C
if (!srt) {
    return -1
}
```
___
*[src/span.c, line 147 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-Mvwlmux5lZBUxY9rM0w:-Mvwlmux5lZBUxY9rM0x:bymacfq) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/span.c#L147)):*
> ```C
> {
> 	const span_bytes *span = span_offset_to_span_ptr(stream, offset);
> 	struct span_runtime *srt = (struct span_runtime *)calloc(1, sizeof(*srt));
> ```

As I can see `*srt` is used only in `default` case; so instead of allocating it here and doing (error prone) free in every case, just create function  `span_get_unknown_runtime()` similar to other runtime  getters. 

Anyhow, it's probably also memory leak.
___
*[src/span.c, line 169 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-MvwlSjm5kwBwyyEuL_H:-MvwlSjm5kwBwyyEuL_I:b-gsw4iy) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/span.c#L169)):*
> ```C
> 			srt->data_offset = offset;
> 			srt->total_size = 0;
> 			*runtime = srt;
> ```

as SPAN_UNKNOWNS is valid span type, you should return 0 from it.


<!-- Sent from Reviewable.io -->

2022-02-15 10:33 UTC, igchor requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/122)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[src/span.c, line 89 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-MvwtuYi9slvnWyyuhsr:-MvwtuYi9slvnWyyuhss:b-6amxv3) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/span.c#L89)):*
> ```C
> 	const span_bytes *span = span_offset_to_span_ptr(stream, offset);
> 
> 	if (!span)
> ```

In general, I belive the error handling should be done in the upper layer - before we call span_get_*. The reason is that we might now have enough information here - the offset which we pass here might be valid or invalid depending on context (see e.g iterator.c)

I would prefer to move checking of stream != NULL to the API functions (the ones which start with pmemstream_) - we can have this at the beginning of each function. This will make it easier to implement and maintain. We also don't need to change the return value of span_get_* functions in that case.


<!-- Sent from Reviewable.io -->

2022-02-15 11:27 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/122)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @lukaszstolarczuk, and @pbalcer)

___
*[src/span.c, line 89 at r2](https://reviewable.io/reviews/pmem/pmemstream/122#-MvwtuYi9slvnWyyuhsr:-Mvx6Q6E5Mj6EvhQcMB1:b66z93p) ([raw file](https://github.com/pmem/pmemstream/blob/ec3c790aebbfb550592dea476e72c10e77e3e0d9/src/span.c#L89)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

In general, I belive the error handling should be done in the upper layer - before we call span_get_*. The reason is that we might now have enough information here - the offset which we pass here might be valid or invalid depending on context (see e.g iterator.c)

I would prefer to move checking of stream != NULL to the API functions (the ones which start with pmemstream_) - we can have this at the beginning of each function. This will make it easier to implement and maintain. We also don't need to change the return value of span_get_* functions in that case.
</blockquote></details>

garbage in/garbage out. It's on the user to make sure that the provided arguments are correct. It's almost never a good idea to null-check input arguments just to return an error from a function. At most, that should be a debug assert. When provided with erroneous (not external) input, software should die as early as possible so that debugging is easier. As you say, Igor - errors should be handled (e.g., propagated up) in the layer that they originate from.


<!-- Sent from Reviewable.io -->

2022-02-16 09:09 UTC, closed without merging