Don't compile debug function in release mode
pmem/pmemstream pull request #129
Opened 2022-02-17 10:50 UTC by KFilipek

This PR uses NDEBUG macro to avoid compilation of some functions in release mode.﻿

2022-02-17 11:04 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6Lb4FEb1DA63JrTOB):*
functions
___
*[examples/03_reserve_publish/main.cpp, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KnHM3TZTycDDpS_k:-Mw6KnHM3TZTycDDpS_l:b-wy3xa4) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L35)):*
> ```cpp
> 	*map = example_map_open(path, EXAMPLE_STREAM_SIZE);
> 	if (*map == NULL) {
> 		throw std::runtime_error("Error from example_map_open!");
> ```

why these changes within this commit?
___
*[examples/03_reserve_publish/main.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KsNSCbbAxY0CebzF:-Mw6KsNSCbbAxY0CebzG:b-zfwoh5) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L67)):*
> ```cpp
> 
> 	if (read_entry != my_entry) {
> 		std::cout << "Stored entry " << read_entry.data << " differs from original entry " << my_entry.data
> ```

why `printf` -> `cout`?


<!-- Sent from Reviewable.io -->

2022-02-17 11:17 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6Lb4FEb1DA63JrTOB):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

functions
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KnHM3TZTycDDpS_k:-Mw6N8HfCZXazPSRuRY7:bd8drhm) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why these changes within this commit?
</blockquote></details>

I don't want to add NDEBUG macro when it's not necessary, these checks should be done in both, release and debug. Last thing, original function does not return any value, so I've decided to use exceptions. 
___
*[examples/03_reserve_publish/main.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KsNSCbbAxY0CebzF:-Mw6NuvIAXuq8r3rtBeE:b-wv1noy) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `printf` -> `cout`?
</blockquote></details>

The only difference is that cout/cerr abstracts from types. When you change uint64_t into, maybe, uint32_t it will works. Print function have predefined formatting string.


<!-- Sent from Reviewable.io -->

2022-02-17 11:27 UTC, igchor requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6Pf3M6fEYZoBeEtjZ:-Mw6Pf3M6fEYZoBeEtj_:bar11fu) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L35)):*
> ```cpp
> 	*map = example_map_open(path, EXAMPLE_STREAM_SIZE);
> 	if (*map == NULL) {
> 		throw std::runtime_error("Error from example_map_open!");
> ```

Adding the exceptions a bit problematic because now, we have leaks. If some operation fails and we throw and exception the stream/pmem2 or any other resources might now be destroyed. For asserts this was not a problem since they called abort(), leading to immediate termination.

Maybe instead of exceptions just define assert to be present also in Release:

```
#define ASSERT(condition) ((void)((cnd) || (abort()))
```

Or something similar?
___
*[examples/03_reserve_publish/main.cpp, line 96 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6PT1Q20jOSzMqajkl:-Mw6PT1Q20jOSzMqajkm:b4t0tt9) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L96)):*
> ```cpp
> 		initialize_stream(argv[1], &map, &stream, &region);
> 	} catch (std::runtime_error &e) {
> 		std::cout << e.what() << std::endl;
> ```

shouldn't you exit in that case?


<!-- Sent from Reviewable.io -->

2022-02-17 11:33 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[examples/03_reserve_publish/main.cpp, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KnHM3TZTycDDpS_k:-Mw6RayCEtpu2nDWY9uX:b79878s) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I don't want to add NDEBUG macro when it's not necessary, these checks should be done in both, release and debug. Last thing, original function does not return any value, so I've decided to use exceptions. 
</blockquote></details>

ok, make sense, but you **can** return some value then :wink: 
___
*[examples/03_reserve_publish/main.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KsNSCbbAxY0CebzF:-Mw6Rjvk4fhnesUxDHxX:b-h2f5d7) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L67)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

The only difference is that cout/cerr abstracts from types. When you change uint64_t into, maybe, uint32_t it will works. Print function have predefined formatting string.
</blockquote></details>

hmm, but we use printf's in other examples as well... so rather random change :wink: 

and if you want to introduce this change, it should definitely be in a separate commit
___
*[examples/03_reserve_publish/main.cpp, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6S3834qILHUcd6Lcn:-Mw6S3834qILHUcd6Lco:b-bmgqiv) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L7)):*
> ```cpp
> #include "libpmemstream.h"
> 
> #include <cassert>
> ```

cassert should be gone, with the current approach


<!-- Sent from Reviewable.io -->

2022-02-17 17:04 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KnHM3TZTycDDpS_k:-Mw7d2Vw5zub07GU9xoW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, make sense, but you **can** return some value then :wink: 
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6S3834qILHUcd6Lcn:-Mw7d1Go7_lJNE_vPCj4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

cassert should be gone, with the current approach
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6Pf3M6fEYZoBeEtjZ:-Mw7d3JTCov7YKZBVxnL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L35)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Adding the exceptions a bit problematic because now, we have leaks. If some operation fails and we throw and exception the stream/pmem2 or any other resources might now be destroyed. For asserts this was not a problem since they called abort(), leading to immediate termination.

Maybe instead of exceptions just define assert to be present also in Release:

```
#define ASSERT(condition) ((void)((cnd) || (abort()))
```

Or something similar?
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 96 at r2](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6PT1Q20jOSzMqajkl:-Mw7d7SDCgZ4dp-QhKc4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/aed11711ae4fc72c45b66cafaa2878015a20a054/examples/03_reserve_publish/main.cpp#L96)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't you exit in that case?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-18 08:20 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/03_reserve_publish/main.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAuRPYCcEsw4xsw5H0:-MwAuRPYCcEsw4xsw5H1:b-noe6qw) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L17)):*
> ```cpp
> #define ASSERT(expr)                                                                                                   \
> 	if (!(expr)) {                                                                                                 \
> 		std::cout << __FILE__ << __LINE__ << std::endl;                                                        \
> ```

perhaps add  __func__ ?
___
*[examples/03_reserve_publish/main.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAuXlF2_1YvjjLpigB:-MwAuXlF2_1YvjjLpigC:b-z70u5q) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L17)):*
> ```cpp
> #define ASSERT(expr)                                                                                                   \
> 	if (!(expr)) {                                                                                                 \
> 		std::cout << __FILE__ << __LINE__ << std::endl;                                                        \
> ```

make it better formatted, e.g. "file (func):line" or something like that
___
*[examples/03_reserve_publish/main.cpp, line 46 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAtrLh0QWkUcYuxz3Y:-MwAtrLh0QWkUcYuxz3Z:b-r0ohl2) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L46)):*
> ```cpp
> 	ret = pmemstream_region_allocate(*stream, 10240, region);
> 	ASSERT(ret == 0);
> 	(void)ret;
> ```

do you need this? it's just an example
___
*[examples/03_reserve_publish/main.cpp, line 58 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAtvXPC7Bip26iOIMK:-MwAtvXPC7Bip26iOIML:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L58)):*
> ```cpp
> 	ASSERT(ret == 0);
> 	pmemstream_entry_iterator_delete(&eiter);
> 	(void)ret;
> ```

.


<!-- Sent from Reviewable.io -->

2022-02-18 10:54 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KsNSCbbAxY0CebzF:-MwBShsb4eEvheS8FGFv:bb76mu4) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm, but we use printf's in other examples as well... so rather random change :wink: 

and if you want to introduce this change, it should definitely be in a separate commit
</blockquote></details>

Why?
___
*[examples/03_reserve_publish/main.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAuRPYCcEsw4xsw5H0:-MwBQx6m3xk8jYJUvY8b:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add  __func__ ?
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAuXlF2_1YvjjLpigB:-MwBQxP2BnyeZ1XZyYaB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it better formatted, e.g. "file (func):line" or something like that
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 46 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAtrLh0QWkUcYuxz3Y:-MwBR3FXEi6pQ2BHbW6D:bjvs4l6) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this? it's just an example
</blockquote></details>

Compilation in release causes warning "defined but not used". This `(void)variable` is a typical solution for that case. Another solution is to reimplement whole example and change error handling, here we get also some leaks, so it could be done as another PR. 


<!-- Sent from Reviewable.io -->

2022-02-18 11:01 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwBTgHp0FYP3s_owfBO:-MwBTgHp0FYP3s_owfBP:bqy7f9r) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L15)):*
> ```cpp
> #include <libpmem2.h>
> 
> #define ASSERT(expr)                                                                                                   \
> ```

You should probably wrap this into do/while: https://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block.
___
*[examples/03_reserve_publish/main.cpp, line 46 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAtrLh0QWkUcYuxz3Y:-MwBTnBd3ClI_xKBr6aj:bshrlt4) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L46)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Compilation in release causes warning "defined but not used". This `(void)variable` is a typical solution for that case. Another solution is to reimplement whole example and change error handling, here we get also some leaks, so it could be done as another PR. 
</blockquote></details>

Can't we make this suppresion insde ASSERT macro? Or define NONDEBUG version of assert which does this?

Or see pmdk: https://github.com/pmem/pmdk/blob/master/src/core/out.h#L152


<!-- Sent from Reviewable.io -->

2022-02-18 13:04 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/03_reserve_publish/main.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/129#-Mw6KsNSCbbAxY0CebzF:-MwBvSod1NTZOxxYRYXd:biezgbj) ([raw file](https://github.com/pmem/pmemstream/blob/f583e8af312bddfd613544883b6d1f08ee8ff0b8/examples/03_reserve_publish/main.cpp#L67)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

because commit says "Don't compile debug functions in release mode" and you change printf's to cout's :smile: 
___
*[examples/03_reserve_publish/main.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/129#-MwAuXlF2_1YvjjLpigB:-MwBuTrz2eys-my1hWSP:bb7p5eq) ([raw file](https://github.com/pmem/pmemstream/blob/b4f29ac06cb8ae275bd91fa5f47eab66711b7e9d/examples/03_reserve_publish/main.cpp#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!


<!-- Sent from Reviewable.io -->

2022-02-18 13:58 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/129#-:-MwC74EmAczxFoHv1UGQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-02-18 14:31 UTC, merged