Create a C++ object wrapper around pmemstream and introduce more advaced rc features
pmem/pmemstream pull request #131
Opened 2022-02-18 18:04 UTC by igchor

And use it inside tests.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemstream/131)

2022-02-21 14:06 UTC, lukaszstolarczuk reviewed
in general, it looks ok
(I'm not sure if all comments necessarily apply to this PR, but I left them anyway :wink: you can skip them and we'll fix them later)

> Reviewed 8 of 12 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131#-:-MwRaQdy59rOhsFzaq54:b-cex5z0)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor)

___
*[tests/common/rapidcheck_helpers.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/pmemstream/131#-MwQf8EtDV0vCNRcufc-:-MwQf8EtDV0vCNRcufc0:bod6eyq) ([raw file](https://github.com/pmem/pmemstream/blob/7653d6616b4e1f14fb0b1fa2cd253782f4b9ca11/tests/common/rapidcheck_helpers.hpp#L70)):*
> ```cpp
> 	void run(const pmemstream_model &m, pmemstream_sut &s) const override
> 	{
> 		if (m.user_created_runtime) {
> ```

did you mean `if ! user_created_runtime`?
___
*[tests/common/rapidcheck_helpers.hpp, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/131#-MwQfcfv-P-j1wz-lXmX:-MwQfcfv-P-j1wz-lXmY:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/7653d6616b4e1f14fb0b1fa2cd253782f4b9ca11/tests/common/rapidcheck_helpers.hpp#L90)):*
> ```cpp
> 	{
> 		s.reopen();
> 		if (m.user_created_runtime_after_reopen) {
> ```

.
___
*[tests/common/rapidcheck_helpers.hpp, line 11 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRRTfd1GPmsVwaDJtl:-MwRRTfd1GPmsVwaDJtm:bm8gd6m) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/rapidcheck_helpers.hpp#L11)):*
> ```cpp
> 
> #include "stream_helpers.hpp"
> ```

you could add some comments in this file, actually (at least put the link to RC's 'Stateful testing' guide
___
*[tests/common/stream_helpers.hpp, line 217 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRUu4u4rBMBIgAfPmu:-MwRUu4u4rBMBIgAfPmv:brejn56) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/stream_helpers.hpp#L217)):*
> ```cpp
> 
> 			if (last_entry.offset == 0)
> 				throw std::runtime_error("No elements in the stream");
> ```

no elements in this region
___
*[tests/common/stream_helpers.hpp, line 264 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRVk-TBmAMpEOS4wCS:-MwRVk-TBmAMpEOS4wCT:b-bzsqvo) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/stream_helpers.hpp#L264)):*
> ```cpp
> 
>  private:
> 	std::tuple<std::string, size_t, size_t> args;
> ```

you could add a comment here, what are the args
___
*[tests/unittest/append.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRC2Dx5gfEPHd1AirC:-MwRC2Dx5gfEPHd1AirD:b-oojk0e) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append.cpp#L14)):*
> ```cpp
> {
> 	if (argc != 2) {
> 		std::cout << "Usage: " << argv[0] << " file-test_config.filename" << std::endl;
> ```

why is this line changed? we shouldn't bother if this is stored in test_config or something else, at this point

if you want to keep it, then perhaps drop the `file-` part
___
*[tests/unittest/append.cpp, line 49 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwREYiQ6bdki5daDWnP:-MwREYiQ6bdki5daDWnQ:b-ci8hxm) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append.cpp#L49)):*
> ```cpp
> 
> 			std::string entry;
> 			auto [ret, new_entry] = stream.sut.append(region, entry);
> ```

you could verify if entry == new_entry.data
___
*[tests/unittest/append_oom.cpp, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIcpq7h1XB-_cWeuw:-MwRIcpr9EuWIBeqVL3A:bgoqdea) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L5)):*
> ```cpp
> 
> #include <cstdint>
> #include <vector>
> ```

you don't need this
___
*[tests/unittest/append_oom.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIfgM9IbYPgyU0AXg:-MwRIfgM9IbYPgyU0AXh:b8rw3v0) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L14)):*
> ```cpp
> {
> 	if (argc != 2) {
> 		std::cout << "Usage: " << argv[0] << " file-test_config.filename" << std::endl;
> ```

this weird string here, again :wink: 
___
*[tests/unittest/append_oom.cpp, line 25 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIsCI5RKC_lsNdOrJ:-MwRIsCI5RKC_lsNdOrK:b-hjs653) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L25)):*
> ```cpp
> 		ret += rc::check(
> 			"verify append will work until OOM", [&](pmemstream_empty &&stream, const std::string &value) {
> 				RC_PRE(value.size() > 0);
> ```

actually... is this `PRE` required? entries' metadata should fill the region up, as well
___
*[tests/unittest/append_oom.cpp, line 39 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRNxN5DVRh02AjgfEU:-MwRNxN5DVRh02AjgfEV:bqchbv5) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L39)):*
> ```cpp
> 					}
> 				}
> 			});
> ```

previously we had pre-defined number of elements, to have pre-defined size - this way we could fit in another arbitrary smaller element... I guess to confirm it's actually OOM. I guess we don't have to bother, but just to consider (it might be useful as long as we don't have proper error codes).
___
*[tests/unittest/create.cpp, line 92 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRX6_W70FG_VPnyNS7:-MwRX6_W70FG_VPnyNS8:burecqg) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/create.cpp#L92)):*
> ```cpp
> 			for (size_t &size : sizes) {
> 				auto [ret, region] = stream.region_allocate(size);
> 				UT_ASSERT(ret != 0);
> ```

UT_ASSERTne


<!-- Sent from Reviewable.io -->

2022-02-21 14:35 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/rapidcheck_helpers.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/pmemstream/131#-MwQf8EtDV0vCNRcufc-:-MwRc_lLB-T3vD_4M6sq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7653d6616b4e1f14fb0b1fa2cd253782f4b9ca11/tests/common/rapidcheck_helpers.hpp#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you mean `if ! user_created_runtime`?
</blockquote></details>

Done.
___
*[tests/common/rapidcheck_helpers.hpp, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/131#-MwQfcfv-P-j1wz-lXmX:-MwRc_zQ3KkMSP-5-ncU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7653d6616b4e1f14fb0b1fa2cd253782f4b9ca11/tests/common/rapidcheck_helpers.hpp#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/common/rapidcheck_helpers.hpp, line 11 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRRTfd1GPmsVwaDJtl:-MwRdPT161UzGTY-MIoB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/rapidcheck_helpers.hpp#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add some comments in this file, actually (at least put the link to RC's 'Stateful testing' guide
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 217 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRUu4u4rBMBIgAfPmu:-MwRbSRm85b3D6S0oM4n:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/stream_helpers.hpp#L217)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no elements in this region
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 264 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRVk-TBmAMpEOS4wCS:-MwRbZ-E98C7R0mI2Fwx:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/common/stream_helpers.hpp#L264)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add a comment here, what are the args
</blockquote></details>

Done.
___
*[tests/unittest/append.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRC2Dx5gfEPHd1AirC:-MwRclFy0wQ64kvdNbfu:b-tsvwof) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append.cpp#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why is this line changed? we shouldn't bother if this is stored in test_config or something else, at this point

if you want to keep it, then perhaps drop the `file-` part
</blockquote></details>

Done. Regexpr went too far 
___
*[tests/unittest/append.cpp, line 49 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwREYiQ6bdki5daDWnP:-MwRbvNL4JMS2k2c2G02:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append.cpp#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could verify if entry == new_entry.data
</blockquote></details>

Done.
___
*[tests/unittest/append_oom.cpp, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIcpq7h1XB-_cWeuw:-MwRfR5y6paNNVaqoCB_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't need this
</blockquote></details>

Done.
___
*[tests/unittest/append_oom.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIfgM9IbYPgyU0AXg:-MwRcp_I3oa0Xbk5zrPd:b-tsvwof) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this weird string here, again :wink: 
</blockquote></details>

Done. Regexpr went too far 
___
*[tests/unittest/append_oom.cpp, line 25 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIsCI5RKC_lsNdOrJ:-MwRfUKZ8XTUUvNE-tgD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually... is this `PRE` required? entries' metadata should fill the region up, as well
</blockquote></details>

Done.
___
*[tests/unittest/append_oom.cpp, line 39 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRNxN5DVRh02AjgfEU:-MwRfUpD-jH0u1JDMwII:b81mj1a) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

previously we had pre-defined number of elements, to have pre-defined size - this way we could fit in another arbitrary smaller element... I guess to confirm it's actually OOM. I guess we don't have to bother, but just to consider (it might be useful as long as we don't have proper error codes).
</blockquote></details>

RIght, but how did you know that this last entry will fit? It could have happened that those 10 entires fitted just perfectly.
___
*[tests/unittest/create.cpp, line 92 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRX6_W70FG_VPnyNS7:-MwRcr_BD0VWdAxRO29K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/create.cpp#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

UT_ASSERTne
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 15:41 UTC, lukaszstolarczuk reviewed
> Reviewed 21 of 21 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[tests/common/stream_helpers.hpp, line 39 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRwEVX88u_Qd4Pf6Sb:-MwRwEVX88u_Qd4Pf6Sc:bb64to4) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/common/stream_helpers.hpp#L39)):*
> ```cpp
> 
> struct pmemstream_sut {
> 	pmemstream_sut(const std::string &file, size_t block_size, size_t size, bool truncate = true) : helpers(*this)
> ```

this `file` param is redundant now...? all tests should have access to test_config now...?
___
*[tests/integrity/append_break.cpp, line 65 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRtdDv572ST9vBSFBe:-MwRtdDv572ST9vBSFBf:b-3qzcqv) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/append_break.cpp#L65)):*
> ```cpp
> {
> 	struct test_config_type test_config;
> 	test_config.filename = std::string(argv[1]);
> ```

we parse a path within `test` function here
___
*[tests/integrity/reserve_publish.cpp, line 23 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRtmkV4URhfcjiggvE:-MwRtmkV4URhfcjiggvF:b7m843z) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L23)):*
> ```cpp
> 	}
> 
> 	auto path = std::string(argv[1]);
> ```

do we still need this `path` then?
___
*[tests/integrity/reserve_publish.cpp, line 28 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRttYh-8dLlkpLmDCL:-MwRttYh-8dLlkpLmDCM:b-oamgly) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L28)):*
> ```cpp
> 	test_config.filename = std::string(argv[1]);
> 
> 	return run_test(test_config, [&] {
> ```

and if you plan using test_config, then `[&]` is not required, I guess...?
___
*[tests/unittest/append_oom.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRIfgM9IbYPgyU0AXg:-MwRqojz7Mq-taEQKGjk:bx50v2h) ([raw file](https://github.com/pmem/pmemstream/blob/b2690c742616cab8429664ceba9562718bdbd97b/tests/unittest/append_oom.cpp#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done. Regexpr went too far 
</blockquote></details>

yeah, I figured :smile:
___
*[tests/unittest/region_initialize.cpp, line 27 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRulZ357YW1fZWiwd9:-MwRulZ357YW1fZWiwdA:b-rnuxz9) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/unittest/region_initialize.cpp#L27)):*
> ```cpp
> 	}
> 
> 	auto path = std::string(argv[1]);
> ```

are we even using path in this test? :wink: 


<!-- Sent from Reviewable.io -->

2022-02-21 18:08 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: 8 of 26 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 39 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRwEVX88u_Qd4Pf6Sb:-MwSPX406uHNECpR892j:b-3pqcda) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/common/stream_helpers.hpp#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this `file` param is redundant now...? all tests should have access to test_config now...?
</blockquote></details>

I left the params for cases where you need some custom path (like when you create 2 streams).
___
*[tests/integrity/append_break.cpp, line 65 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRtdDv572ST9vBSFBe:-MwSSF906NSSF8MHD0NN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/append_break.cpp#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we parse a path within `test` function here
</blockquote></details>

Done.
___
*[tests/integrity/reserve_publish.cpp, line 23 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRtmkV4URhfcjiggvE:-MwSR-GWE8MYOZfXNBnb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we still need this `path` then?
</blockquote></details>

Done.
___
*[tests/integrity/reserve_publish.cpp, line 28 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRttYh-8dLlkpLmDCL:-MwSR0466lUDvOwc86-g:b7mp5eh) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and if you plan using test_config, then `[&]` is not required, I guess...?
</blockquote></details>

Yes, done. In general, most of those test can just use rc generator now. But changing this requires some time so I prefer to do it in next PRs.
___
*[tests/unittest/region_initialize.cpp, line 27 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwRulZ357YW1fZWiwd9:-MwSRfRQ56dN4V7_-IjW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/unittest/region_initialize.cpp#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are we even using path in this test? :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 18:36 UTC, igchor reviewed
There are still places where we could replace manually creating pmemstream with auto generation - this can be done as next step. Also we might extend the test_config with things like default region size. We can also think about extending stream generators to accept the test_config (I'm not sure if this is possible) - this would allow us to avoid having multiple different test types (empty_region, init_region, etc.)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131#-:-MwSYdDF7spUWcQvuG--:b-5jhmk3)* status: 8 of 26 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-02-22 15:22 UTC, karczex requested changes
> Reviewed 1 of 3 files at r4, 5 of 21 files at r7, 1 of 18 files at r8, 1 of 9 files at r9, 3 of 11 files at r10, 1 of 13 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: 9 of 26 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 47 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWtEeSAV8Bt3ZaBbLY:-MwWtEeSAV8Bt3ZaBbLZ:b1jiurl) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L47)):*
> ```cpp
> 	}
> 
> 	stream(const stream &) = delete;
> ```

Also delete copy assignment operator.
___
*[tests/common/stream_helpers.hpp, line 58 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWv5h29C7ZGvE0uHmc:-MwWv5h29C7ZGvE0uHmd:b-z30x9) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L58)):*
> ```cpp
> 	std::tuple<int, struct pmemstream_region_runtime *> region_runtime_initialize(struct pmemstream_region region)
> 	{
> 		struct pmemstream_region_runtime *runtime;
> ```

this ptr probably should be set to NULL if ret !=0 as you return ptr regardless of the result. 

This apply to all methods, which return tuple. 
___
*[tests/common/stream_helpers.hpp, line 105 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWwVVKEg21oC2O4kJQ:-MwWwVVKEg21oC2O4kJR:bfk30n6) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L105)):*
> ```cpp
> 	{
> 		struct pmemstream_entry_iterator *eiter;
> 		UT_ASSERTeq(pmemstream_entry_iterator_new(&eiter, c_stream.get(), region), 0);
> ```

IMO, such asserts shouldn't be included in wrapper helper class. 
It would be hard to use it in tests, where you expect fail. 
And in general it's little bit confusing during debug of tests, when you get assert from inside of helper function. I see it may be hard to return any reasonable value on failure, so maybe just throw runtime_exception.
___
*[tests/common/stream_helpers.hpp, line 114 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWxdqb6dVKJmO7oXlE:-MwWxdqb6dVKJmO7oXlF:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L114)):*
> ```cpp
> 	{
> 		struct pmemstream_region_iterator *riter;
> 		UT_ASSERTeq(pmemstream_region_iterator_new(&riter, c_stream.get()), 0);
> ```

.
___
*[tests/common/stream_helpers.hpp, line 247 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWyJTD1gUgOX59Jiuk:-MwWyJTD1gUgOX59Jiul:b-z3cbin) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L247)):*
> ```cpp
> 	}
> 
> 	pmem::stream &s;
> ```

one letter name is almost always bad idea. Why not just `stream`? 
___
*[tests/integrity/append_break.cpp, line 66 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWG9xj6bCsB9Ic_Qgc:-MwWG9xj6bCsB9Ic_Qgd:b-49047u) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/integrity/append_break.cpp#L66)):*
> ```cpp
> 	test_config.filename = std::string(argv[2]);
> 
> 	return run_test(test_config, [&] { test(argv[1][0]); });
> ```

Maybe assign it to some meaningful variable. 



_Code quote:_
```cpp
argv[1][0]
```
___
*[tests/unittest/id_manager.cpp, line 37 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwX-YHQ-1BNBojOHJeZ:-MwX-YHQ-1BNBojOHJe_:b-64sa2g) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/unittest/id_manager.cpp#L37)):*
> ```cpp
> 	struct test_config_type test_config;
> 
> 	return run_test(test_config, [] {
> ```

Maybe run_test overload for tests which don't need test_config?


<!-- Sent from Reviewable.io -->

2022-02-22 15:37 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r3, 1 of 3 files at r4, 3 of 21 files at r7, 12 of 18 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: 9 of 26 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-02-22 15:56 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: 9 of 26 files reviewed, 11 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 47 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWtEeSAV8Bt3ZaBbLY:-MwX6Rjd7c4UZJGHYAG7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L47)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Also delete copy assignment operator.
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 58 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWv5h29C7ZGvE0uHmc:-MwX4BUS9BaHMfGqImJF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L58)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

this ptr probably should be set to NULL if ret !=0 as you return ptr regardless of the result. 

This apply to all methods, which return tuple. 
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 105 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWwVVKEg21oC2O4kJQ:-MwX4SlN0PbrlIy3MbK7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L105)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

IMO, such asserts shouldn't be included in wrapper helper class. 
It would be hard to use it in tests, where you expect fail. 
And in general it's little bit confusing during debug of tests, when you get assert from inside of helper function. I see it may be hard to return any reasonable value on failure, so maybe just throw runtime_exception.
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 114 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWxdqb6dVKJmO7oXlE:-MwX4TVaBU1Hg31uz8CQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L114)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 247 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWyJTD1gUgOX59Jiuk:-MwX71z4Cx3ZnaLRi0Ly:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/common/stream_helpers.hpp#L247)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

one letter name is almost always bad idea. Why not just `stream`? 
</blockquote></details>

Done.
___
*[tests/integrity/append_break.cpp, line 66 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWG9xj6bCsB9Ic_Qgc:-MwX4fl58Ayenia2Hu8n:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/integrity/append_break.cpp#L66)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Maybe assign it to some meaningful variable. 
</blockquote></details>

Done.
___
*[tests/unittest/id_manager.cpp, line 37 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwX-YHQ-1BNBojOHJeZ:-MwX4pgu0kt-Jfd5XyBV:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/unittest/id_manager.cpp#L37)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Maybe run_test overload for tests which don't need test_config?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-22 16:14 UTC, lukaszstolarczuk reviewed
huh, this PR got pretty big :smile: 

perhaps file some issues based on your thoughts above

> Reviewed 4 of 18 files at r8, 1 of 9 files at r9, 4 of 5 files at r12, 1 of 3 files at r13, 2 of 13 files at r15, 1 of 24 files at r16, 4 of 10 files at r17, 1 of 8 files at r18, 13 of 18 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131#-:-MwWS5KHBqnY01hKYT56:bmlllyb)* status: 21 of 26 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[tests/common/stream_helpers.hpp, line 87 at r15](https://reviewable.io/reviews/pmem/pmemstream/131#-MwX2hRW5FzI6F3pb7hT:-MwX2hRW5FzI6F3pb7hU:b-i63vn) ([raw file](https://github.com/pmem/pmemstream/blob/3badacc08f71815f36c6ea7daab0635b12c168b0/tests/common/stream_helpers.hpp#L87)):*
> ```cpp
> 	{
> 		int ret = pmemstream_publish(c_stream.get(), region, region_runtime, data, size, reserved_entry);
> 		return {ret, reserved_entry};
> ```

we don't have to return `reserved_entry` anymore, I believe
___
*[tests/common/stream_helpers.hpp, line 296 at r20](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXA5LS9YYnXvWcgTE5:-MwXA5LS9YYnXvWcgTE6:b-t23fgq) ([raw file](https://github.com/pmem/pmemstream/blob/4275deef8d6c6c935a2491a3a8e76bc14146dbaf/tests/common/stream_helpers.hpp#L296)):*
> ```cpp
> 			for (auto &r : helpers.region_runtime) {
> 				auto [ret, runtime] = sut.region_runtime_initialize(pmemstream_region{r.first});
> 				UT_ASSERTeq(ret, 0);
> ```

if you want to remove asserts from helpers, then here's one :wink: 
___
*[tests/integrity/append_break.cpp, line 66 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWG9xj6bCsB9Ic_Qgc:-MwXAK0sAOVpVd7SA0HA:b-31nvds) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/integrity/append_break.cpp#L66)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you can move it on top of the `main` so it'd be used already there :wink: 
___
*[tests/integrity/reserve_publish.cpp, line 33 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXAXzHCAmQK0BDrZ_S:-MwXAXzHCAmQK0BDrZ_T:bjfslw1) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L33)):*
> ```cpp
> 		ret += rc::check("verify if mixing reserve+publish with append works fine",
> 				 [&](const std::vector<std::string> &data, const std::vector<std::string> &extra_data,
> 				     const bool use_append, const bool is_runtime_initialized) {
> ```

hmm what about random runtime inits here...?
___
*[tests/unittest/create.cpp, line 60 at r20](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXCAns7H6u4EMMwtqH:-MwXCAns7H6u4EMMwtqI:b-qf8yr8) ([raw file](https://github.com/pmem/pmemstream/blob/4275deef8d6c6c935a2491a3a8e76bc14146dbaf/tests/unittest/create.cpp#L60)):*
> ```cpp
> 			}
> 
> 			pmemstream_test_base stream(get_test_config().filename, get_test_config().block_size,
> ```

you don't have to fix that now, but I feel like `pmemstream_test_base` variables shouldn't be called `stream` (because you call then e.g. `stream.sut.region_free()`, which is weird :wink:


<!-- Sent from Reviewable.io -->

2022-02-22 21:38 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 18 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/common/stream_helpers.hpp, line 216 at r21](https://reviewable.io/reviews/pmem/pmemstream/131#-MwYLmE3AmQJDw_gvamS:-MwYLmE3AmQJDw_gvamT:bffs7wi) ([raw file](https://github.com/pmem/pmemstream/blob/3d02a74398029d8cfa64088ce9f70aed172c51ed/tests/common/stream_helpers.hpp#L216)):*
> ```cpp
> 		struct pmemstream_entry tmp_entry;
> 		while (pmemstream_entry_iterator_next(eiter.get(), nullptr, &tmp_entry) == 0) {
> 			last_entry = tmp_entry;
> ```

I guess we don't need this `tmp_entry` anymore
___
*[tests/integrity/append_break.cpp, line 66 at r10](https://reviewable.io/reviews/pmem/pmemstream/131#-MwWG9xj6bCsB9Ic_Qgc:-MwYB_7j0PTNRilzrwx4:b-p8ddne) ([raw file](https://github.com/pmem/pmemstream/blob/52fd549b890a4d8e52fd580bb8f92ff7438a23ba/tests/integrity/append_break.cpp#L66)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, but then I would have to spit the check, etc. Let's leave it for now
</blockquote></details>

och, yeah, ok
___
*[tests/integrity/reserve_publish.cpp, line 33 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXAXzHCAmQK0BDrZ_S:-MwYFZacEl3GXt3iFYRQ:baqk42b) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L33)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Now, it's called inside initialize_single_region in helpers (whether it's called or not is random). I believe this is good enough
</blockquote></details>

hmm.. is it random, though? I can't see `call_region_runtime_initialize` being set to anything else than `false`, but maybe I'm missing something...?
___
*[tests/unittest/create.cpp, line 60 at r20](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXCAns7H6u4EMMwtqH:-MwYFogCCkDy2BzBaCvb:b-mls886) ([raw file](https://github.com/pmem/pmemstream/blob/4275deef8d6c6c935a2491a3a8e76bc14146dbaf/tests/unittest/create.cpp#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if it's weird, `stream.sut` and `stream.helpers` look quite natural but if you have any ideas for a better name we can change later
</blockquote></details>

what's weird for me is calling `stream.sut` where `sut` means `Stream under test` (at least according to your comment :wink: )

nonetheless, as said previously, we can potentially change that later


<!-- Sent from Reviewable.io -->

2022-02-23 08:05 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/integrity/reserve_publish.cpp, line 33 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXAXzHCAmQK0BDrZ_S:-Mw_b0o_ECP-A0CAaOrg:b-1yp9sr) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. is it random, though? I can't see `call_region_runtime_initialize` being set to anything else than `false`, but maybe I'm missing something...?
</blockquote></details>

Yes, pmemstream_with_single_empty_region (and all other variants) are generated by rapidcheck (see rapidcheck_helpers.hpp). And when they are generated when set the call_region_runtime_initialize ctor parameter to random value.


<!-- Sent from Reviewable.io -->

2022-02-23 08:46 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131#-:-Mw_kYqI3CL7FP_4fZGu:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/integrity/reserve_publish.cpp, line 33 at r7](https://reviewable.io/reviews/pmem/pmemstream/131#-MwXAXzHCAmQK0BDrZ_S:-Mw_kQc-AUhiwWCQG8n8:bzfezyn) ([raw file](https://github.com/pmem/pmemstream/blob/1fcd01f9cd4dc65905cce3e44d0058b04c5db4d7/tests/integrity/reserve_publish.cpp#L33)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, pmemstream_with_single_empty_region (and all other variants) are generated by rapidcheck (see rapidcheck_helpers.hpp). And when they are generated when set the call_region_runtime_initialize ctor parameter to random value.
</blockquote></details>

ohh, I missed that `gen::arbitrary<bool>()`

that's perfect then


<!-- Sent from Reviewable.io -->

2022-02-23 08:50 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 216 at r21](https://reviewable.io/reviews/pmem/pmemstream/131#-MwYLmE3AmQJDw_gvamS:-Mw_lRcHBr5UXrCmeozA:b-ynma73) ([raw file](https://github.com/pmem/pmemstream/blob/3d02a74398029d8cfa64088ce9f70aed172c51ed/tests/common/stream_helpers.hpp#L216)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess we don't need this `tmp_entry` anymore
</blockquote></details>

Added extra check using tmp_entry


<!-- Sent from Reviewable.io -->

2022-02-23 09:26 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/131)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-02-23 13:28 UTC, merged