add async version of append
pmem/pmemstream pull request #136
Opened 2022-02-24 12:22 UTC by lukaszstolarczuk

using libminiasync.

It's an early draft with still some extra features to add, but it seems to compile and execute (an example) just fine.

2022-02-24 13:15 UTC, igchor requested changes
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/04_basic_async/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-Mwfpv2Y5myqFZ3da3fj:-Mwfpv2Z65N9ay8NT6OY:b-ucmyv7) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/examples/04_basic_async/main.cpp#L69)):*
> ```cpp
> 
> 	/* async append, executed in the libminiasync runtime */
> 	struct pmemstream_append_future append_async = pmemstream_append_async(stream, region, NULL, &e, sizeof(e), &entry);
> ```

It would be best to show how you can use miniasync to create multiple concurrent operations.
___
*[src/libpmemstream.c, line 340 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-Mwfq51C9aOFId2gkq5c:-Mwfq51C9aOFId2gkq5d:b-9gz12s) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L340)):*
> ```C
> static enum future_state pmemstream_append_async_impl(struct future_context *ctx, struct future_notifier *notifier)
> {
> 	if (notifier != NULL) {
> ```

shuldn't this be `==`?
___
*[src/libpmemstream.c, line 367 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqJZCCcuC_zpgWbTq:-MwfqJZD5mduBE8lv-yN:bbfmkhb) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L367)):*
> ```C
> 							 struct pmemstream_region_runtime *region_runtime,
> 							 const void *data, size_t size,
> 							 struct pmemstream_entry *new_entry)
> ```

We could also return this new_entry though value (using the pmemstream_append_ret structut). We probably do this already (as new_entry). This could even make sense also for regular append
___
*[src/libpmemstream.c, line 390 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqcvC6-ofqoUWnxaH:-MwfqcvC6-ofqoUWnxaI:bb7r2f0) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L390)):*
> ```C
> 	future.data.ctx.stream = stream;
> 	future.data.ctx.region = region;
> 	future.data.ctx.region_runtime = region_runtime; /* XXX: change it for concurrent append? */
> ```

why?


<!-- Sent from Reviewable.io -->

2022-02-24 14:34 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[examples/04_basic_async/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-Mwfpv2Y5myqFZ3da3fj:-Mwg6VkM8tPR-N9jXJta:bk8r9u) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/examples/04_basic_async/main.cpp#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It would be best to show how you can use miniasync to create multiple concurrent operations.
</blockquote></details>

yep, that's the plan
___
*[src/libpmemstream.c, line 340 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-Mwfq51C9aOFId2gkq5c:-Mwg6YmfAQSsdRQ5Lzv_:b27wrgn) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L340)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shuldn't this be `==`?
</blockquote></details>

tbh, I'm not really sure, I blindly copy-pasted that from miniasync basic example... I'll figure this one out later
___
*[src/libpmemstream.c, line 367 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqJZCCcuC_zpgWbTq:-Mwg6gUDEcGOqN_6J8Gl:bh2cww3) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L367)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We could also return this new_entry though value (using the pmemstream_append_ret structut). We probably do this already (as new_entry). This could even make sense also for regular append
</blockquote></details>

I've updated that, please let me know if it looks better now.

As for regular append - what do you mean? return some kind of wrapper like pmemkv's `result` class?
___
*[src/libpmemstream.c, line 390 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqcvC6-ofqoUWnxaH:-Mwg75GMCUQ9fZZ0v5os:b-fto867) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L390)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why?
</blockquote></details>

this is some early comment, I've left (I'm not sure if we had any synchronization back then). I believe it is outdated now.


<!-- Sent from Reviewable.io -->

2022-02-25 10:11 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 11 of 16 files reviewed, all discussions resolved (waiting on @igchor)

___
*[src/libpmemstream.c, line 367 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqJZCCcuC_zpgWbTq:-MwkLzRfEEJSf71xhUnT:bzdq53) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L367)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I've updated that, please let me know if it looks better now.

As for regular append - what do you mean? return some kind of wrapper like pmemkv's `result` class?
</blockquote></details>

You're going to remove this new_netry parameter, right?

As for regular append, yes. I was thinking about a result struct or something similar for consistency but I'm not sure if this is the best idea - we can discuss this later


<!-- Sent from Reviewable.io -->

2022-03-16 11:55 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 9 of 17 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/04_basic_async/main.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHXpAeAAGDGi_6qSzT:-MyHXpAeAAGDGi_6qSzU:bt1hfhy) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/examples/04_basic_async/main.cpp#L85)):*
> ```cpp
> 	// pmemstream_async_append(thread_mover, stream, region, NULL, &e2, sizeof(e2));
> 
> 	if (append_async_1.output.error_code != 0) {
> ```

hm, do we need to check the error twice? how about checking only after future is completed?
___
*[src/libpmemstream.c, line 351 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZxVz9H45QW9DkXXz:-MyHZxVz9H45QW9DkXY-:b-up4ay5) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L351)):*
> ```C
> 	stream->data.persist(destination, pmemstream_entry_total_size_aligned(size));
> 
> 	/* XXX: will this work with async append...? */
> ```

Yes, assuming that there is only one pending append to a region. To allow multiple appends (even from single thread) we would need to use timestamps, mpc_queue, etc.
___
*[src/libpmemstream.c, line 440 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZE9gAwyvL-ZYEQOD:-MyHZE9gAwyvL-ZYEQOE:b-abzr6z) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L440)):*
> ```C
> 
> // asynchronously appends data buffer to the end of the region
> struct pmemstream_async_append_fut pmemstream_async_append(struct vdm *vdm, struct pmemstream *stream,
> ```

put stream as first argument perhaps?


<!-- Sent from Reviewable.io -->

2022-03-16 16:01 UTC, lukaszstolarczuk reviewed
It looks like it's working properly now (Piotr's fix in miniasync was enough for this PR to work, I guess).

BTW, I've updated the example to look a bit like what Igor proposed.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136#-:-MyISG368ul1keGTAA1l:b54nf1s)* status: 9 of 17 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[examples/04_basic_async/main.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHXpAeAAGDGi_6qSzT:-MyIE8Ed8GWnK9IbVM-K:bsrmunx) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/examples/04_basic_async/main.cpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

hm, do we need to check the error twice? how about checking only after future is completed?
</blockquote></details>

I'm not sure if this is correct, but this is my way of closing up future early, e.g. because of failed `pmemstream_reserve` (within `pmemstream_async_append`). If we don't have entry reserved we cannot run memcpy/publish... and not initialized future will end up with a failure in miniasync.
___
*[src/libpmemstream.c, line 367 at r1](https://reviewable.io/reviews/pmem/pmemstream/136#-MwfqJZCCcuC_zpgWbTq:-MyIFTN92pFczMOBe5H9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/806004502204d0556df2d22085ded536acd1183d/src/libpmemstream.c#L367)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You're going to remove this new_netry parameter, right?

As for regular append, yes. I was thinking about a result struct or something similar for consistency but I'm not sure if this is the best idea - we can discuss this later
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 351 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZxVz9H45QW9DkXXz:-MyIHPwjCaZRiwIaqtfj:bic95af) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L351)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, assuming that there is only one pending append to a region. To allow multiple appends (even from single thread) we would need to use timestamps, mpc_queue, etc.
</blockquote></details>

hmm yeah, but with tje current approach (and in my example) may it fail?
___
*[src/libpmemstream.c, line 440 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZE9gAwyvL-ZYEQOD:-MyIFgGA1dKlcFpaby8q:beoiu1) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L440)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

put stream as first argument perhaps?
</blockquote></details>

I'm really not sure where to put it, to look best... is the second param better...? :wink: 


<!-- Sent from Reviewable.io -->

2022-03-21 18:47 UTC, igchor reviewed
API <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>. We can later think whether we should hide the definition of the futures.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136#-:-MyhlPlA09Pn9EoGfDdI:bjr7rn9)* status: 8 of 19 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/04_basic_async/main.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHXpAeAAGDGi_6qSzT:-MyhjhQxABS5747-XDIc:bd6p7i0) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/examples/04_basic_async/main.cpp#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if this is correct, but this is my way of closing up future early, e.g. because of failed `pmemstream_reserve` (within `pmemstream_async_append`). If we don't have entry reserved we cannot run memcpy/publish... and not initialized future will end up with a failure in miniasync.
</blockquote></details>

Could we do as you suggested in the comment in pmemstream_append? Just return an "empty" future which will return proper error code on future_poll?
___
*[src/libpmemstream.c, line 351 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZxVz9H45QW9DkXXz:-Myhm0ul94eeXs-6knFD:baejmzl) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L351)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm yeah, but with tje current approach (and in my example) may it fail?
</blockquote></details>

Yes, I belive it may: you can try increasing size of the entries so that memcpy takes longer or use different sizes, e.g. first entry biggest and second entry shortest. Then, verify the stream after the first completed future. In such case, first completed future may not correspond to first logical entry. 

The best way to show this API would be to use multiple regions (appends to multiple regions can be done concurrently). 


<!-- Sent from Reviewable.io -->

2022-03-21 18:50 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 8 of 19 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 440 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZE9gAwyvL-ZYEQOD:-MyhnYLRDM4MBVUws0Qm:bt4yucr) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L440)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm really not sure where to put it, to look best... is the second param better...? :wink: 
</blockquote></details>

Yeah, I'm not sure. We can go back to this idea of putting stream-related arguments to a structure and then have something like:
`pmemstream_async_append (struct pmemstream_params params, struct vdm *vdm, void *data, size_t size)` or something like this. But we'd need to do more research on this probably.


<!-- Sent from Reviewable.io -->

2022-03-28 08:32 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 8 of 21 files reviewed, all discussions resolved (waiting on @igchor)

___
*[examples/04_basic_async/main.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHXpAeAAGDGi_6qSzT:-Mz0ZGYnCxRhRS9GeitC:b-mqhrp3) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/examples/04_basic_async/main.cpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could we do as you suggested in the comment in pmemstream_append? Just return an "empty" future which will return proper error code on future_poll?
</blockquote></details>

Done (as discussed we return already completed future with an error code)
___
*[src/libpmemstream.c, line 351 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZxVz9H45QW9DkXXz:-Mz0caa35E9OLEM4Dhk9:byeb7zz) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L351)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, I belive it may: you can try increasing size of the entries so that memcpy takes longer or use different sizes, e.g. first entry biggest and second entry shortest. Then, verify the stream after the first completed future. In such case, first completed future may not correspond to first logical entry. 

The best way to show this API would be to use multiple regions (appends to multiple regions can be done concurrently). 
</blockquote></details>

I've checked behavior with bigger entry and it seems it's not working properly, as you said. I guess we just have to update this example when multiple appends will be possible.
For now, as long as we don't read any entry before all of these futures are complete we're safe, I believe.
___
*[src/libpmemstream.c, line 440 at r3](https://reviewable.io/reviews/pmem/pmemstream/136#-MyHZE9gAwyvL-ZYEQOD:-Mz0jRj4-p6_IMb0DqP3:b-iy4f0w) ([raw file](https://github.com/pmem/pmemstream/blob/d7b7d24e86050129d07698301f8f8d892cec4e38/src/libpmemstream.c#L440)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, I'm not sure. We can go back to this idea of putting stream-related arguments to a structure and then have something like:
`pmemstream_async_append (struct pmemstream_params params, struct vdm *vdm, void *data, size_t size)` or something like this. But we'd need to do more research on this probably.
</blockquote></details>

ok, so for now I'll leave it as is.


<!-- Sent from Reviewable.io -->

2022-04-01 11:35 UTC, lukaszstolarczuk commented
I've rebased the PR and updated the example to run on multiple regions.

2022-04-01 11:57 UTC, igchor approved these changes
> Reviewed 1 of 4 files at r2, 2 of 6 files at r3, 4 of 8 files at r4, 1 of 6 files at r5, 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/04_basic_async/main.cpp, line 87 at r7](https://reviewable.io/reviews/pmem/pmemstream/136#-MzZxCRTESyw9DD1YnMH:-MzZxCRU10gcMptzzDB0:bnsysuh) ([raw file](https://github.com/pmem/pmemstream/blob/9967287247dbaeff13c6eb407130b4ba5feeae03/examples/04_basic_async/main.cpp#L87)):*
> ```cpp
> 
> 	/*
> 	 * Example asynchronous append, executed in the libminiasync runtime
> ```

this comment is not exactly true, you are not using libminiasync's runtime to run the futures, right?
___
*[tests/common/stream_helpers.hpp, line 216 at r7](https://reviewable.io/reviews/pmem/pmemstream/136#-MzZykofAQDRsu2IBf8M:-MzZykofAQDRsu2IBf8N:b9cy3pr) ([raw file](https://github.com/pmem/pmemstream/blob/9967287247dbaeff13c6eb407130b4ba5feeae03/tests/common/stream_helpers.hpp#L216)):*
> ```cpp
> 	void async_append(struct pmemstream_region region, const std::vector<std::string> &data)
> 	{
> 		struct data_mover_threads *dmt = data_mover_threads_default();
> ```

nit: you might put this data_move into unique_ptr so we don't have a leak if there is any exception thrown
___
*[tests/unittest/publish_append_async.cpp, line 35 at r7](https://reviewable.io/reviews/pmem/pmemstream/136#-MzZyzG63VxBZFRWQ7eJ:-MzZyzG63VxBZFRWQ7eK:br06u04) ([raw file](https://github.com/pmem/pmemstream/blob/9967287247dbaeff13c6eb407130b4ba5feeae03/tests/unittest/publish_append_async.cpp#L35)):*
> ```cpp
> 		// env_setter setter("RC_PARAMS", rapidcheck_config, false);
> 
> 		ret += rc::check("verify if mixing regular appends with async appends works fine",
> ```

that's probably a good candidate for stateful tests (even without a model) ;d


<!-- Sent from Reviewable.io -->

2022-04-01 16:12 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 14 of 22 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/common/stream_helpers.hpp, line 216 at r7](https://reviewable.io/reviews/pmem/pmemstream/136#-MzZykofAQDRsu2IBf8M:-Mz_t4li5yLx9ZHwwZYe:b-jkqpqh) ([raw file](https://github.com/pmem/pmemstream/blob/9967287247dbaeff13c6eb407130b4ba5feeae03/tests/common/stream_helpers.hpp#L216)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm all of these functions may lead to leaks (we have things done like this for stream, map, etc...)

I'm not sure if the full error handling should be our concern in the examples.
</blockquote></details>

Which function? I think all other functions are exception safe actually (I tried to wrap each allocation in unique ptr).
It's not very critical but if we'll have tests in which we expect this async append to fail and we execute such test under memcheck we will get an error.


<!-- Sent from Reviewable.io -->

2022-04-04 10:13 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 12 of 22 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/common/stream_helpers.hpp, line 216 at r7](https://reviewable.io/reviews/pmem/pmemstream/136#-MzZykofAQDRsu2IBf8M:-Mzo2y1NEboJAak5CbB7:b4o0ydq) ([raw file](https://github.com/pmem/pmemstream/blob/9967287247dbaeff13c6eb407130b4ba5feeae03/tests/common/stream_helpers.hpp#L216)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Which function? I think all other functions are exception safe actually (I tried to wrap each allocation in unique ptr).
It's not very critical but if we'll have tests in which we expect this async append to fail and we execute such test under memcheck we will get an error.
</blockquote></details>

lol, I was browsing the example's code while reading your comment. Done now :smile: 


<!-- Sent from Reviewable.io -->

2022-04-04 11:05 UTC, lplewa reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/include/libpmemstream.h, line 14 at r10](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoEWGCCZUA_LHDzEDz:-MzoEWGCCZUA_LHDzEE-:bca4ix) ([raw file](https://github.com/pmem/pmemstream/blob/54b546765b1c97bc89849dced792d1b76c5a23f8/src/include/libpmemstream.h#L14)):*
> ```objc
>  */
> #include <libminiasync.h>
> #include <libminiasync/vdm.h>
> ```

you don't need separate include when including the main header.


<!-- Sent from Reviewable.io -->

2022-04-04 11:10 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136#-:-MzoGHNv3-bHzAE-35yZ:bnfp4nl)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-04-04 11:11 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @igchor and @lplewa)

___
*[src/include/libpmemstream.h, line 14 at r10](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoEWGCCZUA_LHDzEDz:-MzoGDnSBjvOsxoGpdGM:b-yc0un3) ([raw file](https://github.com/pmem/pmemstream/blob/54b546765b1c97bc89849dced792d1b76c5a23f8/src/include/libpmemstream.h#L14)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

you don't need separate include when including the main header.
</blockquote></details>

I know, I guess I was just trying to be more explicit. Done.


<!-- Sent from Reviewable.io -->

2022-04-04 14:08 UTC, KFilipek requested changes
> Reviewed 6 of 16 files at r1, 1 of 4 files at r2, 1 of 6 files at r3, 1 of 8 files at r4, 2 of 10 files at r7, 3 of 8 files at r9, 2 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 15 of 22 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, @lplewa, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 111 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoUhciEyWeSS9S4WFs:-MzoUhciEyWeSS9S4WFt:b5zhemk) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/CMakeLists.txt#L111)):*
> ```CMake
> endif()
> 
> # all our components require libpmem2 and libminiasync
> ```

everywhere here this library is called "miniasync"



_Code quote:_
```CMake
libminiasync
```
___
*[INSTALL.md, line 19 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoV-ZxE2kufZSMcKGP:-MzoV-ZxE2kufZSMcKGQ:b-kp1c9e) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/INSTALL.md#L19)):*
> ```Markdown
>     * [CMake](https://cmake.org/) >= 3.16
> * **libpmem2-dev(el)**, which is part of [PMDK](https://github.com/pmem/pmdk) - Persistent Memory Development Kit 1.10
> * **miniasync** - [Mini Library for Asynchronous Programming](https://github.com/pmem/miniasync)
> ```

-> "Mini Asynchronous Library"



_Code quote:_
```Markdown
Mini Library for Asynchronous Programming
```
___
*[examples/04_basic_async/main.cpp, line 47 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzopL6tCPq925Fy32Bl:-MzopL6u4e7U5aQQqM48:bxc67bz) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/examples/04_basic_async/main.cpp#L47)):*
> ```cpp
> 	struct pmemstream_region_iterator *riter;
> 	ret = pmemstream_region_iterator_new(&riter, stream);
> 	assert(ret == 0);
> ```

This is the only place with assert, others have normal error handling, I would prefer like elsewhere:
```cpp
	ret = pmemstream_append(stream, regions[0], NULL, &example_data[0], sizeof(example_data[0]), &entry);
	if (ret) {
		fprintf(stderr, "pmemstream_append failed\n");
		return ret;
	}
```



_Code quote:_
```cpp
assert(ret == 0);
```
___
*[examples/04_basic_async/main.cpp, line 63 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoWmiS2viC_d9bUHlq:-MzoWmiS2viC_d9bUHlr:bkisayk) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/examples/04_basic_async/main.cpp#L63)):*
> ```cpp
> 				return ret;
> 			}
> 		}
> ```

A bit simpler and easier to understand, you will lose `try_get` logic and there is no comparison every iteration. In optimistic case you have only 1 extra check on next loop:
```
        /* Fill regions table */
        int i;
	for (i = 0; i < EXAMPLE_ASYNC_COUNT; ++i) {
		ret = pmemstream_region_iterator_next(riter, &regions[i]);
		if (ret) {
			break;
		}
        }
        /* Allocate missing regions */
	for (; i < EXAMPLE_ASYNC_COUNT; ++i) {
		ret = pmemstream_region_allocate(stream, EXAMPLE_REGION_SIZE, &regions[i]);
		if (ret) {
			fprintf(stderr, "pmemstream_region_allocate failed\n");
			return ret;
		}
	}
```



_Code quote:_
```cpp
	for (int i = 0; i < EXAMPLE_ASYNC_COUNT; ++i) {
		if (try_get) {
			ret = pmemstream_region_iterator_next(riter, &regions[i]);
			if (ret != 0) {
				try_get = false;
			}
		}
		if (!try_get) {
			ret = pmemstream_region_allocate(stream, EXAMPLE_REGION_SIZE, &regions[i]);
			if (ret != 0) {
				fprintf(stderr, "pmemstream_region_allocate failed\n");
				return ret;
			}
		}
	}
```
___
*[examples/04_basic_async/main.cpp, line 72 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzoVwXtDtCGzkT4AAdR:-MzoVwXtDtCGzkT4AAdS:b1s5gp5) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/examples/04_basic_async/main.cpp#L72)):*
> ```cpp
> 	example_data[0].data = 1;
> 	example_data[1].data = UINT64_MAX;
> 	example_data[2].data = 8196;
> ```

Why this value? I believe you want 2*4096 = 8192.



_Code quote:_
```cpp
8196
```
___
*[tests/unittest/publish_append_async.cpp, line 26 at r11](https://reviewable.io/reviews/pmem/pmemstream/136#-MzotByF5GH_Be0yrI0o:-MzotByF5GH_Be0yrI0p:bm7qfo7) ([raw file](https://github.com/pmem/pmemstream/blob/4ab4ef4c41435f97424e9a583ce1e4d1f3bd3316/tests/unittest/publish_append_async.cpp#L26)):*
> ```cpp
> 
> 	struct test_config_type test_config;
> 	test_config.filename = std::string(argv[1]);
> ```

It's enough:
`test_config.filename = argv[1];`
Due to (5):
`basic_string( const CharT* s,
              const Allocator& alloc = Allocator() );`
https://en.cppreference.com/w/cpp/string/basic_string/basic_string



_Code quote:_
```cpp
test_config.filename = std::string(argv[1]);
```


<!-- Sent from Reviewable.io -->

2022-04-05 09:06 UTC, karczex requested changes
> Reviewed 4 of 16 files at r1, 1 of 6 files at r3, 2 of 10 files at r7, 2 of 8 files at r9, 2 of 4 files at r10, 1 of 1 files at r11, 2 of 3 files at r12, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 22 of 23 files reviewed, 5 unresolved discussions (waiting on @KFilipek, @lplewa, and @lukaszstolarczuk)

___
*[examples/04_basic_async/CMakeLists.txt, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-MzsgA27DkCqEwj3fjy4:-MzsgA288x1vjRkNiGfE:b8sxdiu) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/CMakeLists.txt#L4)):*
> ```CMake
> # Copyright 2022, Intel Corporation
> 
> cmake_minimum_required(VERSION 3.3)
> ```

According to https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html should be 3.8 (Also in other examples, but it's out of scope of this PR) 
___
*[examples/04_basic_async/main.cpp, line 43 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsh2Lq0tTfMNDNNCun:-Mzsh2Lq0tTfMNDNNCuo:bhfbffv) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L43)):*
> ```cpp
> 
> 	/* get or allocate regions */
> 	struct pmemstream_region regions[EXAMPLE_ASYNC_COUNT];
> ```

How do you think, it would be better to use c-like array for compatibility with c examples or std::array (or std::vector)? (same for other arrays in the example)
___
*[examples/04_basic_async/main.cpp, line 54 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-MzsjLwA8A0Hx1HnvQHu:-MzsjLwA8A0Hx1HnvQHv:bnvqp58) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L54)):*
> ```cpp
> 	for (; i < EXAMPLE_ASYNC_COUNT; ++i) {
> 		ret = pmemstream_region_iterator_next(riter, &regions[i]);
> 		if (ret != 0) {
> ```

...
You may wrap first loop into `count_existing_regions()`
so you may end with cleaner for loop 

```
for(int i = count_existing_regions(...) ; i< regions.size(); i++) {
                ret = pmemstream_region_allocate(stream, EXAMPLE_REGION_SIZE, region]);
		if (ret != 0) {
			fprintf(stderr, "pmemstream_region_allocate failed\n");
			return ret;
		}
}
```  
```




_Code quote:_
```cpp
	for (; i < EXAMPLE_ASYNC_COUNT; ++i) {
		ret = pmemstream_region_iterator_next(riter, &regions[i]);
		if (ret != 0) {
			break;
		}
	}
	/* if regions are missing - allocate them */
	for (; i < EXAMPLE_ASYNC_COUNT; ++i) {
		ret = pmemstream_region_allocate(stream, EXAMPLE_REGION_SIZE, &regions[i]);
		if (ret != 0) {
			fprintf(stderr, "pmemstream_region_allocate failed\n");
			return ret;
		}
	}
```
___
*[examples/04_basic_async/main.cpp, line 111 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsqhxf0vYIyZrmJEyu:-Mzsqhxg5891fVl5LfoQ:b-2t80f6) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L111)):*
> ```cpp
> 
> 	/* ... or alternatively manually poll until completion. */
> 	int completed_futures[EXAMPLE_ASYNC_COUNT] = {0};
> ```

std::vector?


<!-- Sent from Reviewable.io -->

2022-04-05 10:13 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 22 of 23 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, @lplewa, and @lukaszstolarczuk)

___
*[examples/04_basic_async/main.cpp, line 111 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsqhxf0vYIyZrmJEyu:-Mzt8f0W0vEiFutIQXoX:b716ysi) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L111)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

std::vector?
</blockquote></details>

You might want to check if future_poll is allowed on already completed futures. If yes, then you don't need this vector/array at all, just a counter or bool (zero it on each iteration).


<!-- Sent from Reviewable.io -->

2022-04-05 10:49 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lplewa)

___
*[examples/04_basic_async/CMakeLists.txt, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-MzsgA27DkCqEwj3fjy4:-MztF7LQ8aS9sa3IWi3J:b-q0qd8y) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/CMakeLists.txt#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

According to https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html should be 3.8 (Also in other examples, but it's out of scope of this PR) 
</blockquote></details>

I believe we don't require a specific CXX_STANDARD for this example - it's a standalone compilation only. Pmemstream, which is required here, is already built.
___
*[examples/04_basic_async/main.cpp, line 43 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsh2Lq0tTfMNDNNCun:-MztK1-g54N-w2JNXfHs:br53enw) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L43)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

How do you think, it would be better to use c-like array for compatibility with c examples or std::array (or std::vector)? (same for other arrays in the example)
</blockquote></details>

hmm.. I've tested a few approaches and am not sure if usage of std::array/vector gives any extra readability; and as you stated, this approach is easy to understand for C users and is compatible with C examples
___
*[examples/04_basic_async/main.cpp, line 54 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-MzsjLwA8A0Hx1HnvQHu:-MztBrE-58KSqZ8k5VeF:b-gl4cdc) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

...
You may wrap first loop into `count_existing_regions()`
so you may end with cleaner for loop 

```
for(int i = count_existing_regions(...) ; i< regions.size(); i++) {
                ret = pmemstream_region_allocate(stream, EXAMPLE_REGION_SIZE, region]);
		if (ret != 0) {
			fprintf(stderr, "pmemstream_region_allocate failed\n");
			return ret;
		}
}
```  
```

</blockquote></details>

hmm... I'm not only counting them but also storing them in the array. I think what is now is quite readable; if I move this storing out (e.g. into a function) it may not be clear how they end up being set. (maybe it's just me :smile: )
___
*[examples/04_basic_async/main.cpp, line 111 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsqhxf0vYIyZrmJEyu:-MztD5vi0KvIC-IfLfPh:b3o22k) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L111)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You might want to check if future_poll is allowed on already completed futures. If yes, then you don't need this vector/array at all, just a counter or bool (zero it on each iteration).
</blockquote></details>

that'd be actually a very nice trick with resetting the counter (it would work flawlessly), but then we would print lots of messages (each time the future is polled and already complete). Printing it right after the future's completion gives an extra perspective, that it's safe to read it right away (in this multi-region case).

as for vector, the same as above - I've tested it and IMO it gives no extra readability


<!-- Sent from Reviewable.io -->

2022-04-05 11:14 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lplewa)

___
*[examples/04_basic_async/main.cpp, line 111 at r14](https://reviewable.io/reviews/pmem/pmemstream/136#-Mzsqhxf0vYIyZrmJEyu:-MztQe6UBK3ziXF-CBsP:bqqoem6) ([raw file](https://github.com/pmem/pmemstream/blob/7534e37a9b9f8228b5f4c99b1694730d207290e5/examples/04_basic_async/main.cpp#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that'd be actually a very nice trick with resetting the counter (it would work flawlessly), but then we would print lots of messages (each time the future is polled and already complete). Printing it right after the future's completion gives an extra perspective, that it's safe to read it right away (in this multi-region case).

as for vector, the same as above - I've tested it and IMO it gives no extra readability
</blockquote></details>

Ok, makes sense


<!-- Sent from Reviewable.io -->

2022-04-05 12:51 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/136#-:-MztlveY3-SZwzooSApP:bnfp4nl)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lplewa)



<!-- Sent from Reviewable.io -->

2022-04-05 18:36 UTC, merged