Singly-linked list implementation
pmem/pmemstream pull request #145
Opened 2022-03-14 16:51 UTC by KFilipek

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemstream/145)

2022-03-14 17:48 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/145#-My8O0If73n1fAMxm2DV):*
pls explain why do we need it? :wink: 
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/145#-My8OZ3j-SSe8cBAAjOp):*
FYI, "Singly linked" (no `-`)
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8Wi7s9w-nsrzYxTgX):*
pls fix this commit message :wink: 
___
*[src/singly_linked_list.h, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/145#-My8OjNeA9YrvYdK-db-:-My8OjNeA9YrvYdK-db0:b-x6sxad) ([raw file](https://github.com/pmem/pmemstream/blob/e9a5cff7f6e483a53f509d47d6018ea6c7bd6a11/src/singly_linked_list.h#L30)):*
> ```objc
> #endif
> 
> #endif /* LIBPMEMSTREAM_SINGLY_LINKED_LIST_H */
> ```

no "enter" at the end

// pls run `make check-whitespace`
___
*[src/singly_linked_list.h, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8Wxsr8WHhV5SHnh1i:-My8Wxsr8WHhV5SHnh1j:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/src/singly_linked_list.h#L40)):*
> ```objc
> 
> #ifdef __cplusplus
> ```

redundant empty line
___
*[tests/CMakeLists.txt, line 106 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8XSsqBSeFqx8-n8Pd:-My8XSsqBSeFqx8-n8Pe:bf7e4nf) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/tests/CMakeLists.txt#L106)):*
> ```CMake
> add_test_generic(NAME stream_from_map TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test_rc(NAME slist SRC_FILES unittest/slist.cpp)
> ```

pls rename this test and file to full name - "singly_linked_list.cpp"
___
*[tests/unittest/slist.cpp, line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8XAJ-EA5C5o2nk4ZW:-My8XAJ-EA5C5o2nk4ZX:b-38bvoy) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/tests/unittest/slist.cpp#L45)):*
> ```cpp
> }
> 
> // // SPDX-License-Identifier: BSD-3-Clause
> ```

rm below..?


<!-- Sent from Reviewable.io -->

2022-03-15 09:46 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/145#-MyBvH3qB-KTPRoP9AdO:-MyBvH3qB-KTPRoP9AdP:btky89c) ([raw file](https://github.com/pmem/pmemstream/blob/0c5f31f22c241c6eebda48c0c5658af3de6b1949/src/singly_linked_list.h#L22)):*
> ```objc
> #define SLIST_INIT(list)                                                                                               \
> 	do {                                                                                                           \
> 		(list)->head = UINT64_MAX;                                                                             \
> ```

maybe give this value some meaningful name.



_Code quote:_
```objc
UINT64_MAX
```


<!-- Sent from Reviewable.io -->

2022-03-16 09:24 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 41 at r5](https://reviewable.io/reviews/pmem/pmemstream/145#-MyH0Waz2nx_g-VcvZ0C:-MyH0Waz2nx_g-VcvZ0D:byw4c79) ([raw file](https://github.com/pmem/pmemstream/blob/07f30832a4758c4ba1b6c5e541b07cf8eb38776b/src/singly_linked_list.h#L41)):*
> ```objc
> 			(list)->head = (offset);                                                                       \
> 		}                                                                                                      \
> 		if ((list)->tail != UINT64_MAX) {                                                                      \
> ```

I just realised that in PMDK there is also SIMPLEQ version of queue which actually is what we want (it also stores pointer to last element next ptr) to allow O(1) tail insertion. Please take a look and fix the implementation: https://github.com/pmem/pmdk/blob/master/src/common/queue.h#L347

It's a bit cleaner that this approach with tail offset because it does not require conditionals on tail.


<!-- Sent from Reviewable.io -->

2022-03-18 11:22 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[src/singly_linked_list.h, line 31 at r12](https://reviewable.io/reviews/pmem/pmemstream/145#-MyRih6s7ed-9jafex-C:-MyRih6s7ed-9jafex-D:bj0up58) ([raw file](https://github.com/pmem/pmemstream/blob/cfb22c8c2c66618d19a7e9793cdf1fe2a4fdc91f/src/singly_linked_list.h#L31)):*
> ```objc
> 			(list)->tail = offset;                                                                         \
> 		}                                                                                                      \
> 		((type *)(pmemstream_offset_to_ptr(runtime, offset)))->field = (list)->head;                           \
> ```

SLIST_NEXT(...) = ... ? Also fix in other places
___
*[src/singly_linked_list.h, line 71 at r12](https://reviewable.io/reviews/pmem/pmemstream/145#-MyRk-XY2Z3rNEOHc3GI:-MyRk-XZ4rEPga6GcDCJ:bcf7vlk) ([raw file](https://github.com/pmem/pmemstream/blob/cfb22c8c2c66618d19a7e9793cdf1fe2a4fdc91f/src/singly_linked_list.h#L71)):*
> ```objc
> 			if ((SLIST_NEXT(type, runtime, curelm, field) = SLIST_NEXT(type, runtime, offset, field)) ==   \
> 			    UINT64_MAX)                                                                                \
> 				(list)->tail = UINT64_MAX;                                                             \
> ```

why UINT64_MAX? this should be (list)->tail = curelm I belive


<!-- Sent from Reviewable.io -->

2022-03-18 17:16 UTC, KFilipek reviewed
> Reviewed 3 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/145#-My8O0If73n1fAMxm2DV):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls explain why do we need it? :wink: 
</blockquote></details>

Done.
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8Wi7s9w-nsrzYxTgX):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix this commit message :wink: 
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/145#-My8OjNeA9YrvYdK-db-:-MyT0AOY3zTIblnudpTw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e9a5cff7f6e483a53f509d47d6018ea6c7bd6a11/src/singly_linked_list.h#L30)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no "enter" at the end

// pls run `make check-whitespace`
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8Wxsr8WHhV5SHnh1i:-MySz2NUAJe-JT29OTla:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/src/singly_linked_list.h#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/145#-MyBvH3qB-KTPRoP9AdO:-MySw3yQB50WeGmrZHS9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0c5f31f22c241c6eebda48c0c5658af3de6b1949/src/singly_linked_list.h#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

maybe give this value some meaningful name.
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 31 at r12](https://reviewable.io/reviews/pmem/pmemstream/145#-MyRih6s7ed-9jafex-C:-MySw4vY6eA5JUXz7b7k:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfb22c8c2c66618d19a7e9793cdf1fe2a4fdc91f/src/singly_linked_list.h#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

SLIST_NEXT(...) = ... ? Also fix in other places
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 71 at r12](https://reviewable.io/reviews/pmem/pmemstream/145#-MyRk-XY2Z3rNEOHc3GI:-MyT06Yf-Zan4pYFq49o:b-em8gvk) ([raw file](https://github.com/pmem/pmemstream/blob/cfb22c8c2c66618d19a7e9793cdf1fe2a4fdc91f/src/singly_linked_list.h#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why UINT64_MAX? this should be (list)->tail = curelm I belive
</blockquote></details>

Done. You're right
___
*[tests/CMakeLists.txt, line 106 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8XSsqBSeFqx8-n8Pd:-MyT0Mci1rShSVPozT9j:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/tests/CMakeLists.txt#L106)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls rename this test and file to full name - "singly_linked_list.cpp"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-21 08:44 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbH0J3deR7__KeJ9r):*
you don't have to repeat the same you have in the first commit line :wink: you can rather expand the info, why is it useful for multi-region support



_Code quote:_
```
Implementation of singly linked list
```
___
*[src/singly_linked_list.h, line 6 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbZiN7E336g48o3l_:-MyfbZiO1zz7KRPsOlXA:b-r0m79) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L6)):*
> ```objc
> #ifndef LIBPMEMSTREAM_SINGLY_LINKED_LIST_H
> #define LIBPMEMSTREAM_SINGLY_LINKED_LIST_H
> ```

pls add a general comment about this list (i.a. pls add info it's based on a list from PMDK)
___
*[src/singly_linked_list.h, line 28 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myfc7CM2w6kS4Q84BBG:-Myfc7CM2w6kS4Q84BBH:bmp6u1s) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L28)):*
> ```objc
> 		(list)->head = INVALID_PTR;                                                                            \
> 		(list)->tail = INVALID_PTR;                                                                            \
> 	} while (/*CONSTCOND*/ 0)
> ```

pls drop this comment



_Suggestion:_
```objc
/*CONSTCOND*/
```
___
*[src/singly_linked_list.h, line 33 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfdIot7va7vAqPebWJ:-MyfdIot7va7vAqPebWK:bgs75p9) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L33)):*
> ```objc
> 	do {                                                                                                           \
> 		if ((list)->tail == INVALID_PTR) {                                                                     \
> 			(list)->tail = offset;                                                                         \
> ```

sometimes you write `offset`, sometimes `(offset)` - pls unify
___
*[tests/CMakeLists.txt, line 106 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8XSsqBSeFqx8-n8Pd:-Myfcu7U4kcd-WOTCrAn:bs6adnb) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/tests/CMakeLists.txt#L106)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done - test name is not changed
___
*[tests/CMakeLists.txt, line 141 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myfd4ls10RKDL2orkq7:-Myfd4ls10RKDL2orkq8:b-2ves29) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/tests/CMakeLists.txt#L141)):*
> ```CMake
> 
> 	build_test_rc(NAME slist SRC_FILES unittest/singly_linked_list.cpp)
> 	add_test_generic(NAME slist TRACERS none)
> ```

perhaps add memcheck...?
___
*[tests/unittest/slist.cpp, line 0 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfcnWBBjZRh04HFLXL:-MyfcnWBBjZRh04HFLXM:b8k5gwq) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/tests/unittest/slist.cpp#L0)):*
why did you remove this test file?


<!-- Sent from Reviewable.io -->

2022-03-21 10:46 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 0 of 5 files reviewed, 14 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 20 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg3Yel8m9m-bTLT9fS:-Myg3YemEZ6uRZ_zL9db:b-vyh218) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L20)):*
> ```objc
> };
> 
> #define INVALID_PTR UINT64_MAX
> ```

Please add some prefix (like SLIST_INVALID_PTR).

Also, this is probably an offset, not pointer.
___
*[src/singly_linked_list.h, line 37 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg3vPl4A096gB8Bm9O:-Myg3vPl4A096gB8Bm9P:bko6a5j) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L37)):*
> ```objc
> 		SLIST_NEXT(type, runtime, offset, field) = (list)->head;                                               \
> 		(list)->head = offset;                                                                                 \
> 	} while (0)
> ```

Please keep it consistent (either /*CONSTCOND*/ 0 everuwhere or nowhere)
___
*[tests/unittest/singly_linked_list.cpp, line 77 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg4C_f1z6xpHxI-WuP:-Myg4C_f1z6xpHxI-WuQ:bxl55w9) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L77)):*
> ```cpp
> 		uint64_t it = 0;
> 		auto rit = data.rbegin();
> 		SLIST_FOREACH(struct node, &runtime, &list, it, next)
> ```

Please also check size of the list, right now this test will pass for any empty list (also fix for other testcases)
___
*[tests/unittest/singly_linked_list.cpp, line 156 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg46MAC8BYYVh0i2J3:-Myg46MAC8BYYVh0i2J4:bkzjgqx) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L156)):*
> ```cpp
> 
> 		std::vector<struct node> mod_data(data);
> 		auto random_item_pos = mod_data.size() ? static_cast<size_t>(rand()) % mod_data.size() : 0;
> ```

Do not use rand(), either reimplement it with rc or remove this test for now.


<!-- Sent from Reviewable.io -->

2022-03-21 13:10 UTC, KFilipek reviewed
> Reviewed 1 of 4 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbH0J3deR7__KeJ9r):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to repeat the same you have in the first commit line :wink: you can rather expand the info, why is it useful for multi-region support
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 6 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbZiN7E336g48o3l_:-MygOo3b6ALRfAPc5Nig:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a general comment about this list (i.a. pls add info it's based on a list from PMDK)
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 20 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg3Yel8m9m-bTLT9fS:-MygP7mJ1qjTAVL02nPX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add some prefix (like SLIST_INVALID_PTR).

Also, this is probably an offset, not pointer.
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 28 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myfc7CM2w6kS4Q84BBG:-MygPZVd9BfEK8wWm27r:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop this comment
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 33 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfdIot7va7vAqPebWJ:-MygQ1763OyNkALe0gN9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sometimes you write `offset`, sometimes `(offset)` - pls unify
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 37 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg3vPl4A096gB8Bm9O:-MygQ0y8DJ0HsQqP9fAI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L37)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please keep it consistent (either /*CONSTCOND*/ 0 everuwhere or nowhere)
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 106 at r2](https://reviewable.io/reviews/pmem/pmemstream/145#-My8XSsqBSeFqx8-n8Pd:-MygQYef3SBlNazsWsb8:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99009ea246da9f1de8ab2ab79ecf180b66e73314/tests/CMakeLists.txt#L106)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done - test name is not changed
</blockquote></details>

Done.
___
*[tests/unittest/slist.cpp, line  at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfcnWBBjZRh04HFLXL:-MygQpIM3nqSySlTJpFz:b-ba1b4f) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/tests/unittest/slist.cpp#L)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why did you remove this test file?
</blockquote></details>

I renamed file name without adding new file to git


<!-- Sent from Reviewable.io -->

2022-03-21 13:40 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: 2 of 5 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 77 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg4C_f1z6xpHxI-WuP:-MyghMjP5nCNLYcQvycq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also check size of the list, right now this test will pass for any empty list (also fix for other testcases)
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 156 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg46MAC8BYYVh0i2J3:-MyghNWKE14zUhqAUHNp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L156)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do not use rand(), either reimplement it with rc or remove this test for now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-21 15:04 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 3 files at r14, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: all files reviewed, 14 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[-- commits, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbH0J3deR7__KeJ9r):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done, still no expanded info how is this helpful for multi-region support
___
*[src/singly_linked_list.h, line 6 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbZiN7E336g48o3l_:-Mygm6kc3FBc4HZoJAJT:byehxup) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L6)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1. pls add info it's based on the implementation in PMDK
2. this description is very generic - it's not our public API it doesn't have to be. How does it apply in this repository?
___
*[tests/unittest/singly_linked_list.cpp, line 128 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-Mygwf-h8T9gpZO34PYE:-Mygwf-h8T9gpZO34PYF:b-tri2yy) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L128)):*
> ```cpp
> 
> 		std::vector<struct node> mod_data = data;
> 		std::vector<struct node>::iterator it = mod_data.begin();
> ```

`auto`
___
*[tests/unittest/singly_linked_list.cpp, line 131 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygsjGX1-wXKOb9cLUu:-MygsjGYDVwZUOmi6N-P:bjdny4d) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L131)):*
> ```cpp
> 		if (it != mod_data.end())
> 			it = mod_data.erase(it);
> 		if (list.head != UINT64_MAX) {
> ```

uint64_max?
___
*[tests/unittest/singly_linked_list.cpp, line 135 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-Mygt2GmC5xv0YI4vg9o:-Mygt2GmC5xv0YI4vg9p:bbja9gs) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L135)):*
> ```cpp
> 		}
> 
> 		uint64_t l_it = list.head;
> ```

pls add comment(s)
___
*[tests/unittest/singly_linked_list.cpp, line 136 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygsjjG5-3tnM-I0307:-MygsjjG5-3tnM-I0308:bjdny4d) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L136)):*
> ```cpp
> 
> 		uint64_t l_it = list.head;
> 		if (l_it == UINT64_MAX)
> ```

uint64_max?
___
*[tests/unittest/singly_linked_list.cpp, line 139 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygwbVU0Gl4fWMrJfpZ:-MygwbVU0Gl4fWMrJfp_:baddep7) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L139)):*
> ```cpp
> 			return;
> 
> 		auto v_it = mod_data.begin();
> ```

you already have such iterator - `it`
___
*[tests/unittest/singly_linked_list.cpp, line 169 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygyPSH362vPecU5wnF:-MygyPSH362vPecU5wnG:bo589me) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L169)):*
> ```cpp
> 		auto l_it = list.head;
> 		size_t i;
> 		for (i = 0; i < random_item_pos; ++i) {
> ```

you can move `size_t i` here
___
*[tests/unittest/singly_linked_list.cpp, line 184 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygyC_a4fNeGXEU5dU8:-MygyC_a4fNeGXEU5dU9:bo117y4) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L184)):*
> ```cpp
> 			RC_ASSERT(((node *)(pmemstream_offset_to_ptr(&runtime, l_it)))->data == v_it->data);
> 			v_it++;
> 		}
> ```

pls check if list size is now `== data.size() -1`


<!-- Sent from Reviewable.io -->

2022-03-22 09:09 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[tests/unittest/singly_linked_list.cpp, line 77 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg4C_f1z6xpHxI-WuP:-MyksRnm9QGyaNY5wkvc:bsztwfq) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L77)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done, Now, list with just one element will always pass this test.


<!-- Sent from Reviewable.io -->

2022-03-22 11:14 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[-- commits, line 4 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbH0J3deR7__KeJ9r):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done, still no expanded info how is this helpful for multi-region support
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 6 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbZiN7E336g48o3l_:-Myl2JDUCOTczNLl6MyL:blu50q3) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L6)):*
>  it's not our public API it doesn't have to be. How does it apply in this repository?
Check this
___
*[tests/unittest/singly_linked_list.cpp, line 77 at r15](https://reviewable.io/reviews/pmem/pmemstream/145#-Myg4C_f1z6xpHxI-WuP:-Myl4W-b2Z1L9cyPJv-m:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4878a5367d6ea2a4a6dfaae0f6c4fc7d4af0c92e/tests/unittest/singly_linked_list.cpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still not done, Now, list with just one element will always pass this test.
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 128 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-Mygwf-h8T9gpZO34PYE:-MylBp7r8eCr8VvqD_Ho:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L128)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`auto`
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 131 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygsjGX1-wXKOb9cLUu:-MylBpo98bpemmQZNJ0B:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

uint64_max?
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 135 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-Mygt2GmC5xv0YI4vg9o:-MylCRc62MVGFMBWJD1_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L135)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add comment(s)
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 136 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygsjjG5-3tnM-I0307:-MylCkbDElWVJ3OCv6K3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L136)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

uint64_max?
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 139 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygwbVU0Gl4fWMrJfpZ:-MylD-p_DAVv-HrVBJ5j:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L139)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you already have such iterator - `it`
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 169 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygyPSH362vPecU5wnF:-MylDchK4u4qSmWMNsVw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L169)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can move `size_t i` here
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 184 at r16](https://reviewable.io/reviews/pmem/pmemstream/145#-MygyC_a4fNeGXEU5dU8:-MylKMik-ULo-6c2mVfl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fb9af12b2cc6e733de80d54e64fd16bf5a6cb6a2/tests/unittest/singly_linked_list.cpp#L184)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls check if list size is now `== data.size() -1`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-22 11:30 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145#-:-MylNyd14iJvkMFBJ3AS:bnfp4nl)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 83 at r17](https://reviewable.io/reviews/pmem/pmemstream/145#-MylNnDf3eo32VsKsJJV:-MylNnDf3eo32VsKsJJW:bkjsvve) ([raw file](https://github.com/pmem/pmemstream/blob/810f90d6534675575b95e6cb962391dc2ce22413/tests/unittest/singly_linked_list.cpp#L83)):*
> ```cpp
> 		SLIST_FOREACH(struct node, &runtime, &list, it, next)
> 		{
> 			RC_ASSERT(((node *)(pmemstream_offset_to_ptr(&runtime, it)))->data == rit->data);
> ```

Use GET_PTR here? (and in other places?)


<!-- Sent from Reviewable.io -->

2022-03-22 11:57 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145)* status: all files reviewed, 10 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-03-22 12:48 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/145#-:-MylepEG0SOClPtn29J2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[src/singly_linked_list.h, line 6 at r14](https://reviewable.io/reviews/pmem/pmemstream/145#-MyfbZiN7E336g48o3l_:-MylcmjeE-tpDgkPcyUH:b2nid0f) ([raw file](https://github.com/pmem/pmemstream/blob/c1122e3699e2cdb7b826acc6ee3957f22c6e36f2/src/singly_linked_list.h#L6)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>  it's not our public API it doesn't have to be. How does it apply in this repository?
Check this
</blockquote></details>

thx


<!-- Sent from Reviewable.io -->

2022-03-22 12:54 UTC, karczex approved these changes

2022-03-22 13:03 UTC, merged