Add rapid check tests for singly_linked_list
pmem/pmemstream pull request #147
Opened 2022-03-17 19:57 UTC by Karolina002

Check if head points to the last inserted element by SLIST_INSERT_HEAD
and if tail points to the last inserted element by SLIST_INSERT_TAIL

2022-03-18 09:02 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/147#-MyRFQed-ZRKfUu5pwtG:-MyRFQed-ZRKfUu5pwtH:btno1ox) (no related file):*
same issue - after rebase you should have more than 1 commit listed here :wink: 

---
___
*[tests/CMakeLists.txt, line 103 at r1](https://reviewable.io/reviews/pmem/pmemstream/147#-MyRFfKI8ETlbX20mM1i:-MyRFfKJ7VdZ7liwamUt:brb6wih) ([raw file](https://github.com/pmem/pmemstream/blob/3092880e301fa7c5e781af81ae8eebab93ffee78/tests/CMakeLists.txt#L103)):*
> ```CMake
> add_test_generic(NAME reserve_and_publish TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test(slist_insert_test unittest/slist_insert_test.cpp)
> ```

did you forget to push that file...?


<!-- Sent from Reviewable.io -->

2022-03-22 08:51 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 103 at r1](https://reviewable.io/reviews/pmem/pmemstream/147#-MyRFfKI8ETlbX20mM1i:-MykomWj2Ve6AscDR7w9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3092880e301fa7c5e781af81ae8eebab93ffee78/tests/CMakeLists.txt#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you forget to push that file...?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-23 07:44 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[tests/unittest/slist_insert_test.cpp, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/147#-MypieVp2vYBgoTN5gFO:-MypieVp2vYBgoTN5gFP:bkktpi1) ([raw file](https://github.com/pmem/pmemstream/blob/1d5c09c78d1b4d50d2f16d410b839f7c0f7966b2/tests/unittest/slist_insert_test.cpp#L52)):*
> ```cpp
> int main(int argc, char *argv[])
> {
> 	return run_test([] {
> ```

you can rebase to master and put these new tests into `singly_linked_list.cpp` test file

please also consider if these tests can be merged with the existing ones (perhaps they cover the same cases)


<!-- Sent from Reviewable.io -->

2022-03-28 20:42 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/147#-MyRFQed-ZRKfUu5pwtG:-MzHEdpt-p5xhSo5274N:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

same issue - after rebase you should have more than 1 commit listed here :wink: 
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-04-01 09:53 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/147#-MzZX4gwEJLQmZHHVIPY:-MzZX4gwEJLQmZHHVIPZ:bvqql2i) (no related file):*
copy-pasted from another review; written by Igor:

```
I see we are missing return checks (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L17) and run_test (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L14)
```

---


<!-- Sent from Reviewable.io -->

2022-04-04 08:13 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 7 unresolved discussions (waiting on @Karolina002)

___
*[tests/unittest/singly_linked_list.cpp, line 205 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbpFg-bgel05iQnJP:-MznbpFg-bgel05iQnJQ:b-ovr3rp) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L205)):*
> ```cpp
> 	});
> 
> 	rc::check("Insert remove insert", [](const std::vector<struct node> &data) {
> ```

while this test is nice (it tests random inserts, random removals, and again some random inserts), I believe what Paweł meant by "insert-remove-insert" test was:

Insert data_A, remove data_A, insert data_A - it could be done on previously empty SLIST or partially filled SLIST (you can test both scenarios with an extra bool param in the test).
___
*[tests/unittest/singly_linked_list.cpp, line 219 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-Mznb7EIEcyYsIcCUsAO:-Mznb7EIEcyYsIcCUsAP:bv8es8t) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L219)):*
> ```cpp
> 		/* Add size()-1 elements to list */
> 		uint64_t offset = 0;
> 		for (size_t i = 0; i < data.size() - 1; ++i) {
> ```

since the last element is of any significance to you, you might just pop it from the `data` vector and save it for later...

or you may just extend this test and have 2 lists - 1 for inserts, do some random removals (random number and random positions), and then e.g. insert some other vector with extra_data
___
*[tests/unittest/singly_linked_list.cpp, line 224 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzn_gZzC_4dp8DCxO8g:-Mzn_gZzC_4dp8DCxO8h:b-ton68k) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L224)):*
> ```cpp
> 		}
> 
> 		/* Remove random element from both lists */
> ```

this comment is weird, suddenly some `both lists` - I guess you may want to re-phrase it...

.. or just move this comment before the `for` loop...?
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznZz4j6lOD39PTDdjj:-MznZz4j6lOD39PTDdjk:b-13dah7) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L225)):*
> ```cpp
> 
> 		/* Remove random element from both lists */
> 		auto random_item_pos = *rc::gen::inRange<size_t>(1, data.size() - 1);
> ```

`(0, ` because position 0 is a valid position to remove
___
*[tests/unittest/singly_linked_list.cpp, line 244 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznaK9f7NunHRPi-t5q:-MznaK9f7NunHRPi-t5r:b-18r9cs) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L244)):*
> ```cpp
> 		/* Check correctness */
> 		l_it = list.head;
> 		auto v_it = mod_data.begin();
> ```

you don't need a new variable for that, you already have r_it
___
*[tests/unittest/singly_linked_list.cpp, line 250 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbkVY2dNoodvsrYF3:-MznbkVY2dNoodvsrYF4:bm8jpda) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L250)):*
> ```cpp
> 			v_it++;
> 		}
> 		RC_ASSERT(v_it == mod_data.end());
> ```

you may also want to check is l_it->next is INVALID


<!-- Sent from Reviewable.io -->

2022-04-04 15:52 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/147#-MzZX4gwEJLQmZHHVIPY:-Mzp4zgJ4Mb2_baIqjBf:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

copy-pasted from another review; written by Igor:

```
I see we are missing return checks (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L17) and run_test (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L14)
```
</blockquote></details>

Done.

---
___
*[tests/unittest/singly_linked_list.cpp, line 205 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbpFg-bgel05iQnJP:-MzpGMpd1tvSax6NG6Fl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L205)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

while this test is nice (it tests random inserts, random removals, and again some random inserts), I believe what Paweł meant by "insert-remove-insert" test was:

Insert data_A, remove data_A, insert data_A - it could be done on previously empty SLIST or partially filled SLIST (you can test both scenarios with an extra bool param in the test).
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 219 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-Mznb7EIEcyYsIcCUsAO:-MzpGRgo7bx3Xn-NvaEM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L219)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since the last element is of any significance to you, you might just pop it from the `data` vector and save it for later...

or you may just extend this test and have 2 lists - 1 for inserts, do some random removals (random number and random positions), and then e.g. insert some other vector with extra_data
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 224 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzn_gZzC_4dp8DCxO8g:-MzpGYNbA0AVXf_mh4h5:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L224)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this comment is weird, suddenly some `both lists` - I guess you may want to re-phrase it...

.. or just move this comment before the `for` loop...?
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznZz4j6lOD39PTDdjj:-MzpGZmT2_Mxa3kHd3LF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L225)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`(0, ` because position 0 is a valid position to remove
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 244 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznaK9f7NunHRPi-t5q:-MzpG_QqCaLAk6yPsAGO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L244)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't need a new variable for that, you already have r_it
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 250 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbkVY2dNoodvsrYF3:-MzpGa1gDsnJ7u5lneiP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L250)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may also want to check is l_it->next is INVALID
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 09:10 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 11 unresolved discussions (waiting on @Karolina002)

___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsntS9BHAitRevnJxD):*
pls be more precise, at least inform you clean up in singly linked list test; at best inform what you're changing (not necessarily verbose description)
___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsotIG53wYT_OBx8tM):*
If I see correctly you also add a new test in this commit; either fix by updating commit msg, or by splitting the commit - I personally would make a single commit fix fixes to existing tests and in a separate commit, I'd add all new tests.
___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsnusb-AkL-28_lw_s):*
1. if you want to write some prefix, use just "tests: "
2. as above, pls be more precise, reading this commit msg I have no idea that it's for SLIST :wink: 
___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsojIw9NqnylmxtUgL):*
also, this commit not only adds a new test but also changes something in another test
___
*[tests/unittest/singly_linked_list.cpp, line 205 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbpFg-bgel05iQnJP:-Mzsvhg84MGY2FZj_UPD:bomgy36) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L205)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Right now this test do some other scenario:
```
1. insert vector with data
2. remove 1 element
3. adds 1 element
```

as I said, you should:
```
1. add a vector of data
2. remove all elements of data 
3. add them all again
```

with this approach, it should be fairly easy to generate 2 vectors (e.g., `... &data, ... &extra_data, bool is_empty`). In verification phase you expect `data` or `data + extra_data` (see example in our tests: https://github.com/pmem/pmemstream/blob/master/tests/unittest/append.cpp#L24-L26 )
___
*[tests/unittest/singly_linked_list.cpp, line 38 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzspaFt6_c3pAp7dTks:-MzspaFu5P67UG-lYs93:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L38)):*
> ```cpp
> int main(int argc, char *argv[])
> {
> ```

redundant empty line
___
*[tests/unittest/singly_linked_list.cpp, line 72 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyCoz6rCQTdM1M6R7:-MzsyCoz6rCQTdM1M6R8:b-6qsh16) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L72)):*
> ```cpp
> 			uint64_t offset = 0;
> 			for (size_t i = 0; i < data.size(); ++i) {
> 				SLIST_INSERT_HEAD(struct node, &runtime, &list, offset, next);
> ```

we never check for:
`Head points to last inserted element by SLIST_INSERT_HEAD)`
pls do it, for example, here
___
*[tests/unittest/singly_linked_list.cpp, line 103 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyJky7tU3as_w4mIC:-MzsyJky7tU3as_w4mID:b2mm0td) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L103)):*
> ```cpp
> 			uint64_t offset = 0;
> 			for (size_t i = 0; i < data.size(); ++i) {
> 				SLIST_INSERT_TAIL(struct node, &runtime, &list, offset, next);
> ```

the same here:
`Tail points to last inserted element by SLIST_INSERT_TAIL`
___
*[tests/unittest/singly_linked_list.cpp, line 144 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyzW98wqRMzCA7bYV:-MzsyzW98wqRMzCA7bYW:bnlvbb1) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L144)):*
> ```cpp
> 				it = mod_data.erase(it);
> 			if (list.head != SLIST_INVALID_OFFSET) {
> 				SLIST_REMOVE_HEAD(struct node, &runtime, &list, next);
> ```

you could re-design this test to do more than 1 random removal (and verify after each removal)
___
*[tests/unittest/singly_linked_list.cpp, line 195 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsyr31Ct-hmwOvY5Xy:-Mzsyr32DyloIDyZ-Tv8:bi3dkt2) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L195)):*
> ```cpp
> 
> 			mod_data.erase(r_it);
> 			SLIST_REMOVE(struct node, &runtime, &list, l_it, next);
> ```

the same here
___
*[tests/unittest/singly_linked_list.cpp, line 231 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsvbgh0BcYPYh4EA6-:-Mzsvbgh0BcYPYh4EA60:b-cg5vhc) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L231)):*
> ```cpp
> 
> 			/* Remove head */
> 			if (list.head != SLIST_INVALID_OFFSET) {
> ```

can `list.head` be invalid?


<!-- Sent from Reviewable.io -->

2022-04-07 06:46 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsntS9BHAitRevnJxD):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls be more precise, at least inform you clean up in singly linked list test; at best inform what you're changing (not necessarily verbose description)
</blockquote></details>

Done.
___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsotIG53wYT_OBx8tM):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

If I see correctly you also add a new test in this commit; either fix by updating commit msg, or by splitting the commit - I personally would make a single commit fix fixes to existing tests and in a separate commit, I'd add all new tests.
</blockquote></details>

I just moved test inside run_test
___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsnusb-AkL-28_lw_s):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. if you want to write some prefix, use just "tests: "
2. as above, pls be more precise, reading this commit msg I have no idea that it's for SLIST :wink: 
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 38 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzspaFt6_c3pAp7dTks:-N-1lYTh38wpGhrwtPOY:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 72 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyCoz6rCQTdM1M6R7:-N--y1Hl6WKBcMjrL9A0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we never check for:
`Head points to last inserted element by SLIST_INSERT_HEAD)`
pls do it, for example, here
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 103 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyJky7tU3as_w4mIC:-N--y1YMAkGMu0qZU6Xk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the same here:
`Tail points to last inserted element by SLIST_INSERT_TAIL`
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 144 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsyzW98wqRMzCA7bYV:-N--y2Sp7D8chbHf6lxG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L144)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could re-design this test to do more than 1 random removal (and verify after each removal)
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 195 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsyr31Ct-hmwOvY5Xy:-N--y4gSEyAuHuTw93qS:b-aeuhdj) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L195)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the same here
</blockquote></details>

Done, but doesn't work


<!-- Sent from Reviewable.io -->

2022-04-07 08:09 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 15 unresolved discussions (waiting on @Karolina002)

___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsotIG53wYT_OBx8tM):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I just moved test inside run_test
</blockquote></details>

if I'm not mistaken you're adding `Insert remove insert` test within this (first) commit)
___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsnusb-AkL-28_lw_s):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no 2. still applies in your commits. Even though all your commits do changes in SLIST tests, you still have to repeat information about it in each commit, because each commit is a separate unit
___
*[-- commits, line 11 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1tKWoCVI7Y-DTyxzc):*
pls fix that with a proper commit msg :wink: 

// reminder: https://pmem.io/blog/2014/09/git-workflow/
___
*[-- commits, line 22 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1v7GW1lT3sctSojd2):*
you don't have to copy-paste "the actual code here"; it's (usually) not necessary to precisely inform how many elements will be removed in the test, what's more important (what's the essence of the commit) - is that you make it work with the removal of more than just one element (as it was previously).

perhaps take a moment, please, and read some of the available guides, to avoid my comments :smile: 
// e.g. https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/
___
*[tests/unittest/singly_linked_list.cpp, line 205 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbpFg-bgel05iQnJP:-N-2351YDzlr4TfkbNjo:bsiw25l) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L205)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Right now this test do some other scenario:
```
1. insert vector with data
2. remove 1 element
3. adds 1 element
```

as I said, you should:
```
1. add a vector of data
2. remove all elements of data 
3. add them all again
```

with this approach, it should be fairly easy to generate 2 vectors (e.g., `... &data, ... &extra_data, bool is_empty`). In verification phase you expect `data` or `data + extra_data` (see example in our tests: https://github.com/pmem/pmemstream/blob/master/tests/unittest/append.cpp#L24-L26 )
</blockquote></details>

of course in the scenario, where you apply or not the initial data there's step 0 (based on the bool flag state), which inserts the initial data/or not. `extra_data` is for the actual scenario insert/remove/insert
___
*[tests/unittest/singly_linked_list.cpp, line 195 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsyr31Ct-hmwOvY5Xy:-N-21nq78o4ZboqhpzoY:b-ht07n4) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L195)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done, but doesn't work
</blockquote></details>

what do you mean? what's not working...?

// right now in CI whitespace check is not working, so I can't see any test issue
___
*[tests/unittest/singly_linked_list.cpp, line 74 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1wbjM12wPExZcvfrj:-N-1wbjM12wPExZcvfrk:b-vs9u78) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L74)):*
> ```cpp
> 				SLIST_INSERT_HEAD(struct node, &runtime, &list, offset, next);
> 
> 				/* Check if head points to last inserted element by SLIST_INSERT_HEAD) */
> ```

pls drop `)` at the end of the comment
___
*[tests/unittest/singly_linked_list.cpp, line 156 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2-LfY7tvPGg7RjPE0:-N-2-LfY7tvPGg7RjPE1:b6qqx8m) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L156)):*
> ```cpp
> 				if (it != mod_data.end())
> 					it = mod_data.erase(it);
> 				if (list.head != SLIST_INVALID_OFFSET) {
> ```

actually, this check seems redundant - it's included within SLIST_REMOVE_HEAD
___
*[tests/unittest/singly_linked_list.cpp, line 171 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2-qzH9u1SY8GWgDsz:-N-2-qzI6DmOab7A4eZD:b-6491kc) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L171)):*
> ```cpp
> 					it++;
> 				}
> 				RC_ASSERT(it == mod_data.end());
> ```

this also seems redundant, it's guaranteed by the `while` loop
___
*[tests/unittest/singly_linked_list.cpp, line 174 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-22BVuDe9udf7gCSK-:-N-22BVuDe9udf7gCSK0:b-gihpw9) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L174)):*
> ```cpp
> 				RC_ASSERT(l_it == SLIST_INVALID_OFFSET);
> 				RC_ASSERT(SLIST_INVARIANTS(struct node, &runtime, &list, next));
> 			}
> ```

you could add check like you have below



_Code quote:_
```cpp
RC_ASSERT(mod_data.size() == data.size() - i);
```
___
*[tests/unittest/singly_linked_list.cpp, line 202 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-20QS33DUGRt9kulcC:-N-20QS33DUGRt9kulcD:b-6pyvft) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L202)):*
> ```cpp
> 			for (size_t i = 1; i < num_of_rmv; ++i) {
> 				/* Remove random element from the list */
> 				auto random_item_pos = *rc::gen::inRange<size_t>(0, data.size());
> ```

you rather need `mod_data.size()`...
___
*[tests/unittest/singly_linked_list.cpp, line 204 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-21cpY50nCkAyKcKGg:-N-21cpY50nCkAyKcKGh:b3whcji) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L204)):*
> ```cpp
> 				auto random_item_pos = *rc::gen::inRange<size_t>(0, data.size());
> 
> 				auto r_it = mod_data.begin();
> ```

you can set `r_it` already to `mod_data.begin() + static_cast<long>(random_item_pos)`
___
*[tests/unittest/singly_linked_list.cpp, line 210 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-21OK9Eby7C9R-_dy6:-N-21OK9Eby7C9R-_dy7:bz1o9jo) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L210)):*
> ```cpp
> 					r_it++;
> 					l_it = SLIST_NEXT(struct node, &runtime, l_it, next);
> 					RC_ASSERT((SLIST_GET_PTR(node, &runtime, l_it))->data == r_it->data);
> ```

you don't have to verify each element (you do that in "check correctness" below); I guess you could do just one check, right before the removal
___
*[tests/unittest/singly_linked_list.cpp, line 254 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-22rF35s7I-CroE1Hk:-N-22rF35s7I-CroE1Hl:byxaz5f) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L254)):*
> ```cpp
> 				SLIST_REMOVE_HEAD(struct node, &runtime, &list, next);
> 			}
> ```

pls check here if the list contains what it should


<!-- Sent from Reviewable.io -->

2022-04-07 10:35 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 18 unresolved discussions (waiting on @Karolina002)

___
*[tests/unittest/singly_linked_list.cpp, line 74 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2Y3z855DA1xAY4xUW:-N-2Y3z855DA1xAY4xUX:b-r0l5kr) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L74)):*
> ```cpp
> 				SLIST_INSERT_HEAD(struct node, &runtime, &list, offset, next);
> 
> 				/* Check if head points to last inserted element by SLIST_INSERT_HEAD) */
> ```

You may move this sentence from comment to test description



_Code quote:_
```cpp
head points to last inserted element by SLIST_INSERT_HEAD
```
___
*[tests/unittest/singly_linked_list.cpp, line 110 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2Yi2M4yCsRI9MpW-9:-N-2Yi2M4yCsRI9MpW-A:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L110)):*
> ```cpp
> 				SLIST_INSERT_TAIL(struct node, &runtime, &list, offset, next);
> 
> 				/* Check if tail points to last inserted element by SLIST_INSERT_TAIL */
> ```

.
___
*[tests/unittest/singly_linked_list.cpp, line 148 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2ZDZc9zh5VSuU2urD:-N-2ZDZc9zh5VSuU2urE:bky0t22) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L148)):*
> ```cpp
> 
> 			/* Number of elements to remove */
> 			auto num_of_rmv = *rc::gen::inRange<size_t>(1, data.size());
> ```

this value may be moved to lambda definition 
```
ret += rc::check("Remove head", [](const std::vector<struct node> &data, size_t &num_to_rmv) {
```


<!-- Sent from Reviewable.io -->

2022-04-10 19:30 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 18 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[-- commits, line 3 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-MzsotIG53wYT_OBx8tM):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if I'm not mistaken you're adding `Insert remove insert` test within this (first) commit)
</blockquote></details>

Done.
___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsnusb-AkL-28_lw_s):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no 2. still applies in your commits. Even though all your commits do changes in SLIST tests, you still have to repeat information about it in each commit, because each commit is a separate unit
</blockquote></details>

Done.
___
*[-- commits, line 11 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1tKWoCVI7Y-DTyxzc):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix that with a proper commit msg :wink: 

// reminder: https://pmem.io/blog/2014/09/git-workflow/
</blockquote></details>

Done.
___
*[-- commits, line 22 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1v7GW1lT3sctSojd2):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to copy-paste "the actual code here"; it's (usually) not necessary to precisely inform how many elements will be removed in the test, what's more important (what's the essence of the commit) - is that you make it work with the removal of more than just one element (as it was previously).

perhaps take a moment, please, and read some of the available guides, to avoid my comments :smile: 
// e.g. https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 195 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsyr31Ct-hmwOvY5Xy:-N-JclqU9ks10iqElBDh:bsopa6b) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L195)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean? what's not working...?

// right now in CI whitespace check is not working, so I can't see any test issue
</blockquote></details>

nvm, one of your previous comments solved this problem
___
*[tests/unittest/singly_linked_list.cpp, line 231 at r5](https://reviewable.io/reviews/pmem/pmemstream/147#-Mzsvbgh0BcYPYh4EA6-:-N-Jchn-ASG4omLmDTx7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a96051b03c51bb82315fb11abe65f251eff92d89/tests/unittest/singly_linked_list.cpp#L231)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can `list.head` be invalid?
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 74 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-1wbjM12wPExZcvfrj:-N-Je3QZ93bJUw6yyGqB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop `)` at the end of the comment
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 74 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2Y3z855DA1xAY4xUW:-N-Je31T2TAIDFhXbKxJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L74)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may move this sentence from comment to test description
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 110 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2Yi2M4yCsRI9MpW-9:-N-Je2UH0tD2s7qyi-uq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L110)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 148 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2ZDZc9zh5VSuU2urD:-N-JdF9o7GP_jgDf1O4B:bbn73up) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L148)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

this value may be moved to lambda definition 
```
ret += rc::check("Remove head", [](const std::vector<struct node> &data, size_t &num_to_rmv) {
```
</blockquote></details>

It caused troubles and I changed it back



_Code snippet:_
```cpp
- Remove head
Gave up after 11 tests

/home/karolina/Documents/Docker/Share/PMDK/pmemstream/tests/unittest/singly_linked_list.cpp:132:
RC_PRE(num_to_rmv > 0 && num_to_rmv <= data.size())

Expands to:
10991545238813875741 > 0 && false
```
___
*[tests/unittest/singly_linked_list.cpp, line 156 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2-LfY7tvPGg7RjPE0:-N-JdBydCrlH78b1IXwV:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L156)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, this check seems redundant - it's included within SLIST_REMOVE_HEAD
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 171 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2-qzH9u1SY8GWgDsz:-N-JdBWR2YSPtAcZPdVa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L171)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this also seems redundant, it's guaranteed by the `while` loop
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 174 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-22BVuDe9udf7gCSK-:-N-Jd7RT1H7q4O7LmVQ9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L174)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add check like you have below
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 202 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-20QS33DUGRt9kulcC:-N-Jd6Cv55Kb3eKxq6qA:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L202)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you rather need `mod_data.size()`...
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 204 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-21cpY50nCkAyKcKGg:-N-Jd5PuDjiIxhuXDBJW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L204)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can set `r_it` already to `mod_data.begin() + static_cast<long>(random_item_pos)`
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 210 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-21OK9Eby7C9R-_dy6 [...]

2022-04-10 21:34 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 18 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 205 at r4](https://reviewable.io/reviews/pmem/pmemstream/147#-MznbpFg-bgel05iQnJP:-N-KObDb7x48lilFFgtE:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ace7129b34be9e6cd4696405c28cd471bc899347/tests/unittest/singly_linked_list.cpp#L205)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of course in the scenario, where you apply or not the initial data there's step 0 (based on the bool flag state), which inserts the initial data/or not. `extra_data` is for the actual scenario insert/remove/insert
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 09:18 UTC, KFilipek requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 19 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 148 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2ZDZc9zh5VSuU2urD:-N-Mu1o0C8mGL5EjBXyr:b-rnzltd) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L148)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

It caused troubles and I changed it back
</blockquote></details>

Have you `RC_PRE(num_to_rmv < data.size())` earlier?
___
*[tests/unittest/singly_linked_list.cpp, line 158 at r8](https://reviewable.io/reviews/pmem/pmemstream/147#-N-MuN7BErlPcnlUbZQ1:-N-MuN7BErlPcnlUbZQ2:btb7k01) ([raw file](https://github.com/pmem/pmemstream/blob/4f38b41231fdc157ccd66764c25899d7add3d424/tests/unittest/singly_linked_list.cpp#L158)):*
> ```cpp
> 				auto it = mod_data.begin();
> 				if (it != mod_data.end())
> 					it = mod_data.erase(it);
> ```

it looks like:
```cpp
mod_data.erase(mod_data.begin());
```
`it != mod_data.end()` should be guaranteed by `num_to_rmv < mod_data.size()`, right?



_Code quote:_
```cpp
				auto it = mod_data.begin();
				if (it != mod_data.end())
					it = mod_data.erase(it);
```


<!-- Sent from Reviewable.io -->

2022-04-13 16:41 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 19 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 158 at r8](https://reviewable.io/reviews/pmem/pmemstream/147#-N-MuN7BErlPcnlUbZQ1:-N-YmgE8ANCxyQ83b6Zk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4f38b41231fdc157ccd66764c25899d7add3d424/tests/unittest/singly_linked_list.cpp#L158)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

it looks like:
```cpp
mod_data.erase(mod_data.begin());
```
`it != mod_data.end()` should be guaranteed by `num_to_rmv < mod_data.size()`, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 12:16 UTC, KFilipek requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 19 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 148 at r6](https://reviewable.io/reviews/pmem/pmemstream/147#-N-2ZDZc9zh5VSuU2urD:-N-bkN7H3g9txOWeyAex:b-bmvzws) ([raw file](https://github.com/pmem/pmemstream/blob/7bd6b1ba244c12df0a87374bb19a7c0b537daa83/tests/unittest/singly_linked_list.cpp#L148)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Have you `RC_PRE(num_to_rmv < data.size())` earlier?
</blockquote></details>

we agreed that is ok
___
*[tests/unittest/singly_linked_list.cpp, line 149 at r9](https://reviewable.io/reviews/pmem/pmemstream/147#-N-bk_vKEFBUs9liIKKN:-N-bk_vKEFBUs9liIKKO:b-gyxcuu) ([raw file](https://github.com/pmem/pmemstream/blob/c1a4eef1e8a3f52d497a89a29c89feea10af05d5/tests/unittest/singly_linked_list.cpp#L149)):*
> ```cpp
> 
> 			/* Number of elements to remove */
> 			auto num_to_rmv = *rc::gen::inRange<size_t>(1, data.size());
> ```

in range generates values <1, data.size()) so you never remove all elements



_Code quote:_
```cpp
data.size()
```


<!-- Sent from Reviewable.io -->

2022-04-19 09:11 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 17 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 194 at r9](https://reviewable.io/reviews/pmem/pmemstream/147#-N0039cE9VmpoUPmSv8p:-N000bsJ189TuImtM5Bi:boyknau) ([raw file](https://github.com/pmem/pmemstream/blob/c1a4eef1e8a3f52d497a89a29c89feea10af05d5/tests/unittest/singly_linked_list.cpp#L194)):*
> ```cpp
> 				auto random_item_pos = *rc::gen::inRange<size_t>(0, mod_data.size());
> 
> 				auto r_it = mod_data.begin() + static_cast<long>(random_item_pos);
> ```

To avoid cast you may use [std::advance](https://en.cppreference.com/w/cpp/iterator/advance) 



_Code quote:_
```cpp
static_cast<long>(random_item_pos);
```


<!-- Sent from Reviewable.io -->

2022-04-21 10:00 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 17 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list.cpp, line 149 at r9](https://reviewable.io/reviews/pmem/pmemstream/147#-N-bk_vKEFBUs9liIKKN:-N0AZC-F4f-NNUi4I9dL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1a4eef1e8a3f52d497a89a29c89feea10af05d5/tests/unittest/singly_linked_list.cpp#L149)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

in range generates values <1, data.size()) so you never remove all elements
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 194 at r9](https://reviewable.io/reviews/pmem/pmemstream/147#-N0039cE9VmpoUPmSv8p:-N0AZDlq8y6UhOr3LmEL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c1a4eef1e8a3f52d497a89a29c89feea10af05d5/tests/unittest/singly_linked_list.cpp#L194)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

To avoid cast you may use [std::advance](https://en.cppreference.com/w/cpp/iterator/advance) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-26 17:42 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/singly_linked_list.cpp` line 158 at r10](https://reviewable.io/reviews/pmem/pmemstream/147#-N0UpNA91BbTzWKK5Rxm:-N0axyzT6G8a2V36osfP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/9e4838465cce109a6dae1c1188d5c7f69419e425/tests/unittest/singly_linked_list.cpp#L158)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this check?
</blockquote></details>

Done.
___
*[`tests/unittest/singly_linked_list.cpp` line 239 at r10](https://reviewable.io/reviews/pmem/pmemstream/147#-N0Us8W7AOpCypEOKLc0:-N0axzYG2Ou7M_blmCmX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/9e4838465cce109a6dae1c1188d5c7f69419e425/tests/unittest/singly_linked_list.cpp#L239)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update the test description - it should, as in other property-based tests, be describing "the property"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 07:14 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex, @Karolina002, and @KFilipek)

___
*[`-- commits` line 20 at r11](https://reviewable.io/reviews/pmem/pmemstream/147#-N0dqgA-DrFpUqVfEO-6):*
this commit could be easily merged with the previous one... which adds that test :wink: 
___
*[`tests/unittest/singly_linked_list.cpp` line 239 at r10](https://reviewable.io/reviews/pmem/pmemstream/147#-N0Us8W7AOpCypEOKLc0:-N0drIqlArX8XhWVfQNj:b-ilnxtb) ([raw file](https://github.com/pmem/pmemstream/blob/9e4838465cce109a6dae1c1188d5c7f69419e425/tests/unittest/singly_linked_list.cpp#L239)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

huh, not quite - I believe, the property here is that you can re-insert elements to the list after they were removed from that list


<!-- Sent from Reviewable.io -->

2022-04-27 09:43 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147#-:-N0eOvT0C24scdlfBTsb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-04-27 10:25 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147#-:-N0eYXp46HVnR_kHv1fC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-04-27 11:18 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/147#-:-N0ejeOb5UQww3CjFlo-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)



<!-- Sent from Reviewable.io -->

2022-04-27 11:19 UTC, merged