Add macro to handle returned value in reserve publish example
pmem/pmemstream pull request #149
Opened 2022-03-22 13:57 UTC by KFilipek

This macro handles returned value to check is it correct, even in release mode.

2022-03-22 16:12 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNrzU3_YVrPzlPMy0):*
"check (if) it is"
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymOAoMCcs20eTVoooB):*
the body of this commit msg pretty much repeats the first line above
___
*[examples/03_reserve_publish/main.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNG_Y1IIJ5SpghXoK:-MymNG_Y1IIJ5SpghXoL:b-rdz9lo) ([raw file](https://github.com/pmem/pmemstream/blob/7fd83a73132b5a9a283901844812fcf17efd1c20/examples/03_reserve_publish/main.cpp#L4)):*
> ```cpp
> /* Copyright 2022, Intel Corporation */
> 
> #include "examples_helpers.h"
> ```

perhaps define this macro in that examples helpers header
___
*[examples/03_reserve_publish/main.cpp, line 29 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNQSk-6reShfJ8vGM:-MymNQSk-6reShfJ8vGN:b-8btizg) ([raw file](https://github.com/pmem/pmemstream/blob/7fd83a73132b5a9a283901844812fcf17efd1c20/examples/03_reserve_publish/main.cpp#L29)):*
> ```cpp
> };
> 
> #define CHECK_ERROR(var)                                                                                               \
> ```

consider, similarly to pmemkv, defining this as (more generic) `ASSERT(expr)` (https://github.com/pmem/pmemkv/blob/master/examples/pmemkv_basic_cpp/pmemkv_basic.cpp#L15)


<!-- Sent from Reviewable.io -->

2022-03-23 09:04 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 29 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNQSk-6reShfJ8vGM:-Myq-kF34R2XmhA18qz9:bavrhfs) ([raw file](https://github.com/pmem/pmemstream/blob/7fd83a73132b5a9a283901844812fcf17efd1c20/examples/03_reserve_publish/main.cpp#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

consider, similarly to pmemkv, defining this as (more generic) `ASSERT(expr)` (https://github.com/pmem/pmemkv/blob/master/examples/pmemkv_basic_cpp/pmemkv_basic.cpp#L15)
</blockquote></details>

+1 however the pmemkv macro is a bit broken, expr will be executed twice, - you could just do something like 'if(!cond) assert(false)'


<!-- Sent from Reviewable.io -->

2022-03-23 09:58 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/149#-MyqAumP7hNtO2iD2rXP:-MyqAumQ6NhXUU_RYyek:b-9g7j9p) ([raw file](https://github.com/pmem/pmemstream/blob/d4491e4d66fba192ad4b858df437d35b11c0de9f/src/singly_linked_list.h#L2)):*
> ```objc
> /*
>  * Source: glibc 2.24 (git://sourceware.org/glibc.git /misc/sys/queue.h)
> ```

This should be separate commit. 

Intel's copyright should be present, since 2022


<!-- Sent from Reviewable.io -->

2022-03-23 13:20 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNrzU3_YVrPzlPMy0):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"check (if) it is"
</blockquote></details>

Done.
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymOAoMCcs20eTVoooB):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the body of this commit msg pretty much repeats the first line above
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNG_Y1IIJ5SpghXoK:-MyqvYLuCdU1sPfEffWK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7fd83a73132b5a9a283901844812fcf17efd1c20/examples/03_reserve_publish/main.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps define this macro in that examples helpers header
</blockquote></details>

Done.
___
*[examples/03_reserve_publish/main.cpp, line 29 at r1](https://reviewable.io/reviews/pmem/pmemstream/149#-MymNQSk-6reShfJ8vGM:-MyqvYsdESgZEmYD5-eq:b-mnk1xc) ([raw file](https://github.com/pmem/pmemstream/blob/7fd83a73132b5a9a283901844812fcf17efd1c20/examples/03_reserve_publish/main.cpp#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1 however the pmemkv macro is a bit broken, expr will be executed twice, - you could just do something like 'if(!cond) assert(false)'
</blockquote></details>

Discarded like we discussed.


<!-- Sent from Reviewable.io -->

2022-03-24 08:56 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149#-:-Myv7zFL89N9ryj-9kU_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor and @karczex)



<!-- Sent from Reviewable.io -->

2022-03-24 09:32 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-03-24 12:10 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

it's OK as is, but to make this PR more valuable you may add to Ci buld which was failing - If I remember properly it was Release with Developer mode enabled.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149#-:-MyvowD67YnhtzfE5jHO:bwq1k7o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-03-24 12:58 UTC, lukaszstolarczuk commented
> <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/341bcbc4fc105a8a54332ced9ba9f1163b5fd81578777fffe7568934ec76d9d7/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67">
> 
> it's OK as is, but to make this PR more valuable you may add to Ci buld which was failing - If I remember properly it was Release with Developer mode enabled.
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/149#-:-MyvowD67YnhtzfE5jHO:bwq1k7o)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

I guess, we'll make that a sep. change. Merging as is 😉

2022-03-24 12:58 UTC, merged