Multi region test
pmem/pmemstream pull request #161
Opened 2022-03-30 15:12 UTC by KFilipek

2022-03-30 15:50 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/unittest/multi_region.cpp, line 12 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzQW2L25rLAzFehyf4o:-MzQW2L25rLAzFehyf4p:b6imvir) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L12)):*
> ```cpp
> #include "unittest.hpp"
> 
> int count_regions(pmemstream_test_base &stream)
> ```

you can put this function into pmemstream_helpers _type: https://github.com/pmem/pmemstream/blob/master/tests/common/stream_helpers.hpp#L181
___
*[tests/unittest/multi_region.cpp, line 25 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzQUg0fEqNYUSA5rsq5:-MzQWCOf5u6rm5zuFUiL:bxjfgts) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L25)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

(please use wrapper methods)


<!-- Sent from Reviewable.io -->

2022-03-31 07:44 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 1 of 14 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/multi_region.cpp, line 12 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzTusM1BoI4NaX667JW:-MzTusM1BoI4NaX667JX:b25eoch) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L12)):*
> ```cpp
> #include "unittest.hpp"
> 
> int count_regions(pmemstream_test_base &stream)
> ```

return size_t
___
*[tests/unittest/multi_region.cpp, line 46 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzQVAig81lfAULiRJEz:-MzTsaVo9BOq0LgQflBn:b-c18n7e) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L46)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not random?
</blockquote></details>

or if not random, you can just leave the default value
___
*[tests/unittest/multi_region.cpp, line 53 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzQV6J41dgjvcqhPuvw:-MzTsymm58jVtW16VKIO:b-fsz5bs) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not a rapidcheck test?
</blockquote></details>

I believe this piece of code is here to count max possible number of allocations that'll fit into the stream... but this should be a function, I guess
___
*[tests/unittest/multi_region.cpp, line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzTuOkmB94DIRcP6Uqt:-MzTuOkmB94DIRcP6Uqu:b-q2iujd) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L68)):*
> ```cpp
> 
> 			for (size_t i = 0; i < no_regions; i++) {
> 				auto region = stream.helpers.stream.region_allocate(allocation_size);
> ```

doesn't `region_allocate` return return_code and region? I guess either rename this to something else than `region` or do it as in other tests `auto [ret, region] = `
___
*[tests/unittest/multi_region.cpp, line 92 at r2](https://reviewable.io/reviews/pmem/pmemstream/161#-MzTvAFiBNDgT6BxdGCJ:-MzTvAFiBNDgT6BxdGCK:b-9le7sk) ([raw file](https://github.com/pmem/pmemstream/blob/c46c9c1e8c63409f799ab0816570598947177647/tests/unittest/multi_region.cpp#L92)):*
> ```cpp
> 		});
> 	});
> }
> ```

missing "enter" - please run `make cppformat` :wink: 


<!-- Sent from Reviewable.io -->

2022-03-31 17:12 UTC, igchor reviewed
> Reviewed 1 of 5 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 296 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVxMYgCk81yG01SHLF:-MzVxMYgCk81yG01SHLG:bt19x3s) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L296)):*
> ```cpp
> 	{
> 		try {
> 			for (int i = 0; i < number; i++) {
> ```

why not:
```
for (int i = 0; i < number; i++) {
    UT_ASSERTeq(stream.region_free(get_first_region()), 0);
}
```

?
___
*[tests/common/stream_helpers.hpp, line 305 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVwUIWAQAoz_ws7FgY:-MzVwUIX5oJaVI5Cq1DA:b-w72mui) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L305)):*
> ```cpp
> 			}
> 		} catch (std::runtime_error &e) {
> 			throw std::runtime_error("Exception when removing regions!");
> ```

What's the point of this catch? You are overwriting the original message with some generic one - it's not very useful imo.


<!-- Sent from Reviewable.io -->

2022-04-01 08:00 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 13 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 10 unresolved discussions (waiting on @KFilipek)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ3zCp4ZXj58d_uVK3):*
what's the point of this extra sentence? only new word you write here is "easier" :smile: 
___
*[tests/common/stream_helpers.hpp, line 293 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ5lxo9oO83XbnvmST:-MzZ5lxpEMRXra11BQHz:bhmjw3p) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L293)):*
> ```cpp
> 	}
> 
> 	void remove_regions(int number)
> ```

`int` -> `size_t`
___
*[tests/unittest/multi_region.cpp, line 6 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6Gs12V6pVemTno2S:-MzZ6Gs12V6pVemTno2T:b-osfdem) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L6)):*
> ```cpp
> #include <rapidcheck.h>
> 
> #include "iterator.h"
> ```

I guess you can clean some of these up
___
*[tests/unittest/multi_region.cpp, line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6RJL4zn-zpThSmlY:-MzZ6RJL4zn-zpThSmlZ:bslhfnf) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L15)):*
> ```cpp
> size_t count_max_regions(test_config_type &test_config)
> {
> 	pmemstream_test_base stream(test_config.filename, test_config.block_size, test_config.stream_size);
> ```

hmm.. you work on the same file - aren't these regions persist? may they conflict with the testing...? not sure about that..
___
*[tests/unittest/multi_region.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6pCC0RG5JgH89Gnj:-MzZ6pCC0RG5JgH89Gnk:baxp6x4) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L17)):*
> ```cpp
> 	pmemstream_test_base stream(test_config.filename, test_config.block_size, test_config.stream_size);
> 	size_t max_allocations = 0;
> 	std::tuple<int, pmemstream_region> region;
> ```

same issue - rename to something else than `region` or use `auto []` syntax
___
*[tests/unittest/multi_region.cpp, line 20 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7hn6C6JVHkJ_mN99:-MzZ7hn6C6JVHkJ_mN9A:bz7gknc) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L20)):*
> ```cpp
> 	do {
> 		region = stream.helpers.stream.region_allocate(TEST_DEFAULT_BLOCK_SIZE);
> 		++max_allocations;
> ```

if the first allocation fails you still get the max_alloc = 1
___
*[tests/unittest/multi_region.cpp, line 44 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7bhC4OSMccKEUqTG:-MzZ7bhC4OSMccKEUqTH:b-86onqy) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L44)):*
> ```cpp
> 
> 			for (size_t i = 0; i < no_regions; i++) {
> 				auto [ret, region] = stream.helpers.stream.region_allocate(TEST_DEFAULT_BLOCK_SIZE);
> ```

TEST_DEFAULT_BLOCK_SIZE?
___
*[tests/unittest/multi_region.cpp, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7JTREYhi6JZoGwQ1:-MzZ7JTREYhi6JZoGwQ2:bgd0dw1) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L45)):*
> ```cpp
> 			for (size_t i = 0; i < no_regions; i++) {
> 				auto [ret, region] = stream.helpers.stream.region_allocate(TEST_DEFAULT_BLOCK_SIZE);
> 				UT_ASSERTeq(ret, 0);
> ```

within RC tests pls use `RC_ASSERT(ret == 0)` 

// fix everywhere


<!-- Sent from Reviewable.io -->

2022-04-01 08:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 11 unresolved discussions (waiting on @KFilipek)

___
*[tests/common/stream_helpers.hpp, line 287 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZB1ys8WTu4gxtXSHj:-MzZB1ys8WTu4gxtXSHk:b-3jokti) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L287)):*
> ```cpp
> 		struct pmemstream_region region;
> 		while (pmemstream_region_iterator_next(riter.get(), &region) != -1) {
> 			UT_ASSERTne(region.offset, UINT64_MAX);
> ```

does this check do anything? we have no info what is set on error/what was set before the iter_next call


<!-- Sent from Reviewable.io -->

2022-04-01 11:53 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ3zCp4ZXj58d_uVK3):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's the point of this extra sentence? only new word you write here is "easier" :smile: 
</blockquote></details>

Done. I tried to avoid question about "why here is no extra explanation" xD
___
*[tests/common/stream_helpers.hpp, line 287 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZB1ys8WTu4gxtXSHj:-MzZ_LB74_uN9Ze-8PZe:bpp0i3e) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L287)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

does this check do anything? we have no info what is set on error/what was set before the iter_next call
</blockquote></details>

Assertion is to check that all is correct, if you get something different than -1 you should have also correct offset.
___
*[tests/common/stream_helpers.hpp, line 293 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ5lxo9oO83XbnvmST:-MzZa5tv3OamsbccUT_K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L293)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`int` -> `size_t`
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 296 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVxMYgCk81yG01SHLF:-MzZaC-aC6cKN3JFzSJD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L296)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not:
```
for (int i = 0; i < number; i++) {
    UT_ASSERTeq(stream.region_free(get_first_region()), 0);
}
```

?
</blockquote></details>

Done.
___
*[tests/common/stream_helpers.hpp, line 305 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVwUIWAQAoz_ws7FgY:-MzZaG809yO14yxJvyjs:b-fkm8yc) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L305)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What's the point of this catch? You are overwriting the original message with some generic one - it's not very useful imo.
</blockquote></details>

My point was to change message due to explicitly calling remove_regions() not iterator API. I can change it if you want.
___
*[tests/unittest/multi_region.cpp, line 6 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6Gs12V6pVemTno2S:-MzZhwsF4HnzO9YgIkqe:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can clean some of these up
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6pCC0RG5JgH89Gnj:-MzZurUMD1YVlNU5gJtP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

same issue - rename to something else than `region` or use `auto []` syntax
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 20 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7hn6C6JVHkJ_mN99:-MzZusAm6o87vztg6Up0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if the first allocation fails you still get the max_alloc = 1
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 44 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7bhC4OSMccKEUqTG:-MzZutjxDOd_M8Ck_toE:b3vuzjv) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

TEST_DEFAULT_BLOCK_SIZE?
</blockquote></details>

Why not? I'm just use quite big size to not spend infinity waiting on OOM.
___
*[tests/unittest/multi_region.cpp, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7JTREYhi6JZoGwQ1:-MzZxuO50yr6Hs_4p2Uy:bhbm1yy) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

within RC tests pls use `RC_ASSERT(ret == 0)` 

// fix everywhere
</blockquote></details>

Done. I'm not sure why we don't use it elsewhere. 


<!-- Sent from Reviewable.io -->

2022-04-01 12:05 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 13 of 15 files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 305 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVwUIWAQAoz_ws7FgY:-MzZzRWi7mGc3bOmgzNi:b-tkaq43) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L305)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

My point was to change message due to explicitly calling remove_regions() not iterator API. I can change it if you want.
</blockquote></details>

Ok but the original error message might be useful for debugging - you can append some additional msg but you should not override it.
___
*[tests/unittest/multi_region.cpp, line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6RJL4zn-zpThSmlY:-Mz_-5Nt6F1yhvr6Ymni:bovzvfl) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. you work on the same file - aren't these regions persist? may they conflict with the testing...? not sure about that..
</blockquote></details>

I don;t think so, in later tests we use pmemstream_empty which should truncate the file.
___
*[tests/unittest/multi_region.cpp, line 38 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_-X2w1jVmm6N7y2RH:-Mz_-X2w1jVmm6N7y2RI:bs7p417) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L38)):*
> ```cpp
> 
> 		ret += rc::check("Multiple allocate", [&](pmemstream_empty &&stream) {
> 			size_t no_regions = *rc::gen::inRange<std::size_t>(1, max_allocations);
> ```

I don't think this test makes much sense. If we managed to allocate max_allocation we will manage to allocate any number of regions <= max_allocation, no?


<!-- Sent from Reviewable.io -->

2022-04-01 12:07 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 13 of 15 files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/multi_region.cpp, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7JTREYhi6JZoGwQ1:-Mz_0PHg83SxMp-m9-ij:b-j93gsd) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L45)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. I'm not sure why we don't use it elsewhere. 
</blockquote></details>

It doesn't matter much, UT_ASSERTs will work as well (we use them in helpers anyway).


<!-- Sent from Reviewable.io -->

2022-04-01 12:15 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/common/stream_helpers.hpp, line 287 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZB1ys8WTu4gxtXSHj:-MzZyyrT9uK5GiEi3_10:bc28c6c) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L287)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Assertion is to check that all is correct, if you get something different than -1 you should have also correct offset.
</blockquote></details>

but still, you have no idea if that "something else than UINT64_MAX" is correct :smile: 

nonetheless, it may stay, it shouldn't break anything :wink: 
___
*[tests/common/stream_helpers.hpp, line 305 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzVwUIWAQAoz_ws7FgY:-MzZzburDhHJ4vmMBZyc:b-arezju) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/common/stream_helpers.hpp#L305)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok but the original error message might be useful for debugging - you can append some additional msg but you should not override it.
</blockquote></details>

I think we can just remove the try-catch here - there will be info on where this exception was thrown from...
___
*[tests/unittest/multi_region.cpp, line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ6RJL4zn-zpThSmlY:-Mz_0qqw0NiooFpB9XjN:b-ossgak) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don;t think so, in later tests we use pmemstream_empty which should truncate the file.
</blockquote></details>

if you say so... :smile: (I didn't test it, I'm not sure)
___
*[tests/unittest/multi_region.cpp, line 44 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7bhC4OSMccKEUqTG:-Mz_-gwo4JJ2IqwPnHoR:bwyhqsf) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L44)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why not? I'm just use quite big size to not spend infinity waiting on OOM.
</blockquote></details>

actually, it's quite small - it's test's default **block_size** - you'd rather want to use TEST_DEFAUL_REGION_SIZE :wink: 
___
*[tests/unittest/multi_region.cpp, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/161#-MzZ7JTREYhi6JZoGwQ1:-Mz_1NWA9oBsyfUb-kFO:b-x0rgdb) ([raw file](https://github.com/pmem/pmemstream/blob/f755b4434ff6aed745d80ed738fa1e7ef1c67276/tests/unittest/multi_region.cpp#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It doesn't matter much, UT_ASSERTs will work as well (we use them in helpers anyway).
</blockquote></details>

in helpers we cannot use `RC_`, because they are potentially used outside of RC tests

in RC tests, I believe, it's better to use RC_ASSERTs... but yeah, in general, it will work both ways
___
*[tests/unittest/multi_region.cpp, line 38 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_-X2w1jVmm6N7y2RH:-Mz_1D5G2kB1lpgul8vo:bez851s) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L38)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't think this test makes much sense. If we managed to allocate max_allocation we will manage to allocate any number of regions <= max_allocation, no?
</blockquote></details>

:smile_cat: 
___
*[tests/unittest/multi_region.cpp, line 45 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_1vH_Ecysnsi1GJRi:-Mz_1vH_Ecysnsi1GJRj:b-bg2lsz) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L45)):*
> ```cpp
> 			}
> 
> 			RC_ASSERT(no_regions == static_cast<size_t>(stream.helpers.count_regions()));
> ```

static_cast's are redundant now - count_regions return size_t

// pls fix all
___
*[tests/unittest/multi_region.cpp, line 54 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_2IH92Fti-LQB0I61:-Mz_2IH92Fti-LQB0I62:b-ejjkmr) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L54)):*
> ```cpp
> 			for (size_t i = 0; i < no_regions; i++) {
> 				auto [ret, region] = stream.helpers.stream.region_allocate(TEST_DEFAULT_BLOCK_SIZE);
> 				UT_ASSERTeq(ret, 0);
> ```

still UT_ASSERT (pls fix for consistency)


<!-- Sent from Reviewable.io -->

2022-04-01 12:57 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 14 of 15 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/unittest/multi_region.cpp, line 48 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_Bh0v2mWIcjm2YHWw:-Mz_Bh0v2mWIcjm2YHWx:b-3vuapo) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L48)):*
> ```cpp
> 		});
> 
> 		ret += rc::check("Multiple allocate - multiple free", [&](pmemstream_empty &&stream) {
> ```

How about running this test in a loop? E.g. allocate some regions, free some of them and repeat multiple times?


<!-- Sent from Reviewable.io -->

2022-04-01 16:36 UTC, KFilipek reviewed
> Reviewed 1 of 5 files at r2, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/multi_region.cpp, line 37 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_1yTq-1eLBISvwE5W:-Mz_kHVJ0sUIcBeQF3BD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L37)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Such  property is "It's possible to allocate many regions" 
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 45 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_1vH_Ecysnsi1GJRi:-Mz_yjEz7vWaWqOSW_Sb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

static_cast's are redundant now - count_regions return size_t

// pls fix all
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 48 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_-2SP74dNAGx1K83_:-Mz_yqAB3MnpoC_VySE1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L48)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

such test  should be "Each allocated region may be freed"
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 54 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_2IH92Fti-LQB0I61:-Mz_z1mIDNComKW8aljw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still UT_ASSERT (pls fix for consistency)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-04 07:51 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/unittest/multi_region.cpp, line 48 at r5](https://reviewable.io/reviews/pmem/pmemstream/161#-Mz_Bh0v2mWIcjm2YHWw:-MznXBH05GCwPDzHeARR:b-dcn3uu) ([raw file](https://github.com/pmem/pmemstream/blob/a6cfecae91b9d1abd2cbc82e6811e72f16b737dc/tests/unittest/multi_region.cpp#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about running this test in a loop? E.g. allocate some regions, free some of them and repeat multiple times?
</blockquote></details>

I agree with Igor, right now we're not testing (in any of these tests) re-using previously freed regions
___
*[tests/unittest/multi_region.cpp, line 31 at r7](https://reviewable.io/reviews/pmem/pmemstream/161#-MznVfRM23uAroG1y8M8:-MznVfRM23uAroG1y8M9:bomzg3y) ([raw file](https://github.com/pmem/pmemstream/blob/c4a12ae2d14a81f0c2c718fb6e6cf5fab4ead44e/tests/unittest/multi_region.cpp#L31)):*
> ```cpp
> 	struct test_config_type test_config;
> 	test_config.filename = std::string(argv[1]);
> ```

huh, now, since you're using `TEST_DEFAULT_REGION_SIZE` as region size, max_alloc equals to 1 - you may fix that by setting `test_config.stream_size` equal to e.g. `TEST_DEFAULT_STREAM_SIZE * 10` - it should then fit around 10 regions
___
*[tests/unittest/multi_region.cpp, line 48 at r7](https://reviewable.io/reviews/pmem/pmemstream/161#-MznYIKsBXheZHp7OP7w:-MznYIKsBXheZHp7OP7x:b-kuyb6d) ([raw file](https://github.com/pmem/pmemstream/blob/c4a12ae2d14a81f0c2c718fb6e6cf5fab4ead44e/tests/unittest/multi_region.cpp#L48)):*
> ```cpp
> 
> 			stream.helpers.remove_regions(no_regions);
> 			RC_ASSERT(0 == stream.helpers.count_regions());
> ```

you may try to remove a region after this line and expect a failure
___
*[tests/unittest/multi_region.cpp, line 68 at r7](https://reviewable.io/reviews/pmem/pmemstream/161#-MznXUn8Al_EsTmRj60W:-MznXUn8Al_EsTmRj60X:b-wpmhuu) ([raw file](https://github.com/pmem/pmemstream/blob/c4a12ae2d14a81f0c2c718fb6e6cf5fab4ead44e/tests/unittest/multi_region.cpp#L68)):*
> ```cpp
> 		ret += rc::check("Multiple allocate - random free", [&](pmemstream_empty &&stream) {
> 			size_t no_regions = *rc::gen::inRange<std::size_t>(1, max_allocations);
> 			size_t to_delete = *rc::gen::inRange<std::size_t>(1, no_regions);
> ```

why `(1, no_regions)`? shouldn't it be from `0`? as the first possible index to remove?
___
*[tests/unittest/multi_region.cpp, line 77 at r7](https://reviewable.io/reviews/pmem/pmemstream/161#-MznXhQ3BcCFQ286iXgy:-MznXhQ3BcCFQ286iXgz:b2l3u70) ([raw file](https://github.com/pmem/pmemstream/blob/c4a12ae2d14a81f0c2c718fb6e6cf5fab4ead44e/tests/unittest/multi_region.cpp#L77)):*
> ```cpp
> 			RC_ASSERT(no_regions == stream.helpers.count_regions());
> 
> 			stream.helpers.remove_region_at(to_delete);
> ```

and couldn't this removal be done in a loop? to not remove just a single region?


<!-- Sent from Reviewable.io -->

2022-04-05 09:20 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/common/unittest.h, line 59 at r8](https://reviewable.io/reviews/pmem/pmemstream/161#-Mzt0H7uCmpd75GRA7z3:-Mzt0H7uCmpd75GRA7z4:b-u1cvxf) ([raw file](https://github.com/pmem/pmemstream/blob/134efe6f1cc4aa188b2fcbb839f267ab9766aa66/tests/common/unittest.h#L59)):*
> ```objc
> #define REGION_METADATA_SIZE (4UL * 1024)
> #define TEST_REGION_MULTIPLIER 50
> #define TEST_DEFAULT_STREAM_SIZE (1024UL * 1024 * TEST_REGION_MULTIPLIER)
> ```

actually, this change will impact all our tests and I think it's not a good solution. You may do what I proposed with the usage of test_config, to adjust stream size just for this test


<!-- Sent from Reviewable.io -->

2022-04-05 12:42 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: 14 of 16 files reviewed, 9 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 304 at r10](https://reviewable.io/reviews/pmem/pmemstream/161#-MztjoFjAYI-duJLo7pt:-MztjoFjAYI-duJLo7pu:bvf5tx7) ([raw file](https://github.com/pmem/pmemstream/blob/5dab00e2470756a6e01dad9bdfe807e9a3ce3d47/tests/common/stream_helpers.hpp#L304)):*
> ```cpp
> 		auto riter = stream.region_iterator();
> 
> 		for (size_t i = 0; i <= pos; i++) {
> ```

why '<=' ?


<!-- Sent from Reviewable.io -->

2022-04-05 16:02 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-04-05 16:14 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/multi_region.cpp, line 94 at r15](https://reviewable.io/reviews/pmem/pmemstream/161#-MzuV7bQAj7dMi68tbZw:-MzuV7bQAj7dMi68tbZx:bmqhsea) ([raw file](https://github.com/pmem/pmemstream/blob/dbe251a714c5668b23b60a6ba8b0139e9ce7d572/tests/unittest/multi_region.cpp#L94)):*
> ```cpp
> 
> 			size_t tbd = to_delete;
> 			size_t pos = no_regions;
> ```

We could probably just generate some random list of unique_offsets to remove, instead of just removing from end.


<!-- Sent from Reviewable.io -->

2022-04-05 16:17 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 1 of 2 files at r10, 1 of 2 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/161#-:-MzuVwlL6L0-n0bfNbAi:b-8fx2u7)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-04-05 16:18 UTC, merged