refactor region iterator
pmem/pmemstream pull request #166
Opened 2022-04-11 17:31 UTC by karczex

Iterator API proposal 
Changes in iterator behavior:
1. Getter returns region, which is pointed by iterator, so it's possible to store only iterators in some struct, and always get region from it. 
2.  Iterator never points to INVALID_REGION -  if `region_iterator_next()` fail it means there is no more regions in the stream. However if new region is created it's possible to reach it without discarding existing iterator object.    

TODO: 
- [x] Fix tests and examples 
- [ ] Refactor entry iterator in similar manner  as another PR

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemstream/166)

2022-04-12 08:11 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/166)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[src/iterator.c, line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/166#-N-RnSiB61LQjmcHgQGY:-N-RnSiB61LQjmcHgQGZ:bnvqjo4) ([raw file](https://github.com/pmem/pmemstream/blob/fe32548da45cc379563e4f8202c976013cf3221b/src/iterator.c#L61)):*
> ```C
> 	}
> 
> 	if (it->region.offset == SLIST_INVALID_OFFSET) {
> ```

assert?


<!-- Sent from Reviewable.io -->

2022-04-14 06:20 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/166)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @igchor)

___
*[src/iterator.c, line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/166#-N-RnSiB61LQjmcHgQGY:-N-ahoGjCClyvV35oDpV:bfsm447) ([raw file](https://github.com/pmem/pmemstream/blob/fe32548da45cc379563e4f8202c976013cf3221b/src/iterator.c#L61)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

assert?
</blockquote></details>

Nope. You may create iterator on empty stream. In that case `get()` may fail. IMHO it's convenient scenario, to be able to create iterator before adding any region.  


<!-- Sent from Reviewable.io -->

2022-04-14 10:55 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/166#-:-N-bhieXCRUwjdN9k66-:bnfp4nl)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-04-14 12:28 UTC, KFilipek requested changes
> Reviewed 4 of 7 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/166)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/common/stream_helpers.hpp, line 366 at r3](https://reviewable.io/reviews/pmem/pmemstream/166#-N-c1Yuu1h_pGWRG3q-m:-N-c1YuvDGb3g70xTVzz:bx8fmk9) ([raw file](https://github.com/pmem/pmemstream/blob/c20c6296ded6015e193e2fc0ecb1977200370c63/tests/common/stream_helpers.hpp#L366)):*
> ```cpp
> 			if (pmemstream_region_iterator_next(riter.get()) != 0) {
> 				break;
> 			}
> ```

3 lines less, one break less
```cpp
do {
	struct pmemstream_region region;
	if (pmemstream_region_iterator_get(riter.get(), &region) != 0) {
		break;
	}
	regions.push_back(region);
} while (pmemstream_region_iterator_next(riter.get()) == 0);
```



_Code quote:_
```cpp
		while (true) {
			struct pmemstream_region region;
			if (pmemstream_region_iterator_get(riter.get(), &region) != 0) {

				break;
			}
			regions.push_back(region);
			if (pmemstream_region_iterator_next(riter.get()) != 0) {
				break;
			}
		}
```


<!-- Sent from Reviewable.io -->

2022-04-14 12:39 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/166#-:-N-c4NEI8xn2WP3uVigc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-04-14 12:57 UTC, merged