Move on to the new coverage uploader
pmem/pmemstream pull request #174
Opened 2022-04-27 15:05 UTC by Karolina002

2022-04-28 07:50 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: all files reviewed, 4 unresolved discussions (waiting on @Karolina002)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/174#-N0j8WT913RGrd1ayinj):*
pls add some more details, at least why and what's the new approach
___
*[`utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch` line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/174#-N0j84aj0Dh1vPINwGk7:-N0j84aj0Dh1vPINwGk8:b-iqwehp) ([raw file](https://github.com/pmem/pmemstream/blob/590dc52660c3f9e7ff15f335e5b99bc30785e38b/utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch#L5)):*
> ```Diff
> Date: Mon, 7 May 2018 12:05:40 +0200
> Subject: [PATCH] travis: fix travisci_build_coverity_scan.sh
> ```

- "coverity" is a static analysis checker
- "coverage"/"gcov"/"codecov" is a tool for checking the code coverage :wink: 
___
*[`utils/docker/prepare-for-build.sh` line 49 at r1](https://reviewable.io/reviews/pmem/pmemstream/174#-N0j8Ogk-2Gl8ys4oRDp:-N0j8Ogk-2Gl8ys4oRDq:b-5q31bt) ([raw file](https://github.com/pmem/pmemstream/blob/31cdf60e610d6db70550487069679a6ef2306541/utils/docker/prepare-for-build.sh#L49)):*
> ```Shell
> 	fi
> 
> 	curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
> ```

this downloading should be done (at best) in the image building process
___
*[`utils/docker/run-coverity.sh` line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/174#-N0j8Ibo4hEw9Ko6tLgT:-N0j8IbpCmkvV-eV0Rxw:b9fmzx8) ([raw file](https://github.com/pmem/pmemstream/blob/590dc52660c3f9e7ff15f335e5b99bc30785e38b/utils/docker/run-coverity.sh#L70)):*
> ```Shell
> 
> wget https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh
> patch < ../utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch
> ```

coverity to be not touched :wink:


<!-- Sent from Reviewable.io -->

2022-05-04 06:17 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N1Ch9urCl0lzJOZJOMr:bkfw0em) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
> ```Shell
> 	clang_used=$(cmake -LA -N . | grep -e "CMAKE_C.*_COMPILER" | grep clang | wc -c)
> 	if [[ ${clang_used} -gt 0 ]]; then
> 		return 1
> ```

if clang is used you shouldn't return "1", because CI will fail all the time. If llvm-cov is not supported (is it not?) you should put an "XXX" comment here and print some kind of warning to the log (and return with no error == 0)


<!-- Sent from Reviewable.io -->

2022-05-09 14:08 UTC, lukaszstolarczuk reviewed
> Reviewed 7 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 9 of 11 files reviewed, 12 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d59er023BQsBnAUJk:-N1d59er023BQsBnAUJl:buidz3u) (no related file):*
pls reabse to include CI build fix

---
___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N1d3qt75Sfsad1ugFXG:b2t9d81) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you please ask question/file an issue to codecov script developers - to confirm that llvm support is missing (and perhaps ping them to fix that)
___
*[`utils/docker/prepare-for-build.sh` line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d3cl6B0776SGAToz6:-N1d3cl6B0776SGAToz7:btkv1la) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L34)):*
> ```Shell
> 	printf "\n$(tput setaf 1)$(tput setab 7)COVERAGE ${FUNCNAME[0]} START$(tput sgr 0)\n"
> 
> 	# check used clang
> ```

e.g. `check if code was compiled with clang`
___
*[`utils/docker/prepare-for-build.sh` line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7zUI65vrwhEDpnD3:-N1d7zUI65vrwhEDpnD4:bc8rfhz) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L38)):*
> ```Shell
> 	if [[ ${clang_used} -gt 0 ]]; then
> 		# XXX: llvm-cov not supported
> 		echo "Llvm-cov is not supported"
> ```

pls add e.g. "Warning: ..."
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6t1wD5DvJvDaEoLp:-N1d6t1wD5DvJvDaEoLq:b-yr118j) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
> ```Shell
> 	# run codecov using gcov (set flag and exit 1 if not successful)
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov -F ${1} -Z --gcov -R .
> ```

`-R, --rootDir     Specify the project root directory when not in a git repo` - I think you may omit that param
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6x772WZ-TurUyKHX:-N1d6x772WZ-TurUyKHY:bh0z1nq) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
> ```Shell
> 	# run codecov using gcov (set flag and exit 1 if not successful)
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov -F ${1} -Z --gcov -R .
> ```

you may add `--verbose` param to see if there's anything relevant (and if there's not too much spam, you may actually use it in the CI)
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7D3CBEDo1kAZhZAd:-N1d7D3CBEDo1kAZhZAe:b-c8ddn1) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
> ```Shell
> 	# run codecov using gcov (set flag and exit 1 if not successful)
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov -F ${1} -Z --gcov -R .
> ```

you may use the long names of params, e.g. `--flags` instead of `-F`; this way you may omit the part of the comment with params' explanation
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d82nE8XhGbLDBSFb0:-N1d82nE8XhGbLDBSFb1:b-1vdmrc) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
> ```Shell
> 	# run codecov using gcov (set flag and exit 1 if not successful)
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov -F ${1} -Z --gcov -R .
> ```

don't we need `-c, --clean       Move discovered coverage reports to the trash` ? as previously?

this way all discovered files will be gone and the "leftover_files" below should be empty
___
*[`utils/docker/images/download-scripts.sh` line 3 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d4qjV1YUaZ0Ljs6ii:-N1d4qjWBD28ncUhStmz:bwi7omx) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2021-2022, Intel Corporation
> ```

why change the `2020-` part?
___
*[`utils/docker/images/download-scripts.sh` line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5KSmBJbFoXtgAOH9:-N1d5KSmBJbFoXtgAOHA:be0dro0) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L8)):*
> ```Shell
> # download-scripts.sh - downloads specific version of
> #			codecov's bash script to generate and upload reports.
> #			It's useful, since they may break our coverage.
> ```

pls make this description up-to-date
___
*[`utils/docker/images/download-scripts.sh` line 14 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d4mNyC1mQXohZ4Dop:-N1d4mNyC1mQXohZ4Doq:b-6v6p70) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L14)):*
> ```Shell
> 
> # master: Merge pull request #342 from codecov/revert-proj-name-..., 18.08.2020
> CODECOV_VERSION="e877c1280cc6e902101fb5df2981ed1c962da7f0"
> ```

these lines are redundant now
___
*[`utils/docker/images/download-scripts.sh` line 27 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5YYdAZVi4zDRHKQW:-N1d5YYdAZVi4zDRHKQX:b363t44) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L27)):*
> ```Shell
> 	return 1
> fi
> ```

you may perform these downloads in a temporary directory so it could be removed when done (like the previous `rm -rf codecov-bash` command)


<!-- Sent from Reviewable.io -->

2022-05-11 09:13 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 7 of 11 files reviewed, 12 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d59er023BQsBnAUJk:-N1mO4P51UW0ZB8ondQL:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls reabse to include CI build fix
</blockquote></details>

Done.

___
___
*[`utils/docker/prepare-for-build.sh` line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d3cl6B0776SGAToz6:-N1mO7F568Fzn0489GWd:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

e.g. `check if code was compiled with clang`
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7zUI65vrwhEDpnD3:-N1mO7lw4lKrH3koGdmy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add e.g. "Warning: ..."
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6t1wD5DvJvDaEoLp:-N1mJCfZDo3UHZ08DONP:byrfb1o) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-R, --rootDir     Specify the project root directory when not in a git repo` - I think you may omit that param
</blockquote></details>

I added this after consultation on the last daily. It solves problem I've been having.
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6x772WZ-TurUyKHX:-N1mO9O0-4dR8T-YnOgj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may add `--verbose` param to see if there's anything relevant (and if there's not too much spam, you may actually use it in the CI)
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7D3CBEDo1kAZhZAd:-N1mO9kaCr6ir-MNW978:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may use the long names of params, e.g. `--flags` instead of `-F`; this way you may omit the part of the comment with params' explanation
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d82nE8XhGbLDBSFb0:-N1mOARQ-ny94S5Ru_T0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't we need `-c, --clean       Move discovered coverage reports to the trash` ? as previously?

this way all discovered files will be gone and the "leftover_files" below should be empty
</blockquote></details>

Done.
___
*[`utils/docker/images/download-scripts.sh` line 3 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d4qjV1YUaZ0Ljs6ii:-N1mOBfr6GdUEz53IFMX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why change the `2020-` part?
</blockquote></details>

Done.
___
*[`utils/docker/images/download-scripts.sh` line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5KSmBJbFoXtgAOH9:-N1mOCcA7gWnkweu5Wr6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make this description up-to-date
</blockquote></details>

Done.
___
*[`utils/docker/images/download-scripts.sh` line 14 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d4mNyC1mQXohZ4Dop:-N1mODI2ARO7UuKl_0nJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

these lines are redundant now
</blockquote></details>

Done.
___
*[`utils/docker/images/download-scripts.sh` line 27 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5YYdAZVi4zDRHKQW:-N1mODzcDzXfBks7RTrh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may perform these downloads in a temporary directory so it could be removed when done (like the previous `rm -rf codecov-bash` command)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-11 13:33 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N1nJZvvCbUjKFYaVeM0:-N1nJZvvCbUjKFYaVeM1:b-ds8qpo) (no related file):*
the coverage is not working - CI is marked in red :wink:

___
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6x772WZ-TurUyKHX:-N1nHrzn25qbHbOmj-kz:b-z2soqx) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, the log is quite long, as we can see in the CI, so I believe, when the PR will be ready we may remove this param (if we make sure the coverage uploader works correctly).
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7D3CBEDo1kAZhZAd:-N1nI3oJ0W7mDfTeRsPA:bgd73zr) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you can shorten the comment now, I guess
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6t1wD5DvJvDaEoLp:-N1nIAhhCsB03xISXtSF:b-7xu1hz) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I added this after consultation on the last daily. It solves problem I've been having.
</blockquote></details>

are you sure it's not working without that param? their readme says that "current working dir" should be included by default...
___
*[`utils/docker/images/download-scripts.sh` line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5KSmBJbFoXtgAOH9:-N1nIy-lESmc20foiUYL:b-e58jfd) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L8)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the last sentence is redundant now, we don't download a specific version


<!-- Sent from Reviewable.io -->

2022-05-13 09:44 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d7D3CBEDo1kAZhZAd:-N1wnRNvAhYzQfPltCey:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can shorten the comment now, I guess
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6t1wD5DvJvDaEoLp:-N1wnV7yBZR8RIsqKKHt:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure it's not working without that param? their readme says that "current working dir" should be included by default...
</blockquote></details>

Done.
___
*[`utils/docker/images/download-scripts.sh` line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d5KSmBJbFoXtgAOH9:-N1wnSmFEIxn5LEmcaCv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/images/download-scripts.sh#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the last sentence is redundant now, we don't download a specific version
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 10:30 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)



<!-- Sent from Reviewable.io -->

2022-05-18 16:46 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`utils/docker/prepare-for-build.sh` line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/174#-N1d6x772WZ-TurUyKHX:-N2N3-YV2vTjivYHzl3H:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1204b5e0331f973a05c7c6443ad25e3ecb553fe3/utils/docker/prepare-for-build.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, the log is quite long, as we can see in the CI, so I believe, when the PR will be ready we may remove this param (if we make sure the coverage uploader works correctly).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-19 07:14 UTC, lukaszstolarczuk requested changes
> Reviewed 3 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`-- commits` line 3 at r8](https://reviewable.io/reviews/pmem/pmemstream/174#-N2Q8eOM3XtOsjQAAcQ-):*
are you planning on pushing these 2 commits together or is it a temporary solution? if the latter, please mark this PR as a draft (to not merge it until it's done + (at best) add `- [ ] something to do yet` into the description of this PR.
___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N2Q97ys49Z7DKgt09tS:b-tuxast) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please ask question/file an issue to codecov script developers - to confirm that llvm support is missing (and perhaps ping them to fix that)
</blockquote></details>

how about this one?
___
*[`utils/docker/prepare-for-build.sh` line 45 at r7](https://reviewable.io/reviews/pmem/pmemstream/174#-N2Q9ExsDH6w39cr01Cc:-N2Q9ExsDH6w39cr01Cd:b-ai5wjb) ([raw file](https://github.com/pmem/pmemstream/blob/b3ca55c6314f17354b36453eef970c412e3ecef2/utils/docker/prepare-for-build.sh#L45)):*
> ```Shell
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov --verbose --flags ${1} --nonZero --gcov --rootDir . --clean
> ```

that empty line was fine, I believe, the above part is not connected to the below one


<!-- Sent from Reviewable.io -->

2022-05-19 18:46 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`-- commits` line 3 at r8](https://reviewable.io/reviews/pmem/pmemstream/174#-N2Q8eOM3XtOsjQAAcQ-):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you planning on pushing these 2 commits together or is it a temporary solution? if the latter, please mark this PR as a draft (to not merge it until it's done + (at best) add `- [ ] something to do yet` into the description of this PR.
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 45 at r7](https://reviewable.io/reviews/pmem/pmemstream/174#-N2Q9ExsDH6w39cr01Cc:-N2S_LgW0ydgwK9UIpq1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b3ca55c6314f17354b36453eef970c412e3ecef2/utils/docker/prepare-for-build.sh#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that empty line was fine, I believe, the above part is not connected to the below one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-20 08:15 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @Karolina002 and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-05-20 14:22 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N2WqF6l9Ye7trF5SHR1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

how about this one?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 09:11 UTC, KFilipek reviewed
> Reviewed 1 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-05-25 15:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N2voPUdEVwDgGlv8k8r:b-nb979c) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

huh, they're saying it's doable :wink: 

https://community.codecov.com/t/llvm-cov-support/3664


<!-- Sent from Reviewable.io -->

2022-06-13 09:09 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

___
*[`utils/docker/prepare-for-build.sh` line 34 at r11](https://reviewable.io/reviews/pmem/pmemstream/174#-N4RJa45AYYARFNo4kwK:-N4RJa45AYYARFNo4kwL:bz1nhpb) ([raw file](https://github.com/pmem/pmemstream/blob/88b01a2919dcd217750c38ad29866e83dc859bfa/utils/docker/prepare-for-build.sh#L34)):*
> ```Shell
> function upload_codecov() {
> 	# validate codecov.yaml file
> 	cat ${WORKDIR}/codecov.yml | curl --data-binary @- https://codecov.io/validate
> ```

why do we validate it, since it is not used...? or is it? then why do we have to manually use "ignore paths" option?
___
*[`utils/docker/prepare-for-build.sh` line 48 at r11](https://reviewable.io/reviews/pmem/pmemstream/174#-N4RJXcm2dstUHkK8VR7:-N4RJXcm2dstUHkK8VR8:b-37wbjd) ([raw file](https://github.com/pmem/pmemstream/blob/88b01a2919dcd217750c38ad29866e83dc859bfa/utils/docker/prepare-for-build.sh#L48)):*
> ```Shell
> 	# run codecov using gcov
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov --verbose --flags ${1} --nonZero --gcov --gcovIgnore ${PATHS_TO_IGNORE} --rootDir . --clean
> ```

there's different name of the var here :wink: 


<!-- Sent from Reviewable.io -->

2022-06-13 09:39 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174#-:-N4RQhJsB5gI9NcisPbD:bnfp4nl)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-06-13 10:32 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`utils/docker/prepare-for-build.sh` line 37 at r2](https://reviewable.io/reviews/pmem/pmemstream/174#-N1Ch9urCl0lzJOZJOMq:-N4RakUlBEWdlQw9TIPL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e4ee8cb4ccef43dce6feb6b7eb066eabfb1aa58f/utils/docker/prepare-for-build.sh#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

huh, they're saying it's doable :wink: 

https://community.codecov.com/t/llvm-cov-support/3664
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 34 at r11](https://reviewable.io/reviews/pmem/pmemstream/174#-N4RJa45AYYARFNo4kwK:-N4Raiqc4V2P2EUerMf-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/88b01a2919dcd217750c38ad29866e83dc859bfa/utils/docker/prepare-for-build.sh#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we validate it, since it is not used...? or is it? then why do we have to manually use "ignore paths" option?
</blockquote></details>

Done.
___
*[`utils/docker/prepare-for-build.sh` line 48 at r11](https://reviewable.io/reviews/pmem/pmemstream/174#-N4RJXcm2dstUHkK8VR7:-N4RbdAm0B3ZY5MBg6n3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/88b01a2919dcd217750c38ad29866e83dc859bfa/utils/docker/prepare-for-build.sh#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's different name of the var here :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 10:43 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4ReC1iCuouwma5hXe7:-N4ReC1iCuouwma5hXe8:b-eh72nr) (no related file):*
please investigate current lower coverage number

___
___
*[`-- commits` line 12 at r14](https://reviewable.io/reviews/pmem/pmemstream/174#-N4Rce4K6TcXKATT1B5u):*
please be more precise
___
*[`utils/docker/prepare-for-build.sh` line 45 at r14](https://reviewable.io/reviews/pmem/pmemstream/174#-N4Rdy6VDTnwNIsd37pp:-N4Rdy6VDTnwNIsd37pq:bfxfu27) ([raw file](https://github.com/pmem/pmemstream/blob/0d120024400583c82b7c878b8125db5a93862f29/utils/docker/prepare-for-build.sh#L45)):*
> ```Shell
> 	# run codecov using gcov
> 	# we rely on parsed report on codecov.io
> 	/opt/scripts/codecov --verbose --flags ${1} --nonZero --gcov ${IGNORE_PATHS} --rootDir . --clean
> ```

so, do you want to keep `verbose`, after all?


<!-- Sent from Reviewable.io -->

2022-06-13 19:14 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4ReC1iCuouwma5hXe7:-N4TUAUx-9sNk-Mrzter:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please investigate current lower coverage number
</blockquote></details>

Done.

___
___
*[`utils/docker/prepare-for-build.sh` line 45 at r14](https://reviewable.io/reviews/pmem/pmemstream/174#-N4Rdy6VDTnwNIsd37pp:-N4TUH_C9Jth4ZNviPfU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d120024400583c82b7c878b8125db5a93862f29/utils/docker/prepare-for-build.sh#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

so, do you want to keep `verbose`, after all?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 07:43 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4ReC1iCuouwma5hXe7:-N4W9V2h1OV3jfaCiuwT:b-y7zohb) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please investigate current lower coverage number
</blockquote></details>

we're still on the "red" side of the coverage diff :wink: 

___
___
*[`utils/docker/prepare-for-build.sh` line 16 at r15](https://reviewable.io/reviews/pmem/pmemstream/174#-N4W9OlIEL1DlRYccfuG:-N4W9OlIEL1DlRYccfuH:bb1g8g2) ([raw file](https://github.com/pmem/pmemstream/blob/c9faa2492cd569ce855a170f543ad14a88935b12/utils/docker/prepare-for-build.sh#L16)):*
> ```Shell
> STANDALONE_BUILD_DIR=/tmp/build_dir
> TEST_DIR=${PMEMSTREAM_TEST_DIR:-${DEFAULT_TEST_DIR}}
> IGNORE_PATHS="--gi benchmarks --gi doc --gi examples --gi tests --gi utils --gi **/critnib"
> ```

why `**`?


<!-- Sent from Reviewable.io -->

2022-06-14 08:24 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4ReC1iCuouwma5hXe7:-N4TUAUx-9sNk-Mrzter:b1cmc6v) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we're still on the "red" side of the coverage diff :wink: 
</blockquote></details>

Coverage differs within the same files, maybe they're calculating it differently

___
___
*[`utils/docker/prepare-for-build.sh` line 16 at r15](https://reviewable.io/reviews/pmem/pmemstream/174#-N4W9OlIEL1DlRYccfuG:-N4WHuC72zOKr5AdYTAZ:b-2jkfeb) ([raw file](https://github.com/pmem/pmemstream/blob/c9faa2492cd569ce855a170f543ad14a88935b12/utils/docker/prepare-for-build.sh#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `**`?
</blockquote></details>

Because it didn't work any other way. I found this solution here: https://docs.codecov.com/docs/ignoring-paths


<!-- Sent from Reviewable.io -->

2022-06-14 10:45 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4ReC1iCuouwma5hXe7:-N4Wo2Pp8iFEBHhRThVw:bwil7vw) (no related file):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Coverage differs within the same files, maybe they're calculating it differently
</blockquote></details>

I'm afraid you have to investigate and see if these lines are really covered or not... maybe we tested different code branches using clang...? if so we should be aware of that and perhaps fix our tests

___
___
*[`-- commits` line 12 at r14](https://reviewable.io/reviews/pmem/pmemstream/174#-N4Rce4K6TcXKATT1B5u):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please be more precise
</blockquote></details>

is it not removed after all?
___
*[`utils/docker/prepare-for-build.sh` line 16 at r15](https://reviewable.io/reviews/pmem/pmemstream/174#-N4W9OlIEL1DlRYccfuG:-N4WnlDSAnMh-GBOvLIV:b-jfcawj) ([raw file](https://github.com/pmem/pmemstream/blob/c9faa2492cd569ce855a170f543ad14a88935b12/utils/docker/prepare-for-build.sh#L16)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Because it didn't work any other way. I found this solution here: https://docs.codecov.com/docs/ignoring-paths
</blockquote></details>

but on the very same page you have:
`"path/to/folder"  # ignore folders and all its contents`
so it should work - perhaps it should be within `'...'`


<!-- Sent from Reviewable.io -->

2022-06-14 12:08 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4X5sta7yT05ghGKk_r:-N4X5sta7yT05ghGKk_s:bxug3dc) (no related file):*
are you rebased on the latest master? the test keeps timeouting in CI, when it shouldn't

___


<!-- Sent from Reviewable.io -->

2022-06-15 10:10 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/174#-N4X5sta7yT05ghGKk_r:-N4apafo-cRtDwqGKQmr:bpfru5z) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you rebased on the latest master? the test keeps timeouting in CI, when it shouldn't
</blockquote></details>

I am on the latest version

___
___
*[`-- commits` line 12 at r14](https://reviewable.io/reviews/pmem/pmemstream/174#-N4Rce4K6TcXKATT1B5u):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it not removed after all?
</blockquote></details>

It is, I retracted it temporarily
___
*[`utils/docker/prepare-for-build.sh` line 16 at r15](https://reviewable.io/reviews/pmem/pmemstream/174#-N4W9OlIEL1DlRYccfuG:-N4ac6E-6xEWnVA4WNQl:b-3vmtoy) ([raw file](https://github.com/pmem/pmemstream/blob/c9faa2492cd569ce855a170f543ad14a88935b12/utils/docker/prepare-for-build.sh#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but on the very same page you have:
`"path/to/folder"  # ignore folders and all its contents`
so it should work - perhaps it should be within `'...'`
</blockquote></details>

I tested every approach  mentioned on that page and the ones that should work, didn't


<!-- Sent from Reviewable.io -->

2022-06-15 11:35 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/174#-:-N4b8S_T0Kz7NnJpOlZ3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)



<!-- Sent from Reviewable.io -->

2022-06-15 12:43 UTC, merged