Extra timestamp tests
pmem/pmemstream pull request #217
Opened 2022-06-17 13:08 UTC by KFilipek

### TODO:
- [ ] prereq 1: (multiple regions, multithreaded synchronously appended entries)
    - [ ] case 1: (in every region, all timestamps increase)
    - [ ] case 2: (in stream, all timestamps increase (duplications))
- [ ] prereq 2: (multiple regions, multithreaded asynchronously appended entries)
    - [ ] case 1: (in every region, all timestamps increase)
    - [ ] case 2: (in stream, all timestamps increase (duplications))
- [ ] case 3: (multiple regions, remove single region with entries, add an empty region and then add new entries then check _case 2_)

### Description from issue:
(Prereq 1) Add generator derivated by pmemstream_test_base for that case:

Generates multiple regions
Multithreaded synchronously append entries to regions
(Prereq 2) Add generator derivated by pmemstream_test_base for that case:

Generates multiple regions
Multithreaded asynchronously append entries to regions
Cases for (prereq 1 and 2):
Case 1:
In every region, all timestamps increase.

Case 2:
In stream, all timestamps increase (duplications).

Case 3:
Add regions, remove single region with entries, add an empty region and then add new entries then check Case 2.

Closes #211

2022-06-17 14:10 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/CMakeLists.txt` line 146 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lxYDh0eXgVPpts5JG:-N4lxYDh0eXgVPpts5JH:bcg8ny1) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/CMakeLists.txt#L146)):*
> ```CMake
> 
> 	build_test_rc(NAME timestamp SRC_FILES unittest/timestamp.cpp LIBS miniasync)
> 	add_test_generic(NAME timestamp TRACERS none)
> ```

\+ memcheck and pmemcheck
___
*[`tests/common/stream_helpers.hpp` line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4ltYyD12Dx9iy0Ti9q:-N4ltYyD12Dx9iy0Ti9r:b-ewag7h) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L23)):*
> ```cpp
>  * different regions in global order. */
> template <typename T>
> class entry_iterator {
> ```

looks like these classes are copy-pasted from example, please add info about that in the commit msg
___
*[`tests/common/stream_helpers.hpp` line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lziKyDEjDeCsFjjTD:-N4lziKyDEjDeCsFjjTE:baudzww) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L23)):*
> ```cpp
>  * different regions in global order. */
> template <typename T>
> class entry_iterator {
> ```

I think you can move this class into "pmem" namespace here
___
*[`tests/common/stream_helpers.hpp` line 36 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lyfQu2gDjnevUezkD:-N4lyfQu2gDjnevUezkE:b-klh3iv) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L36)):*
> ```cpp
> 		pmemstream_entry_iterator_seek_first(it.get());
> 		if (pmemstream_entry_iterator_is_valid(it.get()) != 0) {
> 			throw std::runtime_error("No entries to iterate");
> ```

should it throw when there are no entries...?
___
*[`tests/common/stream_helpers.hpp` line 623 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lxHY9AAiZg-UmacmI:-N4lxHY9AAiZg-UmacmJ:byoeqsj) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L623)):*
> ```cpp
> 	}
> 
> 	bool validate_timestamps(bool possible_gaps = true)
> ```

you can ASSERT here already, no need for returning bool from the func
___
*[`tests/common/stream_helpers.hpp` line 629 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4ltiWp9cwyo24VcbTY:-N4ltiWp9cwyo24VcbTZ:b6i7nd) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L629)):*
> ```cpp
> 		auto entry_iterators = entry_iterator<void>::get_entry_iterators(stream.c_ptr(), regions);
> 
> 		uint64_t timestamp = (possible_gaps ? PMEMSTREAM_INVALID_TIMESTAMP : PMEMSTREAM_FIRST_TIMESTAMP);
> ```

why do we need this line?
___
*[`tests/unittest/timestamp.cpp` line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvtra5u_FT9a3pHyE:-N4lvtra5u_FT9a3pHyF:b351kyx) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L26)):*
> ```cpp
> 
> /* User data. */
> struct payload {
> ```

why do we need this payload struct? we won't print the data in a pretty form within the test
___
*[`tests/unittest/timestamp.cpp` line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lv4LPA-6Y5U7_DNry:-N4lv4LQCN3A7dMgsjHd:b-ka1iei) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L68)):*
> ```cpp
> 			"verify increasing timestamp values in each region after synchronous append",
> 			[&](pmemstream_test_base &&stream) {
> 				size_t no_elements = *rc::gen::inRange<size_t>(1, 15);
> ```

why do you need to limit the elems count?
if you really need it - you can use our shrinkable `struct ranged` instead
___
*[`tests/unittest/timestamp.cpp` line 69 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvGb_B745C7G54aKa:-N4lvGb_B745C7G54aKb:b-hsm753) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L69)):*
> ```cpp
> 			[&](pmemstream_test_base &&stream) {
> 				size_t no_elements = *rc::gen::inRange<size_t>(1, 15);
> 				size_t no_regions = *rc::gen::inRange<size_t>(1, TEST_DEFAULT_REGION_MULTI_MAX_COUNT);
> ```

you can use `pmemstream_with_multi_empty_regions ` instead
___
*[`tests/unittest/timestamp.cpp` line 76 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvl444YN5Ql0_Bm3v:-N4lvl444YN5Ql0_Bm3w:bflkpm7) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L76)):*
> ```cpp
> 				/* Asynchronous append to many regions with global ordering */
> 				parallel_exec(no_regions, [&](size_t thread_id) {
> 					for (size_t i = 0; i < no_elements; i++) {
> ```

we have a helper `append` for this whole `for` loop
___
*[`tests/unittest/timestamp.cpp` line 88 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lwRVp8TYB8XuZQ1NT:-N4lwRVp8TYB8XuZQ1NU:b7izctm) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L88)):*
> ```cpp
> 				uint64_t prev_timestamp = PMEMSTREAM_INVALID_TIMESTAMP;
> 				size_t entry_counter = 0;
> 				for (auto e_iterator : entry_iterators) {
> ```

can't you use your new helper function for a single region, instead...?
___
*[`tests/unittest/timestamp.cpp` line 104 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lw8BE60VEdCfXUvwq:-N4lw8BE60VEdCfXUvwr:bdzvqiw) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L104)):*
> ```cpp
> 			});
> 	});
> }
> ```

pls make the CI green, e.g. by providing a proper styling


<!-- Sent from Reviewable.io -->

2022-06-21 13:05 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 635 at r3](https://reviewable.io/reviews/pmem/pmemstream/217#-N55LxHNAxN9z08RyPdk:-N55LxHNAxN9z08RyPdl:b-126lea) ([raw file](https://github.com/pmem/pmemstream/blob/49400dc168f71fcb78e44d74bfe2562823ace12d/tests/common/stream_helpers.hpp#L635)):*
> ```cpp
> 				entries.push_back(pmemstream_entry_iterator_get(oldest_iterator->raw_iterator()));
> 			} else {
> 				entry_iterators.erase(entry_iterators.begin() +
> ```

isn't it the same as `entry_iterators.erase(oldest_iterator)`?
___
*[`tests/common/stream_helpers.hpp` line 648 at r3](https://reviewable.io/reviews/pmem/pmemstream/217#-N55M45N4rhjmFJxZNkr:-N55M45N4rhjmFJxZNks:b2w71f3) ([raw file](https://github.com/pmem/pmemstream/blob/49400dc168f71fcb78e44d74bfe2562823ace12d/tests/common/stream_helpers.hpp#L648)):*
> ```cpp
> 		std::vector<uint64_t> timestamps;
> 		std::transform(entries.begin(), entries.end(), timestamps.begin(),
> 			       [this](decltype(get_entries_for_regions(regions))::value_type entry) {
> ```

`const auto& entry`
___
*[`tests/common/stream_helpers.hpp` line 660 at r3](https://reviewable.io/reviews/pmem/pmemstream/217#-N55MDXq38nDzfdCDMI-:-N55MDXq38nDzfdCDMI0:bmtnj13) ([raw file](https://github.com/pmem/pmemstream/blob/49400dc168f71fcb78e44d74bfe2562823ace12d/tests/common/stream_helpers.hpp#L660)):*
> ```cpp
> 			return std::adjacent_find(timestamps.begin(), timestamps.end()) == timestamps.end();
> 		} else {
> 			std::vector<uint64_t> correct_timestamps(timestamps.size());
> ```

you can just do `return std::adjacent_find(timestamps.begin(), timestamps.end()) == timestamps.end() && timetamps.front() == PMEMSTREAM_FIRST_TIMESTAMP && timestamps.back() == PMEMSTREAM_FIRST_TIMESTAMP  + timestamps.size()`


<!-- Sent from Reviewable.io -->

2022-06-22 10:56 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 0 of 6 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 26 at r6](https://reviewable.io/reviews/pmem/pmemstream/217#-N5A2JEnBX_kXOcsJtur:-N5A2JEnBX_kXOcsJtus:bf9txyg) ([raw file](https://github.com/pmem/pmemstream/blob/0a0823380aad8869a5d9d68f7e1ba960512b3f6c/tests/common/stream_helpers.hpp#L26)):*
> ```cpp
> /* pmememstream entry iterator wrapper, which helps to manage entries from
>  * different regions in global order. */
> template <typename T>
> ```

Please remove the template, you don;t need it
___
*[`tests/common/stream_helpers.hpp` line 644 at r6](https://reviewable.io/reviews/pmem/pmemstream/217#-N5A2YTd9nqvv-NR7zuK:-N5A2YTd9nqvv-NR7zuL:bboswq1) ([raw file](https://github.com/pmem/pmemstream/blob/0a0823380aad8869a5d9d68f7e1ba960512b3f6c/tests/common/stream_helpers.hpp#L644)):*
> ```cpp
> 	}
> 
> 	bool validate_timestamps(bool possible_gaps = true)
> ```

as we discussed, it would be nice to be able to pass some custom vector of entries/timestamps here


<!-- Sent from Reviewable.io -->

2022-06-23 15:59 UTC, igchor requested changes
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 2 of 6 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 75 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GGRBbEWcyTKgHisgv:-N5GGRBbEWcyTKgHisgw:b8j0mnp) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L75)):*
> ```cpp
> 
> 				/* Multithreaded append to many regions with global ordering */
> 				parallel_exec(no_regions, [&](size_t thread_id) {
> ```

nit: regions.size(), no need for additional call to count_regions()
___
*[`tests/unittest/timestamp.cpp` line 88 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GGdcFAY1cVC4qFgMY:-N5GGdcFAY1cVC4qFgMZ:b-zae6pu) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L88)):*
> ```cpp
> 					std::vector<pmemstream_region> region_container;
> 					region_container.push_back(region);
> 					UT_ASSERTeq(stream.helpers.validate_timestamps(region_container, true), true);
> ```

nit: `UT_ASSERTeq(stream.helpers.validate_timestamps({region}, true), true);`

No need to create region_container.
___
*[`tests/unittest/timestamp.cpp` line 123 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GGysT34dctSwOiecJ:-N5GGysT34dctSwOiecK:b76w1bc) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L123)):*
> ```cpp
> 
> 				/* Multithreaded append to many regions with global ordering */
> 				parallel_exec(no_regions, [&](size_t thread_id) {
> ```

can you either use existing helper method or move common code in all testcases to separate function? I see the same thing for the 3rd time ;d
___
*[`tests/unittest/timestamp.cpp` line 136 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GHOyLEjMshWk-9Iov:-N5GHOyLEjMshWk-9Iow:bjkbear) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L136)):*
> ```cpp
> 				auto region_size = stream.sut.region_size(region_to_remove);
> 				UT_ASSERTeq(stream.helpers.remove_region(region_to_remove.offset), 0);
> 				regions.erase(regions.begin() + (int)pos);
> ```

avoid C-style casint
___
*[`tests/unittest/timestamp.cpp` line 141 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GHVHq567S4-6IYJoY:-N5GHVHq567S4-6IYJoZ:bb44cqn) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L141)):*
> ```cpp
> 				UT_ASSERTeq(stream.helpers.validate_timestamps(regions, true), true);
> 
> 				auto respawned_regions = stream.helpers.allocate_regions(1, region_size);
> ```

`initialize_single_region`? It will append the data automatically


<!-- Sent from Reviewable.io -->

2022-06-23 17:11 UTC, KFilipek reviewed
> Reviewed 1 of 6 files at r4, 2 of 4 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lv4LPA-6Y5U7_DNry:-N5GJGvj8nIUqa4Fjfs-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do you need to limit the elems count?
if you really need it - you can use our shrinkable `struct ranged` instead
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 88 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GGdcFAY1cVC4qFgMY:-N5GK5SX8R-pprUHTyLJ:b-3nwuyu) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L88)):*
> nit: UT_ASSERTeq(stream.helpers.validate_timestamps({region}, true), true);

right
___
*[`tests/unittest/timestamp.cpp` line 123 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GGysT34dctSwOiecJ:-N5GXdnD4ElObR26theI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L123)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

can you either use existing helper method or move common code in all testcases to separate function? I see the same thing for the 3rd time ;d
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 141 at r9](https://reviewable.io/reviews/pmem/pmemstream/217#-N5GHVHq567S4-6IYJoY:-N5GQWzj0_bCVJZoFpB6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5477683cb572266c1ed2a4dbf4f7ae128a61683f/tests/unittest/timestamp.cpp#L141)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`initialize_single_region`? It will append the data automatically
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 20:06 UTC, igchor requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 31 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 71 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9O1q2b14Q3nSmwXy:-N5H9O1q2b14Q3nSmwXz:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L71)):*
> ```cpp
> 	}
> 
> 	T get_data()
> ```

not needed?
___
*[`tests/common/stream_helpers.hpp` line 80 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9MO2AmSVokqWoGtP:-N5H9MO2AmSVokqWoGtQ:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L80)):*
> ```cpp
> 	}
> 
> 	uint64_t get_timestamp()
> ```

not needed?
___
*[`tests/common/stream_helpers.hpp` line 110 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9XSO4vzOeqYGxFBV:-N5H9XSO4vzOeqYGxFBW:b-b26q57) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L110)):*
> ```cpp
> template <typename T>
> std::vector<entry_iterator<T>> entry_iterator<T>::get_entry_iterators(pmemstream *stream,
> 								      std::vector<pmemstream_region> regions)
> ```

`const std::vector<pmemstream_region> &regions`
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9_Bk6VQ5Um84K5bY:-N5H9_Bk6VQ5Um84K5bZ:b-b26q57) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
> ```cpp
> 	}
> 
> 	std::vector<pmemstream_entry> get_entries_for_regions(std::vector<pmemstream_region> regions)
> ```

`const std::vector<pmemstream_region> &regions`
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9aRlE_XS8izoq2LO:-N5H9aRlE_XS8izoq2LP:b-b26q57) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
> ```cpp
> 	}
> 
> 	bool validate_timestamps(std::vector<struct pmemstream_region> regions, bool possible_gaps = true)
> ```

`const std::vector<pmemstream_region> &regions`
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9e7n-EvsNV9SeqJ0:-N5H9e7n-EvsNV9SeqJ1:bf8vlys) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
> ```cpp
> 	}
> 
> 	bool validate_timestamps(std::vector<struct pmemstream_region> regions, bool possible_gaps = true)
> ```

nit: consider creating two functions:
validate_timestamps_possible_gaps()
validate_timestamp_no_gaps()

When you call validate_timestamp(..., true) it's hard to tell what it means without looking at the signature of this function.
___
*[`tests/unittest/timestamp.cpp` line 8 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8Yjo0DlKn5fe624W:-N5H8Yjo0DlKn5fe624X:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L8)):*
> ```cpp
> // #include "../examples/examples_helpers.hpp"
> #include "libpmemstream.h"
> #include "libpmemstream_internal.h"
> ```

not needed?
___
*[`tests/unittest/timestamp.cpp` line 10 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8R-K1Q2TXBHd7ZDm:-N5H8R-K1Q2TXBHd7ZDn:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L10)):*
> ```cpp
> #include "libpmemstream_internal.h"
> #include "rapidcheck_helpers.hpp"
> #include "span.h"
> ```

not needed?
___
*[`tests/unittest/timestamp.cpp` line 13 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8Sj54nM8HdBPu4Bz:-N5H8Sj54nM8HdBPu4C-:bcbxvm7) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L13)):*
> ```cpp
> #include "stream_helpers.hpp"
> #include "thread_helpers.hpp"
> #include "unittest.h"
> ```

not needed? you probably want unittest.hpp though
___
*[`tests/unittest/timestamp.cpp` line 15 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8aby68xCE64kYzYs:-N5H8aby68xCE64kYzYt:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L15)):*
> ```cpp
> #include "unittest.h"
> 
> #include <iostream>
> ```

not needed?
___
*[`tests/unittest/timestamp.cpp` line 16 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8_qG7KIV8pbJJ7fy:-N5H8_qG7KIV8pbJJ7fz:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L16)):*
> ```cpp
> 
> #include <iostream>
> #include <string.h>
> ```

not needed?
___
*[`tests/unittest/timestamp.cpp` line 41 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8dZ-0E96FeqdRm6U:-N5H8dZ-0E96FeqdRm6V:bfcm7qw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L41)):*
> ```cpp
> };
> 
> std::ostream &operator<<(std::ostream &os, const payload &data)
> ```

not needed?
___
*[`tests/unittest/timestamp.cpp` line 48 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8vEd3-TuRA-xoziC:-N5H8vEd3-TuRA-xoziD:b1xwyld) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L48)):*
> ```cpp
> 
> template <typename T>
> void multithreaded_synchronous_append(T &stream, std::vector<pmemstream_region> regions, size_t no_elements)
> ```

`const std::vector<>&  regions`

You also don't need the template, you can just accept `pmemstream_test_base &stream`
___
*[`tests/unittest/timestamp.cpp` line 51 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H57yl62nq8zqC9AzV:-N5H57yl62nq8zqC9AzW:b-s6i1xv) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L51)):*
> ```cpp
> {
> 	parallel_exec(regions.size(), [&](size_t thread_id) {
> 		for (size_t i = 0; i < no_elements; i++) {
> ```

why can't you use existing helper instead of this loop?
___
*[`tests/unittest/timestamp.cpp` line 73 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8HGE2z4u9UZSndyB:-N5H8HGE2z4u9UZSndyC:b-bl9egu) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L73)):*
> ```cpp
> 		return_check ret;
> 		// cases:
> 		// (prereq1 case1) "verify increasing timestamp values in each region after synchronous append"
> ```

please remove this comment, it just repeats the strings from rc::checks
___
*[`tests/unittest/timestamp.cpp` line 89 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H89TE99-DlAwJkfqZ:-N5H89TE99-DlAwJkfq_:brimqd) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L89)):*
> ```cpp
> 					 // Single region ordering validation
> 					 for (auto &region : regions) {
> 						 UT_ASSERTeq(stream.helpers.validate_timestamps({region}, true), true);
> ```

nit: `UT_ASSERT(stream.helpers.validate_timestamps(regions, true));`
___
*[`tests/unittest/timestamp.cpp` line 96 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H5RS17FpVjzOjlU78:-N5H5RS17FpVjzOjlU79:b-6etlkw) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L96)):*
> ```cpp
> 			"verify globally increasing timestamp values in multi region environment after synchronous append",
> 			[&](pmemstream_with_multi_empty_regions &&stream,
> 			    ranged<size_t, 1, TEST_DEFAULT_REGION_MULTI_MAX_COUNT> no_elements) {
> ``` [...]

2022-06-27 09:52 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 33 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`-- commits` line 7 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZAbDy2kdG6GnPLGx2):*
it's not "moved"
___
*[`tests/common/stream_helpers.hpp` line 18 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZAjajDlE1w2lu8z8w:-N5ZAjajDlE1w2lu8z8x:bbnpsb9) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L18)):*
> ```cpp
> // #include "libpmemstream_internal.h"
> #define PMEMSTREAM_INVALID_TIMESTAMP (0ULL)
> #define PMEMSTREAM_FIRST_TIMESTAMP (PMEMSTREAM_INVALID_TIMESTAMP + 1ULL)
> ```

do you need these?
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZB5nTEP3hHIx4QypQ:-N5ZB5nTEP3hHIx4QypR:b-b51ym7) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
> ```cpp
> 	}
> 
> 	std::vector<pmemstream_entry> get_entries_for_regions(std::vector<pmemstream_region> regions)
> ```

get_entries_from_regions + default value for 'regions' to get all entries in stream
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBKdX2HRqe2539qyc:-N5ZBKdX2HRqe2539qyd:b-efbi1k) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
> ```cpp
> 	}
> 
> 	bool validate_timestamps(std::vector<struct pmemstream_region> regions, bool possible_gaps = true)
> ```

you can add a short comment for this helper, it's not obvious what "validate_timestamps" mean
___
*[`tests/common/stream_helpers.hpp` line 700 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBSnlEKk4o-GqBP5e:-N5ZBSnlEKk4o-GqBP5f:bqebhii) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L700)):*
> ```cpp
> 
> 	/* This function closes and reopens the stream. All pointers to stream data, iterators, etc. are
> 	 * invalidated. */
> ```

why this change?
___
*[`tests/unittest/timestamp.cpp` line 4 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBW1e39Qbe804LCxe:-N5ZBW1e39Qbe804LCxf:b-j3yu1) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L4)):*
> ```cpp
> /* Copyright 2022, Intel Corporation */
> 
> #include <rapidcheck.h>
> ```

no need for this, since you use "rapidcheck_helpers"


<!-- Sent from Reviewable.io -->

2022-06-27 10:49 UTC, KFilipek reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 71 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9O1q2b14Q3nSmwXy:-N5ZXSKGE-HGL9r9Hqrz:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 80 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9MO2AmSVokqWoGtP:-N5ZX5iHAsU6VASRRXyY:b-41rodi) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L80)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Needed internally by class, is implemented as an extended timestamp compare
___
*[`tests/common/stream_helpers.hpp` line 110 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9XSO4vzOeqYGxFBV:-N5ZXrHD0uBsDiUn632c:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L110)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<pmemstream_region> &regions`
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9_Bk6VQ5Um84K5bY:-N5ZYC722GwFl3zAZBoT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<pmemstream_region> &regions`
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9aRlE_XS8izoq2LO:-N5ZYLFk5j9nzxA3mg9Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<pmemstream_region> &regions`
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBKdX2HRqe2539qyc:-N5Zb1b6-uoAL2spWw7a:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add a short comment for this helper, it's not obvious what "validate_timestamps" mean
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 700 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBSnlEKk4o-GqBP5e:-N5Zb5WYBlTNuXiGVz3u:b-3k75uc) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L700)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

It's good question for `make cppformat`. I've reverted this change
___
*[`tests/unittest/timestamp.cpp` line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvtra5u_FT9a3pHyE:-N5Zhm928cA1roA1Mw3p:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need this payload struct? we won't print the data in a pretty form within the test
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 76 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvl444YN5Ql0_Bm3v:-N5ZkQnd1Bewaa52cohE:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L76)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we have a helper `append` for this whole `for` loop
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 4 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBW1e39Qbe804LCxe:-N5Zf68Y8N1o-e0V1NPr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no need for this, since you use "rapidcheck_helpers"
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 8 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8Yjo0DlKn5fe624W:-N5ZfGhy0M5rZHzee3rs:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 10 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8R-K1Q2TXBHd7ZDm:-N5Zh8VNADghVHp2p-CO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 15 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8aby68xCE64kYzYs:-N5ZhJb2-pB2KxD-221a:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 16 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8_qG7KIV8pbJJ7fy:-N5ZhJxp4EVR1DsfJk3f:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 41 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8dZ-0E96FeqdRm6U:-N5ZhmfZDc23NAB0RbOe:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L41)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 48 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8vEd3-TuRA-xoziC:-N5ZkIay-xb6WEB-jUcv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<>&  regions`

You also don't need the template, you can just accept `pmemstream_test_base &stream`
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 73 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8HGE2z4u9UZSndyB:-N5ZkMTP7XoxKGHHyRVM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L73)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></sum [...]

2022-06-27 11:54 UTC, igchor requested changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed (commit messages unreviewed), 16 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9_Bk6VQ5Um84K5bY:-N5_-Ak7EAoFs7nD1d2q:bfhqmln) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[`tests/unittest/timestamp.cpp` line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvtra5u_FT9a3pHyE:-N5_-NX98xyhUiML4xXB:b-bhun86) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L26)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not use std::string as in other tests?
___
*[`tests/unittest/timestamp.cpp` line 48 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8vEd3-TuRA-xoziC:-N5_-QYp8jpD0Md_8YKT:bfo3vfk) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L48)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done: `const std::vector<>& regions`
___
*[`tests/unittest/timestamp.cpp` line 117 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H715c1e0OHwiCTIQ4:-N5_-jy65VSTjC28VhkF:bb90w66) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L117)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> *rc::gen::elementOf(regions))

Right, but:
- I have some set of regions
- Remove 1, then add 1
- If something other will change (e.g. you miss another region, it will fail).
In your case you will miss it.
</blockquote></details>

I don't understand what you mean by "miss another region". But nevermind, it's OK


<!-- Sent from Reviewable.io -->

2022-06-27 14:56 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 4 of 7 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`-- commits` line 6 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_XUz60QVQwqI2HVbD):*
\+ why?
___
*[`tests/common/stream_helpers.hpp` line 36 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lyfQu2gDjnevUezkD:-N5_ZLMw4UPMtfkoSN_e:btzvmch) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L36)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> should it throw when there are no entries...?
I think it's the only way to fail using constructor. Other way is to provide fabric method.
</blockquote></details>

what I'm saying is that a entry_iterator with no entries is a valid iterator - entries may come later on
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZB5nTEP3hHIx4QypQ:-N5_ct1B4MkO0BueFa1-:b-hx1yju) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

get_entries_from_regions + default value for 'regions' to get all entries in stream
</blockquote></details>

hmm, maybe no default value (for consistency with other helpers), but please rename to `_from_regions`
___
*[`tests/common/stream_helpers.hpp` line 28 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_e63bBmPrBuH9HDYd:-N5_e63bBmPrBuH9HDYe:b-riblrg) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/stream_helpers.hpp#L28)):*
> ```cpp
> class entry_iterator {
>  public:
> 	entry_iterator(pmemstream *stream, pmemstream_region &region) : stream(stream)
> ```

isn't this class taken (partially) from the example? please mention that in commit msg
___
*[`tests/common/stream_helpers.hpp` line 634 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_Zv6z21W1j9h3KhEh:-N5_Zv6z21W1j9h3KhEi:b-z112fa) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/stream_helpers.hpp#L634)):*
> ```cpp
> 
> 	/* Validation method to check timestamp order across regions when some entries/regions are missing */
> 	bool validate_timestamps_possible_gaps(const std::vector<struct pmemstream_region> &regions)
> ```

why do we need 2 functions instead of just 1?
___
*[`tests/unittest/timestamp.cpp` line 4 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_dR719wfELsz-TU_i:-N5_dR719wfELsz-TU_j:b1khojm) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L4)):*
> ```cpp
> /* Copyright 2022, Intel Corporation */
> 
> #include "libpmemstream.h"
> ```

I think you rather want to include "unittest.hpp"
___
*[`tests/unittest/timestamp.cpp` line 36 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__fjT-pv6snM0ZJjW:-N5__fjT-pv6snM0ZJjX:b-f23vxp) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L36)):*
> ```cpp
> 	return run_test(test_config, [&] {
> 		return_check ret;
> 		ret += rc::check("verify increasing timestamp values in each region after synchronous append",
> ```

these are not "properties" - pls fix all tests' descriptions
___
*[`tests/unittest/timestamp.cpp` line 45 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__cIW1KYR7e_UrymB:-N5__cIW1KYR7e_UrymC:bliakv3) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L45)):*
> ```cpp
> 					 multithreaded_synchronous_append(stream, regions, data);
> 
> 					 // Single region ordering validation
> ```

all `//` comments -> `/**/`
___
*[`tests/unittest/timestamp.cpp` line 84 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_boJz4b-YswvW-fu3:-N5_boJz4b-YswvW-fu4:b-47moim) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L84)):*
> ```cpp
> 				UT_ASSERT(stream.helpers.validate_timestamps_possible_gaps(regions));
> 
> 				regions[pos] = stream.helpers.initialize_single_region(region_size, data);
> ```

you could use another set of data (`extra_data`) instead
___
*[`tests/unittest/timestamp.cpp` line 89 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__tom2IHGuPEvZath:-N5__tom2IHGuPEvZati:br9gvk5) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L89)):*
> ```cpp
> 			});
> 
> 		ret += rc::check(
> ```

if you're not adding this test case now, please remove this test and just leave a comment, what TC should be added in the future


<!-- Sent from Reviewable.io -->

2022-06-27 15:40 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 4 of 7 files reviewed, 17 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/rapidcheck_helpers.hpp` line 144 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_o2UIEA-9OLDnUmE1:-N5_o2UIEA-9OLDnUmE2:bukom8z) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/rapidcheck_helpers.hpp#L144)):*
> ```cpp
> 
> template <>
> struct Arbitrary<pmemstream_with_multi_empty_regions<true, true>> {
> ```

WHy do you implement a generator for specialized template? You can just implement it for all combinations:

```
template <bool I1, bool I2>
struct Arbitrary<pmemstream_with_multi_empty_regions<I1, I2>> {
	static Gen<pmemstream_with_multi_empty_regions<I1, I2>> arbitrary()
	{
		return gen::noShrink(gen::construct<pmemstream_with_multi_empty_regions<I1, I2>>(
			gen::arbitrary<pmemstream_test_base>(),
			gen::inRange<size_t>(1, TEST_DEFAULT_REGION_MULTI_MAX_COUNT)));
	}
};

```


<!-- Sent from Reviewable.io -->

2022-06-29 13:07 UTC, KFilipek reviewed
> Reviewed 2 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`-- commits` line 6 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_XUz60QVQwqI2HVbD):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ why?
</blockquote></details>

Done.
___
*[`tests/common/rapidcheck_helpers.hpp` line 144 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_o2UIEA-9OLDnUmE1:-N5jNRI58N8W9Z5tnPfb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/rapidcheck_helpers.hpp#L144)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

WHy do you implement a generator for specialized template? You can just implement it for all combinations:

```
template <bool I1, bool I2>
struct Arbitrary<pmemstream_with_multi_empty_regions<I1, I2>> {
	static Gen<pmemstream_with_multi_empty_regions<I1, I2>> arbitrary()
	{
		return gen::noShrink(gen::construct<pmemstream_with_multi_empty_regions<I1, I2>>(
			gen::arbitrary<pmemstream_test_base>(),
			gen::inRange<size_t>(1, TEST_DEFAULT_REGION_MULTI_MAX_COUNT)));
	}
};

```
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 36 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lyfQu2gDjnevUezkD:-N5jRqAM6J8Iz7OnusnI:byxjjgd) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what I'm saying is that a entry_iterator with no entries is a valid iterator - entries may come later on
</blockquote></details>

Right, but it's not the case. 
___
*[`tests/common/stream_helpers.hpp` line 26 at r6](https://reviewable.io/reviews/pmem/pmemstream/217#-N5A2JEnBX_kXOcsJtur:-N5jQnE--1Ux5NszfVO5:b4zuvgi) ([raw file](https://github.com/pmem/pmemstream/blob/0a0823380aad8869a5d9d68f7e1ba960512b3f6c/tests/common/stream_helpers.hpp#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please remove the template, you don;t need it
</blockquote></details>

Indeed xD
___
*[`tests/common/stream_helpers.hpp` line 18 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZAjajDlE1w2lu8z8w:-N5dux_w-NnOULqizYJd:b-rui55y) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need these?
</blockquote></details>

Yes. I can link `libpmemstream_internal.h`, but then relative paths will fail in benchmark compilation. I lose 1 day to pożenić this and I failed, so I've reverted change and moved it here.
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H9_Bk6VQ5Um84K5bY:-N5jS8UeD0WlX_hsqM-X:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 627 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZB5nTEP3hHIx4QypQ:-N5jSOWC7HluaoKcB-PM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L627)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm, maybe no default value (for consistency with other helpers), but please rename to `_from_regions`
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 28 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_e63bBmPrBuH9HDYd:-N5jRoXJ21OHd0r9woVL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/stream_helpers.hpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't this class taken (partially) from the example? please mention that in commit msg
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 634 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_Zv6z21W1j9h3KhEh:-N5jSPxO-TAQsCsfKgzX:b-szfoaj) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/stream_helpers.hpp#L634)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need 2 functions instead of just 1?
</blockquote></details>

It's @igchor requirement to be more verbose on function calls.
`validate_timestamps(regions, true)` is less clear than `validate_timestamps_possible_gaps(regions)`
___
*[`tests/unittest/timestamp.cpp` line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lvtra5u_FT9a3pHyE:-N5jTB_12Ud73LJeNu7p:b-tkxymf) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/unittest/timestamp.cpp#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not use std::string as in other tests?
</blockquote></details>

Now should be fine
___
*[`tests/unittest/timestamp.cpp` line 48 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5H8vEd3-TuRA-xoziC:-N5jTMy62XAIyNDglhhI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/unittest/timestamp.cpp#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not done: `const std::vector<>& regions`
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 4 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_dR719wfELsz-TU_i:-N5jT62e4zN2bvHFvwf_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you rather want to include "unittest.hpp"
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 36 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__fjT-pv6snM0ZJjW:-N5jYYPg77ZVDJiNLGcN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

these are not "properties" - pls fix all tests' descriptions
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 45 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__cIW1KYR7e_UrymB:-N5jTaiy5oqauz-RpRS6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

all `//` comments -> `/**/`
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 84 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_boJz4b-YswvW-fu3:-N5jXKfuAuGzluNyi3RI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could use another set of data (`extra_data`) instead
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 89 at r13](h [...]

2022-06-29 13:12 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 4 of 7 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lziKyDEjDeCsFjjTD:-N5j_kd-6OUttWnnkw4j:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you can move this class into "pmem" namespace here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-29 13:19 UTC, igchor requested changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 5 of 7 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/rapidcheck_helpers.hpp` line 144 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_o2UIEA-9OLDnUmE1:-N5jagwQE1Il32BnM6Sg:b59lapw) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/rapidcheck_helpers.hpp#L144)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done? you dont need this specialization


<!-- Sent from Reviewable.io -->

2022-06-29 14:44 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r15, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 14 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/common/rapidcheck_helpers.hpp` line 144 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5_o2UIEA-9OLDnUmE1:-N5juKMZ3gmZ8hAK1EUf:bsfu08z) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/common/rapidcheck_helpers.hpp#L144)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still not done? you dont need this specialization
</blockquote></details>

Right, I missed it when committing some part. Sorry for that.


<!-- Sent from Reviewable.io -->

2022-06-29 15:01 UTC, igchor reviewed
LGTM, but it does not close #211 until asynchronous cases are implemneted

> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217#-:-N5jybb25zfcVrhQ49JF:bcy2jcj)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-06-29 15:07 UTC, KFilipek commented
> LGTM, but it does not close #211 until asynchronous cases are implemneted
> 
> > Reviewed 1 of 1 files at r17.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217#-:-N5jybb25zfcVrhQ49JF:bcy2jcj)_ status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk)

I've change description to not resolve issue #211

2022-06-30 08:24 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217#-:-N5nhapo4nksaMIInQD7:bnfp4nl)* status: 6 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-06-30 08:26 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: 6 of 7 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/common/stream_helpers.hpp` line 390 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5nhfkm6jNlpI_bWdwW:-N5nhfkm6jNlpI_bWdwX:b-90bopr) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L390)):*
> ```cpp
> 		struct pmemstream_entry entry;
> 		for (size_t i = 0; i < data.size(); ++i) {
> 			pmemstream_region_runtime *rrt = nullptr;
> ```

Hm, after this change, do we still need to set `call_region_initialize` in the generator at all? (do we need those extra template params to the generator?) We are not inserting anything concurrently now.


<!-- Sent from Reviewable.io -->

2022-06-30 10:57 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 3 files at r15, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 9 unresolved discussions (waiting on @KFilipek)

___
*[`-- commits` line 7 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5nckt9ESWNFjgp_cns):*
that also would require some explanation, I think, especially since there's no comment in the code for that part
___
*[`tests/common/stream_helpers.hpp` line 36 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lyfQu2gDjnevUezkD:-N5o8Jak1ASvl1-S6TH1:b4inc9d) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L36)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Right, but it's not the case. 
</blockquote></details>

what's not the case? we may use this helper for other tests than just this one :wink:

when you try to `get_timestamp` from the iterator or when using `get_entries_from_region` you have checks for valid iterators - so this check is not required on the creation time, I think
___
*[`tests/common/stream_helpers.hpp` line 18 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZAjajDlE1w2lu8z8w:-N5ngTqvAezkuD_lbE50:bbkwwm4) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Yes. I can link `libpmemstream_internal.h`, but then relative paths will fail in benchmark compilation. I lose 1 day to pożenić this and I failed, so I've reverted change and moved it here.
</blockquote></details>

when I asked this question it wasn't used anywhere :wink: 
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBKdX2HRqe2539qyc:-N5o9HlNEnddg2zvQeUL:bt3yblq) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you can drop `Validation method` from these 2 descriptions - it's rather obvious, these are methods :wink:
___
*[`tests/common/stream_helpers.hpp` line 637 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5o9XYj9EIcLS9zGeDx:-N5o9XYj9EIcLS9zGeDy:b-2lryww) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L637)):*
> ```cpp
> 	}
> 
> 	/* Validation method to check timestamp order across regions when some entries/regions are missing */
> ```

1. `regions are missing` may be misleading - I think you'll get an error (when creating an iterator) if you'll pass here a non-existing region...?
2. soo... I'd just leave here: `... when entries may be missing` (it's not for sure that they are missing :wink: )
___
*[`tests/common/stream_helpers.hpp` line 637 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5o9eGSDNvwFmb-vCK6:-N5o9eGT5WEWYiwIJCyR:b7nqi4j) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L637)):*
> ```cpp
> 	}
> 
> 	/* Validation method to check timestamp order across regions when some entries/regions are missing */
> ```

`timestamps' order`
___
*[`tests/common/stream_helpers.hpp` line 675 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5oAzzUDSjjGkSKN8eZ:-N5oAzzUDSjjGkSKN8e_:bmreohp) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L675)):*
> ```cpp
> 				timestamps.back() == PMEMSTREAM_FIRST_TIMESTAMP + timestamps.size() - 1;
> 		}
> 		return true;
> ```

redundant return path
___
*[`tests/unittest/timestamp.cpp` line 45 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__cIW1KYR7e_UrymB:-N5ntuxOC-jREOeqfoDW:b-2lo72c) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L45)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

there are still some `//` comments in this PR
___
*[`tests/unittest/timestamp.cpp` line 56 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5oCNcF52yD_ozL-7pq:-N5oCNcGE1ruHC1BDeHJ:btlxlnw) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/unittest/timestamp.cpp#L56)):*
> ```cpp
> 				/* Multithreaded append to many regions with global ordering. */
> 				multithreaded_synchronous_append(stream, regions, data);
> ```

you can use the new helper func `get_entries_from_regions(regions)` to check if entries' count is as expected


<!-- Sent from Reviewable.io -->

2022-06-30 13:44 UTC, KFilipek reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 7 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5nckt9ESWNFjgp_cns):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that also would require some explanation, I think, especially since there's no comment in the code for that part
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 36 at r2](https://reviewable.io/reviews/pmem/pmemstream/217#-N4lyfQu2gDjnevUezkD:-N5oq1_v6VI8zcYeK9eb:bs7wumx) ([raw file](https://github.com/pmem/pmemstream/blob/4996b06dc46a16f95af67f10d1dea5b4989d4bf2/tests/common/stream_helpers.hpp#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's not the case? we may use this helper for other tests than just this one :wink:

when you try to `get_timestamp` from the iterator or when using `get_entries_from_region` you have checks for valid iterators - so this check is not required on the creation time, I think
</blockquote></details>

Done. 
___
*[`tests/common/stream_helpers.hpp` line 643 at r10](https://reviewable.io/reviews/pmem/pmemstream/217#-N5ZBKdX2HRqe2539qyc:-N5ohPZD9xYwJqPrndNi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d9e05fdac229a8d96f4978b373769f2d58ff2b5c/tests/common/stream_helpers.hpp#L643)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop `Validation method` from these 2 descriptions - it's rather obvious, these are methods :wink:
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 637 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5o9XYj9EIcLS9zGeDx:-N5ohO_m1zDYNMEM2FOg:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L637)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. `regions are missing` may be misleading - I think you'll get an error (when creating an iterator) if you'll pass here a non-existing region...?
2. soo... I'd just leave here: `... when entries may be missing` (it's not for sure that they are missing :wink: )
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 637 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5o9eGSDNvwFmb-vCK6:-N5ohOpR0KpdCL4lxJtX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L637)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`timestamps' order`
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 675 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5oAzzUDSjjGkSKN8eZ:-N5oheRoEDBttDvn_GqZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/common/stream_helpers.hpp#L675)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant return path
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 45 at r13](https://reviewable.io/reviews/pmem/pmemstream/217#-N5__cIW1KYR7e_UrymB:-N5ohun9-aEeWOyDb1iw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7404ee14d2afd91fc9d36dd6bb8b3ffb2b89ebe5/tests/unittest/timestamp.cpp#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there are still some `//` comments in this PR
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 56 at r18](https://reviewable.io/reviews/pmem/pmemstream/217#-N5oCNcF52yD_ozL-7pq:-N5opOqy40VbMCCk5umU:bs7wumx) ([raw file](https://github.com/pmem/pmemstream/blob/7390c2f245369a480b4198e3297cc4fd0d5f15be/tests/unittest/timestamp.cpp#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can use the new helper func `get_entries_from_regions(regions)` to check if entries' count is as expected
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2022-06-30 16:01 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/217#-:-N5pL3gb7gW21hy_MSDj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-06-30 16:12 UTC, merged