Change definition of span_entry_atomic_store and span_entry_atomic_load
pmem/pmemstream pull request #247
Opened 2022-07-13 13:02 UTC by KFilipek

There are 2 ways of mitigating ABI warning.
The first one is to avoid copying structures with a flexible array member
by using pointers. The second is to change structures declarations, e.g.:

struct span_timestamped_base {
    struct span_base span_base;
    uint64_t timestamp;
};

struct span_entry {
    struct span_timestamped_base span_base;
    uint64_t data[];
};

2022-07-13 13:12 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[`src/span.c` line 63 at r1](https://reviewable.io/reviews/pmem/pmemstream/247#-N6rfpWJ801qrWX2zSus:-N6rfpWKC2xXcnxaRnQe:baztxu4) ([raw file](https://github.com/pmem/pmemstream/blob/a2b25864d7d723b3ce870b6d46e56a35ed070efd/src/span.c#L63)):*
> ```C
> struct span_entry *span_entry_atomic_load(const struct span_entry *entry_ptr)
> {
> 	struct span_entry *entry = (struct span_entry *)malloc(sizeof(struct span_entry));
> ```

We don't want to allocate the memory if it's not necessary. I prefer to have a note from the compiler than call malloc/free.


<!-- Sent from Reviewable.io -->

2022-07-14 09:23 UTC, lukaszstolarczuk reviewed
hmm.. do you plan to update/change this PR somehow or are we closing this...?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247#-:-N6w07tk-9FNWos6LjbK:b3546d0)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/span.c` line 63 at r1](https://reviewable.io/reviews/pmem/pmemstream/247#-N6rfpWJ801qrWX2zSus:-N6w04fb3nMEuEZbzW9w:b-8fx2u7) ([raw file](https://github.com/pmem/pmemstream/blob/a2b25864d7d723b3ce870b6d46e56a35ed070efd/src/span.c#L63)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We don't want to allocate the memory if it's not necessary. I prefer to have a note from the compiler than call malloc/free.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-07-15 11:55 UTC, karczex commented
*[`src/span.c` line 63 at r1](https://reviewable.io/reviews/pmem/pmemstream/247#-N6rfpWJ801qrWX2zSus:-N70hiL60piXPn5d-nZI:b44tpx) ([raw file](https://github.com/pmem/pmemstream/blob/a2b25864d7d723b3ce870b6d46e56a35ed070efd/src/span.c#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

👍


<!-- Sent from Reviewable.io -->

2022-07-21 12:36 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/span.c` line 63 at r1](https://reviewable.io/reviews/pmem/pmemstream/247#-N6rfpWJ801qrWX2zSus:-N7Vkddi1S4MUjVdw5L6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a2b25864d7d723b3ce870b6d46e56a35ed070efd/src/span.c#L63)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

👍
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 13:21 UTC, igchor reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`src/span.c` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/247#-N7VtyfM6cKiWZJr0UmT:-N7VtyfM6cKiWZJr0UmU:b629v8i) ([raw file](https://github.com/pmem/pmemstream/blob/f4e0cde6183def099008d809ef61dd78b0cdb7d5/src/span.c#L54)):*
> ```C
> }
> 
> void span_entry_atomic_store(struct span_timestamped_base *dst, struct span_timestamped_base entry)
> ```

you should rename the function name to something like: `span_timestamped_base_atomic_store`
Same for load


<!-- Sent from Reviewable.io -->

2022-07-22 14:25 UTC, lukaszstolarczuk reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[`src/span.c` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/247#-N7VtyfM6cKiWZJr0UmT:-N7aHB3L9X4jgS0fMN_3:bb03hgx) ([raw file](https://github.com/pmem/pmemstream/blob/f4e0cde6183def099008d809ef61dd78b0cdb7d5/src/span.c#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you should rename the function name to something like: `span_timestamped_base_atomic_store`
Same for load
</blockquote></details>

Actually, I think it should be the other way around. We should keep `span_entry` as param (and in the name of this function) and just cast to `span_timestamped_base` inside of this function.

This extra function is here specifically for span_entry.


<!-- Sent from Reviewable.io -->

2022-07-27 12:54 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[`src/span.c` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/247#-N7VtyfM6cKiWZJr0UmT:-N7zi25NAaedOWKRTEeI:b-bkgur3) ([raw file](https://github.com/pmem/pmemstream/blob/f4e0cde6183def099008d809ef61dd78b0cdb7d5/src/span.c#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually, I think it should be the other way around. We should keep `span_entry` as param (and in the name of this function) and just cast to `span_timestamped_base` inside of this function.

This extra function is here specifically for span_entry.
</blockquote></details>

But if we'd keep span_entry as param then we would still have the GCC note.


<!-- Sent from Reviewable.io -->

2022-08-01 14:27 UTC, KFilipek reviewed
I renamed the structure as you wished.

> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247#-:-N8OnVSI08KKOneMscso:b8237ez)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-08-01 15:11 UTC, lukaszstolarczuk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`src/span.c` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/247#-N7VtyfM6cKiWZJr0UmT:-N8OxK3K6Xzd3WE4SQ5L:bsqpj7j) ([raw file](https://github.com/pmem/pmemstream/blob/f4e0cde6183def099008d809ef61dd78b0cdb7d5/src/span.c#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

But if we'd keep span_entry as param then we would still have the GCC note.
</blockquote></details>

yy what happened here? the function name should be changed, not the struct :confused: 


<!-- Sent from Reviewable.io -->

2022-08-03 09:44 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/247#-:-N8Y2gCeEePuPEXPQuhI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-08-03 12:15 UTC, merged