[tests] add sync cases for timestamp test
pmem/pmemstream pull request #248
Opened 2022-07-13 16:51 UTC by KFilipek

2022-07-14 11:37 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6w1I1sE9Y9qwlH-sgR:-N6wUS7c4dg9m50b7h4M:b-w3t1le) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we poll these futures somewhere?
</blockquote></details>

as discussed it should be polled somewhere within the test body, not in the dtor (of future wrapper)
___
*[`tests/unittest/timestamp.cpp` line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6wUpU91L9Prmt2Q3xe:-N6wUpU91L9Prmt2Q3xf:b7y23xc) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L88)):*
> ```cpp
> 
> 				/* Global ordering validation. */
> 				if (regions.size() > 1)
> ```

are you rebased to the latest master? I think this value line is updated on the master branch :wink: 


<!-- Sent from Reviewable.io -->

2022-07-19 08:08 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7KUszV8icOyUSa69g7:br7u1ma) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
> ```cpp
> 	std::vector<std::vector<future_type>> futures(concurrency_level);
> 
> 	for (size_t i = 0; i < concurrency_level; i++) {
> ```

Didn't we want to test multithreaded appends? Why it's not inside parallel_exec?


<!-- Sent from Reviewable.io -->

2022-07-19 10:40 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6w0SB74ulFBakUrQ7B):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`async`
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6vgZ_tAybvIsOJ_Xxt:-N70DD1t2na0Gocoa1JO:b-81la7d) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

where is the multithreading in this test?
</blockquote></details>

Right
___
*[`tests/unittest/timestamp.cpp` line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6w1I1sE9Y9qwlH-sgR:-N7L1WsSEhK5_XUXfAMu:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed it should be polled somewhere within the test body, not in the dtor (of future wrapper)
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6w287hDobpSuWHPVj0:-N7L1cAE4Cn1XxTOcULN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we should use config's `max_concurrency`, because CI timed-out on pmemcheck test (probably because we had too many regions...?)
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6wUpU91L9Prmt2Q3xe:-N7FsO_HCs8Jd3NuPCPl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you rebased to the latest master? I think this value line is updated on the master branch :wink: 
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 97 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6w0_wpCeHBjrkON2-w:-N7L1feEDFz6fVyyf0Nr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can get rid of this comment, after this PR :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 14:05 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LfTNJAGRIaQiZWoFo):*
?
___
*[`tests/unittest/timestamp.cpp` line 98 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6vg6xS57LqcZaXLPI0:-N7LlNagAOJNX5zZxXeN:b-nwlmlv) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L98)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

All those tests look exactly the same as the sync ones, Can't you just make them generic? (e.g. make a template and pass `append` function as a parameter or just accept a bool param in lambda and decide whether to do sync or async based on it?)
</blockquote></details>

what about this one? I think for sync tests it makes a little more sense to use "chunks", but it wouldn't hurt, so this change is still possible :-)
___
*[`tests/unittest/timestamp.cpp` line 17 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LiogAEPJlx3aIjcxA:-N7LiogB-gC9E9yS7Al5:bbx4osp) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L17)):*
> ```cpp
> 
> void multithreaded_asynchronous_append(pmemstream_test_base &stream, const std::vector<pmemstream_region> &regions,
> 				       const std::vector<std::vector<std::string>> &data, size_t concurrency_level)
> ```

`concurrency_level` == `data.size()` (?)
___
*[`tests/unittest/timestamp.cpp` line 178 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LlV5C2oCxtm33GW-V:-N7LlV5D-lRB1-5HxYsX:bj6nnxy) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L178)):*
> ```cpp
> 
> 				size_t elements = 0;
> 				for (auto &part : data) {
> ```

pls use `chunk` name to be consistent with the helper function


<!-- Sent from Reviewable.io -->

2022-07-20 17:24 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LfTNJAGRIaQiZWoFo):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 98 at r1](https://reviewable.io/reviews/pmem/pmemstream/248#-N6vg6xS57LqcZaXLPI0:-N7RcYVH11iNV9JVZ194:biqo4ij) ([raw file](https://github.com/pmem/pmemstream/blob/0f009b05a668d305520ce9fb142aaaef2f17ec9e/tests/unittest/timestamp.cpp#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about this one? I think for sync tests it makes a little more sense to use "chunks", but it wouldn't hurt, so this change is still possible :-)
</blockquote></details>

I unified tests a lot, please review this part once again
___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7RcnHT-RxHwiwvCUeX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Didn't we want to test multithreaded appends? Why it's not inside parallel_exec?
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 17 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LiogAEPJlx3aIjcxA:-N7RcdbfCEVzOJMMk8r6:b-ijqnil) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`concurrency_level` == `data.size()` (?)
</blockquote></details>

it's max number of threads will be run
___
*[`tests/unittest/timestamp.cpp` line 178 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LlV5C2oCxtm33GW-V:-N7RccAS0QcLTFp0RMUJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L178)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use `chunk` name to be consistent with the helper function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 08:15 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 17 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LiogAEPJlx3aIjcxA:-N7UmynlBYRa0ryFZp-V:b-fo9ccm) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

it's max number of threads will be run
</blockquote></details>

but `data` is generated using `concurrency_level`, so I guess this param is redundant here...?
___
*[`tests/unittest/timestamp.cpp` line 59 at r7](https://reviewable.io/reviews/pmem/pmemstream/248#-N7UnDmsCv18zsJo4ryy:-N7UnDmsCv18zsJo4ryz:b1fnqqa) ([raw file](https://github.com/pmem/pmemstream/blob/ce59860405d2cec54e352a55c941a479817e9df5/tests/unittest/timestamp.cpp#L59)):*
> ```cpp
> {
> 	auto regions = stream.helpers.get_regions();
> 	size_t concurrency_level = std::min(regions.size(), test_config.max_concurrency);
> ```

use `get_concurrency_level()`
___
*[`tests/unittest/timestamp.cpp` line 173 at r7](https://reviewable.io/reviews/pmem/pmemstream/248#-N7Umkh8807NFhFW9j2g:-N7Umkh9E1_VT-wQDSxr:b1sc1ot) ([raw file](https://github.com/pmem/pmemstream/blob/ce59860405d2cec54e352a55c941a479817e9df5/tests/unittest/timestamp.cpp#L173)):*
> ```cpp
> 				RC_PRE(extra_data.size() > 0);
> 				auto [regions, elements] =
> 					generate_and_append_data(stream, test_config, true /* sync */);
> ```

`/* async */`


<!-- Sent from Reviewable.io -->

2022-07-21 09:56 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 17 at r5](https://reviewable.io/reviews/pmem/pmemstream/248#-N7LiogAEPJlx3aIjcxA:-N7V8T0V5Mk2VRhmcuLw:b-x9mm65) ([raw file](https://github.com/pmem/pmemstream/blob/891ccd44c78c03b300260f0488d82a55b0660677/tests/unittest/timestamp.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but `data` is generated using `concurrency_level`, so I guess this param is redundant here...?
</blockquote></details>

Done. Previously I don't get your point of view, right
___
*[`tests/unittest/timestamp.cpp` line 59 at r7](https://reviewable.io/reviews/pmem/pmemstream/248#-N7UnDmsCv18zsJo4ryy:-N7V8lvO6RLNqu_NpL4-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ce59860405d2cec54e352a55c941a479817e9df5/tests/unittest/timestamp.cpp#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use `get_concurrency_level()`
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 173 at r7](https://reviewable.io/reviews/pmem/pmemstream/248#-N7Umkh8807NFhFW9j2g:-N7VAttYDdm1J0wxS96Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ce59860405d2cec54e352a55c941a479817e9df5/tests/unittest/timestamp.cpp#L173)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`/* async */`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 10:59 UTC, igchor requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7VOd_W7L0g7TUnsxT-:b-c8qh9b) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done? I don't see any appends inside parallel_exec


<!-- Sent from Reviewable.io -->

2022-07-21 11:51 UTC, lukaszstolarczuk reviewed
Besides Igor's issue <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248#-:-N7Va7QvALZ-IHasKblp:b-gt30ze)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-07-21 12:56 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7VpFBC1pa1b6I4qnTn:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still not done? I don't see any appends inside parallel_exec
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 12:59 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7VpXDCDIrhG-tAghHJ:b5ohq8y) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now it's too much :stuck_out_tongue_winking_eye:  you have X threads doing appends over X regions


<!-- Sent from Reviewable.io -->

2022-07-21 13:24 UTC, igchor reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-08-04 06:22 UTC, karczex reviewed
Looks good.... besides it cause segfault on CI. Fun part is that, I cannot reproduce this failure on my local environment.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248#-:-N8bVu_x9byu66yB3GgJ:bfvhn5s)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-08-12 09:07 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGxFb61XPgoPmvytz:-N9GGxFb61XPgoPmvyu-:bvj569q) (no related file):*
pls use the latest miniasync version in dockers

___
___
*[`tests/unittest/timestamp.cpp` line 21 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGiUA0j8wakeygiCU:-N9GGiUA0j8wakeygiCV:b-peka4a) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L21)):*
> ```cpp
> 	using future_type = decltype(stream.helpers.async_append(regions[0], data[0]));
> 	std::vector<std::vector<future_type>> futures(data.size());
> 	std::mt19937_64 g(*rc::gen::arbitrary<size_t>());
> ```

is it safe to have one generator for multiple threads?
___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-N9GGpu83zevxzkAjGHS:b-aplulo) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
> ```cpp
> 		}
> 
> 		syncthreads();
> ```

do we still need syncthreads if we apply Piotr's miniasync's fix...?


<!-- Sent from Reviewable.io -->

2022-08-12 11:14 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/248#-N7KUszV8icOyUSa69g6:-N7Vu7AIEDTb-2iX4BQj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d0fd692644681029f29cf259b9057e1cb8de2ff6/tests/unittest/timestamp.cpp#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now it's too much :stuck_out_tongue_winking_eye:  you have X threads doing appends over X regions
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-N9GkKLt5QkcP6x1IYJy:bke3t6d) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we still need syncthreads if we apply Piotr's miniasync's fix...?
</blockquote></details>

Probably not, but previously we had 2x parallel_exec, syncthread do the same job. I think it's good to trigger polling simultaneously.


<!-- Sent from Reviewable.io -->

2022-08-12 11:44 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-N9GqenG5L6-sOBN-Wlg:bo7kv2y) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Probably not, but previously we had 2x parallel_exec, syncthread do the same job. I think it's good to trigger polling simultaneously.
</blockquote></details>

I think we want the opposite of that - from the test scenario point of view I think it'd be nice to do it independently, rather than start the second operation only after the first part is completely done
___
*[`tests/unittest/timestamp.cpp` line 28 at r15](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GrAeL0Nbk3HyyM0sn:-N9GrAeL0Nbk3HyyM0so:b-xeu8se) ([raw file](https://github.com/pmem/pmemstream/blob/98e3f012bca82bceeb6615b13b67eff6f7e38212/tests/unittest/timestamp.cpp#L28)):*
> ```cpp
> 		}
> 
> 		thread_local std::mt19937_64 g(thread_id);
> ```

as discussed: random seed + tid (`*rc::gen::arbitrary<size_t>() + thread_id`)


<!-- Sent from Reviewable.io -->

2022-08-12 15:11 UTC, lukaszstolarczuk commented
you can apply your fix (https://github.com/pmem/miniasync/pull/109) here as a workaround and we can update that later on (when they merge it)

2022-08-12 17:20 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGxFb61XPgoPmvytz:-N9GneXY2A67LVimuF70:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use the latest miniasync version in dockers
</blockquote></details>

Done.

___
___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-N9Hay4HDJBWGv8OycZ4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we want the opposite of that - from the test scenario point of view I think it'd be nice to do it independently, rather than start the second operation only after the first part is completely done
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 28 at r15](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GrAeL0Nbk3HyyM0sn:-N9Haj4F2rZr-oQw2C0-:bltvgpe) ([raw file](https://github.com/pmem/pmemstream/blob/98e3f012bca82bceeb6615b13b67eff6f7e38212/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed: random seed + tid (`*rc::gen::arbitrary<size_t>() + thread_id`)
</blockquote></details>

I removed it because of `*rc::gen::arbitrary<size_t>()` was the problem with waiting on lock (o.O)
Without this part it works like a charm.


<!-- Sent from Reviewable.io -->

2022-08-16 08:43 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-N9_nu7z5nijUl2VFEc7:bi3atph) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now, I believe `syncthreads_barrier` is redundant
___
*[`tests/unittest/timestamp.cpp` line 28 at r15](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GrAeL0Nbk3HyyM0sn:-N9_nb3r21n22wQybE5o:bprvkl6) ([raw file](https://github.com/pmem/pmemstream/blob/98e3f012bca82bceeb6615b13b67eff6f7e38212/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I removed it because of `*rc::gen::arbitrary<size_t>()` was the problem with waiting on lock (o.O)
Without this part it works like a charm.
</blockquote></details>

but now there's no randomization here...? `thread_id` will always be sequential and most likely identical between runs...?


<!-- Sent from Reviewable.io -->

2022-08-16 11:46 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 28 at r15](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GrAeL0Nbk3HyyM0sn:-N9aTE8bCloUx6sbJuuP:b36lepm) ([raw file](https://github.com/pmem/pmemstream/blob/98e3f012bca82bceeb6615b13b67eff6f7e38212/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but now there's no randomization here...? `thread_id` will always be sequential and most likely identical between runs...?
</blockquote></details>

Right, I also don't like this approach. Since miniasync is already fix, please revert those changes (leave 2 separate parallel_execs) and just use correct miniasync version in docker image.


<!-- Sent from Reviewable.io -->

2022-08-26 15:21 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 28 at r12](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GGpu83zevxzkAjGHR:-NAPjZJS2s3JxgHswvEG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/98e65f783dfae8972842a16b21849a1e89d49726/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now, I believe `syncthreads_barrier` is redundant
</blockquote></details>

Done.
___
*[`tests/unittest/timestamp.cpp` line 28 at r15](https://reviewable.io/reviews/pmem/pmemstream/248#-N9GrAeL0Nbk3HyyM0sn:-NAPjZkxAsOGttlWwdbi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/98e3f012bca82bceeb6615b13b67eff6f7e38212/tests/unittest/timestamp.cpp#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, I also don't like this approach. Since miniasync is already fix, please revert those changes (leave 2 separate parallel_execs) and just use correct miniasync version in docker image.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-29 08:58 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NAckpR3AEzd3egzn81Z:be23dz0) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
> ```cpp
> 	size_t concurrency_level = get_concurrency_level(test_config, regions);
> 	if (regions.size() > concurrency_level) {
> 		regions.erase(regions.begin() + static_cast<int>(concurrency_level), regions.end());
> ```

why is this erasing happening? we generate as many data vectors as `concurrency_level` (see below generator) - if there are any unused regions it's not a problem

perhaps, we should worry the other way around - what if `concurrency level > regions.size()`? can this happen?
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAcj-oS0LZMeDWDeQ3P:bkb3w6o) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
> ```cpp
> 	return run_test(test_config, [&] {
> 		return_check ret;
> 		test_config = get_test_config();
> ```

why do you need this line? test_config is passed to the `run_test` wrapper
___
*[`tests/unittest/timestamp.cpp` line 176 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcjBNO8_PIQYlJ1DtB:-NAcjBNO8_PIQYlJ1DtC:byqfla5) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L176)):*
> ```cpp
> 			[&](pmemstream_with_multi_empty_regions &&stream, const std::vector<std::string> &extra_data) {
> 				RC_PRE(extra_data.size() > 0);
> 				RC_PRE(extra_data.size() < 128);
> ```

why `<128`?


<!-- Sent from Reviewable.io -->

2022-08-29 11:46 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NAdPCerA8mteuU6DkQf:bxuiqq2) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why is this erasing happening? we generate as many data vectors as `concurrency_level` (see below generator) - if there are any unused regions it's not a problem

perhaps, we should worry the other way around - what if `concurrency level > regions.size()`? can this happen?
</blockquote></details>

It doesn't triggered after line 104.
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAdPLLi3i-IHEnY4DYE:boxkkc4) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do you need this line? test_config is passed to the `run_test` wrapper
</blockquote></details>

I use few times 'test_config' instead of calling `get_test_config()`. The `run_test()` creates copy of config object.
___
*[`tests/unittest/timestamp.cpp` line 176 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcjBNO8_PIQYlJ1DtB:-NAdQ09J0PA5uDYlrHV9:b-rn32ul) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L176)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `<128`?
</blockquote></details>

Done. Only for build testing, I've removed it in latest revision.


<!-- Sent from Reviewable.io -->

2022-08-29 12:04 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NAdU59A9ryFwCXFheoc:b-rsab22) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It doesn't triggered after line 104.
</blockquote></details>

I'm not sure what you're saying...
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAdTpOD08_mmTMFskCz:bn168jy) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I use few times 'test_config' instead of calling `get_test_config()`. The `run_test()` creates copy of config object.
</blockquote></details>

I'm not sure if I understand the problem...


<!-- Sent from Reviewable.io -->

2022-08-29 18:39 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NAet1aq3Gr2_e9HyNIP:b-quf8bj) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure what you're saying...
</blockquote></details>

Done. nvm, it was dead code after adding line 104
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAetbcf-xMQ7AxcXLnm:b-qgc4kk) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if I understand the problem...
</blockquote></details>

Look at the declaration of `run_test()`


<!-- Sent from Reviewable.io -->

2022-08-30 08:16 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NAhlQuO1wADVhvh7z1H:b-p3lcyy) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. nvm, it was dead code after adding line 104
</blockquote></details>

I'm not sure what line 104 (https://github.com/pmem/pmemstream/pull/248/files#diff-9126e2b93f71c2e4ad4cf05036c2e1b8def1558a31a08a2a4fdd808b183b6dc6R104) has to do with it?

And my second question is still unanswered - "what if concurrency level > regions.size()? can this happen?"
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAhlsVq2IiDT6rEFb-q:b-ncwsop) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Look at the declaration of `run_test()`
</blockquote></details>

I've seen it and still am not sure what the problem is... 
so what, we make a copy of the test_config? it still has the proper values - set a few lines above


<!-- Sent from Reviewable.io -->

2022-08-30 08:19 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/248#-NAhpL5rEHj-r3HhJ8uH:-NAhpL5rEHj-r3HhJ8uI:b3f37n2) (no related file):*
also, CI is failing on `timestamp_0_pmemcheck` :face_with_head_bandage: 

___


<!-- Sent from Reviewable.io -->

2022-08-30 10:01 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NAiBMXI1fIFA9hVS4vS:b-f0pyjp) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I've seen it and still am not sure what the problem is... 
so what, we make a copy of the test_config? it still has the proper values - set a few lines above
</blockquote></details>

as discussed, pls add XXXs here and in run_test


<!-- Sent from Reviewable.io -->

2022-10-19 11:02 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/unittest/timestamp.cpp` line 62 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAckpR3AEzd3egzn81Y:-NEjt41xCgUNd4-SW-l9:bnmkxep) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure what line 104 (https://github.com/pmem/pmemstream/pull/248/files#diff-9126e2b93f71c2e4ad4cf05036c2e1b8def1558a31a08a2a4fdd808b183b6dc6R104) has to do with it?

And my second question is still unanswered - "what if concurrency level > regions.size()? can this happen?"
</blockquote></details>

The code is deleted, so I think it doesn't matter
___
*[`tests/unittest/timestamp.cpp` line 104 at r18](https://reviewable.io/reviews/pmem/pmemstream/248#-NAcj-oS0LZMeDWDeQ3O:-NEjtjUH1Wsf4PY4qv95:bh22ajq) ([raw file](https://github.com/pmem/pmemstream/blob/96b748ef98111d1bb19b0b3b517b43c88ff157da/tests/unittest/timestamp.cpp#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed, pls add XXXs here and in run_test
</blockquote></details>

Done. The change we talked about here was merged some time ago (https://github.com/pmem/pmemstream/commit/105f04960e5534c015398ceb590473f8f15765b0)


<!-- Sent from Reviewable.io -->

2022-10-19 11:02 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/248#-NAhpL5rEHj-r3HhJ8uH:-NEjuH3ZByfNbAsnLMul:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

also, CI is failing on `timestamp_0_pmemcheck` :face_with_head_bandage: 
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-11-02 15:07 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/248#-:-NFssY3Z9D-VjJ6yK6hD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-11-02 15:08 UTC, merged