Add popcount validate to iterator
pmem/pmemstream pull request #25
Opened 2021-12-10 10:48 UTC by KFilipek

TODO:
- [ ] zeroing all blocks when popcount fails

2021-12-17 15:29 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 170 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr7zHku5gCriY0RK73P:-Mr7zHku5gCriY0RK73Q:biyx42d) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L170)):*
> ```C
> }
> 
> int validateEntrySpan(pmemstream_span_bytes* entry_span) {
> ```

snake case
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-K_9DczrsnMSLwab:-Mr8-K_9DczrsnMSLwac:bjd7fgm) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
> ```C
> 	if (rt.type == PMEMSTREAM_SPAN_ENTRY) {
> 		if (validateEntrySpan(entry_span) < 0) {
> 			pmemstream_span_create_empty(iter->stream, entry_span, region_rt.total_size - iter->offset - sizeof(pmemstream_span_bytes));
> ```

you also need to persist the metadata (as in pmemstream_init):
```
	pmemstream_span_create_empty(stream, entry_span, span_size);
	stream->persist(entry_span, span_size);
```
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-T8n6_yXi86_Vnee:-Mr8-T8n6_yXi86_Vnef:b-i9ble7) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
> ```C
> 	if (rt.type == PMEMSTREAM_SPAN_ENTRY) {
> 		if (validateEntrySpan(entry_span) < 0) {
> 			pmemstream_span_create_empty(iter->stream, entry_span, region_rt.total_size - iter->offset - sizeof(pmemstream_span_bytes));
> ```

why `- sizeof(pmemstream_span_bytes())`?
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-eAe0i_rC106Ddir:-Mr8-eAe0i_rC106Ddis:bvavzfo) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
> ```C
> 	if (rt.type == PMEMSTREAM_SPAN_ENTRY) {
> 		if (validateEntrySpan(entry_span) < 0) {
> 			pmemstream_span_create_empty(iter->stream, entry_span, region_rt.total_size - iter->offset - sizeof(pmemstream_span_bytes));
> ```

region_rt.total_size - iter->offset is wrong, you need to add region.offset to it


<!-- Sent from Reviewable.io -->

2021-12-17 15:33 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-K_9DczrsnMSLwab:-Mr80MwI7k2JceU0keB-:b-4pug4l) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you also need to persist the metadata (as in pmemstream_init):
```
	pmemstream_span_create_empty(stream, entry_span, span_size);
	stream->persist(entry_span, span_size);
```
</blockquote></details>

Correction:
```
	size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
	pmemstream_span_create_empty(stream, entry_span, size_to_clear);
	stream->persist(entry_span, metadata_size);
```

In general we might move the persist step into span_creaty_empty but not now (this needs some further discussion).


<!-- Sent from Reviewable.io -->

2021-12-17 17:14 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemstream.c, line 170 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr7zHku5gCriY0RK73P:-Mr8EE7s4bfhy7dRvQ7C:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L170)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

snake case
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-T8n6_yXi86_Vnee:-Mr8EJE7143WgypFL301:b-oihwlt) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why `- sizeof(pmemstream_span_bytes())`?
</blockquote></details>

Let's assume that we want to mark as empty 1024B.
`pmemstream_span_create_empty` creates `span[0]`  with metadata for empty span and then erase following 1024B instead of 1016B.
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-K_9DczrsnMSLwab:-Mr8GLCVBBXR4z8Uc3ii:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Correction:
```
	size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
	pmemstream_span_create_empty(stream, entry_span, size_to_clear);
	stream->persist(entry_span, metadata_size);
```

In general we might move the persist step into span_creaty_empty but not now (this needs some further discussion).
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-eAe0i_rC106Ddir:-Mr8M0yQ6BW46uG-M_hw:b-edac4) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
> region_rt.total_size
I don't get it.


<!-- Sent from Reviewable.io -->

2021-12-17 17:41 UTC, igchor requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-T8n6_yXi86_Vnee:-Mr8SXLuAOhCeZq-xUrd:b-19cxly) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Let's assume that we want to mark as empty 1024B.
`pmemstream_span_create_empty` creates `span[0]`  with metadata for empty span and then erase following 1024B instead of 1016B.
</blockquote></details>

Ok, you're right - could you just replace `sizeof(pmemstream_span_bytes)` with `metadata_size`? It would be a bit more readable.
___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-eAe0i_rC106Ddir:-Mr8RzKx7hcYzrzWiq5q:b-pxmvvn) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> region_rt.total_size
I don't get it.
</blockquote></details>

Region can start at arbitraty offfset in general. For example, we might have:
region.offset = 1000, region_rt.total_size = 1000

For such case, if you consider iter->offset == 1500 (which is with this region) , regio_rt.total_size - iter->offset will give you `-500`. Is that what you want?

Also, I think you should use `region_rt.size` instead of `region_rt.total_size`. total_size includes metadata size (8 bytes) and we don't care about this because iter->offset is always >= region_metadata_offset.
___
*[main.cpp, line 107 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8Tf2_4jNvjGMJU7Iz:-Mr8Tf2a2epT5ic1fIsX:b2d4oag) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/main.cpp#L107)):*
> ```cpp
> 
> 	return 0;
> }
> ```

remove this file?
___
*[examples/01-iterate/main.c, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8ThPm8zg1I3MuxCLQ:-Mr8ThPm8zg1I3MuxCLR:b3kre) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/examples/01-iterate/main.c#L111)):*
> ```C
> 		// 	return ret;
> 		// } else {
> 		// 	printf("appended: data entry %lu: in region\n", entry.offset);
> ```

?


<!-- Sent from Reviewable.io -->

2021-12-20 08:59 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemstream.c, line 106 at r7](https://reviewable.io/reviews/pmem/pmemstream/25#-MrM1wGf2QRUrZ4j6-Vw:-MrM1wGf2QRUrZ4j6-Vx:b-edwvl) ([raw file](https://github.com/pmem/pmemstream/blob/723ca28d2041471cca82e5741a85b62de282cdf7/src/libpmemstream.c#L106)):*
> ```C
> {
> 	struct pmemstream_span_runtime rt = pmemstream_span_get_runtime(entry_span);
> 	if (rt.type == PMEMSTREAM_SPAN_ENTRY && util_popcount_memory(rt.data, rt.entry.size) == rt.entry.popcount) {
> ```

What if `size` is corrupted? it could be set to something like UINT64_MAX which would result in this loop spinning for a long time and then probably crashing on invalid memory access. I think we should compare size with some max value before calculating popcount. I think the easiest way would be to just ensure that entry_offset + entry_size <= region_offset + region_size

@lukaszstolarczuk  we should probably have test for corrupted size.


<!-- Sent from Reviewable.io -->

2021-12-20 09:51 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[main.cpp, line 107 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8Tf2_4jNvjGMJU7Iz:-MrMEqYoEIprvU0Z4CON:b-xprjr4) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/main.cpp#L107)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

remove this file?
</blockquote></details>

It was removed when you created review (r4) :) 
___
*[examples/01-iterate/main.c, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8ThPm8zg1I3MuxCLQ:-MrMF0IIB7_raFI0kkmg:btmj6w3) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/examples/01-iterate/main.c#L111)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

I don't understand the question.


<!-- Sent from Reviewable.io -->

2021-12-20 09:53 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[main.cpp, line 107 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8Tf2_4jNvjGMJU7Iz:-MrMFS_A1dCwL1nHTtiw:b-27d2a8) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/main.cpp#L107)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It was removed when you created review (r4) :) 
</blockquote></details>

I know, that's why I retracted this comment.
___
*[examples/01-iterate/main.c, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8ThPm8zg1I3MuxCLQ:-MrMFWsS6YJVfN21EAP8:b-kfqger) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/examples/01-iterate/main.c#L111)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I don't understand the question.
</blockquote></details>

It's resolved - it was for a different revision


<!-- Sent from Reviewable.io -->

2021-12-20 13:11 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 3 files at r2, 2 of 3 files at r4, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 203 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMw85r062FhvVxcNua:-MrMw85r062FhvVxcNub:beotaip) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L203)):*
> ```C
> 	pmemstream_span_bytes *entry_span = pmemstream_get_span_for_offset(stream, offset);
> 	pmemstream_span_create_entry(entry_span, count, util_popcount_memory(buf, count));
> 	// TODO: for popcount, we also need to make sure that the memory is zeroed - maybe it can be done by bg thread?
> ```

pls drop this TODO as well
___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrMwFg9CE5g3BL974MV:bo0yvj5) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
> ```C
> 
> // returns pointer to the data of the entry
> void *pmemstream_entry_data(struct pmemstream *stream, struct pmemstream_entry entry)
> ```

we should also validate popcount here
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwdg-743U-TQyaR_D:-MrMwdg-743U-TQyaR_E:bcssnaj) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
> ```C
> 	iter->offset += rt.total_size;
> 	
> 	if (entry->offset + rt.entry.size <= region->offset + region_rt.region.size) {
> ```

shouldn't it be`>=` here?
___
*[src/libpmemstream.c, line 313 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMxADX5AX9jx4aKGZr:-MrMxADX5AX9jx4aKGZs:bmpafwz) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L313)):*
> ```C
> 	}
> 	if (rt.type == PMEMSTREAM_SPAN_ENTRY) {
> 		if (validate_entry_span(entry_span) < 0) {
> ```

pls add a comment


<!-- Sent from Reviewable.io -->

2021-12-20 13:28 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwdg-743U-TQyaR_D:-MrN0V1eBnHpsz2CLm4P:b2nhx5p) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't it be`>=` here?
</blockquote></details>

`>`
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrN0Y_K8D6TbQ_RAz3e:b-689dpb) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
> ```C
> 	iter->offset += rt.total_size;
> 	
> 	if (entry->offset + rt.entry.size <= region->offset + region_rt.region.size) {
> ```

`entry->offset + rt.total_size < region->offset + region_rt.total_size` (you want to find offset of the end of region and end of the entry)


<!-- Sent from Reviewable.io -->

2021-12-20 13:37 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-eAe0i_rC106Ddir:-MrN2Zue5b511PCKLqPR:biw9eh5) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Region can start at arbitraty offfset in general. For example, we might have:
region.offset = 1000, region_rt.total_size = 1000

For such case, if you consider iter->offset == 1500 (which is with this region) , regio_rt.total_size - iter->offset will give you `-500`. Is that what you want?

Also, I think you should use `region_rt.size` instead of `region_rt.total_size`. total_size includes metadata size (8 bytes) and we don't care about this because iter->offset is always >= region_metadata_offset.
</blockquote></details>

```
uint64_t region_end_offset = region.offset + region_rt.total_size
size_t remainaing_size = region_end_offset - iter->offset;

pmemstream_span_create_empty(iter->stream, entry_span, remanming_size - metadata_size);
```


<!-- Sent from Reviewable.io -->

2021-12-20 14:47 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 326 at r3](https://reviewable.io/reviews/pmem/pmemstream/25#-Mr8-eAe0i_rC106Ddir:-MrNHXHx65H0xpVwh3ml:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cda494880671fd2f4ecdb3a2c5e30ed09228cfc6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

```
uint64_t region_end_offset = region.offset + region_rt.total_size
size_t remainaing_size = region_end_offset - iter->offset;

pmemstream_span_create_empty(iter->stream, entry_span, remanming_size - metadata_size);
```

</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 106 at r7](https://reviewable.io/reviews/pmem/pmemstream/25#-MrM1wGf2QRUrZ4j6-Vw:-MrMJJQL75_EzWRv3LwL:bsb5jup) ([raw file](https://github.com/pmem/pmemstream/blob/723ca28d2041471cca82e5741a85b62de282cdf7/src/libpmemstream.c#L106)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What if `size` is corrupted? it could be set to something like UINT64_MAX which would result in this loop spinning for a long time and then probably crashing on invalid memory access. I think we should compare size with some max value before calculating popcount. I think the easiest way would be to just ensure that entry_offset + entry_size <= region_offset + region_size

@lukaszstolarczuk  we should probably have test for corrupted size.
</blockquote></details>

Better would be add 1B (or more?) checksum at the end of metadata block. In some cases error would be: entry span with max, correct value, just checksum calculation for metadata block guarantees some consistency and I prefer that way.
___
*[src/libpmemstream.c, line 203 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMw85r062FhvVxcNua:-MrNIKC5ATwn3gC5uBce:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L203)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop this TODO as well
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrNHrCZ0J2CnN13_MaY:b1t9lpy) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should also validate popcount here
</blockquote></details>

We will discuss it, because we don't need to validate twice (since they was checked on `iterator_next()`)
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwdg-743U-TQyaR_D:-MrNHUuR2VrILEAqdUXF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`>`
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrNHVgPCVH5Nj-cT37t:b5cj169) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`entry->offset + rt.total_size < region->offset + region_rt.total_size` (you want to find offset of the end of region and end of the entry)
</blockquote></details>

Done, but I stuck on SIGV due to `region` can be 0. Please verify that is correct.
___
*[src/libpmemstream.c, line 313 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMxADX5AX9jx4aKGZr:-MrNJ-7v-M_uz-z70iHb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L313)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-20 15:12 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNOQ9pEDPUW5pfxEBd:-MrNOQ9pEDPUW5pfxEBe:b-w5iw5z) (no related file):*
we should definitely add tests for corner cases in this scenario :wink: (not to be done now, we can adjust it in the next sprint)

---
___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrNLIvLE-zYqkn4n0Ix:b1vfl7p) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We will discuss it, because we don't need to validate twice (since they was checked on `iterator_next()`)
</blockquote></details>

I can use entry_data without using iterators. I believe we did discuss this some time ago and decided to validate it both for now...?
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrNO0b7DvPoZ-UTDICH:b-yrumo8) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done, but I stuck on SIGV due to `region` can be 0. Please verify that is correct.
</blockquote></details>

values look cool, but `>`...? if entry + its size fits within (are less than) the end of a region, then we're good to go, am I incorrect?
___
*[src/libpmemstream.c, line 313 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMxADX5AX9jx4aKGZr:-MrNN0GcAj3x7GdL27NC:b-44ujnz) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L313)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"fix it" is a bit of an overstatement :smile: more like -> "clear out the region from that point" :wink: 
___
*[src/libpmemstream.c, line 316 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNNV-u7TCyhI_KBi1k:-MrNNV-u7TCyhI_KBi1l:b-4cgwst) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L316)):*
> ```C
> 			size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
> 			size_t region_end_offset = region->offset + region_rt.total_size;
> 			size_t remaining_size = region_end_offset - iter->offset;
> ```

`iter->offset`? not `entry->offset`? `iter` is already moved ahead of the current entry and we want to clear this entry as well, I believe


<!-- Sent from Reviewable.io -->

2021-12-20 15:17 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 106 at r7](https://reviewable.io/reviews/pmem/pmemstream/25#-MrM1wGf2QRUrZ4j6-Vw:-MrNOCPi7HLwoTgjMA4l:b-gonrf5) ([raw file](https://github.com/pmem/pmemstream/blob/723ca28d2041471cca82e5741a85b62de282cdf7/src/libpmemstream.c#L106)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Better would be add 1B (or more?) checksum at the end of metadata block. In some cases error would be: entry span with max, correct value, just checksum calculation for metadata block guarantees some consistency and I prefer that way.
</blockquote></details>

Yeah, checksum would solve this, we could even encode that for in the popcount field. Could you open issue for that? We can discuss it further.
___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrNOd3Y6OhqQZ9BSONB:b-w74887) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We will discuss it, because we don't need to validate twice (since they was checked on `iterator_next()`)
</blockquote></details>

Please open some issue or add comment in code to do this.
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrNPFAV50m0a5dPHzwz:b4vyrcz) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

values look cool, but `>`...? if entry + its size fits within (are less than) the end of a region, then we're good to go, am I incorrect?
</blockquote></details>

`>` is fine because entry data can end at the region boundary (so if entry->offset + rt.total_size == region.offset + region.rt_total_size that's fine)
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwdg-743U-TQyaR_D:-MrNPLXzE0kUnnqSmjnu:b-cnmk1k) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I also used wrong sign in my comment below ;d It should be `>` as stated above.
___
*[src/libpmemstream.c, line 308 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNPjf39dSPEODdTTCf:-MrNPjf39dSPEODdTTCg:b8lzgad) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L308)):*
> ```C
> 	iter->offset += rt.total_size;
> 
> 	if (entry->offset + rt.total_size < iter->region.offset + region_rt.total_size) {
> ```

Please add comment why this check is here - if we solve it difference (e.g by checksum as you proposed), we might not needed anymore)
___
*[src/libpmemstream.c, line 316 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNNV-u7TCyhI_KBi1k:-MrNP7Z3CDEO2hiF_wzX:b86vsa6) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L316)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`iter->offset`? not `entry->offset`? `iter` is already moved ahead of the current entry and we want to clear this entry as well, I believe
</blockquote></details>

Yeah, youre'right, it should be entry->offset.


<!-- Sent from Reviewable.io -->

2021-12-20 15:23 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrNQZe7DDhKDjumxnJk:bb6mt9b) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please open some issue or add comment in code to do this.
</blockquote></details>

:+1:
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrNQjzC9lfFwVF579Cr:b-um77r5) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`>` is fine because entry data can end at the region boundary (so if entry->offset + rt.total_size == region.offset + region.rt_total_size that's fine)
</blockquote></details>

yeah, the case `==` is ok, I understand. Please just flip the sign (my prev. comment may have been unclear)


<!-- Sent from Reviewable.io -->

2021-12-20 17:13 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 103 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNn8Mr9qTGuRQv7jqg:-MrNn8Mr9qTGuRQv7jqh:b-yf9iz4) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L103)):*
> ```C
> }
> 
> static int validate_entry_span(pmemstream_span_bytes *entry_span)
> ```

bool?  


<!-- Sent from Reviewable.io -->

2021-12-20 18:04 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNOQ9pEDPUW5pfxEBd:-MrO-k3h2WUcZzj0SoFM:b-91vz6i) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should definitely add tests for corner cases in this scenario :wink: (not to be done now, we can adjust it in the next sprint)
</blockquote></details>

Yeah, @lukaszstolarczuk would you add a task for this? ;d

---
___
*[src/libpmemstream.c, line 103 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNn8Mr9qTGuRQv7jqg:-MrO-oPEARS-p5_sUuDe:brtn0tv) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L103)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

bool?  
</blockquote></details>

int (or an enum) is better imho, we might want to return more specific value later - e.g. SPAN_NOT_ENTRY or ENTRY_CORRUPTED


<!-- Sent from Reviewable.io -->

2021-12-20 23:09 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 106 at r7](https://reviewable.io/reviews/pmem/pmemstream/25#-MrM1wGf2QRUrZ4j6-Vw:-MrOyZOw-t1v4Mo_sSC6:blh3m5e) ([raw file](https://github.com/pmem/pmemstream/blob/723ca28d2041471cca82e5741a85b62de282cdf7/src/libpmemstream.c#L106)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, checksum would solve this, we could even encode that for in the popcount field. Could you open issue for that? We can discuss it further.
</blockquote></details>

Done. Opened
___
*[src/libpmemstream.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwFg9CE5g3BL974MU:-MrOzEHu2DI2og1QSEYT:bihbrbh) ([raw file](https://github.com/pmem/pmemstream/blob/edec07ec2295da0e097c20be6e8ff2ea521dca39/src/libpmemstream.c#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.  #42 - ideal number
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMwdg-743U-TQyaR_D:-MrP12F019COR5sXUXmh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Sorry, I also used wrong sign in my comment below ;d It should be `>` as stated above.
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 309 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrN0Y_K8D6TbQ_RAz3d:-MrP4Xds6nUTyMRNA5h8:bnta1xg) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L309)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, the case `==` is ok, I understand. Please just flip the sign (my prev. comment may have been unclear)
</blockquote></details>

Done. Tested.
___
*[src/libpmemstream.c, line 313 at r9](https://reviewable.io/reviews/pmem/pmemstream/25#-MrMxADX5AX9jx4aKGZr:-MrP524X6es-AFWXEVJl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/eea136404cd14efcd8fd689398831671b002d84d/src/libpmemstream.c#L313)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"fix it" is a bit of an overstatement :smile: more like -> "clear out the region from that point" :wink: 
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 103 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNn8Mr9qTGuRQv7jqg:-MrOVHil1jLVfczRclaO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L103)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

int (or an enum) is better imho, we might want to return more specific value later - e.g. SPAN_NOT_ENTRY or ENTRY_CORRUPTED
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 308 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNPjf39dSPEODdTTCf:-MrP0IKr5ZPqm_-9GN_-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L308)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add comment why this check is here - if we solve it difference (e.g by checksum as you proposed), we might not needed anymore)
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 316 at r12](https://reviewable.io/reviews/pmem/pmemstream/25#-MrNNV-u7TCyhI_KBi1k:-MrP5Xst13OI0NN77AAe:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/83310bd174eb54cf5a020d625f1e17d63655fa62/src/libpmemstream.c#L316)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, youre'right, it should be entry->offset.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 08:30 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25#-:-MrR67co4h56mPXclYIM:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-12-21 08:55 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25#-:-MrRC06TDJrxPjnu5Q2O:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-12-21 08:59 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/25#-:-MrRCptUC4w9EZ83x-5e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-12-21 08:59 UTC, merged