Extract reserve and write from append
pmem/pmemstream pull request #27
Opened 2021-12-13 14:14 UTC by lukaszstolarczuk

into separate public functions.

One might want to reserve space in a region for later data writes
and in the meantime e.g. keep appending data at the end of the region.

2021-12-14 11:35 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 266 at r1](https://reviewable.io/reviews/pmem/pmemstream/27#-Mqsf0zj6H9bph5wdsus:-Mqsf0zj6H9bph5wdsut:b-gjfqo4) ([raw file](https://github.com/pmem/pmemstream/blob/7a37b1e9543591af310193db0f272d1c662a6aac/src/libpmemstream.c#L266)):*
> ```C
> 	pmemstream_span_bytes *entry_span = pmemstream_get_span_for_offset(stream, offset);
> 	pmemstream_span_create_entry(entry_span, size, 0);
> 	stream->persist(&entry_span[0], entry_total_size);
> ```

I don't think we should call persist here. reserve should only modify runtime state - needed by pmemstream_write.

Also, I think that pmemstream_reserve should return a pointer to the data, instead of pmemstream_entry. 
___
*[src/libpmemstream.c, line 274 at r1](https://reviewable.io/reviews/pmem/pmemstream/27#-MqsfZa9Dm9HYoej8pXr:-MqsfZaA27T3iLMHu2og:b-jbk4s4) ([raw file](https://github.com/pmem/pmemstream/blob/7a37b1e9543591af310193db0f272d1c662a6aac/src/libpmemstream.c#L274)):*
> ```C
>  * entry is not updated in any way.
>  * size of the entry have to match the previous reservation. */
> int pmemstream_write(struct pmemstream *stream, struct pmemstream_region *region, struct pmemstream_entry *entry,
> ```

After some thought, I actually think that this function should be called publish and it should not perform any copy.

This way we can allow user to fill in the data as he wants (e.g. by memset, emplace new ctor, etc.). pmemstream_write would then only persist the data.


<!-- Sent from Reviewable.io -->

2021-12-20 09:15 UTC, igchor requested changes
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 172 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM3sf5-9KkqVuOn5ot:-MrM3sf5-9KkqVuOn5ou:b-exmkbk) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L172)):*
> ```C
> /* Reserve space (for a future, custom write) of a given size, in a region at offset pointed by entry.
>  * Entry's data have to be copied into reserved space by the user and then published using pmemstream_publish.
>  * For regular usage it's simpler and safer to use pmemstream_append.
> ```

nit: and it has better performance (... because it uses optimized instructions)
___
*[src/libpmemstream.c, line 178 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM4ecFBOwRMHhoJath:-MrM4ecFBOwRMHhoJati:b-3yi5ak) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L178)):*
> ```C
>  * data is updated with a pointer to reserved space - this is a destination for, e.g., custom memcpy. */
> int pmemstream_reserve(struct pmemstream *stream, struct pmemstream_region *region, struct pmemstream_entry *entry,
> 		       size_t size, struct pmemstream_entry *reserved_entry, uint8_t **data)
> ```

I think it should be void `**data`, to be consistent with buf
___
*[src/libpmemstream.c, line 197 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5dx_AtcNmV4innpy:-MrM5dx_AtcNmV4innpz:b-djjklr) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L197)):*
> ```C
> 
> 	pmemstream_span_bytes *entry_span = pmemstream_get_span_for_offset(stream, offset);
> 	pmemstream_span_create_entry(entry_span, 0, 0);
> ```

Hm, after some googling - this might be a bit slow: https://stackoverflow.com/questions/34501243/what-happens-with-a-non-temporal-store-if-the-data-is-already-in-cache 

Since, we are using non-temporal stores in append, we don't want the data to be loaded into cache (it will have to be evicted in that case). Can we avoid creating this span with zero size? 
___
*[src/libpmemstream.c, line 242 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5xF00wAW_FE6StAg:-MrM5xF00wAW_FE6StAh:bwn2mja) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L242)):*
> ```C
> 
> 	stream->memcpy(reserved_dest, buf, size, PMEM2_F_MEM_NONTEMPORAL);
> 	ret = pmemstream_publish(stream, region, &reserved_entry, buf, size);
> ```

We don't want to call strem->persist which is called in pmemstream_publish - I think the easiest way would be just to copy the implementation into the append (or create a separate function with some flag)
___
*[tests/unittest/reserve_publish.cpp, line 51 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM6RHd5FctaMBs2cDI:-MrM6RHd5FctaMBs2cDJ:b-k4gq17) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/tests/unittest/reserve_publish.cpp#L51)):*
> ```cpp
> /* initialize stream with a single region and initial data (if given) */
> struct pmemstream_region init_stream_single_region(struct pmemstream *stream, size_t region_size,
> 						   const std::vector<std::string> *data = nullptr)
> ```

why ptr? if you want no data you can just pass {} as empty string


<!-- Sent from Reviewable.io -->

2021-12-20 17:23 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 172 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM3sf5-9KkqVuOn5ot:-MrNVHpd38Gepd7ploIG:bh5iiyf) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L172)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: and it has better performance (... because it uses optimized instructions)
</blockquote></details>

Done. The funny thing is I had written a sentence like this, but rolled it back (because a user could also use the same optimized instructions :wink: ). Nonetheless, it's better to put it here for the time, we'll be writing the manpages.
___
*[src/libpmemstream.c, line 178 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM4ecFBOwRMHhoJath:-MrNVtmlAuJopTOI03mH:bi43jyz) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L178)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it should be void `**data`, to be consistent with buf
</blockquote></details>

Done.
good catch
___
*[src/libpmemstream.c, line 197 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5dx_AtcNmV4innpy:-MrNXbV567NMd80WvbbH:b-u6xgts) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, after some googling - this might be a bit slow: https://stackoverflow.com/questions/34501243/what-happens-with-a-non-temporal-store-if-the-data-is-already-in-cache 

Since, we are using non-temporal stores in append, we don't want the data to be loaded into cache (it will have to be evicted in that case). Can we avoid creating this span with zero size? 
</blockquote></details>

the solution (I propose here) is not the best one, I think. I'd benchmark this issue later on and possibly see if there are any real differences because of this cached 0.
___
*[src/libpmemstream.c, line 242 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5xF00wAW_FE6StAg:-MrNfypu9XJVCxXxQpaA:b-axoo26) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L242)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We don't want to call strem->persist which is called in pmemstream_publish - I think the easiest way would be just to copy the implementation into the append (or create a separate function with some flag)
</blockquote></details>

mea culpa, of course, done. Why a separate function? I just added flags in the current implementation - pls let me know if that's alright.
___
*[tests/unittest/reserve_publish.cpp, line 51 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM6RHd5FctaMBs2cDI:-MrNhfVZ5uFPSbOPoXcj:bsqd9ob) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/tests/unittest/reserve_publish.cpp#L51)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why ptr? if you want no data you can just pass {} as empty string
</blockquote></details>

well, of course, thx.


<!-- Sent from Reviewable.io -->

2021-12-21 14:52 UTC, igchor requested changes
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 197 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5dx_AtcNmV4innpy:-MrSSRouACOJ5FXyOGKN:b-aiyc4z) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L197)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the solution (I propose here) is not the best one, I think. I'd benchmark this issue later on and possibly see if there are any real differences because of this cached 0.
</blockquote></details>

Why do we actually need this span to be created? Only for entry_sr? Mybe we could just get rid of entry_sr and initialize *data by `pmemstream_get_span_for_offset(stream, offset + ENTRY_METADATA_SIZE)`?
___
*[src/libpmemstream.c, line 242 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5xF00wAW_FE6StAg:-MrSReu2890-nlDh9aH-:b-2uk4wc) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L242)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

mea culpa, of course, done. Why a separate function? I just added flags in the current implementation - pls let me know if that's alright.
</blockquote></details>

Yeah, that's a good idea.
___
*[src/libpmemstream.c, line 234 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSS8Eo1lrSSUKlcW3y:-MrSS8Eo1lrSSUKlcW3z:b6ksase) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/src/libpmemstream.c#L234)):*
> ```C
> 
> 	/* save size and popcount in entry_span; data (from user) should be already right next to it */
> 	pmemstream_span_create_entry(entry_span, size, util_popcount_memory(buf, size));
> ```

After my change which does memcpy and persist inside pmemstream_span_create_entry - I think you would have to extend pmemstream_span_create_entry. Maybe add flags parameter and also if data ptr is NULL, then just set metadata?
___
*[src/libpmemstream.c, line 236 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSROOo8pFWEDu6v-FQ:-MrSROOo8pFWEDu6v-FR:b3fy8hc) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/src/libpmemstream.c#L236)):*
> ```C
> 	pmemstream_span_create_entry(entry_span, size, util_popcount_memory(buf, size));
> 
> 	if (flags & PMEMSTREAM_PUBLISH_PERSIST) {
> ```

I think that it would be better to reverse the logic - do persist by default and pass flag like NO_DRAIN/NO_FLUSH for opting-out. This would be consistent pmem2 memcpy/memset functions.
___
*[tests/unittest/reserve_publish.cpp, line 66 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrST0GnBo-Ugx9cx8VE:-MrST0GnBo-Ugx9cx8VF:b-vr763h) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/tests/unittest/reserve_publish.cpp#L66)):*
> ```cpp
> 	pmemstream_entry_iterator_delete(&eiter);
> 
> 	if (!data.empty()) {
> ```

nit: you don't event need this if ;d
___
*[tests/unittest/reserve_publish.cpp, line 135 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSTCDY9-sQQv4PVz8S:-MrSTCDY9-sQQv4PVz8T:b-uw4yy6) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/tests/unittest/reserve_publish.cpp#L135)):*
> ```cpp
> 		data_to_reserve.emplace_back("ABCDEFGHIJKL");
> 		std::string long_entry(512, 'A');
> 		data_to_reserve.emplace_back(long_entry);
> ```

nit: `data_to_reserve.emplace_back(512, 'A'):`
___
*[tests/unittest/reserve_publish.cpp, line 138 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSTOew4o95anUSdm_X:-MrSTOew4o95anUSdm_Y:b-p4ettd) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/tests/unittest/reserve_publish.cpp#L138)):*
> ```cpp
> 
> 		/* reserve and publish at the last offset (and update the offset value) */
> 		reserve_and_publish_at_offset(s.get(), &r, &last_offset, data_to_reserve);
> ```

I thnik it would be good to make this line parametrizable (e.g. pass reserve_and_publish_at_offset function as a parameter to the test). This would allow us to test both append and reserve + publish with the same code. (and both should result in the same output - perfect test for property based testing ;d)


<!-- Sent from Reviewable.io -->

2021-12-31 16:10 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 197 at r2](https://reviewable.io/reviews/pmem/pmemstream/27#-MrM5dx_AtcNmV4innpy:-MsFnn-I90kIL3oEDR39:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b8cc88265098ec267f3124001de29e4b9468ddf1/src/libpmemstream.c#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why do we actually need this span to be created? Only for entry_sr? Mybe we could just get rid of entry_sr and initialize *data by `pmemstream_get_span_for_offset(stream, offset + ENTRY_METADATA_SIZE)`?
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 234 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSS8Eo1lrSSUKlcW3y:-MsGETKcDEK5nZfyDxYq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/src/libpmemstream.c#L234)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

After my change which does memcpy and persist inside pmemstream_span_create_entry - I think you would have to extend pmemstream_span_create_entry. Maybe add flags parameter and also if data ptr is NULL, then just set metadata?
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 236 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSROOo8pFWEDu6v-FQ:-MsFZ43W5d9KOXlCZ2up:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/src/libpmemstream.c#L236)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that it would be better to reverse the logic - do persist by default and pass flag like NO_DRAIN/NO_FLUSH for opting-out. This would be consistent pmem2 memcpy/memset functions.
</blockquote></details>

Done.
___
*[tests/unittest/reserve_publish.cpp, line 138 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSTOew4o95anUSdm_X:-MsGF6tNBn5Yqyt6jlAp:b-x423g6) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/tests/unittest/reserve_publish.cpp#L138)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I thnik it would be good to make this line parametrizable (e.g. pass reserve_and_publish_at_offset function as a parameter to the test). This would allow us to test both append and reserve + publish with the same code. (and both should result in the same output - perfect test for property based testing ;d)
</blockquote></details>

added TODO for now


<!-- Sent from Reviewable.io -->

2022-01-03 10:30 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 234 at r3](https://reviewable.io/reviews/pmem/pmemstream/27#-MrSS8Eo1lrSSUKlcW3y:-MsUU5L6A4k7MY_Stl6o:bvc8w4t) ([raw file](https://github.com/pmem/pmemstream/blob/11b35ee07d196504213ac3ca0f5a4c8afdf2e4f4/src/libpmemstream.c#L234)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, I don't think we need to set "entry" type into srt, because with my change it wasn't recovered well.


<!-- Sent from Reviewable.io -->

2022-01-03 15:11 UTC, igchor requested changes
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 1 of 11 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/iterator.c, line 143 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVPVnrBe_MlOSbqFDN:-MsVPVnsC8JJUkYEU5E3:b-84g79y) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/iterator.c#L143)):*
> ```C
> 
> 	/* Verify all metadata and data fits inside the region - this should not fail unless stream was corrupted */
> 	assert(entry.offset + srt.total_size <= iterator->region.offset + region_srt.total_size);
> ```

why did you move it here?
___
*[src/libpmemstream.c, line 177 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVPtU_8pDprehxjUn-:-MsVPtUa7L1n6nsj2PeB:by7m28p) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L177)):*
> ```C
> 	}
> 
> 	// span_create_entry(stream, offset, NULL, size, 0, 0);
> ```

is this comment left here on purpose? if so, maybe write why isn't it used?
___
*[src/libpmemstream_internal.h, line 18 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVQRsB-FWgdi-E3tKD:-MsVQRsB-FWgdi-E3tKE:b8jm423) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream_internal.h#L18)):*
> ```objc
> #endif
> 
> #define PMEMSTREAM_PUBLISH_PERSIST (0)
> ```

I think it would be better to have NOFLUSH + NODRAIN instead of explicit PERSIST flag (PERSIST == not providing either of those flags == passing just 0).
___
*[src/include/libpmemstream.h, line 63 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVRlwSDMNqj-Uhv_0z:-MsVRlwSDMNqj-Uhv_1-:b-suuvph) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/include/libpmemstream.h#L63)):*
> ```objc
> /* Publish previously custom-written entry.
>  * After calling pmemstream_reserve and writing/memcpy'ing data into a reserved_entry it's required
>  * to calculate the checksum (based on the data and size).
> ```

Doe this information matter for the user? It gives an impression as if user would have to calculate the checksum.
___
*[src/include/libpmemstream.h, line 67 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVR6bk26GpGKTR8qnU:-MsVR6bk26GpGKTR8qnV:b2w280h) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/include/libpmemstream.h#L67)):*
> ```objc
>  * *data has to hold the same data as they were written by user (e.g. in custom memcpy).
>  * size of the entry have to match the previous reservation and the actual size of the data written by user.
>  * flags may be used to adjust behavior of persisting the data. */
> ```

Are the flags exposed in any public header?
___
*[tests/integrity/append_break.gdb, line 8 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVS9G10zXrUT59Limj:-MsVS9G10zXrUT59Limk:bkthebm) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/integrity/append_break.gdb#L8)):*
> ```GDB
> 
> # go to memcpy in append
> b pmemstream_append
> ```

cant' we break on pmemstream_reserve, and just step once? reserved_dest should be ready then
___
*[tests/unittest/reserve_publish.cpp, line 22 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVTJxqB4NSk6VTEko5:-MsVTJxqB4NSk6VTEko6:b-ryz5sk) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/unittest/reserve_publish.cpp#L22)):*
> ```cpp
> namespace
> {
> /* XXX: these helper methods are copy-pasted from "append_break.cpp" test. */
> ```

is there any reason why you can't use rapidcheck for this test?  (as a first step, even with hardcoded data  but you could use helpers from stream_helpers.hpp then).
___
*[tests/unittest/reserve_publish.cpp, line 126 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVTjsh5MmxM3XBXjWN:-MsVTjsh5MmxM3XBXjWO:b-z8fn13) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/unittest/reserve_publish.cpp#L126)):*
> ```cpp
> 		UT_ASSERTeq(ret, 0);
> 
> 		/* verify count of all appended/written entries */
> ```

all the code from here to end of this function can be replaced with something like:

```
data_to_reserve.push_back(extra_entry);
verify(stream, r, init_data, data_to_reserve);
```

verify is from stream_helpers.hpp

It would be nice to generalize the verify function to accept arbitrary number of vectors actually, so you could just write:
```
verify(stream, r, init_data, data_to_reserve, {extra_entry});
```

or (probably simpler to implement - vector of vectors):
```
verify(stream, r, {init_data, data_to_reserve, {extra_entry}});
```


<!-- Sent from Reviewable.io -->

2022-01-03 17:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 177 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVPtU_8pDprehxjUn-:-MsV_zbS0ReoTUgiIQ33:b-jatxvi) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is this comment left here on purpose? if so, maybe write why isn't it used?
</blockquote></details>

I left this only for the review sake, just to make sure we don't need it :-) removed
___
*[src/libpmemstream_internal.h, line 18 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVQRsB-FWgdi-E3tKD:-MsVnThXCh0qRYwVqy1b:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream_internal.h#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better to have NOFLUSH + NODRAIN instead of explicit PERSIST flag (PERSIST == not providing either of those flags == passing just 0).
</blockquote></details>

Done.
___
*[src/include/libpmemstream.h, line 63 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVRlwSDMNqj-Uhv_0z:-MsVnPEa9ZbhWtpwdwaC:bk4fszc) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/include/libpmemstream.h#L63)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Doe this information matter for the user? It gives an impression as if user would have to calculate the checksum.
</blockquote></details>

Done. Re-written.
___
*[src/include/libpmemstream.h, line 67 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVR6bk26GpGKTR8qnU:-MsVnQhv1ajmy3stuIO4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/include/libpmemstream.h#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Are the flags exposed in any public header?
</blockquote></details>

Done.
___
*[tests/integrity/append_break.gdb, line 8 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVS9G10zXrUT59Limj:-MsVbkUc6CetMxzPBeE2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/integrity/append_break.gdb#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

cant' we break on pmemstream_reserve, and just step once? reserved_dest should be ready then
</blockquote></details>

Done.
___
*[src/iterator.c, line 143 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVPVnrBe_MlOSbqFDN:-MsV_lWO18iUDoCtAx0Q:bh7hn12) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/iterator.c#L143)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why did you move it here?
</blockquote></details>

ok, mea culpa, I thought it's required to recovery work properly, but I must have had some different issue there.
I dropped this change.
___
*[tests/unittest/reserve_publish.cpp, line 22 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVTJxqB4NSk6VTEko5:-MsVbpHp78O2RYY3-KgP:bbiukbs) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/unittest/reserve_publish.cpp#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is there any reason why you can't use rapidcheck for this test?  (as a first step, even with hardcoded data  but you could use helpers from stream_helpers.hpp then).
</blockquote></details>

I will figure this out later, as for now I'd like to leave it as is (and merge this PR finally :smile: )
___
*[tests/unittest/reserve_publish.cpp, line 126 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVTjsh5MmxM3XBXjWN:-MsVv3HlENK4rw4_ybLT:bguwtbi) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/tests/unittest/reserve_publish.cpp#L126)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

all the code from here to end of this function can be replaced with something like:

```
data_to_reserve.push_back(extra_entry);
verify(stream, r, init_data, data_to_reserve);
```

verify is from stream_helpers.hpp

It would be nice to generalize the verify function to accept arbitrary number of vectors actually, so you could just write:
```
verify(stream, r, init_data, data_to_reserve, {extra_entry});
```

or (probably simpler to implement - vector of vectors):
```
verify(stream, r, {init_data, data_to_reserve, {extra_entry}});
```

</blockquote></details>

I'd leave it as-is for now, to be updated later (added TODO mark)


<!-- Sent from Reviewable.io -->

2022-01-03 18:19 UTC, KFilipek requested changes
> Reviewed 5 of 9 files at r4, 5 of 5 files at r5, 2 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 5 of 12 files reviewed, 15 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 177 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsV34j17FySXBiyXCIg:-MsV34j17FySXBiyXCIh:bjqxyzh) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L177)):*
> ```C
> 	}
> 
> 	// span_create_entry(stream, offset, NULL, size, 0, 0);
> ```

not necessary
___
*[src/libpmemstream.c, line 181 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMUpfEgFHVz-kbkOc:-MsVMUpfEgFHVz-kbkOd:blc1s) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L181)):*
> ```C
> 	/* data are right next after the entry metadata */
> 	*data_addr = span_offset_to_span_ptr(stream, offset + SPAN_ENTRY_METADATA_SIZE);
> ```

not needed empty line
___
*[src/libpmemstream.c, line 189 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMT010-FILxkTkQM_:-MsVMT024sYlogXaaplW:blc1s) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L189)):*
> ```C
> {
> 	span_create_entry(stream, reserved_entry->offset, data, size, util_popcount_memory(data, size), flags);
> ```

not needed empty line
___
*[src/libpmemstream.c, line 201 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMZeq4GVQFP8tWH8f:-MsVMZeq4GVQFP8tWH8g:b-efbhgr) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L201)):*
> ```C
> 	void *reserved_dest;
> 	int ret = pmemstream_reserve(stream, region, region_context, size, &reserved_entry, &reserved_dest);
> 	if (ret != 0) {
> ```

`if (ret != 0)` == `if (ret)`



_Code quote:_
```C
ret != 0
```
___
*[src/libpmemstream.c, line 207 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMtsXB_aTuVCrq91U:-MsVMtsXB_aTuVCrq91V:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L207)):*
> ```C
> 	stream->memcpy(reserved_dest, data, size, PMEM2_F_MEM_NONTEMPORAL | PMEM2_F_MEM_NODRAIN);
> 	ret = pmemstream_publish(stream, region, data, size, &reserved_entry, PMEMSTREAM_PUBLISH_PERSIST);
> 	if (ret != 0) {
> ```

.



_Code quote:_
```C
ret != 0
```
___
*[src/span.c, line 7 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVzbxb15KwvKq-UgJh:-MsVzbxb15KwvKq-UgJi:b-74ucj5) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/span.c#L7)):*
> ```C
> #include "libpmemstream_internal.h"
> 
> #include <assert.h>
> ```

reorder:
```
#include "span.h"

#include <assert.h>

#include "libpmemstream_internal.h"
```



_Code quote:_
```C
#include "span.h"
#include "libpmemstream_internal.h"

#include <assert.h>
```
___
*[tests/unittest/reserve_publish.cpp, line 10 at r7](https://reviewable.io/reviews/pmem/pmemstream/27#-MsW01z92OHjc7KR8l29:-MsW01zAAWwlEJGTnpAl:b-oeirwx) ([raw file](https://github.com/pmem/pmemstream/blob/4c07e68cd8bf6a590968d5c4378b945c4196c345/tests/unittest/reserve_publish.cpp#L10)):*
> ```cpp
>  */
> 
> #include "libpmemstream_internal.h"
> ```

reorder:
#include <cstring>
#include <vector>

#include "libpmemstream_internal.h"
#include "unittest.hpp"



_Code quote:_
```cpp
#include "libpmemstream_internal.h"
#include "unittest.hpp"

#include <cstring>
#include <vector>
```


<!-- Sent from Reviewable.io -->

2022-01-04 08:30 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: 4 of 12 files reviewed, 15 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemstream.c, line 177 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsV34j17FySXBiyXCIg:-MsZ9rl33ewxoap3p7CY:b-prfit2) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L177)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

not necessary
</blockquote></details>

pls see the latest revision
___
*[src/libpmemstream.c, line 181 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMUpfEgFHVz-kbkOc:-MsZAfvs6liZChTyEYgP:bhiar9i) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L181)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

not needed empty line
</blockquote></details>

I personally like it that way and we have at least a few places written like that.
___
*[src/libpmemstream.c, line 189 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMT010-FILxkTkQM_:-MsZApbY9YgUe0x8rMcH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L189)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

not needed empty line
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 201 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMZeq4GVQFP8tWH8f:-MsZAF9P7txixEMJqGd3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L201)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`if (ret != 0)` == `if (ret)`
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 207 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVMtsXB_aTuVCrq91U:-MsZAFiH8qgyu3-w8maN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/libpmemstream.c#L207)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/span.c, line 7 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVzbxb15KwvKq-UgJh:-MsZAxAs966vpuNCCokg:bolt9sc) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/span.c#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

reorder:
```
#include "span.h"

#include <assert.h>

#include "libpmemstream_internal.h"
```
</blockquote></details>

Done.

Anyway, as Igor said some time ago, if you believe we should commit to some guideline with ordering includes, pls write a check for that. I personally think there are little to no benefits for us.
___
*[tests/unittest/reserve_publish.cpp, line 10 at r7](https://reviewable.io/reviews/pmem/pmemstream/27#-MsW01z92OHjc7KR8l29:-MsZBkJaDPYrNFjW0RAm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4c07e68cd8bf6a590968d5c4378b945c4196c345/tests/unittest/reserve_publish.cpp#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

reorder:
#include <cstring>
#include <vector>

#include "libpmemstream_internal.h"
#include "unittest.hpp"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 12:28 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27#-:-Ms_2zDi27wYxxtme8tU:bnfp4nl)* status: 4 of 12 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/include/libpmemstream.h, line 63 at r8](https://reviewable.io/reviews/pmem/pmemstream/27#-Ms_1vgP6AxJfC8ZhKTv:-Ms_1vgP6AxJfC8ZhKTw:b148qur) ([raw file](https://github.com/pmem/pmemstream/blob/02bd449a11d04feab40ad24acf9dd2bba5580227/src/include/libpmemstream.h#L63)):*
> ```objc
> /* Publish previously custom-written entry.
>  * After calling pmemstream_reserve and writing/memcpy'ing data into a reserved_entry, it's required
>  * to call this function for setting proper entry's metadata.
> ```

metadata ... and persist the data?


<!-- Sent from Reviewable.io -->

2022-01-04 13:02 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 9 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27#-:-Ms_AmLIBACTJX7VSLXy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/span.c, line 7 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVzbxb15KwvKq-UgJh:-Ms_AHj6AJ4F17XQF1If:b-eiwxdw) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/span.c#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.

Anyway, as Igor said some time ago, if you believe we should commit to some guideline with ordering includes, pls write a check for that. I personally think there are little to no benefits for us.
</blockquote></details>

Sure, but including `span.h` in `span.c` file should be definitely separated.


<!-- Sent from Reviewable.io -->

2022-01-04 13:03 UTC, karczex reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-04 13:26 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[src/span.c, line 7 at r6](https://reviewable.io/reviews/pmem/pmemstream/27#-MsVzbxb15KwvKq-UgJh:-Ms_Fq2U10hop58GeVge:bt2g82o) ([raw file](https://github.com/pmem/pmemstream/blob/e62303c2b3f28d170553bfad92d595fee0f3220a/src/span.c#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Sure, but including `span.h` in `span.c` file should be definitely separated.
</blockquote></details>

yeah, that actually started to grow on me, especially in tests
___
*[src/include/libpmemstream.h, line 63 at r8](https://reviewable.io/reviews/pmem/pmemstream/27#-Ms_1vgP6AxJfC8ZhKTv:-Ms_Fx5iC15GF1DG_4Kr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/02bd449a11d04feab40ad24acf9dd2bba5580227/src/include/libpmemstream.h#L63)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

metadata ... and persist the data?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 13:26 UTC, merged