[GHA] Add Gha workflow for compare bench.
pmem/pmemstream pull request #273
Opened 2022-10-14 09:05 UTC by nedved1

Signed-off-by: Pawel Niedzwiecki <pawelx.niedzwiecki@intel.com>

2022-10-14 15:39 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 13 unresolved discussions (waiting on @nedved1)

___
*[`.github/workflows/compare_bench.yml` line 44 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3dNd1lyyovnQQKBR:-NEM3dNe8-v65QQXDQ8t:b27ta4m) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L44)):*
> ```YAML
>   linux:
>     name: Linux-Self_Hosted
>  #   if: github.repository == 'pmem/pmemstream'
> ```

pls uncomment, when ready for review
___
*[`.github/workflows/compare_bench.yml` line 49 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3bwDE3BxrQ8ZgiKp:-NEM3bwE4hcPXPpL-WNa:b20k74h) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L49)):*
> ```YAML
>     env:
>       PMEMSTREAM_TEST_DIR: /mnt/pmem0/${{ github.job }}
>       CHECK_CPP_STYLE: OFF
> ```

do we need this line?
___
*[`.github/workflows/compare_bench.yml` line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3pdRAuJTq5cK3lnA:-NEM3pdRAuJTq5cK3lnB:b-2om7gg) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L56)):*
> ```YAML
> 
>         - name: Check github event
>           if: contains(fromJson('["push", "pull_request"]'), github.event_name)
> ```

why "push"? shouldn't we care only for PRs?
___
*[`.github/workflows/compare_bench.yml` line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4-vr-iLRsxO4RYRI:-NEM4-vr-iLRsxO4RYRJ:bukg) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L61)):*
> ```YAML
>           run: echo "PR_NUMBER ${{ github.event.number }}"
> 
>         - name: Run run-compare-bench script
> ```

heh, perhaps "Execute" instead of "Run"
___
*[`.github/workflows/compare_bench.yml` line 65 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4x2q12LfRaIKrAsv:-NEM4x2q12LfRaIKrAsw:bkxeykx) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L65)):*
> ```YAML
>             set -x
>             VERBOSE_PARAM=''
>             if ${{ inputs.QUIET }}; then
> ```

if this GHA variable is empty, it breaks the CI (see GHA logs in this PR) - pls fix this `if` (similarly to below cases)
___
*[`.github/workflows/compare_bench.yml` line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4SZa0iDOWPokOXQt:-NEM4SZa0iDOWPokOXQu:b20e3ee) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L70)):*
> ```YAML
> 
>             PR_PARAM=''
>             if [ ! ${{ inputs.PR }} == '' ]; then
> ```

I recommend using `-n` instead of this comparison (see e.g. https://github.com/pmem/pmemstream/blob/master/utils/docker/run-compare-bench.sh#L159 )
___
*[`.github/workflows/compare_bench.yml` line 75 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4_ST98QxOgdmE3HU:-NEM4_ST98QxOgdmE3HV:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L75)):*
> ```YAML
> 
>             COMPARE_REF_PARAM=''
>             if [ ! ${{ inputs.COMPARE_REF }} == '' ]; then
> ```

.
___
*[`.github/workflows/compare_bench.yml` line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Ik-8xFfNCwbpAe0:-NEM5Ik-8xFfNCwbpAe1:bf32blt) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L79)):*
> ```YAML
>             fi
> 
>             ./utils/docker/run-compare-bench.sh -t $VERBOSE_PARAM $PR_PARAM $COMPARE_REF_PARAM --baseline_repo=${{ inputs.BASELINE_REPO_ADDR }} --baseline_ref=${{ inputs.BASELINE_REF }} --compare_repo=${{ inputs.BASELINE_REPO_ADDR }}
> ```

pls use `${VARIABLE_NAME}` notation, everywhere
___
*[`utils/docker/run-compare-bench.sh` line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5j1P0utsRWOMamUD:-NEM5j1P0utsRWOMamUE:bb25l8x) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L18)):*
> ```Shell
> TEST_PATH=${PMEMSTREAM_TEST_DIR:-"/tmp/pmemstream/benchfile"}
> USE_FORCED_PMEM=${TESTS_USE_FORCED_PMEM:-ON}
> P_THRESHOLD=${TEST_BENCH_THRESHOLD:-20}
> ```

why `P_`?
___
*[`utils/docker/run-compare-bench.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM86BB2SE9rrBBKKTj:-NEM86BB2SE9rrBBKKTk:b-382vjn) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L35)):*
> ```Shell
> 	echo "-h, --help       Print help and exit"
> 	echo "-q, --quiet      Hide part of the verbose output (e.g. from CMake), to make it more readable"
> 	echo "-t, --test       Test bench results and exit with error when values from comparing repo are worse than value defined in TEST_BENCH_THRESHOLD [TEST_BENCH_THRESHOLD: ${P_THRESHOLD}]"
> ```

that's a bit too long/verbose - pls shorten it
___
*[`utils/docker/run-compare-bench.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM8OHb70ynL4hyZTes:-NEM8OHb70ynL4hyZTet:b-rq0zvs) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L35)):*
> ```Shell
> 	echo "-h, --help       Print help and exit"
> 	echo "-q, --quiet      Hide part of the verbose output (e.g. from CMake), to make it more readable"
> 	echo "-t, --test       Test bench results and exit with error when values from comparing repo are worse than value defined in TEST_BENCH_THRESHOLD [TEST_BENCH_THRESHOLD: ${P_THRESHOLD}]"
> ```

I'm not sure about `test` parameter name.. right now I don't have better name, but pls re-think it
___
*[`utils/docker/run-compare-bench.sh` line 146 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Y9C0JS8LlowoQre:-NEM5Y9C0JS8LlowoQrf:b-y3imgh) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L146)):*
> ```Shell
> 	fi
> 
> 	for (( i=6; i<=$(wc -l < ${baseline_log}); i++ )); do
> ```

pls move this `$(wc -l < ${baseline_log})` into a variable, before the `for` loop
___
*[`utils/docker/run-compare-bench.sh` line 151 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5yV7AKVO7I3bS-oo:-NEM5yV89fJZtvIUyzXF:bo8ivew) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L151)):*
> ```Shell
> 		compare_name=$(sed -n ${i}p ${compare_log} | sed 's/[0-9,.,:]*//g' | awk '{$1=$1}1')
> 
> 		# equation_result is a percentage value of diverence of the compare_val campared to the baseline_val, 0 if negative value.
> ```

1. pls re-write this comment, I'm not sure what it is saying
2. pls fix misspells


<!-- Sent from Reviewable.io -->

2022-10-17 11:30 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 14 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

___
*[`.github/workflows/compare_bench.yml` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NE_fjOi9H5pD648u5wM:-NE_fjOj8_aLruZ1mPPm:b-5bcuqq) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L46)):*
> ```YAML
>  #   if: github.repository == 'pmem/pmemstream'
> 
>     runs-on: self-hosted
> ```

I'd like to recommend specifying an existing self-hosted runner by adding its labels, because as it is now, this job would run on every existing runner simultaneously, considering possibility of more runners added in the future.
Unless this is fine in current form @lukaszstolarczuk 
___
*[`utils/docker/run-compare-bench.sh` line 146 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Y9C0JS8LlowoQre:-NE__NKv42Pj6WWHN9i_:b2jh8ol) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L146)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls move this `$(wc -l < ${baseline_log})` into a variable, before the `for` loop
</blockquote></details>

As well as `i=6` unless it's hardcoded purposely
___
*[`utils/docker/run-compare-bench.sh` line 151 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5yV7AKVO7I3bS-oo:-NE_a3Ij5nLBr9x0654q:br6bw5t) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. pls re-write this comment, I'm not sure what it is saying
2. pls fix misspells
</blockquote></details>

My proposal for this comment:
# equation_result is a percentage based value derived from the comparison between $compare_val and the $baseline_val variables.
# If the result is negative, then the value is 0.


<!-- Sent from Reviewable.io -->

2022-10-18 09:22 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 14 unresolved discussions (waiting on @nedved1 and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NE_fjOi9H5pD648u5wM:-NEeOWuy-7hQhtfJ3z5b:b5zwxkb) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L46)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I'd like to recommend specifying an existing self-hosted runner by adding its labels, because as it is now, this job would run on every existing runner simultaneously, considering possibility of more runners added in the future.
Unless this is fine in current form @lukaszstolarczuk 
</blockquote></details>

:+1: I believe we need to add a label, agree


<!-- Sent from Reviewable.io -->

2022-11-02 11:07 UTC, lukaszstolarczuk commented
@nedved1, ping - what about this one?

2022-11-02 12:53 UTC, nedved1 reviewed
Sorry for delay, I've committed new changes.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273#-:-NFsOQueBfg4qnGpFKls:b-od9npy)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @lukaszstolarczuk and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 44 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3dNd1lyyovnQQKBR:-NFsG4wf9DyXeYt4AI1p:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls uncomment, when ready for review
</blockquote></details>

done
___
*[`.github/workflows/compare_bench.yml` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NE_fjOi9H5pD648u5wM:-NFsGKe55DRSwMh5xBSn:b-o1ra4u) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L46)):*
> I'd like to recommend specifying an existing self-hosted runner by adding its labels, because as it is now, this job would run on every existing runner simultaneously, considering possibility of more runners added in the future.
Changed runner name to 'compare-bench'
___
*[`.github/workflows/compare_bench.yml` line 49 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3bwDE3BxrQ8ZgiKp:-NFsGgM6-gb2edA4nmXm:bb7lgjf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this line?
</blockquote></details>

nope
___
*[`.github/workflows/compare_bench.yml` line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM3pdRAuJTq5cK3lnA:-NFsGmXaESczq0FOjGVA:bspsxm7) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why "push"? shouldn't we care only for PRs?
</blockquote></details>

ok, removed push
___
*[`.github/workflows/compare_bench.yml` line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4-vr-iLRsxO4RYRI:-NFsH3-v81uk1mDrG11Z:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, perhaps "Execute" instead of "Run"
</blockquote></details>

done
___
*[`.github/workflows/compare_bench.yml` line 65 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4x2q12LfRaIKrAsv:-NFsJ-n-ENLp-lhZGX7z:b-7ql1td) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if this GHA variable is empty, it breaks the CI (see GHA logs in this PR) - pls fix this `if` (similarly to below cases)
</blockquote></details>

fixed
___
*[`.github/workflows/compare_bench.yml` line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4SZa0iDOWPokOXQt:-NFsJ1dY15-MNEb2Lsd-:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I recommend using `-n` instead of this comparison (see e.g. https://github.com/pmem/pmemstream/blob/master/utils/docker/run-compare-bench.sh#L159 )
</blockquote></details>

done
___
*[`.github/workflows/compare_bench.yml` line 75 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM4_ST98QxOgdmE3HU:-NFsJ2Pa5dhezm2qXLoe:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

done
___
*[`.github/workflows/compare_bench.yml` line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Ik-8xFfNCwbpAe0:-NFsJhMJEIvhyMt8k7E5:b-7ql1td) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/.github/workflows/compare_bench.yml#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use `${VARIABLE_NAME}` notation, everywhere
</blockquote></details>

fixed
___
*[`utils/docker/run-compare-bench.sh` line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5j1P0utsRWOMamUD:-NFsJnHX13wk5chvMaqH:b-qmwwei) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `P_`?
</blockquote></details>

emm... I think it was for 'percentage' 😅
___
*[`utils/docker/run-compare-bench.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM86BB2SE9rrBBKKTj:-NFsLQr64zReE38CFcfW:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's a bit too long/verbose - pls shorten it
</blockquote></details>

done
___
*[`utils/docker/run-compare-bench.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM8OHb70ynL4hyZTes:-NFsNIwY9MJ7NSHfwjNA:bs9izmb) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure about `test` parameter name.. right now I don't have better name, but pls re-think it
</blockquote></details>

hmm, maybe change it for -r and -error ?
___
*[`utils/docker/run-compare-bench.sh` line 146 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Y9C0JS8LlowoQre:-NFsMzLMA60lAUbq2opV:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L146)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

As well as `i=6` unless it's hardcoded purposely
</blockquote></details>

done
___
*[`utils/docker/run-compare-bench.sh` line 151 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5yV7AKVO7I3bS-oo:-NFsNCaM30pNKXq07DzN:bimsq2s) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L151)):*
> If the result is negative, then the value is 0.
done, thnx


<!-- Sent from Reviewable.io -->

2022-11-04 15:31 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 63 at r2](https://reviewable.io/reviews/pmem/pmemstream/273#-NFy9CFG8pdGmEldazap:-NG2CjxVDnGxt7EHY9tu:bbhxwf1) ([raw file](https://github.com/pmem/pmemstream/blob/e7fa1cd7379a9c914211451c3ee85612a9eab2b0/.github/workflows/compare_bench.yml#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing an opening `"`
</blockquote></details>

thnx, fixed
___
*[`utils/docker/run-compare-bench.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM8OHb70ynL4hyZTes:-NG2D9uG3_npAWtDBn2h:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-e` and `--error` might be better, yeah :)
</blockquote></details>

Done.
___
*[`utils/docker/run-compare-bench.sh` line 146 at r1](https://reviewable.io/reviews/pmem/pmemstream/273#-NEM5Y9C0JS8LlowoQre:-NG2EBp51vWW_szkQH-w:b-bsvjrg) ([raw file](https://github.com/pmem/pmemstream/blob/5f91ce1659a44c76f2986f54d753d66ce72458fa/utils/docker/run-compare-bench.sh#L146)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done here; only in the function above
</blockquote></details>

ooops! 😅
___
*[`utils/docker/run-compare-bench.sh` line 33 at r2](https://reviewable.io/reviews/pmem/pmemstream/273#-NFy9uLA4J5h8vHTb2Es:-NG2D7LNETiI1eNVl3XK:b-lv8hrz) ([raw file](https://github.com/pmem/pmemstream/blob/e7fa1cd7379a9c914211451c3ee85612a9eab2b0/utils/docker/run-compare-bench.sh#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls extend this line with new param
</blockquote></details>

fixed, thnx


<!-- Sent from Reviewable.io -->

2022-11-04 16:44 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 6 unresolved discussions (waiting on @nedved1 and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2VEum7RrrGJKKWw9k:-NG2VEum7RrrGJKKWw9l:b-q8t3cm) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/.github/workflows/compare_bench.yml#L77)):*
> ```YAML
>             fi
> 
>             ./utils/docker/run-compare-bench.sh -t ${VERBOSE_PARAM} ${PR_PARAM} ${COMPARE_REF_PARAM} --baseline_repo=${{ inputs.BASELINE_REPO_ADDR }} --baseline_ref=${{ inputs.BASELINE_REF }} --compare_repo=${{ inputs.BASELINE_REPO_ADDR }}
> ```

`-t` pls fix
___
*[`utils/docker/run-compare-bench.sh` line 36 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2Vu5rDncEF7kv6YpE:-NG2Vu5rDncEF7kv6YpF:b-fw70ym) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L36)):*
> ```Shell
> 	echo "-h, --help       Print help and exit"
> 	echo "-q, --quiet      Hide part of the verbose output (e.g. from CMake), to make it more readable"
> 	echo "-e, --error      Return error when comparing values are worse than TEST_BENCH_THRESHOLD [TEST_BENCH_THRESHOLD: ${TEST_BENCH_THRESHOLD}%]"
> ```

hmm perhaps the second `TEST_BENCH_THRESHOLD:` should be replaced with just `current threshold:` and the third occurrence should be replaced with `P_THRESHOLD` (the actual currently used value)

// the first occurrence is alright, because it should be known, what env variable should be set - so no change there
___
*[`utils/docker/run-compare-bench.sh` line 173 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2WiLKCMJuEHV8qeSY:-NG2WiLKCMJuEHV8qeSZ:bmch8fn) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L173)):*
> ```Shell
> echo "Start of '${0}'"
> 
> while getopts ":hqt-:" optchar; do
> ```

pls fix `t`
___
*[`utils/docker/run-compare-bench.sh` line 179 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2V5qN9la1fZGJbKiC:-NG2V5qN9la1fZGJbKiD:b10898t) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L179)):*
> ```Shell
> 			help) print_usage ${0} && exit 0 ;;
> 			quiet) QUIET=1 ;;
> 			test) TEST_BENCH=1 ;;
> ```

pls fix

perhaps `TEST_BENCH` -> `ERROR_BENCH`
___
*[`utils/docker/run-compare-bench.sh` line 190 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2V7aw2aIXmGJf6lt4:-NG2V7aw2aIXmGJf6lt5:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L190)):*
> ```Shell
> 		h) print_usage ${0} && exit 0 ;;
> 		q) QUIET=1 ;;
> 		t) TEST_BENCH=1 ;;
> ```

.


<!-- Sent from Reviewable.io -->

2022-11-07 16:11 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2VEum7RrrGJKKWw9k:-NGHp09u47E1iAhgEWSg:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/.github/workflows/compare_bench.yml#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-t` pls fix
</blockquote></details>

done
___
*[`utils/docker/run-compare-bench.sh` line 36 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2Vu5rDncEF7kv6YpE:-NGHqF1p6nit8I7HHvsR:b-n9tkhd) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm perhaps the second `TEST_BENCH_THRESHOLD:` should be replaced with just `current threshold:` and the third occurrence should be replaced with `P_THRESHOLD` (the actual currently used value)

// the first occurrence is alright, because it should be known, what env variable should be set - so no change there
</blockquote></details>

changed
___
*[`utils/docker/run-compare-bench.sh` line 173 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2WiLKCMJuEHV8qeSY:-NGHqGv85UbSOXOF-fy6:bb7f2mf) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L173)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix `t`
</blockquote></details>

done
___
*[`utils/docker/run-compare-bench.sh` line 179 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2V5qN9la1fZGJbKiC:-NGHqHxtEUhTn4KVpc9K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L179)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix

perhaps `TEST_BENCH` -> `ERROR_BENCH`
</blockquote></details>

Done.
___
*[`utils/docker/run-compare-bench.sh` line 190 at r3](https://reviewable.io/reviews/pmem/pmemstream/273#-NG2V7aw2aIXmGJf6lt4:-NGHqJ24BWpqNhD13nbv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c9d662784d2ecca7f660e25187ea695f1a2f5b2f/utils/docker/run-compare-bench.sh#L190)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-08 10:52 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273#-:-NGLrR2M-M10gTC1f2w4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2022-11-09 15:39 UTC, lukaszstolarczuk requested changes
FYI:

```
Linux-compare-bench

This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273#-:-NGS1r6T2Jh8z-FfjeFd:b-jwxzs0)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2022-11-17 12:26 UTC, tszczyp reviewed
The proper label must be added for the available runner in the repository settings:
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/RrcK9ByWCsm8depYoXXtrzdP/image.png)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/25879106/moMBtakn772W-QbcZq1-hWUe/image.png)
Then click on the runner and add label
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/25879106/oy-r0fsMFEdcVKrUA60MCalV/image.png)
This must be done by the repo admin, otherwise in this current form the workflow will not work

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273#-:-NH4XJOo5OU2RGgz1PAc:b-v1b9ol)* status: all files reviewed, 1 unresolved discussion (waiting on @nedved1)



<!-- Sent from Reviewable.io -->

2022-11-29 08:52 UTC, lukaszstolarczuk reviewed
thanks @tszczyp, we set up the label as you instructed :)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273#-:-NI1_VOhD4DwmewM8B-4:b-i0of8a)* status: all files reviewed, 2 unresolved discussions (waiting on @nedved1 and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 69 at r4](https://reviewable.io/reviews/pmem/pmemstream/273#-NI1_KEzAc4YhLMhcIPM:-NI1_KEzAc4YhLMhcIPN:bom1l1r) ([raw file](https://github.com/pmem/pmemstream/blob/f05aee9a5aae3355456780a711bfd9ebb6a66847/.github/workflows/compare_bench.yml#L69)):*
> ```YAML
>             PR_PARAM=''
>             if [ -n "${{ inputs.PR }}" ]; then
>               PR_PARAM="--pr=${{ inputs.PR }}"
> ```

`inputs.PR` is not set when the event is pull_request, so we need to set it up somehow

// https://github.com/pmem/pmemstream/actions/runs/3412012437/jobs/6005266607#step:4:24


<!-- Sent from Reviewable.io -->

2022-12-20 13:06 UTC, lukaszstolarczuk commented
@nedved1, ping :)

2022-12-22 11:28 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 2 unresolved discussions (waiting on @nedved1 and @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 69 at r4](https://reviewable.io/reviews/pmem/pmemstream/273#-NI1_KEzAc4YhLMhcIPM:-NJt_cv48h0rLhEW6qbz:bw7ivi6) ([raw file](https://github.com/pmem/pmemstream/blob/f05aee9a5aae3355456780a711bfd9ebb6a66847/.github/workflows/compare_bench.yml#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`inputs.PR` is not set when the event is pull_request, so we need to set it up somehow

// https://github.com/pmem/pmemstream/actions/runs/3412012437/jobs/6005266607#step:4:24
</blockquote></details>

soo, @nedved1, is my issue fixed now? you didn't confirm it's done :wink: 


<!-- Sent from Reviewable.io -->

2022-12-23 08:27 UTC, lukaszstolarczuk approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/273)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[`.github/workflows/compare_bench.yml` line 69 at r4](https://reviewable.io/reviews/pmem/pmemstream/273#-NI1_KEzAc4YhLMhcIPM:-NJy4xrkBYVLxEfof3E8:b9y27z0) ([raw file](https://github.com/pmem/pmemstream/blob/f05aee9a5aae3355456780a711bfd9ebb6a66847/.github/workflows/compare_bench.yml#L69)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

I forgot to publish my comment and it stayed as "draft", sorry! I think that I fixed that issue as workflow job now passes: https://github.com/pmem/pmemstream/actions/runs/3741711042/jobs/6351685241
</blockquote></details>

great, thanks!


<!-- Sent from Reviewable.io -->

2022-12-23 08:27 UTC, merged