Add information in README about discontinuation of project
pmem/pmemstream pull request #283
Opened 2023-02-03 10:34 UTC by szadam

2023-02-03 12:38 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwOcj8UiMWq25Nt9g:-NNLwOckEk-3bdnc2QTZ:b-gncgs0) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L26)):*
> ```Markdown
> ![example pmemstream](doc/pmemstream.png)
> 
> # DISCONTINUATION OF PROJECT
> ```

I guess no need for all caps; to be concise with the rest of the paragraphs
___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwSDSA_mSGrWo4-xm:-NNLwSDSA_mSGrWo4-xn:b-8i66x7) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L26)):*
> ```Markdown
> ![example pmemstream](doc/pmemstream.png)
> 
> # DISCONTINUATION OF PROJECT
> ```

`of the project` (I guess)
___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNLwUxM0qVY4blZCfUN:b4amadk) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
> ```Markdown
> 
> # DISCONTINUATION OF PROJECT
> pmemstream project will no longer be maintained by Intel Project Maintainers.
> ```

just discussing: perhaps we could add some icon, like a warning sign (like :warning: `:warning:`)
___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNMGFdq0Y7ttJxU1sTT:-NNMGFdq0Y7ttJxU1sTU:bj3sfnl) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
> ```Markdown
> 
> # DISCONTINUATION OF PROJECT
> pmemstream project will no longer be maintained by Intel Project Maintainers.
> ```

I think `project maintainers` is rather redundant here ("maintained by maintainers" :wink: )
___
*[`README.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwM8dEu8IqCTJkHRU:-NNLwM8e3aRzVpR6zbYX:bcswsya) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L33)):*
> ```Markdown
> - If you have an ongoing need to use this project, are interested in independently developing it, or would like to
> maintain patches for the open source software community, please create your own fork of this project.
> ```

perhaps we should add a link to the blog post with the further details
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNLwA4H-8aRYyJznqqs:b-mr9d5o) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
> ```Markdown
> - read our whitepaper [attached to 0.2.1 release](https://github.com/pmem/pmemstream/releases/download/0.2.1/Libpmemstream_whitepaper.docx),
> <!-- update contact points -->
> - contact Igor Chorążewicz (igor.chorazewicz@intel.com) or Piotr Balcer (piotr.balcer@intel.com),
> ```

remember to update all information, incl. contact points


<!-- Sent from Reviewable.io -->

2023-02-03 14:03 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwOcj8UiMWq25Nt9g:-NNM_NmQ9VGiESfe_-yr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess no need for all caps; to be concise with the rest of the paragraphs
</blockquote></details>

Done.
___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwSDSA_mSGrWo4-xm:-NNM_OOv3Sd_yrWzDC0k:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`of the project` (I guess)
</blockquote></details>

Done.
___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNM_OvE773n1J7lgsSW:b6fvnsg) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just discussing: perhaps we could add some icon, like a warning sign (like :warning: `:warning:`)
</blockquote></details>

I think it is a good idea
___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNMGFdq0Y7ttJxU1sTT:-NNM_WhJ34UahK5vKUD2:b-dp1jkm) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think `project maintainers` is rather redundant here ("maintained by maintainers" :wink: )
</blockquote></details>

you are right
___
*[`README.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwM8dEu8IqCTJkHRU:-NNM_ZQEEsWuNGwqV9aI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps we should add a link to the blog post with the further details
</blockquote></details>

Done.
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNM__LU0xUBf3RUWSc3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remember to update all information, incl. contact points
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-03 15:19 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNMptP11x5AfS20O7IJ:b-1ri6hs) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I think it is a good idea
</blockquote></details>

hmm... perhaps just one icon, in the title...? (like: `# :warning: Disc...`)
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNMqOHKBJ2upPApaf8b:b-f7col3) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1. google group and Slack stays, for now
2. perhaps write something more than just "contact email" :wink: maybe something like: if you have more questions/you can contact/you can reach out <> for more information ...
___
*[`README.md` line 33 at r2](https://reviewable.io/reviews/pmem/pmemstream/283#-NNMqIl0CEVeEFxxTSVE:-NNMqIl0CEVeEFxxTSVF:b-5f2xee) ([raw file](https://github.com/pmem/pmemstream/blob/890b56c1e41e72cdc006cad0eeb8a98781d2388a/README.md#L33)):*
> ```Markdown
> - If you have an ongoing need to use this project, are interested in independently developing it, or would like to
> maintain patches for the open source software community, please create your own fork of this project.
> - You will find more information [here](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/)
> ```

pls add `.` at the end, as the rest of the points have


<!-- Sent from Reviewable.io -->

2023-02-06 07:31 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NN_cUW16KC6FH24lcwD:b8rfqq2) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... perhaps just one icon, in the title...? (like: `# :warning: Disc...`)
</blockquote></details>

In my opinion it should be above pmemstream descriprion, at the very top.


<!-- Sent from Reviewable.io -->

2023-02-06 08:53 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`README.md` line 27 at r2](https://reviewable.io/reviews/pmem/pmemstream/283#-NN_vICL8yuK1pABFj_e:-NN_vICL8yuK1pABFj_f:b-gy20xl) ([raw file](https://github.com/pmem/pmemstream/blob/890b56c1e41e72cdc006cad0eeb8a98781d2388a/README.md#L27)):*
> ```Markdown
> 
> # Discontinuation of the project
> ⚠️pmemstream project will no longer be maintained by Intel.⚠️
> ```

I discussed this update with Marek and he's only input, for now, is - please make the beginning like `The **pmemstream** project will no ...`


<!-- Sent from Reviewable.io -->

2023-02-06 09:53 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNa7Ru54BPT0kzOCLrZ:bpg7r33) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@wlemkows, what do you mean - the icon should be on top, or do you mean the whole paragraph?

if the latter, then maybe you're right... but if we move this paragraph to the top of the page (below our scan badges), then we should add something like `# Introduction` for the intro paragraph (currently with no title)
</blockquote></details>

I mean:
! DISCONTINUATION... ! (capitals maybe)
-
-
-

`pmemstream` is a loggibng ....

## Table of....


<!-- Sent from Reviewable.io -->

2023-02-06 09:55 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNa8LB-D3VC48e4hu1O:bnlqeu7) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

I mean:
! DISCONTINUATION... ! (capitals maybe)
-
-
-

`pmemstream` is a loggibng ....

## Table of....



</blockquote></details>

I mean:
! DISCONTINUATION... ! (capitals maybe)
 
 \-
\-
\-

\`pmemstream\` is a logging ....

\#\#Table of....


<!-- Sent from Reviewable.io -->

2023-02-06 09:57 UTC, szadam commented
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNa8tJL0YY2WM5CfASy:brz3olq) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

I mean:
! DISCONTINUATION... ! (capitals maybe)
 
 \-
\-
\-

\`pmemstream\` is a logging ....

\#\#Table of....

</blockquote></details>

so, do you mean that I should merge this paragraph with the previous one?


<!-- Sent from Reviewable.io -->

2023-02-06 10:36 UTC, szadam reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNaHxIH2GsRFwsDxUHd:baag62t) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

so, do you mean that I should merge this paragraph with the previous one?
</blockquote></details>

I suggest something like this.
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNaI680AIqXaAzf_p8L:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. google group and Slack stays, for now
2. perhaps write something more than just "contact email" :wink: maybe something like: if you have more questions/you can contact/you can reach out <> for more information ...
</blockquote></details>

Done.
___
*[`README.md` line 27 at r2](https://reviewable.io/reviews/pmem/pmemstream/283#-NN_vICL8yuK1pABFj_e:-NNaI4PREh8-7acuPg_M:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/890b56c1e41e72cdc006cad0eeb8a98781d2388a/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I discussed this update with Marek and he's only input, for now, is - please make the beginning like `The **pmemstream** project will no ...`
</blockquote></details>

Done.
___
*[`README.md` line 33 at r2](https://reviewable.io/reviews/pmem/pmemstream/283#-NNMqIl0CEVeEFxxTSVE:-NNaI53V2Zev8v_9dO-d:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/890b56c1e41e72cdc006cad0eeb8a98781d2388a/README.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `.` at the end, as the rest of the points have
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-06 10:47 UTC, wlemkows reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNaKQx91HGHS1umm_ht:b2ooqa2) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I suggest something like this.
</blockquote></details>

I like that the message is at the very top and is the first thing we come across in the readme.


<!-- Sent from Reviewable.io -->

2023-02-06 10:50 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNaL9mB5sfxQL9JPeYH:b-1t4byu) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@lukaszstolarczuk why do you want to leave `post on our #pmem Slack channel using this invite link or Google group` line?


<!-- Sent from Reviewable.io -->

2023-02-06 11:28 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNaTUNi6sFSaFEkFF9m:b-i2h8xb) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

I like that the message is at the very top and is the first thing we come across in the readme.
</blockquote></details>

to be honest, I liked it better before - you have a simple intro to the project, then the warning information... It's not like missing this warning may lead to a **major** issue/confusion/etc :wink: 

I believe it looks weird, especially with the badges "in the middle" of the page

// https://github.com/szadam/pmemstream/blob/master/README.md#discontinuation-of-the-project 
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwA4H-8aRYyJznqqr:-NNaS9S3-92jjvlCFRjo:bqzn2eb) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L46)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

@lukaszstolarczuk why do you want to leave `post on our #pmem Slack channel using this invite link or Google group` line?
</blockquote></details>

yeah, I think for now we're still supporting the pmem group and Slack channel, once it's dead we'll remove these contact points
___
*[`README.md` line 1 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaTmqn5-ZVWwwm8yjA:-NNaTmqn5-ZVWwwm8yjB:b-8h11r3) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L1)):*
> ```Markdown
> # ⚠️ Discontinuation of the **pmemstream** project
> ```

I believe you can drop "pmemstream" from this line (from the title)
___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNaSUYdEyOXDWiciBoE:b-a0vabn) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
> ```Markdown
> [this invite link](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg)
> or [Google group](https://groups.google.com/g/pmem),
> - if you steel have some more question you can reach out pmdk_support@intel.com for more information.
> ```

1. `steel` as in Man of Steel? :stuck_out_tongue_winking_eye: 
2. I'm not very fond of this sentence - you can ask questions everywhere (on Slack/pmem group/email), so "still have more questions" is not suitable here in my opinion


<!-- Sent from Reviewable.io -->

2023-02-06 13:37 UTC, szadam commented
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNavzNE26xjIa-PxEuD:b9isfav) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. `steel` as in Man of Steel? :stuck_out_tongue_winking_eye: 
2. I'm not very fond of this sentence - you can ask questions everywhere (on Slack/pmem group/email), so "still have more questions" is not suitable here in my opinion
</blockquote></details>

so just "if you have more questions you can reach..." or maybe just "You can reach out..."?


<!-- Sent from Reviewable.io -->

2023-02-06 13:49 UTC, lukaszstolarczuk commented
> _[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNavzNE26xjIa-PxEuD:b9isfav) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):_
> 
> Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…
> so just "if you have more questions you can reach..." or maybe just "You can reach out..."?

As I said, questions can be asked in several places, this is just one of them. From my point of view, the second version is better, e.g.:
`You can reach us out using the dedicated e-mail: ...`

2023-02-06 14:40 UTC, szadam reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNb9r5z-oQBttnyqRHM:b-kmz2c4) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to be honest, I liked it better before - you have a simple intro to the project, then the warning information... It's not like missing this warning may lead to a **major** issue/confusion/etc :wink: 

I believe it looks weird, especially with the badges "in the middle" of the page

// https://github.com/szadam/pmemstream/blob/master/README.md#discontinuation-of-the-project 
</blockquote></details>

maybe like that?
___
*[`README.md` line 1 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaTmqn5-ZVWwwm8yjA:-NNb9pNf2gcdslImtzPG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can drop "pmemstream" from this line (from the title)
</blockquote></details>

Done.
___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNb9z4L8w3sTOQ68g4_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

As I said, questions can be asked in several places, this is just one of them. From my point of view, the second version is better, e.g.:
`You can reach us out using the dedicated e-mail: ...` 

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 08:22 UTC, wlemkows approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/283#-NNLwUxM0qVY4blZCfUM:-NNexn8h7d1ew9jd9DY9:b-bohsbu) ([raw file](https://github.com/pmem/pmemstream/blob/af634362d1f3862c6dbf8d3aaaf33dee010904a6/README.md#L27)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

maybe like that?
</blockquote></details>

Now it is exactly as I thought.


<!-- Sent from Reviewable.io -->

2023-02-07 11:19 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNf_xoXAb0qmp0ewcyf:b8rw71o) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

maybe a little change: "- or reach us out ..." (drop "you can" and replace with "or")
___
*[`README.md` line 18 at r4](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfaQnv2Ssf8qDY4GAW:-NNfaQnv2Ssf8qDY4GAX:b-xw92yp) ([raw file](https://github.com/pmem/pmemstream/blob/195bc4ec278156c81c057865b0e47844601ce3a9/README.md#L18)):*
> ```Markdown
> ## Introduction
> 
> `pmemstream` is a logging data structure optimized for persistent memory.
> ```

pls update, as discussed `**pmemstream**`
___
*[`README.md` line 35 at r4](https://reviewable.io/reviews/pmem/pmemstream/283#-NNf_rv521JK4XxSZgpu:-NNf_rv60WW516BTbmLs:b-g8rs19) ([raw file](https://github.com/pmem/pmemstream/blob/195bc4ec278156c81c057865b0e47844601ce3a9/README.md#L35)):*
> ```Markdown
> ![example pmemstream](doc/pmemstream.png)
> 
> ## Table of contents
> ```

please remove the ToC, as discussed


<!-- Sent from Reviewable.io -->

2023-02-07 11:32 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfdDsF2OhkGhGeHrbH:-NNfdDsF2OhkGhGeHrbI:b-t7wl5m) (no related file):*
I think that if "The **pmemstream** project will no longer be maintained by Intel."  we should not provide links to Intel slack or Intel's e-mail addresses

___


<!-- Sent from Reviewable.io -->

2023-02-07 11:32 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-02-07 11:33 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-02-07 11:47 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam and @wlemkows)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfdDsF2OhkGhGeHrbH:-NNfg_5M2Vcgm4i167S1:blapwlh) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that if "The **pmemstream** project will no longer be maintained by Intel."  we should not provide links to Intel slack or Intel's e-mail addresses
</blockquote></details>

@wlemkows, what do you think, should we remove all contact points (from dropped repos) after all?

___


<!-- Sent from Reviewable.io -->

2023-02-08 12:31 UTC, szadam reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNl-TYr8Pj4mcgD-SD2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe a little change: "- or reach us out ..." (drop "you can" and replace with "or")
</blockquote></details>

Done.
___
*[`README.md` line 18 at r4](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfaQnv2Ssf8qDY4GAW:-NNl-PLl1cSnXRqmokJ2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/195bc4ec278156c81c057865b0e47844601ce3a9/README.md#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update, as discussed `**pmemstream**`
</blockquote></details>

Done.
___
*[`README.md` line 35 at r4](https://reviewable.io/reviews/pmem/pmemstream/283#-NNf_rv521JK4XxSZgpu:-NNl-Pmf4a6UPp969Fy-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/195bc4ec278156c81c057865b0e47844601ce3a9/README.md#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please remove the ToC, as discussed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-08 12:51 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)

___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/283#-NNaSUYdEyOXDWiciBoD:-NNl47IF4mW05wYtyrCq:b2nid0f) ([raw file](https://github.com/pmem/pmemstream/blob/cd9792918bc2c9007d93021704b9cc3e4173b858/README.md#L47)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx


<!-- Sent from Reviewable.io -->

2023-02-08 13:03 UTC, wlemkows requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfdDsF2OhkGhGeHrbH:-NNl5iLCCFnv-VOfmSKV:b-40eth2) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@wlemkows, what do you think, should we remove all contact points (from dropped repos) after all?
</blockquote></details>

I think we should remove other contacts. From now on the only proper contact will be e-mail pmdk_support@intel.com.
As a result, after archiving the project we are not obliged to follow other sources with possible questions/information.

___


<!-- Sent from Reviewable.io -->

2023-02-09 10:13 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @szadam)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfdDsF2OhkGhGeHrbH:-NNpdbCLDTtVnDT9rBkz:buej5hq) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe Tomek is saying - he'd remove all contact information from this readme.
From Tomek's perspective: on [the blog post](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/) we don't say anything about the support for archived repositories...
</blockquote></details>

ok, we've discussed it a little today and decided we'll leave only one contact point, and it's going to be an email address. It's already accessible on pmem.io, so there should be no harm in putting it here as well

___
___
*[`README.md` line 42 at r5](https://reviewable.io/reviews/pmem/pmemstream/283#-NNpdsdL5FVPTrojHEhP:-NNpdsdL5FVPTrojHEhQ:b-fmjqrw) ([raw file](https://github.com/pmem/pmemstream/blob/48b58a19c7ae90e73ec41ff860f677ede3ce8645/README.md#L42)):*
> ```Markdown
> For more information about **pmemstream**, please:
> - read our whitepaper [attached to 0.2.1 release](https://github.com/pmem/pmemstream/releases/download/0.2.1/Libpmemstream_whitepaper.docx),
> - post on our **#pmem** Slack channel using
> ```

pls remove this point (Slack and google group)
___
*[`README.md` line 45 at r5](https://reviewable.io/reviews/pmem/pmemstream/283#-NNpdvxfAKPl2Xn1UMHB:-NNpdvxfAKPl2Xn1UMHC:b-pmmz6i) ([raw file](https://github.com/pmem/pmemstream/blob/48b58a19c7ae90e73ec41ff860f677ede3ce8645/README.md#L45)):*
> ```Markdown
> [this invite link](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg)
> or [Google group](https://groups.google.com/g/pmem),
> - or reach us out using the dedicated email: pmdk_support@intel.com.
> ```

perhaps, re-phrase to something like `- if the [blog post](<link here>) didn't answer your question please contact us using email: ...`


<!-- Sent from Reviewable.io -->

2023-02-10 10:14 UTC, szadam reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/283#-NNfdDsF2OhkGhGeHrbH:-NNuoFZq7GVxOfuO-N66:b-cstnkg) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, we've discussed it a little today and decided we'll leave only one contact point, and it's going to be an email address. It's already accessible on pmem.io, so there should be no harm in putting it here as well
</blockquote></details>

I agree

___
___
*[`README.md` line 42 at r5](https://reviewable.io/reviews/pmem/pmemstream/283#-NNpdsdL5FVPTrojHEhP:-NNuoJpF9OGpYyJrhFI4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/48b58a19c7ae90e73ec41ff860f677ede3ce8645/README.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls remove this point (Slack and google group)
</blockquote></details>

Done.
___
*[`README.md` line 45 at r5](https://reviewable.io/reviews/pmem/pmemstream/283#-NNpdvxfAKPl2Xn1UMHB:-NNuoKSvEGEeafaH_wDv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/48b58a19c7ae90e73ec41ff860f677ede3ce8645/README.md#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps, re-phrase to something like `- if the [blog post](<link here>) didn't answer your question please contact us using email: ...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-21 11:49 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-02-23 11:17 UTC, szadam reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`README.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmemstream/283#-NOFUh0F9yBSnJhky2v0:-NOxzYSL3bQEFC_QDdPG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4d51f7f80a7c6aa9427975798680c30b4e04a209/README.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`question,`
</blockquote></details>

Done.
___
*[`README.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmemstream/283#-NOFUilN0i_LGd4md7rA:-NOxzYth1DRrgKh3MGRT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4d51f7f80a7c6aa9427975798680c30b4e04a209/README.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`the dedicated e-mail address: `
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 11:32 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2023-02-27 16:55 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283#-:-NPInCfE0bFaTv5DxHBU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-22 09:55 UTC, wlemkows approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-22 09:55 UTC, merged