Nontemportal memcpy
pmem/pmemstream pull request #30
Opened 2021-12-15 13:55 UTC by karczex

- [ ] Add memcpy description
- [ ] Add more tests

2021-12-15 14:53 UTC, Karolina002 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @Karolina002)



<!-- Sent from Reviewable.io -->

2021-12-15 14:55 UTC, karczex commented
![nontemporal_variadic_memcy](https://user-images.githubusercontent.com/23352575/146209242-13e31e28-d93b-4abe-a098-1e3e9634b104.png)

2021-12-15 14:59 UTC, Karolina002 reviewed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-12-16 10:18 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: all files reviewed, 16 unresolved discussions (waiting on @karczex)

___
*[src/libpmemstream.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dCvP2gWlllEuHg2I:-Mr1dCvP2gWlllEuHg2J:bpbkdne) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream.c#L11)):*
> ```C
> 
> #include <assert.h>
> #include <libpmem2.h>
> ```

it's not required anymore (included in internal.h), same as libpmemstream.h
___
*[src/libpmemstream_internal.h, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1djoFEvXcXEiUbAFH:-Mr1djoFEvXcXEiUbAFI:b-tssp16) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream_internal.h#L4)):*
> ```objc
> /* Copyright 2021, Intel Corporation */
> 
> /* Internal Header */
> ```

should this file go into src/common dir...?
___
*[src/common/util.h, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dszy9N-8jmi9ioEG:-Mr1dszy9N-8jmi9ioEH:b-hrnooy) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L11)):*
> ```objc
> #include "libpmemstream_internal.h"
> #include <assert.h>
> #include <libpmem2.h>
> ```

redundant now
___
*[src/common/util.h, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1jYgo8w8Q1sKUqfQG:-Mr1jYgo8w8Q1sKUqfQH:b-uv4q79) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L64)):*
> ```objc
> 		size_t size;
> 	};
> 	struct buffer arguments[parts];
> ```

perhaps rename to "parsed_args" or something...
___
*[src/common/util.h, line 73 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1eCVJ3O1qCT9XjZjd:-Mr1eCVJ3O1qCT9XjZje:b-vz67lr) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L73)):*
> ```objc
> 	va_end(argv);
> 
> 	/* memcpy */
> ```

what do you mean by "memcpy"? perhaps be more accurate, e.g., "Do the memcpy" :wink: at first I thought this comment is only for the struct
___
*[src/common/util.h, line 80 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1jFyW5PEqkHie6-0W:-Mr1jFyW5PEqkHie6-0X:b-vgfhso) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L80)):*
> ```objc
> 	tmp_buffer.offset = 0;
> 
> 	uint8_t *destination = (uint8_t *)dest;
> ```

I'd personally switch the names (dest <> destination) - "destination" is used more frequently in here, so perhaps it'd be easier to have it shorter below
___
*[tests/unittest/pmemstream_memcpy.cpp, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1evVEDtWdsv-o0U_c:-Mr1evVEDtWdsv-o0U_d:b-omglw6) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L1)):*
> ```cpp
> #include "common/util.h"
> ```

missing SPDX tag
___
*[tests/unittest/pmemstream_memcpy.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1eylE9L1dJDs3oMtp:-Mr1eylE9L1dJDs3oMtq:b-4de1v1) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L9)):*
> ```cpp
> #include <fstream>
> #include <iostream>
> ```

you could clean up these includes a little :wink: 
___
*[tests/unittest/pmemstream_memcpy.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1f5h_6y2BwgR0rY3J:-Mr1f5h_6y2BwgR0rY3K:bsfwkz6) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L16)):*
> ```cpp
> #include <iostream>
> 
> struct foo {
> ```

"foo" ? :D
___
*[tests/unittest/pmemstream_memcpy.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fAGh3gzhYAXYsrBO:-Mr1fAGh3gzhYAXYsrBP:b-wcmrbq) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L38)):*
> ```cpp
> 				     sizeof(e));
> 
> 	UT_ASSERTeq(ret, 0);
> ```

sicne this is a RC test, you can use RC_ASSERTs
___
*[tests/unittest/pmemstream_memcpy.cpp, line 53 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1hJlA-DaXakkS7W-l:-Mr1hJlA-DaXakkS7W-m:bz8mklx) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L53)):*
> ```cpp
> }
> 
> static void test_not_aligned_array(struct pmemstream *stream)
> ```

perhaps also add here as well a short comment what this test does
___
*[tests/unittest/pmemstream_memcpy.cpp, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1gfRQBPF1_XXdJi4j:-Mr1gfRQBPF1_XXdJi4k:bco4ivf) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L64)):*
> ```cpp
> }
> 
> static auto property_tests(struct pmemstream *stream)
> ```

pls rename, we could start all test methods with "test_"
___
*[tests/unittest/pmemstream_memcpy.cpp, line 78 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1h9fR0QlupE3EbG0v:-Mr1h9fR0QlupE3EbG0w:b9mbokr) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L78)):*
> ```cpp
> 	});
> 
> 	return ret;
> ```

I think you should rather check if ret is ok, instead of returning it...?
___
*[tests/unittest/pmemstream_memcpy.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fXv23hGGKhxYk1jz:-Mr1fXv23hGGKhxYk1k-:bt006ng) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L83)):*
> ```cpp
> int main(int argc, char *argv[])
> {
> ```

empty line
___
*[tests/unittest/pmemstream_memcpy.cpp, line 89 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fHub-5xLtCvU_ol_:-Mr1fHub-5xLtCvU_ola:b-atjuez) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L89)):*
> ```cpp
> 	auto path = std::filesystem::path(argv[1]);
> 
> 	if (!std::filesystem::exists(path)) {
> ```

heh, yet another approach to create/extend a file :smile: we have to clean it up and unify between our tests (to be done next sprint - pls add an XXX)
___
*[tests/unittest/pmemstream_memcpy.cpp, line 102 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1g1eSB_GudnTKCnQk:-Mr1g1eSB_GudnTKCnQl:b-gwlkkw) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L102)):*
> ```cpp
> 	UT_ASSERTne(stream, NULL);
> 
> 	// Add finaly labmda to run_test?
> ```

Do you mean you want to add cleanup into the "finally" part of the lambda? pls mark it as XXX, if so


<!-- Sent from Reviewable.io -->

2021-12-16 10:26 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: all files reviewed, 16 unresolved discussions (waiting on @karczex)

___
*[tests/unittest/pmemstream_memcpy.cpp, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1evVEDtWdsv-o0U_c:-Mr1lOSNE1y5j1TaniQY:b-lxpf46) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing SPDX tag
</blockquote></details>

actually, why CI didn't find this? :thinking: funny, we don;t run check-license properly I guess :smile:  


<!-- Sent from Reviewable.io -->

2021-12-16 11:35 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: all files reviewed, 16 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[src/libpmemstream_internal.h, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1djoFEvXcXEiUbAFH:-Mr20FX922Yk1WMuAsCo:bpjdabj) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream_internal.h#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should this file go into src/common dir...?
</blockquote></details>

I think not, common folder would make sense if we would have multiple modules/etc. For now, I think it's better to keep it simple


<!-- Sent from Reviewable.io -->

2021-12-16 12:09 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: all files reviewed, 15 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/unittest/pmemstream_memcpy.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1f5h_6y2BwgR0rY3J:-Mr288JkAytEiHl9Kar9:b-kffipz) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"foo" ? :D
</blockquote></details>

What's wrong with foo? ;)
___
*[tests/unittest/pmemstream_memcpy.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fAGh3gzhYAXYsrBO:-Mr26s1uDASVCO7h9pbq:b-cecnyu) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sicne this is a RC test, you can use RC_ASSERTs
</blockquote></details>

It's not RC test. As we discussed I will move it to separate file


<!-- Sent from Reviewable.io -->

2021-12-16 12:18 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: all files reviewed, 15 unresolved discussions (waiting on @karczex)

___
*[tests/unittest/pmemstream_memcpy.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1f5h_6y2BwgR0rY3J:-Mr2AES40_yjj1NLJRD7:bargybc) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L16)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

What's wrong with foo? ;)
</blockquote></details>

I don't know, it's just that... I'd rename it to something more meaningful :smile: 
___
*[tests/unittest/pmemstream_memcpy.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fAGh3gzhYAXYsrBO:-Mr2AOX-9-N9evMLdZoa:b-7pvwig) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L38)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's not RC test. As we discussed I will move it to separate file
</blockquote></details>

great


<!-- Sent from Reviewable.io -->

2021-12-16 13:55 UTC, igchor requested changes
It would be very nice if you could convert this image to ascii and put as comment

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30#-:-Mr2Tc3c7Q69jO4wMu_T:b-vpvkz7)* status: 1 of 7 files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr2TuUY6FKRmMBgRhI-:b-qy6oxf) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
> ```objc
> 		size_t size;
> 	};
> 	struct buffer parsed_args[parts];
> ```

variable length array is an extension, not supported by the standard I think (I belive argc is not a compile time constant in this context). 
___
*[src/common/util.h, line 93 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2WZZm51pBUAt1jxXB:-Mr2WZZm51pBUAt1jxXC:b-jard5k) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L93)):*
> ```objc
> 			chunk.ptr = NULL;
> 
> 			size_t tmp_buffer_free_space = sizeof(tmp_buffer.array) - tmp_buffer.offset;
> ```

why `- offset`?


<!-- Sent from Reviewable.io -->

2021-12-16 14:14 UTC, KFilipek requested changes
> Reviewed 2 of 5 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 2 of 7 files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/common/util.h, line 84 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr-OagK37z1rS1CHAKh:-Mr-OagL3oDdoaa3LQ7m:b-7iu02p) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L84)):*
> ```
> 		uint8_t *src = arguments[part].ptr;
> 		size_t size = arguments[part].size;
> ```
*src and size looks similar to `buffer` structure, but I don't have no idea how it should be connected
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 56 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2_fVK7uMRtQ9hHr-0:-Mr2_fVL6iGGYziLxKmL:bro22jr) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L56)):*
> ```
> sizeof(not_aligned_data)
> ```
if you mean no. of elements so it should be: 
```cpp
size_t buf[sizeof(not_aligned_data)/sizeof(*not_aligned_data)]
```


<!-- Sent from Reviewable.io -->

2021-12-16 14:32 UTC, KFilipek requested changes
> Reviewed 1 of 5 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 7 files reviewed, 23 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 79 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2aBXDC1BBdC8_UQY9:-Mr2aBXDC1BBdC8_UQYA:bwtie9t) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L79)):*
> ```cpp
> 	auto stream = make_pmemstream(path, block_size, std::filesystem::file_size(path));
> 
> 	// Add finaly labmda to run_test?
> ```

1. typo: lambda
2. Add "XXX:" to don't miss it in the future
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 82 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2aJnQ1-w6dg7btkYr:-Mr2aJnQ1-w6dg7btkYs:bq5mtlz) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L82)):*
> ```cpp
> 	return run_test([&] {
> 		test_basic(stream.get());
> 		//		test_not_aligned_array(stream);
> ```

unnecessary tabs after double '/'
___
*[tests/unittest/pmemstream_memcpy.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1f5h_6y2BwgR0rY3J:-Mr2alPwDF-9hva5gsBu:b-hh2e22) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't know, it's just that... I'd rename it to something more meaningful :smile: 
</blockquote></details>

if you think `foo` you automaticaly look for a `bar`somewhere :D
___
*[tests/unittest/pmemstream_memcpy.cpp, line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2b7p74532l68JXdkg:-Mr2b7p74532l68JXdkh:blqaxp7) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L56)):*
> ```
> sizeof(not_aligned_data)
> ```
no of elements as above.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 59 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2c1Bz6ZyiAMeovOaB:-Mr2c1C-9OBOjeaoaRuu:b-1542dn) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L59)):*
> ```
> 	for (size_t i = 0; i < sizeof(not_aligned_data) / sizeof(not_aligned_data[0]); i++) {
> 		UT_ASSERTeq(buf[i], not_aligned_data[i]);
> 	}
> ```
here we itarate 2 times, but we allocated 16 elements of size `size_t` instead of 2.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 78 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1h9fR0QlupE3EbG0v:-Mr2cd5n69p9hVPp0_nq:b8ohhrg) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you should rather check if ret is ok, instead of returning it...?
</blockquote></details>

it was approach for returning statuses and comparing it at the end of execution with information "how many tests failed".
```cpp
ret += test1();
ret += test2();
ret += test3();
printf("%d test(s) failed\n", ret);
```
Generally we don't use returned value, so I understand you POV.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 89 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fHub-5xLtCvU_ol_:-Mr2ddNVAgyWK7x7NQQA:bwqo4qh) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, yet another approach to create/extend a file :smile: we have to clean it up and unify between our tests (to be done next sprint - pls add an XXX)
</blockquote></details>

I like @karczex approach for this. Also method with `ftruncate()` is better than creating file with `dd` that can be a little tricky, it forces user to do external job, I know, it's just a test, but.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2cwOt4P6yaI3cpQIz:-Mr2cwOt4P6yaI3cpQJ-:b-6wijtk) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L109)):*
> ```
> 	pmemstream_delete(&stream);
> 	pmem2_map_delete(&map);
> ```
dead code :)


<!-- Sent from Reviewable.io -->

2021-12-16 14:35 UTC, KFilipek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 7 files reviewed, 24 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/pmemstream_memcpy.cpp, line 103 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2eaUx6wv2-UDvoHrb:-Mr2eaUyBuvI5TQR6lQi:b-jfrmy1) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L103)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	return run_test([&] {
> 		test_basic(stream);
> 		test_not_aligned_array(stream);
> 		property_tests(stream);
> 	});
> ```
</details>

Maybe it should do the job:
```cpp
auto ret = run_test([&] {
 		test_basic(stream);
 		test_not_aligned_array(stream);
 		property_tests(stream);
});
pmemstream_delete(&stream);
pmem2_map_delete(&map);
return ret;
```


<!-- Sent from Reviewable.io -->

2021-12-16 14:39 UTC, karczex commented
___
*[tests/unittest/pmemstream_memcpy.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2ffeG-8EDHiXLgzgC:-Mr2ffeG-8EDHiXLgzgD:bro2ql1) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L34)):*
> ```cpp
> 	size_t d[] = {21, 22, 23, 24};
> 	size_t e[] = {31, 32, 33, 34, 35, 36, 37, 38};
> 	bar = (struct foo *)malloc(sizeof(struct foo));
> ```

should be new 


<!-- Sent from Reviewable.io -->

2021-12-16 14:55 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 7 files reviewed, 25 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/pmemstream_memcpy.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2ffeG-8EDHiXLgzgC:-Mr2jFeM8Eu_iLNgJw-h:b-3b175x) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L34)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

should be new 
</blockquote></details>

coul be just created on stack ;d


<!-- Sent from Reviewable.io -->

2021-12-16 15:17 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 7 files reviewed, 25 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/common/util.h, line 97 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2o1dQ6MSTXaE7Ieyv:-Mr2o1dQ6MSTXaE7Ieyw:b-myovq5) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L97)):*
> ```objc
> 				chunk.size = size - src_offset;
> 			} else {
> 				chunk.size = tmp_buffer_free_space;
> ```

hm, if tmp_buffer_free_space is == 0 AND (size - src_offset) > CACHELINE_SIZE we could potentially copy more than just a single cachline. E.g. if size - src_offset = 500, we can just copy (7 * 64) bytes at once. 
___
*[src/common/util.h, line 102 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2kSNS7LDqynY-juim:-Mr2kSNS7LDqynY-juin:b-s8yd3p) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L102)):*
> ```objc
> 			if (chunk.size == CACHELINE_SIZE) {
> 				chunk.ptr = src + src_offset;
> 			} else {
> ```

could you add assert(chunk.size < CACHE_LINE) here (plus some comment perhaps)? It would make it slightly easier to understand


<!-- Sent from Reviewable.io -->

2021-12-16 15:22 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 7 files reviewed, 29 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2oY0X0TT8IKjsxffq:-Mr2oY0X0TT8IKjsxffr:b-edh19u) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L28)):*
> ```cpp
> static void test_basic(struct pmemstream *stream)
> {
> 	auto *bar = new foo();
> ```

why not on stack?
___
*[tests/unittest/pmemstream_memcpy_pbt.cpp, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2oms_9LgvQ_LCiQt9:-Mr2oms_9LgvQ_LCiQtA:bb7phvt) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_pbt.cpp#L34)):*
> ```cpp
> 
> 		ret += rc::check(
> 			"verify if all data is copyied in correct order", [&](const std::vector<uint64_t> &data) {
> ```

typo
___
*[tests/unittest/pmemstream_memcpy_pbt.cpp, line 42 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2p22LA1l1aw6htuta:-Mr2p22LA1l1aw6htutb:b-ckobft) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_pbt.cpp#L42)):*
> ```cpp
> 				auto res = std::equal(data.begin(), data.end(), output.get());
> 
> 				RC_ASSERT(res == true);
> ```

nit: just (res)
___
*[tests/unittest/pmemstream_memcpy.cpp, line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2pFj36EWdl8plphzU:-Mr2pFj36EWdl8plphzV:b-vi6blr) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L32)):*
> ```cpp
> 	size_t b = 1;
> 	size_t c[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
> 	size_t d[] = {21, 22, 23, 24};
> ```

it would be ggod to have some test where some of the arrays are longer than a cacheline (and even multiple cachelines) - perhaps a rapidcheck test?


<!-- Sent from Reviewable.io -->

2021-12-16 23:22 UTC, KFilipek reviewed
> Reviewed 2 of 5 files at r1, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 5 of 7 files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dCvP2gWlllEuHg2I:-Mr45WR60Dh-KLOea84h:bks5krl) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream.c#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not required anymore (included in internal.h), same as libpmemstream.h
</blockquote></details>

Good practice is to include what you need and not depend on what other headers include.
https://stackoverflow.com/questions/15420891/header-files-and-include-best-practice
___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr4RCjP89jm54pJeDbt:bgql124) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

variable length array is an extension, not supported by the standard I think (I belive argc is not a compile time constant in this context). 
</blockquote></details>

AFAIK array length is correct only for not dynamically allocated arrays, here compiler can deduct the length of array.
Source: 
http://cslabcms.nju.edu.cn/problem_solving/images/c/cc/The_C_Programming_Language_%282nd_Edition_Ritchie_Kernighan%29.pdf
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2oY0X0TT8IKjsxffq:-Mr4Wzb7BkMsA26tActc:bx281g7) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not on stack?
</blockquote></details>

why not unique_ptr? xD


<!-- Sent from Reviewable.io -->

2021-12-17 08:54 UTC, karczex commented
___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr6ZvSe1pwvivXEc85b:bwrqsps) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

AFAIK array length is correct only for not dynamically allocated arrays, here compiler can deduct the length of array.
Source: 
http://cslabcms.nju.edu.cn/problem_solving/images/c/cc/The_C_Programming_Language_%282nd_Edition_Ritchie_Kernighan%29.pdf
</blockquote></details>

In this context argc is compiletime, as it's computed by COUNT macro. Possibly there may be some problem if someone call pmemstream_memcpy_impl directly, instead of calling it via pmemstream_memcpy macro. 
Good catch. thx.


<!-- Sent from Reviewable.io -->

2021-12-17 09:42 UTC, karczex commented
___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr6k2CK2f_l2c_G9bXi:b-w7v76p) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

In this context argc is compiletime, as it's computed by COUNT macro. Possibly there may be some problem if someone call pmemstream_memcpy_impl directly, instead of calling it via pmemstream_memcpy macro. 
Good catch. thx.
</blockquote></details>

Actually variable length array is defined in standard as conditional feature, that compilers need not support. 

I wonder, why c standard has conditional features. It's extremely tricky :/ 


<!-- Sent from Reviewable.io -->

2021-12-17 13:25 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 5 of 7 files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr7YvhC2QbHL4f9HEIl:b-mnqk5u) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Actually variable length array is defined in standard as conditional feature, that compilers need not support. 

I wonder, why c standard has conditional features. It's extremely tricky :/ 
</blockquote></details>

Yeah, I think we should change this (perhaps to a static array of size 16?) I know that argc comes from a compile time context but `const size_t args` is not compile time constant itself - and it might be a problem.

Do we even need to have this array? Can't we just do mempcy with va_start/va_end?


<!-- Sent from Reviewable.io -->

2021-12-20 08:52 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 5 of 7 files reviewed, 30 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/common/util.h, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-MrM1H9j4b5xycUr9Uti:-MrM1H9j4b5xycUr9Utj:bnl7qz1) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L52)):*
> ```objc
> #define COUNT_I(_, _16, _15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, X, ...) X
> 
> int pmemstream_memcpy_impl(pmem2_memcpy_fn pmem2_memcpy, void *destination, const size_t argc, ...)
> ```

This function should either be static inline (probably not) or implemented in util.c 


<!-- Sent from Reviewable.io -->

2021-12-20 16:40 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 0 of 8 files reviewed, 25 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dCvP2gWlllEuHg2I:-Mr6nP9N59hsOPFslPdl:bhq6jv6) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream.c#L11)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Good practice is to include what you need and not depend on what other headers include.
https://stackoverflow.com/questions/15420891/header-files-and-include-best-practice
</blockquote></details>

Argumentum ad stackoverflowum :) but I agree with it :) 
Done.
___
*[src/common/util.h, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dszy9N-8jmi9ioEG:-MrNNi5x2TkWeUO3rSr_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant now
</blockquote></details>

Done.
___
*[src/common/util.h, line 73 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1eCVJ3O1qCT9XjZjd:-Mr2B4QR5qKAErUoYTST:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L73)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by "memcpy"? perhaps be more accurate, e.g., "Do the memcpy" :wink: at first I thought this comment is only for the struct
</blockquote></details>

Done.
___
*[src/common/util.h, line 80 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1jFyW5PEqkHie6-0W:-Mr2BVvU9z_OsXpV7xz5:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd personally switch the names (dest <> destination) - "destination" is used more frequently in here, so perhaps it'd be easier to have it shorter below
</blockquote></details>

Done.
___
*[src/common/util.h, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-MrM1H9j4b5xycUr9Uti:-MrNhi6X2Jgn-5qS8u8z:bvel5vk) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This function should either be static inline (probably not) or implemented in util.c 
</blockquote></details>

moved to libpmemstream.c. 
Done.
___
*[src/common/util.h, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2TuUY6FKRmMBgRhHz:-Mr7KN3F-pKt9GgPVyCk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L63)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Actually variable length array is defined in standard as conditional feature, that compilers need not support. 

I wonder, why c standard has conditional features. It's extremely tricky :/ 
</blockquote></details>

Done.
___
*[src/common/util.h, line 97 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2o1dQ6MSTXaE7Ieyv:-MrNNZjU2ux0Fk6JOV1z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

hm, if tmp_buffer_free_space is == 0 AND (size - src_offset) > CACHELINE_SIZE we could potentially copy more than just a single cachline. E.g. if size - src_offset = 500, we can just copy (7 * 64) bytes at once. 
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2oY0X0TT8IKjsxffq:-Mr6eoC_AN0R57ucQTvD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

why not unique_ptr? xD
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 56 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2_fVK7uMRtQ9hHr-0:-Mr6g1nq6hF48dc1bHKY:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L56)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> sizeof(not_aligned_data)
> ```
if you mean no. of elements so it should be: 
```cpp
size_t buf[sizeof(not_aligned_data)/sizeof(*not_aligned_data)]
```
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 79 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2aBXDC1BBdC8_UQY9:-Mr6g3tR9RUZPEDc_Zuu:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L79)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

1. typo: lambda
2. Add "XXX:" to don't miss it in the future
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 82 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2aJnQ1-w6dg7btkYr:-Mr6g8Cn4tnMJOI0L2Ev:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L82)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

unnecessary tabs after double '/'
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1evVEDtWdsv-o0U_c:-Mr6gWkMAA0MjENWtJVc:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, why CI didn't find this? :thinking: funny, we don;t run check-license properly I guess :smile:  
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1eylE9L1dJDs3oMtp:-Mr6gY3m8OjZ83MeNSTT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could clean up these includes a little :wink: 
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1f5h_6y2BwgR0rY3J:-Mr6gyWjCbey09XWvoWg:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L16)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

if you think `foo` you automaticaly look for a `bar`somewhere :D
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1fAGh3gzhYAXYsrBO:-Mr6h0RME4YoEJEhgpYU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/tests/unittest/pmemstream_memcpy.cpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

great
</blockquote></details>

Done.
___
*[tests/unittest/pmemstream_memcpy.cpp [...]

2021-12-20 17:05 UTC, igchor requested changes
> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 3 of 8 files reviewed, 30 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1dCvP2gWlllEuHg2I:-MrNjtcW8IDq2C5U8Pes:b-hlf5f0) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/libpmemstream.c#L11)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Argumentum ad stackoverflowum :) but I agree with it :) 
Done.
</blockquote></details>

I'd argue that it does not make much sense for things like pmem2 (it is a hard dependency for structs in libpmemstream_internal and we cannot replace it with anything else). But anyway, it's fine.
___
*[src/libpmemstream.c, line 324 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNnG6GD3rGORijqUIY:-MrNnG6GD3rGORijqUIZ:bimka6b) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L324)):*
> ```C
> 
> 	struct buffer {
> 		struct sized_ptr head;
> ```

I don't quite understand what are those head, body and tail pointers. Can you add some comments?
___
*[src/libpmemstream.c, line 338 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNkcUk9rF7r8qMIo4g:-MrNkcUk9rF7r8qMIo4h:bhai3tu) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L338)):*
> ```C
> 	/* Parse variadic arguments */
> 	va_list argv;
> 	const size_t parts = argc / 2;
> ```

nit: maybe some assert for `argc % 2 == 0`?
___
*[src/libpmemstream.c, line 344 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNkjXH4Ll2vKS54_Ol:-MrNkjXH4Ll2vKS54_Om:b-97oyzr) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L344)):*
> ```C
> 	for (size_t i = 0; i < parts; i++) {
> 
> 		struct sized_ptr input = {0}; // {} ?
> ```

`// {} ?` ?
___
*[src/libpmemstream.c, line 363 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNl5puCL8nBMIQMraH:-MrNl5puCL8nBMIQMraI:blhq564) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L363)):*
> ```C
> 		buff.body.size = input.size - buff.head.size - buff.tail.size;
> 
> 		assert(buff.head.size >= 0);
> ```

it can't ever fail - size is unsigned  integer
___
*[src/libpmemstream.c, line 376 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNm8bF-WBJl3yjX7U4:-MrNm8bF-WBJl3yjX7U5:b-7mkvry) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L376)):*
> ```C
> 		/* Copy head to temporary buffer */
> 		if (buff.head.size > 0) {
> 			memcpy(tmp_buffer.array + tmp_buffer.offset / sizeof(tmp_buffer.array[0]), buff.head.ptr,
> ```

this division is not necessary
___
*[src/libpmemstream.c, line 392 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNmsBP05h_8A16K3Jq:-MrNmsBP05h_8A16K3Jr:b-bksu5j) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L392)):*
> ```C
> 
> 		/* Copy body to pmem */
> 		if (buff.body.size > 0) {
> ```

Is it always this branch whish executed as last op? Is it possible that this code is skipped and only the above one is executed? (if so, we miss a drain).
___
*[src/libpmemstream.map, line 24 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNjQ3CCT-w6sCN4wGd:-MrNjQ3CCT-w6sCN4wGe:b-dpmt81) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.map#L24)):*
> ```
> 		pmemstream_region_allocate;
> 		pmemstream_region_free;
> 		pmemstream_memcpy_impl;
> ```

do we want to expose it?
___
*[src/common/util.h, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-MrM1H9j4b5xycUr9Uti:-MrNiWYx3J8crUm5UC2e:b9h8vuo) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/src/common/util.h#L52)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

moved to libpmemstream.c. 
Done.
</blockquote></details>

Where is the function declaration? I think it would make more sense to have function declaration and the macro here, and implementation in util.c  instead of libpmemstream.c
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2oY0X0TT8IKjsxffq:-MrNiq6t0gMwcI-BBQWy:b-fo7dex) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L28)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: that's pretty funny syntax and it's quite close to https://en.wikipedia.org/wiki/Most_vexing_parse ;d you can just write `aligned_struct to_fill`
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 56 at r3](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr2_fVK7uMRtQ9hHr-0:-MrNj2m-D_brcxn6_ZJ_:bqwr5ka) ([raw file](https://github.com/pmem/pmemstream/blob/1cf92c1eab2e7ec575abe5ee5dc561acb519762c/tests/unittest/pmemstream_memcpy_basic.cpp#L56)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: for future:
```
std::vector<size_t> not_aligned_data = {0x1, 0x2};
std::vector<size_t> buf(not_aligned_data.size());
```


<!-- Sent from Reviewable.io -->

2021-12-20 17:46 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r2, 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 7 of 8 files reviewed, 23 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNq8CG5tNPcyxK0uJx):*
the commit description is a bit unlike you :P (a bit too short? :wink: )
___
*[src/common/util.h, line 80 at r1](https://reviewable.io/reviews/pmem/pmemstream/30#-Mr1jFyW5PEqkHie6-0W:-MrNqy_O9hxqtDPknsz0:b2nid0f) ([raw file](https://github.com/pmem/pmemstream/blob/42075e053bfd64b9532e4447e535798b756af0e9/src/common/util.h#L80)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 7 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNwCuQCI-fprg5yN5c:-MrNwCuQCI-fprg5yN5d:bb7lgjf) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/tests/unittest/pmemstream_memcpy_basic.cpp#L7)):*
> ```cpp
> #include "unittest.hpp"
> 
> #include <rapidcheck.h>
> ```

nope
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 9 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNwRJg04rZerCdDREi:-MrNwRJh5xOzL6PvW9Az:b-7m313w) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/tests/unittest/pmemstream_memcpy_basic.cpp#L9)):*
> ```cpp
> #include <rapidcheck.h>
> 
> #include <algorithm>
> ```

nope?
___
*[tests/unittest/pmemstream_memcpy_basic.cpp, line 14 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNwSCY-kmJ3VFkV1XH:-MrNwSCY-kmJ3VFkV1XI:bb7lgjf) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/tests/unittest/pmemstream_memcpy_basic.cpp#L14)):*
> ```cpp
> #include <fstream>
> #include <memory>
> #include <vector>
> ```

nope
___
*[tests/unittest/pmemstream_memcpy_pbt.cpp, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNszZP08jWa0PZ5IBw:-MrNszZP08jWa0PZ5IBx:bu33ksr) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/tests/unittest/pmemstream_memcpy_pbt.cpp#L3)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

a short description pls


<!-- Sent from Reviewable.io -->

2021-12-20 17:56 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 7 of 8 files reviewed, 23 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 324 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrNnG6GD3rGORijqUIY:-MrNyRIZ2vMBkrKKoHPN:b-sxymiv) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L324)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't quite understand what are those head, body and tail pointers. Can you add some comments?
</blockquote></details>

To be honest, I think you could simplify this a lot if you didn;t use those helper structures, tmp_buffer should be enough. Somthing like this perhaps? https://godbolt.org/z/7YP4eMseG (it probably does not work for all cases but just shows an idea).


<!-- Sent from Reviewable.io -->

2021-12-21 08:59 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/30)* status: 7 of 8 files reviewed, 24 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 316 at r4](https://reviewable.io/reviews/pmem/pmemstream/30#-MrR6yXxB5HMIU4alA_D:-MrR6yXxB5HMIU4alA_E:blq4uk0) ([raw file](https://github.com/pmem/pmemstream/blob/08c2ac3228663357b3d6d5cf5952826e9322cf14/src/libpmemstream.c#L316)):*
> ```C
> }
> 
> int pmemstream_memcpy_impl(pmem2_memcpy_fn pmem2_memcpy, void *destination, const size_t argc, ...)
> ```

Since we don't want to enforce any alignment after all, this means that destination is not necessary cacheline-aligned. This means that there will still be partial cacheline writes in this code. 

For example:

```
dst = (void*)8;
memcpy(dst, tmp_buffer.data, CACHELINE_SIZE); // this will result in write to 2 cacheline: one starting at address 8 ,one starting at address 64
```

Please look at this descriptions: https://github.com/pmem/pmdk/blob/adcff83ca3d08e448479e89e6cea4e1986d505e1/src/libpmem/pmem.c#L33 It states that nontemporal is only used for the aligned part (in the example above pmem2_memcpy would not use nontemporal at all).

To fix this, I would suggest to first copy the data directly from src to dst until dst is aligned (passing NONTEMPORAL flag or not, doesn't matter). And only then considering filling up the tmp_buffer.


<!-- Sent from Reviewable.io -->

2022-02-23 15:24 UTC, closed without merging