Fix offset checking in pmemstream_entry_iterator_next
pmem/pmemstream pull request #40
Opened 2021-12-20 11:28 UTC by igchor

We only checked that entry span starts within a region. This
new check also makes sure that all the metadata are within the
region.

2021-12-20 11:29 UTC, igchor commented
@KFilipek if you were to also fix this in your PR, I can close this one.

2021-12-20 14:54 UTC, KFilipek requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/libpmemstream.c, line 294 at r1](https://reviewable.io/reviews/pmem/pmemstream/40#-MrNK-604m93nRzC7qsj:-MrNK-617PHOchbDetVQ:bf7y7d3) ([raw file](https://github.com/pmem/pmemstream/blob/20ee5d5ffb44de0dd3ef183c71ff55766866e620/src/libpmemstream.c#L294)):*
> ```C
> 	}
> 
> 	if (rt.data >= region_rt.data + region_rt.region.size) {
> ```

I think that we should check that we exceeded, we can place metadata at the end of region. Then empty span can be created, but the other types shouldn't.

```
	if (rt.data > region_rt.data + region_rt.region.size) {
		return -1;
	}
```



_Code quote:_
```C
	if (rt.data >= region_rt.data + region_rt.region.size) {
		return -1;
	}
```


<!-- Sent from Reviewable.io -->

2021-12-20 14:54 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 294 at r1](https://reviewable.io/reviews/pmem/pmemstream/40#-MrNJFRz7d1Mnb6NcVnr:-MrNJFRz7d1Mnb6NcVns:bkzlojp) ([raw file](https://github.com/pmem/pmemstream/blob/20ee5d5ffb44de0dd3ef183c71ff55766866e620/src/libpmemstream.c#L294)):*
> ```C
> 	}
> 
> 	if (rt.data >= region_rt.data + region_rt.region.size) {
> ```

1. we actually only check if the beginning of the data fits within the region
2. .. and why are we even doing this check here? just to check if runtime was properly created... and if iter didn't move out of the region? I guess we could add a short comment here


<!-- Sent from Reviewable.io -->

2021-12-20 15:09 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 294 at r1](https://reviewable.io/reviews/pmem/pmemstream/40#-MrNK-604m93nRzC7qsj:-MrNKmUp8kNc9ixe3e4i:b5uriga) ([raw file](https://github.com/pmem/pmemstream/blob/20ee5d5ffb44de0dd3ef183c71ff55766866e620/src/libpmemstream.c#L294)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think that we should check that we exceeded, we can place metadata at the end of region. Then empty span can be created, but the other types shouldn't.

```
	if (rt.data > region_rt.data + region_rt.region.size) {
		return -1;
	}
```
</blockquote></details>

You're right that should `>` if we allow span with 0-sized data.
___
*[src/libpmemstream.c, line 294 at r1](https://reviewable.io/reviews/pmem/pmemstream/40#-MrNJFRz7d1Mnb6NcVnr:-MrNLBGa0mL4bloFAJoU:bqo1t53) ([raw file](https://github.com/pmem/pmemstream/blob/20ee5d5ffb44de0dd3ef183c71ff55766866e620/src/libpmemstream.c#L294)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. we actually only check if the beginning of the data fits within the region
2. .. and why are we even doing this check here? just to check if runtime was properly created... and if iter didn't move out of the region? I guess we could add a short comment here
</blockquote></details>

1. True this checks is just to make sure that metadata fits into the region.
2. Fair point, this should not happen during normal execution (if this fails, we either have corrupted data or buggy append). I changed it to assert but thb, I think this assert should be called after entry validation (by @kfilipek).


<!-- Sent from Reviewable.io -->

2021-12-20 15:19 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 294 at r1](https://reviewable.io/reviews/pmem/pmemstream/40#-MrNJFRz7d1Mnb6NcVnr:-MrNPz7sDDR-Z4nLTPzx:brxe1dl) ([raw file](https://github.com/pmem/pmemstream/blob/20ee5d5ffb44de0dd3ef183c71ff55766866e620/src/libpmemstream.c#L294)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

1. True this checks is just to make sure that metadata fits into the region.
2. Fair point, this should not happen during normal execution (if this fails, we either have corrupted data or buggy append). I changed it to assert but thb, I think this assert should be called after entry validation (by @kfilipek).
</blockquote></details>

yeah, it makes sense, we can move this after Krzysiek's PR


<!-- Sent from Reviewable.io -->

2021-12-21 09:28 UTC, igchor commented
I removed my check and left the one added by @KFilipek - and as he initially suggested, it makes more sense to have is as assert. If we were to return an error for corrupted size we would also need to clear rest of the region. For now, it;s simpler to just assert.

2021-12-21 11:21 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40#-:-MrRiHXm21tourfwBC6w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-12-21 15:34 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/40#-:-MrScMAI9Xm6e-6Xt9sl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-12-21 15:35 UTC, merged