Add example to print content of stream created by 01-iterate example
pmem/pmemstream pull request #46
Opened 2021-12-21 16:05 UTC by KFilipek

This example prints stream layout as tree view.

2021-12-21 16:42 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSq5IXEczAI-KiR45-:-MrSq5IXEczAI-KiR450:b-nippaq) (no related file):*
pls, add a link to https://github.com/pmem/pmemstream/issues/33

---
___
*[examples/02-visual_iterator/main.cpp, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpaxj0lQt9hmaGx3A:-MrSpaxj0lQt9hmaGx3B:b-lhl089) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L5)):*
> ```cpp
> 
> #include "libpmemstream.h"
> #include <cassert>
> ```

is it used? pls clean includes, if needed
___
*[examples/02-visual_iterator/main.cpp, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr8TP6NF4EyQw35zi:-MrSr8TP6NF4EyQw35zj:bfm2xbf) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L15)):*
> ```cpp
> #include <unistd.h>
> 
> static struct pmem2_map *map_open(const char *file)
> ```

perhaps this could be moved to an "examples helper" :wink: 
___
*[examples/02-visual_iterator/main.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpj0S2k2TaxB6VZx1:-MrSpj0S2k2TaxB6VZx2:b7lkt3q) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L57)):*
> ```cpp
> 
> /**
>  * This example prints a stream from map2 source created by a 01-iterate example, just prints its content
> ```

is the part `, just prints its content` needed?
___
*[examples/02-visual_iterator/main.cpp, line 59 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpmoC3Ld9Oi38ZYjp:-MrSpmoC3Ld9Oi38ZYjq:b-264vyi) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L59)):*
> ```cpp
>  * This example prints a stream from map2 source created by a 01-iterate example, just prints its content
>  *
>  * It accepts a path to already existing file filled with the 01-iterate data.
> ```

you can add an example usage, something like:

```
./01-iterate/main XYZ
./02/main XYZ
```
___
*[examples/02-visual_iterator/main.cpp, line 76 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSqHfnCI3lq20YzyaU:-MrSqHfnCI3lq20YzyaV:b-pghem4) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L76)):*
> ```cpp
> 	struct pmemstream *stream;
> 	int ret = pmemstream_from_map(&stream, 4096, map);
> 	if (ret == -1) {
> ```

perhaps already `!= 0` for this to work with future exit codes
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr-GiBF7YyTjmQvgf:-MrSr-GiBF7YyTjmQvgg:bdytbhn) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
> ```cpp
> 				  << " " << std::dec << entry_length << "bytes ";
> 			for (size_t i = 0; i < entry_length; i++) {
> 				printf("%.2X ", (int)d[i]);
> ```

A mix of printf's and cout's...?


<!-- Sent from Reviewable.io -->

2021-12-21 16:54 UTC, igchor requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 100 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSu8ABCfHusfEFZqAu:-MrSu8ABCfHusfEFZqAv:b5gisqg) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L100)):*
> ```cpp
> 			return ret;
> 		}
> 		printf("%s region%ld\n", inner_pointers[0].data(), region_id++);
> ```

please print also region size
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr-GiBF7YyTjmQvgf:-MrStxlx0vCZpnNPORWH:b37852e) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

A mix of printf's and cout's...?
</blockquote></details>

+1, decide on one or the other
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuMBx0xe2E_uYkyRL:-MrSuMBx0xe2E_uYkyRM:bvti862) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
> ```cpp
> 				  << " " << std::dec << entry_length << "bytes ";
> 			for (size_t i = 0; i < entry_length; i++) {
> 				printf("%.2X ", (int)d[i]);
> ```

nit: it might be nice to give user an option (as optional parameter to this example's binary) - whether he wants to print binary data (like you do right now) or print data as string (just std::cout << std::string(d, entry_length) << std::endl;


<!-- Sent from Reviewable.io -->

2021-12-21 16:55 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuuY72OfVh-o6zGg5:-MrSuuY72OfVh-o6zGg6:b-lzeqqv) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L54)):*
> ```cpp
> 
> static vector<string> inner_pointers = { "├── ", "│   " };
> static vector<string> final_pointers = { "└── ", "    " };
> ```

do you use it anywhere?


<!-- Sent from Reviewable.io -->

2021-12-22 07:49 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuuY72OfVh-o6zGg5:-MrW5sR3EISH5Lsx4ziw:b4czrkw) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

do you use it anywhere?
</blockquote></details>

I would say, it's not worth to implement any logic, which may use it. 
___
*[examples/02-visual_iterator/main.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpj0S2k2TaxB6VZx1:-MrW4QtRAPBgPGwCWLmJ:bfn2urm) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is the part `, just prints its content` needed?
</blockquote></details>

It prints content of any already created stream file. 
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr-GiBF7YyTjmQvgf:-MrW5JxO79E-WXcoKqcx:b-fh6rdf) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1, decide on one or the other
</blockquote></details>

In this case, printf() probably would be better. 
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuMBx0xe2E_uYkyRL:-MrW5VV19R2TMTaNjZ7u:b32v57) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: it might be nice to give user an option (as optional parameter to this example's binary) - whether he wants to print binary data (like you do right now) or print data as string (just std::cout << std::string(d, entry_length) << std::endl;
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-12-22 10:29 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuuY72OfVh-o6zGg5:-MrWfzDt3Zgg-e3vBW_u:b-7kofmb) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would say, it's not worth to implement any logic, which may use it. 
</blockquote></details>

So, remove it I guess?


<!-- Sent from Reviewable.io -->

2021-12-22 14:47 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSq5IXEczAI-KiR45-:-MrWogDG-5sFy2F9Zlix:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls, add a link to https://github.com/pmem/pmemstream/issues/33
</blockquote></details>

Done.

---
___
*[examples/02-visual_iterator/main.cpp, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpaxj0lQt9hmaGx3A:-MrXWGig3pLIGd4TmzLb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it used? pls clean includes, if needed
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr8TP6NF4EyQw35zi:-MrXWPe33IY7kIycqwEt:b3juql3) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps this could be moved to an "examples helper" :wink: 
</blockquote></details>

Done. Sure, please open issue.
___
*[examples/02-visual_iterator/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuuY72OfVh-o6zGg5:-MrXWYY_EziOOn2oBXk6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, remove it I guess?
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpj0S2k2TaxB6VZx1:-MrXXtjy2fM5prisEkPc:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L57)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It prints content of any already created stream file. 
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 59 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSpmoC3Ld9Oi38ZYjp:-MrXXbqtDQbshPKOON2k:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add an example usage, something like:

```
./01-iterate/main XYZ
./02/main XYZ
```
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 76 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSqHfnCI3lq20YzyaU:-MrXY5la7kULwnMSE_Pl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L76)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps already `!= 0` for this to work with future exit codes
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSr-GiBF7YyTjmQvgf:-MrX_XtCE8L9WeZS9il4:b-k1wfgn) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

In this case, printf() probably would be better. 
</blockquote></details>

Done. cout and printing mixed data is a nightmare.
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuMBx0xe2E_uYkyRL:-MrXamL9BKK7E2g2rqfc:b32v57) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-12-22 15:05 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuMBx0xe2E_uYkyRL:-MrXf3bV4McWymf2GgfB:b-4zjj12) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Will you add it in this PR?


<!-- Sent from Reviewable.io -->

2021-12-22 16:44 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/02-visual_iterator/main.cpp, line 100 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSu8ABCfHusfEFZqAu:-MrXelT-DOqVH2yFaUsH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L100)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please print also region size
</blockquote></details>

Done.
___
*[examples/02-visual_iterator/main.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/pmemstream/46#-MrSuMBx0xe2E_uYkyRL:-MrXz63mBo28Fis4efGr:bb74ce2) ([raw file](https://github.com/pmem/pmemstream/blob/add92dc8b3484e02bfa2cbc09cf50cbd023d86bc/examples/02-visual_iterator/main.cpp#L109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Will you add it in this PR?
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2021-12-22 17:07 UTC, karczex commented
___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/46#-MrY5sB84CPV385vnuOO):*
oO 
Do we need test if all functions defined in map file are implemented? (spoiler: we do) 


<!-- Sent from Reviewable.io -->

2021-12-22 17:19 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46#-:-MrY8y3UA7TFNUMtW0ZE:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-12-22 19:00 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/46#-:-MrYVaooEzs9UsBojwLN:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/46#-MrY5sB84CPV385vnuOO):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

oO 
Do we need test if all functions defined in map file are implemented? (spoiler: we do) 
</blockquote></details>

We even have this planned for this sprint ;d


<!-- Sent from Reviewable.io -->

2021-12-22 19:01 UTC, merged