Refactor pmemstream_span_get_runtime
pmem/pmemstream pull request #48
Opened 2021-12-22 16:16 UTC by karczex

Split pmemstream_span_get_entry_runtime() into smaller getters, and call
it accordingly if it is possible.

2021-12-22 19:10 UTC, igchor requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/48)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[src/libpmemstream.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYWSsc6i61OfnsKUQe:-MrYWSsc6i61OfnsKUQf:b-uxcnhi) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L72)):*
> ```C
> static struct pmemstream_span_runtime pmemstream_span_get_empty_runtime(struct pmemstream *stream, uint64_t offset)
> {
> 	pmemstream_span_bytes *span = (pmemstream_span_bytes *)pmemstream_offset_to_ptr(stream, offset);
> ```

I think you should verify if offset is aligned in all those functions (they can be called directly):

```
assert(offset % sizeof(pmemstream_span_bytes) == 0);
```

... or maybe we should have extra function? `pmemstream_offset_to_ptr` (or rename it to `pmemstream_offset_to_data_ptr`) would return uint8_t* and `pmemstream_offset_to_span_ptr`would return pmemstream_span_bytes* and do the assert internally?
___
*[src/libpmemstream.c, line 269 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYXtf5Ctn4QS9z_Mo2:-MrYXtf5Ctn4QS9z_Mo3:b-evght4) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L269)):*
> ```C
> void *pmemstream_entry_data(struct pmemstream *stream, struct pmemstream_entry entry)
> {
> 	struct pmemstream_span_runtime entry_sr = pmemstream_span_get_runtime(stream, entry.offset);
> ```

you can use pmemstream_span_get_entry_runtime here
___
*[src/libpmemstream.c, line 278 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYXxG3BAmV3VyIVMfg:-MrYXxG3BAmV3VyIVMfh:b-evght4) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L278)):*
> ```C
> size_t pmemstream_entry_length(struct pmemstream *stream, struct pmemstream_entry entry)
> {
> 	struct pmemstream_span_runtime entry_sr = pmemstream_span_get_runtime(stream, entry.offset);
> ```

you can use pmemstream_span_get_entry_runtime here
___
*[src/libpmemstream.c, line 326 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYY5Gc2qsEQcSA6cdt:-MrYY5Gc2qsEQcSA6cdu:b9uv7yo) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L326)):*
> ```C
> 				  struct pmemstream_region region)
> {
> 	struct pmemstream_span_runtime rt = pmemstream_span_get_runtime(stream, region.offset);
> ```

you can use pmemstream_span_get_region_runtime here


<!-- Sent from Reviewable.io -->

2021-12-23 09:34 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/48)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYWSsc6i61OfnsKUQe:-MraBZ8vAJI6UzaOkIaU:b3e3si) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should verify if offset is aligned in all those functions (they can be called directly):

```
assert(offset % sizeof(pmemstream_span_bytes) == 0);
```

... or maybe we should have extra function? `pmemstream_offset_to_ptr` (or rename it to `pmemstream_offset_to_data_ptr`) would return uint8_t* and `pmemstream_offset_to_span_ptr`would return pmemstream_span_bytes* and do the assert internally?
</blockquote></details>

I like the idea of hiding tricky casts :) 
Done.
___
*[src/libpmemstream.c, line 269 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYXtf5Ctn4QS9z_Mo2:-Mra9sKb1etwQDYylfAP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L269)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you can use pmemstream_span_get_entry_runtime here
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 278 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYXxG3BAmV3VyIVMfg:-Mra9t8VDAx24qcRIj4d:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L278)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you can use pmemstream_span_get_entry_runtime here
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 326 at r1](https://reviewable.io/reviews/pmem/pmemstream/48#-MrYY5Gc2qsEQcSA6cdt:-MraBJze0W1d64jgzXA1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7bfd82afbff9859a41c368848452a4205bb400d6/src/libpmemstream.c#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you can use pmemstream_span_get_region_runtime here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-23 13:37 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/48#-:-MrbVZIv1QMFqzp9Qc0P:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-12-23 14:52 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/48#-:-Mrblrmi64JHALZ5QJZc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-12-23 14:52 UTC, merged