Add const keyword for those arguments that are not modified
pmem/pmemstream pull request #59
Opened 2022-01-05 13:39 UTC by KFilipek

2022-01-05 14:28 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-MseciCXD6sT0gkNwM11):*
I believe you touched only pointer types


<!-- Sent from Reviewable.io -->

2022-01-10 09:04 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59#-:-Mt2Dtas0_I2VZxX6S_T:bnfp4nl)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-10 10:24 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 1 of 9 files reviewed, 12 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2ULb19Se4elkCwjvK:-Mt2ULb19Se4elkCwjvL:b9alt55) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/iterator.c#L18)):*
> ```C
> 	}
> 
> 	iter->stream = (struct pmemstream *)stream;
> ```

Why you cast to non-const here? If stream is const then you should make `iter->stream` const either. However, I don't think iterator should accept const stream at this moment (see my comments in the iterator.h header)
___
*[src/iterator.c, line 62 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2UR1q6HhalJvOJIJe:-Mt2UR1q6HhalJvOJIJf:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/iterator.c#L62)):*
> ```C
> 	iter.offset = region_srt.data_offset;
> 	iter.region = region;
> 	iter.stream = (struct pmemstream *)stream;
> ```

same here
___
*[src/region.c, line 102 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Usyp9nSmcz8tiLR_:-Mt2Usyp9nSmcz8tiLRa:b-nerhgo) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L102)):*
> ```C
> }
> 
> void region_contexts_map_remove(const struct region_contexts_map *map, struct pmemstream_region region)
> ```

why it's const? we remove the element from map after all
___
*[src/region.c, line 128 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Ve3X44-0cbwzeOD_:-Mt2Ve3X44-0cbwzeODa:b-nlo9bs) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L128)):*
> ```C
> }
> 
> int region_try_recover_locked(const struct pmemstream *stream, struct pmemstream_region region,
> ```

why const? you are modyfing the stream here
___
*[src/span.c, line 10 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V75z6sdDMAlmOv5I:-Mt2V75z6sdDMAlmOv5J:bq6lgwl) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L10)):*
> ```C
> #include "libpmemstream_internal.h"
> 
> span_bytes *span_offset_to_span_ptr(const struct pmemstream *stream, uint64_t offset)
> ```

either make return value also const or leave parameter as non-const - now you are returning non-const ptr to stream which might be const
___
*[src/span.c, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V1kW6Hd5FYweu_tL:-Mt2V1kW6Hd5FYweu_tM:b-fpt3kj) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L17)):*
> ```C
> }
> 
> void span_create_empty(const struct pmemstream *stream, uint64_t offset, size_t data_size)
> ```

why const? we are actually creating data here
___
*[src/span.c, line 32 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VHrx2mItgxcUg5t-:-Mt2VHry9xSkETG2TKPz:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L32)):*
> ```C
>  * flags may be used to adjust behavior of persisting the data; use 0 for default persist.
>  */
> void span_create_entry(const struct pmemstream *stream, uint64_t offset, const void *data, size_t data_size,
> ```

same here
___
*[src/span.c, line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VJGl8VYUokwqV5O0:-Mt2VJGl8VYUokwqV5O1:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L54)):*
> ```C
> }
> 
> void span_create_region(const struct pmemstream *stream, uint64_t offset, size_t size)
> ```

same here
___
*[src/include/libpmemstream.h, line 38 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VMvE3_Li331aOdoF:-Mt2VMvE3_Li331aOdoG:bsbwe7y) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L38)):*
> ```objc
> // stream owns the region object - the user gets a reference, but it's not
> // necessary to hold on to it and explicitly delete it.
> int pmemstream_region_allocate(const struct pmemstream *stream, size_t size, struct pmemstream_region *region);
> ```

why const? we are modifying the stream inside
___
*[src/include/libpmemstream.h, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VQOx4p7y_NR7q5oD:-Mt2VQOx4p7y_NR7q5oE:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L40)):*
> ```objc
> int pmemstream_region_allocate(const struct pmemstream *stream, size_t size, struct pmemstream_region *region);
> 
> int pmemstream_region_free(const struct pmemstream *stream, struct pmemstream_region region);
> ```

same here
___
*[src/include/libpmemstream.h, line 96 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VkKZ53Huc-6EFNMf:-Mt2VkKZ53Huc-6EFNMg:b4ldt4p) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L96)):*
> ```objc
> // truncation can only affect regions.
> 
> int pmemstream_region_iterator_new(struct pmemstream_region_iterator **iterator, const struct pmemstream *stream);
> ```

Right now, it should not be const - iterator can perform recovery.

This can be const after merging https://github.com/pmem/pmemstream/pull/58


<!-- Sent from Reviewable.io -->

2022-01-10 17:25 UTC, KFilipek reviewed
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2ULb19Se4elkCwjvK:-Mt3mY5U6aCZthwYmG29:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/iterator.c#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why you cast to non-const here? If stream is const then you should make `iter->stream` const either. However, I don't think iterator should accept const stream at this moment (see my comments in the iterator.h header)
</blockquote></details>

Done.
___
*[src/iterator.c, line 62 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2UR1q6HhalJvOJIJe:-Mt3nfIC7Z-ykezBXyDm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/iterator.c#L62)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/region.c, line 102 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Usyp9nSmcz8tiLR_:-Mt3nr4CE1-VU7GPIHtP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L102)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why it's const? we remove the element from map after all
</blockquote></details>

Done.
___
*[src/region.c, line 128 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Ve3X44-0cbwzeOD_:-Mt3nx15ELNqw_Akclkm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L128)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why const? you are modyfing the stream here
</blockquote></details>

Done.
___
*[src/span.c, line 10 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V75z6sdDMAlmOv5I:-Mt3zytSCEj9UJPJu9iu:b-6dzcmg) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

either make return value also const or leave parameter as non-const - now you are returning non-const ptr to stream which might be const
</blockquote></details>

cannot be `const*` because of such usage `span[0]=sth;`
___
*[src/span.c, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V1kW6Hd5FYweu_tL:-Mt4-RFhBgr1WnVNrVQ5:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L17)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why const? we are actually creating data here
</blockquote></details>

Done.
___
*[src/span.c, line 32 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VHrx2mItgxcUg5t-:-Mt4-U5r6tlO4EVtPFoX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L32)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/span.c, line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VJGl8VYUokwqV5O0:-Mt4-WE9BQ4-uL5Wc6di:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/include/libpmemstream.h, line 38 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VMvE3_Li331aOdoF:-Mt40Ao28B_moBr6dZzJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L38)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why const? we are modifying the stream inside
</blockquote></details>

Done.
___
*[src/include/libpmemstream.h, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VQOx4p7y_NR7q5oD:-Mt40AaF5dVdtzum3sqJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/include/libpmemstream.h, line 96 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2VkKZ53Huc-6EFNMf:-Mt40VHO5nkHbo3Zrr-F:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/include/libpmemstream.h#L96)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right now, it should not be const - iterator can perform recovery.

This can be const after merging https://github.com/pmem/pmemstream/pull/58
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 17:27 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-MseciCXD6sT0gkNwM11):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you touched only pointer types
</blockquote></details>

You cannot modify arguments passed as a value, so it's obvious.


<!-- Sent from Reviewable.io -->

2022-01-10 17:47 UTC, igchor requested changes
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 1 of 9 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.h, line 20 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43Ju7--iqPCul8DHP:-Mt43Ju7--iqPCul8DHQ:bfvilet) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.h#L20)):*
> ```objc
> 	struct pmemstream const *stream;
> 	struct pmemstream_region region;
> 	struct pmemstream_region_context *region_context;
> ```

I guess all members can be const (region and region_context too)
___
*[src/iterator.h, line 26 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43P8EEAa2hV7mqVhW:-Mt43P8EEAa2hV7mqVhX:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.h#L26)):*
> ```objc
> struct pmemstream_region_iterator {
> 	struct pmemstream const *stream;
> 	struct pmemstream_region region;
> ```

same here
___
*[src/iterator.c, line 62 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2UR1q6HhalJvOJIJe:-Mt42tB64kAmCR7-gFi4:b7hl5lk) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/iterator.c#L62)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I guess you initialize all of the members this way
___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-Mt438LS-hVOCQELhSPj:bb7r2f0) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
> ```C
> 		/* If region was not yet recovered, validate that entry is correct. If there is any problem, recover the
> 		 * region. */
> 		region_recover((struct pmemstream *)iterator->stream, iterator->region, iterator->region_context, entry);
> ```

why?
___
*[src/libpmemstream_internal.h, line 53 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43ATl1Dct9EnLNwme:-Mt43ATl1Dct9EnLNwmf:b-lyiz24) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/libpmemstream_internal.h#L53)):*
> ```objc
> static inline uint8_t *pmemstream_offset_to_ptr(const struct pmemstream *stream, uint64_t offset)
> {
> 	return (uint8_t *)stream->data->spans + offset;
> ```

return `const uint8_t*` then? It's dangerous to cast it to (uint8_t*) when we don't know where the streams come from.
___
*[src/region.c, line 128 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Ve3X44-0cbwzeOD_:-Mt43YdYDDKw_OydS5Su:b-3dodox) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L128)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

and region_context? region_iterate_and_try_recover will possibly modify region_context->append_offset
___
*[src/region.c, line 114 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43jCN4ioFuqEYZgl6:-Mt43jCN4ioFuqEYZgl7:b-n6rgfw) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/region.c#L114)):*
> ```C
> 
> /* Iterates over entire region. Might perform recovery. */
> static int region_iterate_and_try_recover(const struct pmemstream *stream, struct pmemstream_region region)
> ```

as we discussed, it should not be const right now, this function does recovery (modifies stream)
___
*[src/span.c, line 10 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V75z6sdDMAlmOv5I:-Mt43yK_BT6QIPX0IZaU:bp70l4y) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

cannot be `const*` because of such usage `span[0]=sth;`
</blockquote></details>

You still could have `const struct pmemstream *stream` as param and return `const span_bytes*` by default and just cast it to `span_bytes*` only when necessary (and when you know that stream is not actually const, like in append, it's allowed).

I would prefer actually having const ptr as parameter and return type.
___
*[src/span.c, line 75 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44V8n8uhDoQtpq97m:-Mt44V8n8uhDoQtpq97n:b-83kaym) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L75)):*
> ```C
> struct span_runtime span_get_empty_runtime(const struct pmemstream *stream, uint64_t offset)
> {
> 	span_bytes *span = span_offset_to_span_ptr((struct pmemstream *)stream, offset);
> ```

This is why I would prefer having span_offset_to_span_ptr take and return const ptr. You have `span_bytes *span` here which looks like it can be modified (and it can't in general, it can result in UB).
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-Mt44oaA6WumnHmRKQPZ:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
> ```C
> struct span_runtime span_get_entry_runtime(const struct pmemstream *stream, uint64_t offset)
> {
> 	span_bytes *span = span_offset_to_span_ptr((struct pmemstream *)stream, offset);
> ```

same here
___
*[src/span.c, line 106 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44pH_6TfddW2_CyME:-Mt44pH_6TfddW2_CyMF:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L106)):*
> ```C
> struct span_runtime span_get_region_runtime(const struct pmemstream *stream, uint64_t offset)
> {
> 	span_bytes *span = span_offset_to_span_ptr((struct pmemstream *)stream, offset);
> ```

same here
___
*[src/span.c, line 121 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44q5CEmNr7f87DBnH:-Mt44q5CEmNr7f87DBnI:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L121)):*
> ```C
> struct span_runtime span_get_runtime(const struct pmemstream *stream, uint64_t offset)
> {
> 	span_bytes *span = span_offset_to_span_ptr((struct pmemstream *)stream, offset);
> ```

same here
___
*[src/include/libpmemstream.h, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt45FNvEbJ_an9IFCnG:-Mt45FNw2aym9-CQU4nr:bpnmop3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/include/libpmemstream.h#L87)):*
> ```objc
> 
> // returns pointer to the data of the entry
> void *pmemstream_entry_data(struct pmemstream *stream, struct pmemstream_entry entry);
> ```

I guess this should return `const void*`


<!-- Sent from Reviewable.io -->

2022-01-11 09:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 1 of 9 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-MseciCXD6sT0gkNwM11):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You cannot modify arguments passed as a value, so it's obvious.
</blockquote></details>

anyway, now you're not only updating arguments, so pls update
___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-Mt7RhU70f8qLY6W1OeG:b-vs6mt5) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
> ```C
> {
> 	struct span_runtime region_srt = span_get_region_runtime(stream, region.offset);
> 	struct pmemstream_entry_iterator iter = {.stream = stream};
> ```

why this change? we still have to set up the rest of the struct below


<!-- Sent from Reviewable.io -->

2022-01-12 17:57 UTC, KFilipek reviewed
> Reviewed 2 of 8 files at r3, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 0 of 14 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.h, line 20 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43Ju7--iqPCul8DHP:-MtDOlX63HHttUyaVZzp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.h#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess all members can be const (region and region_context too)
</blockquote></details>

Done.
___
*[src/iterator.h, line 26 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43P8EEAa2hV7mqVhW:-MtDOmG7DicPrzRR2y0K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-MtDOnXMCPzLF1_Bu8ms:b-lwy87d) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why this change? we still have to set up the rest of the struct below
</blockquote></details>

It's needed due to initialization const variable, I moved all fields.
___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtDP64M1QGoGWdu-0av:b-tzwnb1) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why?
</blockquote></details>

What? I don't make any change here.
___
*[src/libpmemstream_internal.h, line 53 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43ATl1Dct9EnLNwme:-MtDQ_FABNolAbw59lRf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/libpmemstream_internal.h#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

return `const uint8_t*` then? It's dangerous to cast it to (uint8_t*) when we don't know where the streams come from.
</blockquote></details>

Done.
___
*[src/region.c, line 128 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2Ve3X44-0cbwzeOD_:-MtDTJI91vQvL_Y13AsN:b97eacp) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/region.c#L128)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

and region_context? region_iterate_and_try_recover will possibly modify region_context->append_offset
</blockquote></details>

Done. It's not const for now.
___
*[src/region.c, line 114 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43jCN4ioFuqEYZgl6:-MtDQhzvB9hLxfVc4JtH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/region.c#L114)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

as we discussed, it should not be const right now, this function does recovery (modifies stream)
</blockquote></details>

Done.
___
*[src/span.c, line 75 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44V8n8uhDoQtpq97m:-MtDduEi4cYCbObVhKqr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L75)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is why I would prefer having span_offset_to_span_ptr take and return const ptr. You have `span_bytes *span` here which looks like it can be modified (and it can't in general, it can result in UB).
</blockquote></details>

Done.
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-MtDVD5h1QxJm5Y-oE0G:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/span.c, line 106 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44pH_6TfddW2_CyME:-MtDVDQlAMVP33Nt8LE9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L106)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/span.c, line 121 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44q5CEmNr7f87DBnH:-MtDVDnf1nmrBuUTnOeW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L121)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 17:57 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 0 of 14 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/include/libpmemstream.h, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt45FNvEbJ_an9IFCnG:-MtEQxbnBNc5TcJTuoMT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/include/libpmemstream.h#L87)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess this should return `const void*`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-13 08:13 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 13 files at r6, 3 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 7 of 14 files reviewed, 17 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-MseciCXD6sT0gkNwM11):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

anyway, now you're not only updating arguments, so pls update
</blockquote></details>

now the description is a bit too simplified :wink: pls at least mention "const"
___
*[examples/02_visual_iterator/main.cpp, line 97 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHUD-v3s5LO1nAeENP:-MtHUD-v3s5LO1nAeENQ:b-bgdx8g) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/examples/02_visual_iterator/main.cpp#L97)):*
> ```cpp
> 				auto d = static_cast<const unsigned char *>(pmemstream_entry_data(stream, entry));
> 				for (size_t i = 0; i < entry_length; i++) {
> 					printf("%.2X ", (int)d[i]);
> ```

actually, why casting to unsigned char, to cast it here into int?
___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-MtHR6nY4GweoSSP9-eO:bptsa4d) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's needed due to initialization const variable, I moved all fields.
</blockquote></details>

but iter is not const here...?

in general, IMHO, changes within this function seem kind of for worse...? for me it's less readable now - what is the gain?
___
*[src/iterator.c, line 10 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHUud08VcZ4vLruBHE:-MtHUud08VcZ4vLruBHF:bdymkxo) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L10)):*
> ```C
> 
> #include <assert.h>
> #include <string.h>
> ```

why do we need this string.h ?
___
*[src/region.c, line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHSX_AAQZiUXRSbeaD:-MtHSX_AAQZiUXRSbeaE:bxa5p8c) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/region.c#L113)):*
> ```C
> }
> 
> /* Iterates over entire region. Might perform recovery. */
> ```

merge issue - the new version of this comment is outdated now
___
*[src/span.c, line 75 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHTLtF-h905AdeihCk:-MtHTLtF-h905AdeihCl:b7r510) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L75)):*
> ```C
> struct span_runtime span_get_empty_runtime(const struct pmemstream *stream, uint64_t offset)
> {
> 	const span_bytes *span = span_offset_to_span_ptr((const struct pmemstream *)stream, offset);
> ```

why the cast?



_Code quote:_
```C
(const struct pmemstream *)
```


<!-- Sent from Reviewable.io -->

2022-01-13 09:59 UTC, igchor requested changes
> Reviewed 2 of 13 files at r6, 2 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 11 of 14 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtHqjxS5zf4ZwYF9lz3:b-m6sjv6) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

What? I don't make any change here.
</blockquote></details>

I mean this case below:

`region_runtime_initialize((struct pmemstream_region_runtime *)iterator->region_runtime, entry);`

Why do you need this?
___
*[src/iterator.c, line 56 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrl3D8gCP9qbSw-y7:-MtHrl3D8gCP9qbSw-y8:bfjx5w5) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L56)):*
> ```C
> }
> 
> int entry_iterator_initialize(struct pmemstream_entry_iterator *iterator, const struct pmemstream *stream,
> ```

didn't we agree that iterators do not require `const pmemstream* stream`? I think this const should be dropped from the parameter
___
*[src/iterator.c, line 63 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHlHqjD-q5d8jdRXil:-MtHlHqjD-q5d8jdRXim:bik8fzs) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L63)):*
> ```C
> 
> 	int ret = region_runtimes_map_get_or_create(stream->region_runtimes_map, region,
> 						    (struct pmemstream_region_runtime **)&iter.region_runtime);
> ```

nit: I think you could actually avoid this cast by calling this function before initializing iter. You could just create temporary region_runtime pointer, pass it to this function and the call:

```
struct pmemstream_entry_iterator iter = {.stream = stream, .offset = region_srt.data_offset, .region = region, .region_runtime=region_runtime};
```
___
*[src/iterator.c, line 73 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrxscE3jDnrPqHnW8:-MtHrxscE3jDnrPqHnW9:b-5h08ab) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L73)):*
> ```C
> }
> 
> int pmemstream_entry_iterator_new(struct pmemstream_entry_iterator **iterator, const struct pmemstream *stream,
> ```

same herer
___
*[src/libpmemstream_internal.h, line 53 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43ATl1Dct9EnLNwme:-MtHqyCLEvkn11t2pPl-:b-gcek6y) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/libpmemstream_internal.h#L53)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also change `(uint8_t *)stream->data->spans + offset;` to `(const uint8_t *)stream->data->spans + offset;`
___
*[src/span.c, line 10 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V75z6sdDMAlmOv5I:-MtHrBJo3TLGLEiqhQOd:b-6c9l7g) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You still could have `const struct pmemstream *stream` as param and return `const span_bytes*` by default and just cast it to `span_bytes*` only when necessary (and when you know that stream is not actually const, like in append, it's allowed).

I would prefer actually having const ptr as parameter and return type.
</blockquote></details>

Also change cast int the return statement
___
*[src/span.c, line 75 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44V8n8uhDoQtpq97m:-MtHrM_5AOrOWEIqsiSp:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same here
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-MtHrP5l9wIjnFCV0MIi:bauxmb8) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why stream cast?
and why can't `*span` be const?
___
*[src/span.c, line 106 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44pH_6TfddW2_CyME:-MtHrcRkD9c9pHoDm1SD:bauxmb8) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L106)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why stream cast?
and why can't `*span` be const?
___
*[src/span.c, line 121 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44q5CEmNr7f87DBnH:-MtHreiJ3HEo-7ZUhW7n:bauxmb8) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L121)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why stream cast?
and why can't `*span` be const?
___
*[src/span.c, line 35 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrGEd97KqXkimho7g:-MtHrGEd97KqXkimho7h:b-t8tri0) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L35)):*
> ```C
> 		       int flags)
> {
> 	span_bytes *span = (span_bytes *)span_offset_to_span_ptr((const struct pmemstream *)stream, offset);
> ```

this cast of pmemstream to const is not necessary 
___
*[src/span.c, line 56 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrL1sA2m6O9iK90xj:-MtHrL1sA2m6O9iK90xk:b-2guby3) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L56)):*
> ```C
> void span_create_region(struct pmemstream *stream, uint64_t offset, size_t size)
> {
> 	span_bytes *span = (span_bytes *)span_offset_to_span_ptr((const struct pmemstream *)stream, offset);
> ```

same here


<!-- Sent from Reviewable.io -->

2022-01-13 13:48 UTC, KFilipek reviewed
> Reviewed 2 of 13 files at r6, 3 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 13 of 14 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/02_visual_iterator/main.cpp, line 97 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHUD-v3s5LO1nAeENP:-MtIT3kL6yBsbLgb9vle:bysk5va) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/examples/02_visual_iterator/main.cpp#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, why casting to unsigned char, to cast it here into int?
</blockquote></details>

Good point with this cast. Intention of first static cast was to split data into 1B parts. The second was the legacy.
___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-MtITvdk0cRo1mhuYrdV:bc8acge) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but iter is not const here...?

in general, IMHO, changes within this function seem kind of for worse...? for me it's less readable now - what is the gain?
</blockquote></details>

You can't do simply assignment when you have `const` specifier in fields. There are at least 2 fields with `const` specifier in `pmemstream_entry_iterator`. I'm also not a fan of this kind of style, but it's C.
___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtIXLA0Am6l3aCKdSxu:b-p1bu38) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I mean this case below:

`region_runtime_initialize((struct pmemstream_region_runtime *)iterator->region_runtime, entry);`

Why do you need this?
</blockquote></details>

`iterator->region_runtime` is type: `const struct pmemstream_region_runtime *`
___
*[src/iterator.c, line 10 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHUud08VcZ4vLruBHE:-MtITP3i7A3qQXq5kmMv:b4gevnf) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need this string.h ?
</blockquote></details>

memcpy is defined there
___
*[src/iterator.c, line 56 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrl3D8gCP9qbSw-y7:-MtITYG67hc0FCNlav4Y:b605rkn) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

didn't we agree that iterators do not require `const pmemstream* stream`? I think this const should be dropped from the parameter
</blockquote></details>

We agreed, but you still explore my changes with wrong revision xD


<!-- Sent from Reviewable.io -->

2022-01-13 14:49 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 13 of 14 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.c, line 63 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHlHqjD-q5d8jdRXil:-MtIswNIDMXgEC7kuJ4R:b-pye9fx) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L63)):*
>  calling this function before initializing iter
You mean that whole `entry_iterator_initialize` sucks and should be moved into `pmemstream_entry_iterator_new`. Otherwise I implement part of initialization outside and whole function will be splitted.
Generally, I can remove this function and move the implementation to `pmemstream_entry_iterator_new` as another PR, because `entry_iterator_initialize` is used once in  `region_iterate_and_try_recover`.


<!-- Sent from Reviewable.io -->

2022-01-13 16:35 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed (commit messages unreviewed), 14 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtJHPwx3s23UmgYvDeY:b-v87uxt) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`iterator->region_runtime` is type: `const struct pmemstream_region_runtime *`
</blockquote></details>

I know, but this should work without the cast I think. Do you say it will not compile with the check?
___
*[src/iterator.c, line 63 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHlHqjD-q5d8jdRXil:-MtJH9UR9x4iN39yiJIn:b-wns3wm) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L63)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>  calling this function before initializing iter
You mean that whole `entry_iterator_initialize` sucks and should be moved into `pmemstream_entry_iterator_new`. Otherwise I implement part of initialization outside and whole function will be splitted.
Generally, I can remove this function and move the implementation to `pmemstream_entry_iterator_new` as another PR, because `entry_iterator_initialize` is used once in  `region_iterate_and_try_recover`.
</blockquote></details>

A big benefit of entry_iterator_initialize is no allocation. And I don't think moving it would make any difference.


<!-- Sent from Reviewable.io -->

2022-01-13 16:36 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed (commit messages unreviewed), 14 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtJHukF3JmatCqCAE-u:b-fsfk9y) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I know, but this should work without the cast I think. Do you say it will not compile with the check?
</blockquote></details>

edit: "Do you say it will not compile without the cast?"


<!-- Sent from Reviewable.io -->

2022-01-13 17:40 UTC, KFilipek reviewed
> Reviewed 4 of 13 files at r6, 3 of 7 files at r7, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-MseciCXD6sT0gkNwM11):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now the description is a bit too simplified :wink: pls at least mention "const"
</blockquote></details>

Done.
___
*[src/libpmemstream_internal.h, line 53 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt43ATl1Dct9EnLNwme:-MtIu_TE6VkhHDQZzQgE:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/libpmemstream_internal.h#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also change `(uint8_t *)stream->data->spans + offset;` to `(const uint8_t *)stream->data->spans + offset;`
</blockquote></details>

Done.
___
*[src/region.c, line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHSX_AAQZiUXRSbeaD:-MtIur_z7x76RB7zyt32:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/region.c#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

merge issue - the new version of this comment is outdated now
</blockquote></details>

Done.
___
*[src/span.c, line 10 at r2](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt2V75z6sdDMAlmOv5I:-MtIuvmF-XnCMqan1Hne:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/564aa4b99937f70f0b1c02a8b8126b0039c88f79/src/span.c#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also change cast int the return statement
</blockquote></details>

Done.
___
*[src/span.c, line 75 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44V8n8uhDoQtpq97m:-MtIvVB3CFoW1SzbrYc3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L75)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-MtIvcvL0fUTj4eLj0E-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why stream cast?
and why can't `*span` be const?
</blockquote></details>

Done.
___
*[src/span.c, line 106 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44pH_6TfddW2_CyME:-MtIvm1F0mc5h3AN8zNL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L106)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why stream cast?
and why can't `*span` be const?
</blockquote></details>

Done.
___
*[src/span.c, line 121 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44q5CEmNr7f87DBnH:-MtIvmaa68xttBju28OK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L121)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why stream cast?
and why can't `*span` be const?
</blockquote></details>

Done.
___
*[src/span.c, line 35 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrGEd97KqXkimho7g:-MtIvOKr6SDLEFoMDTSj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L35)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this cast of pmemstream to const is not necessary 
</blockquote></details>

Done.
___
*[src/span.c, line 56 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrL1sA2m6O9iK90xj:-MtIvSZSCm_h-660gcge:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[src/span.c, line 75 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHTLtF-h905AdeihCk:-MtIvW-51Y9q1WK23n0M:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/span.c#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why the cast?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-13 18:23 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed, 14 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtJfSsRDZoDuJjy3YJ2:b-bu7id0) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

edit: "Do you say it will not compile without the cast?"
</blockquote></details>

It works until -Werr
`warning: passing argument 1 of ‘region_runtime_initialize’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]`
___
*[src/iterator.c, line 56 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrl3D8gCP9qbSw-y7:-MtJXVkZD8E7D4VNNsUj:b-1hkg89) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm looking at the last revision and still can see `const struct pmemstream *stream` - so perhaps you forgot to push something?
</blockquote></details>

Done. "page wrapping issue", you were right.
___
*[src/iterator.c, line 73 at r7](https://reviewable.io/reviews/pmem/pmemstream/59#-MtHrxscE3jDnrPqHnW8:-MtJXgqvDgfiIHe9tsXq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dc374a0ead413a325fda2b340957dbf0fa846828/src/iterator.c#L73)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

same herer
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-14 10:37 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtN0romDtFO_Xs-9r74:b-egai7b) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It works until -Werr
`warning: passing argument 1 of ‘region_runtime_initialize’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]`
</blockquote></details>

So, this suggests that you have the wrong qualifier for region_runtime. Looking at the members declarations in iterator I just realized you put:
`struct pmemstream_region_runtime const *region_runtime;` which is I believe the same as `const  struct pmemstream_region_runtime *region_runtime;` It should be `struct pmemstream_region_runtime *const  region_runtime;` instead.

see: https://stackoverflow.com/questions/21476869/constant-pointer-vs-pointer-to-constant
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-MtN1sVXDeR-peMt-Y37:br47gll) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done, `*span` is still non-const


<!-- Sent from Reviewable.io -->

2022-01-14 10:46 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-MtN9FhPDW0JB2wUokV8:b40bdjr) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You can't do simply assignment when you have `const` specifier in fields. There are at least 2 fields with `const` specifier in `pmemstream_entry_iterator`. I'm also not a fan of this kind of style, but it's C.
</blockquote></details>

but we don't have any const now, don't we? so this whole change below is not necessary...?



_Code quote:_
```C
	struct pmemstream_entry_iterator iter = {
		.stream = stream, .offset = region_srt.data_offset, .region = region, .region_runtime = region_rt};
	memcpy(iterator, &iter, sizeof(struct pmemstream_entry_iterator));
```


<!-- Sent from Reviewable.io -->

2022-01-14 12:35 UTC, KFilipek reviewed
> Reviewed 5 of 5 files at r11, 1 of 1 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt7RhU70f8qLY6W1OeF:-MtNJIJk4xlZ1iutfFF8:bgrus70) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but we don't have any const now, don't we? so this whole change below is not necessary...?
</blockquote></details>

Don't we?



_Code snippet:_
```C
struct pmemstream_entry_iterator {
	struct pmemstream const *stream;
	const struct pmemstream_region region;
	struct pmemstream_region_runtime const *region_runtime;
	uint64_t offset;
};
```
___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtNZuMi8x0G_jNiOJwv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, this suggests that you have the wrong qualifier for region_runtime. Looking at the members declarations in iterator I just realized you put:
`struct pmemstream_region_runtime const *region_runtime;` which is I believe the same as `const  struct pmemstream_region_runtime *region_runtime;` It should be `struct pmemstream_region_runtime *const  region_runtime;` instead.

see: https://stackoverflow.com/questions/21476869/constant-pointer-vs-pointer-to-constant
</blockquote></details>

Done.
___
*[src/span.c, line 90 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt44oaA6WumnHmRKQPY:-MtN_3R_9Si64vGiSb-c:bh006wj) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/span.c#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still not done, `*span` is still non-const
</blockquote></details>

Done. Right, I missed it :/


<!-- Sent from Reviewable.io -->

2022-01-14 16:50 UTC, igchor requested changes
> Reviewed 2 of 5 files at r11, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-MtOUZGA6mSsxfc9EEop:b-2hq9h5) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, did you entirely remove const from `struct pmemstream_region_runtime *region_runtime`?  Also `struct pmemstream const *stream;` is still wrong.


<!-- Sent from Reviewable.io -->

2022-01-17 12:36 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/iterator.c, line 142 at r3](https://reviewable.io/reviews/pmem/pmemstream/59#-Mt438LS-hVOCQELhSPi:-Mtc1L6-BTU0RyiFH1MT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/78211e80ad9cb6f3082d0d26541e6f09931ba3e3/src/iterator.c#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Wait, did you entirely remove const from `struct pmemstream_region_runtime *region_runtime`?  Also `struct pmemstream const *stream;` is still wrong.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-17 13:56 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r9, 1 of 5 files at r11, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/59#-:-MtcEOrQBtRu7SNl51cz:bnfp4nl)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-17 13:59 UTC, merged