Move clearing region to pmemstream_append
pmem/pmemstream pull request #60
Opened 2022-01-10 12:48 UTC by igchor

With this change iterator does not have to modify any peristent data
which will be beneficial for adding multi-process support.

Also, previous implementation was racy if there was a concurrent append
and iterate. If region_recover was called in iterator, append could
start doing data memcpy before region_recover finished - data could
be oberwritten by 0s.

Also, this patch removes atomic_fetch_add on append_offset - for now
pmemstream_append/reserve can only be called from single thread anyway.

2022-01-10 14:12 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/iterator.c, line 106 at r1](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt3COEq-429V0YIU5Mt:-Mt3COEq-429V0YIU5Mu:bpkta7s) ([raw file](https://github.com/pmem/pmemstream/blob/f484ac6f01621d1293ae5c0a1e02e1def361d5c6/src/iterator.c#L106)):*
> ```C
> }
> 
> /* Advances entry iterator by one. Verifies entry integrity and sets append_offset is end of data is found. */
> ```

`if end of data...`
___
*[src/iterator.c, line 133 at r1](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt3CeD0AjzBfNFaa-TG:-Mt3CeD0AjzBfNFaa-TH:bt0d0cf) ([raw file](https://github.com/pmem/pmemstream/blob/f484ac6f01621d1293ae5c0a1e02e1def361d5c6/src/iterator.c#L133)):*
> ```C
> 	assert(entry.offset + srt.total_size <= iterator->region.offset + region_srt.total_size);
> 
> 	int region_initialize_append_offseted = region_is_append_offset_initialized(iterator->region_context);
> ```

this is just a local var., perhaps rename to `append_offset_initialized`



_Code quote:_
```C
region_initialize_append_offseted
```
___
*[src/region.h, line 41 at r1](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt3Do6EBHP-yS8MzlY1:-Mt3Do6EBHP-yS8MzlY2:bf9vfh) ([raw file](https://github.com/pmem/pmemstream/blob/f484ac6f01621d1293ae5c0a1e02e1def361d5c6/src/region.h#L41)):*
> ```objc
> 	 *
> 	 * If PMEMSTREAM_OFFSET_DIRTY_BIT is set, append_offset points to a valid location but the memory from
> 	 * append_offset & PMEMSTREAM_OFFSET_DIRTY_MASK to the end of region was not yet cleared. */
> ```

please put this expression e.g. within '...' = `'append_offset & PMEMSTREAM_OFFSET_DIRTY_MASK'`
___
*[src/region.c, line 147 at r1](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt3DCyN9YCYblupqPnI:-Mt3DCyN9YCYblupqPnJ:b-torlcd) ([raw file](https://github.com/pmem/pmemstream/blob/f484ac6f01621d1293ae5c0a1e02e1def361d5c6/src/region.c#L147)):*
> ```C
> }
> 
> void region_initialize_append_offset(struct pmemstream *stream, struct pmemstream_region region,
> ```

stream and region are not needed here, anymore


<!-- Sent from Reviewable.io -->

2022-01-11 09:46 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7V3PT893ybZGKjHKe):*
pls fix copyright dates in these 2 new commits :wink: 
___
*[src/iterator.c, line 64 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7VqU-ByDEIQX80wTj:-Mt7VqU-ByDEIQX80wTk:b8empzs) ([raw file](https://github.com/pmem/pmemstream/blob/8005256e488c74793cdc2752a4dafbdf287f8012/src/iterator.c#L64)):*
> ```C
> 	iter.stream = stream;
> 
> 	int ret = region_runtime_map_get_or_create(stream->region_runtime_map, region, &iter.region_runtime);
> ```

`region_runtimes_map`
___
*[src/region.c, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7VDuLD3wcPtLLlBq4:-Mt7VDuLD3wcPtLLlBq5:bo2g869) ([raw file](https://github.com/pmem/pmemstream/blob/8005256e488c74793cdc2752a4dafbdf287f8012/src/region.c#L87)):*
> ```C
> 
> 		if (ret == EEXIST) {
> 			/* Someone else inserted the region context - just get a pointer to it. */
> ```

I believe you have to grep also for "context" and update it :wink: 


<!-- Sent from Reviewable.io -->

2022-01-11 10:40 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7V3PT893ybZGKjHKe):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix copyright dates in these 2 new commits :wink: 
</blockquote></details>

Done.
___
*[src/iterator.c, line 64 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7VqU-ByDEIQX80wTj:-Mt7iCoQ9zJjlB4uTzjk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8005256e488c74793cdc2752a4dafbdf287f8012/src/iterator.c#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`region_runtimes_map`
</blockquote></details>

Done.
___
*[src/region.c, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7VDuLD3wcPtLLlBq4:-Mt7iDYJEyaX02JUqdhz:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8005256e488c74793cdc2752a4dafbdf287f8012/src/region.c#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you have to grep also for "context" and update it :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 11:42 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 13 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[src/region.c, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7w2-g8tq_Ly4TgaVk:-Mt7w2-h5BxRf57pxuqo:b-nlme3k) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/src/region.c#L63)):*
> ```C
> 
> int region_runtimes_map_get_or_create(struct region_runtimes_map *map, struct pmemstream_region region,
> 				      struct pmemstream_region_runtime **container_handle)
> ```

`container_handle` might be too precise - perhaps `runtime_handle`...?
___
*[src/include/libpmemstream.h, line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7vrZVCC4bliuHw1X8:-Mt7vrZVCC4bliuHw1X9:b-suz4kd) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/src/include/libpmemstream.h#L47)):*
> ```objc
>  * have to explicitly delete/free it. Runtime becomes invalid after corresponding region is freed. */
> int pmemstream_get_region_runtime(struct pmemstream *stream, struct pmemstream_region region,
> 				  struct pmemstream_region_runtime **ctx);
> ```

`**ctx` :wink: 
___
*[tests/unittest/append.cpp, line 72 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7wMQf-y-GV7kJL6KL:-Mt7wMQf-y-GV7kJL6KM:b2ni0oy) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/tests/unittest/append.cpp#L72)):*
> ```cpp
> 						 auto stream = make_pmemstream(path, TEST_DEFAULT_BLOCK_SIZE,
> 									       TEST_DEFAULT_STREAM_SIZE, false);
> 						 pmemstream_region_runtime *ctx = NULL;
> ```

ctx


<!-- Sent from Reviewable.io -->

2022-01-11 11:47 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/region.c, line 63 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7w2-g8tq_Ly4TgaVk:-Mt7xK85671Ybx6ZBtXr:bj2acc1) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/src/region.c#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`container_handle` might be too precise - perhaps `runtime_handle`...?
</blockquote></details>

Actually that's the idea, to make it clear that the return value comes from the data structure (and is not just malloced and unlinked).
___
*[src/include/libpmemstream.h, line 47 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7vrZVCC4bliuHw1X8:-Mt7xaau7iPKYno2n3E-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/src/include/libpmemstream.h#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`**ctx` :wink: 
</blockquote></details>

Done.
___
*[tests/unittest/append.cpp, line 72 at r3](https://reviewable.io/reviews/pmem/pmemstream/60#-Mt7wMQf-y-GV7kJL6KL:-Mt7xbDs5pr-pLGFeJ2U:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2826645c21b6ad845d952399da92e7cb154e9c3d/tests/unittest/append.cpp#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ctx
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 08:14 UTC, karczex requested changes
> Reviewed 3 of 13 files at r2, 7 of 9 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/60#-MtCIHPbDqfwutdCdNg1):*
You moved clearing region to pmemstream_reserve, not to append. Please change commit message.
___
*[src/region.h, line 25 at r4](https://reviewable.io/reviews/pmem/pmemstream/60#-MtCFQBO7VtSGVKSQTLl:-MtCFQBO7VtSGVKSQTLm:bxy7z1m) ([raw file](https://github.com/pmem/pmemstream/blob/f893018643fd92698a853d10ed54b1ba280665be/src/region.h#L25)):*
> ```objc
> 
> #define PMEMSTREAM_OFFSET_UNINITIALIZED 0ULL
> #define PMEMSTREAM_OFFSET_DIRTY_BIT (1ULL << 63)
> ```

I would suggest to add functions: set_dirty_bit(), clear_dirty_bit and is_dirty(). 

```c
if(is_dirty(offset)) 
```

is much more readable than 

```c
if (offset & PMEMSTREAM_OFFSET_DIRTY_BIT)
```


<!-- Sent from Reviewable.io -->

2022-01-12 09:22 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @karczex)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/60#-MtCIHPbDqfwutdCdNg1):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You moved clearing region to pmemstream_reserve, not to append. Please change commit message.
</blockquote></details>

Done.
___
*[src/region.h, line 25 at r4](https://reviewable.io/reviews/pmem/pmemstream/60#-MtCFQBO7VtSGVKSQTLl:-MtCa3tr134El5is_W8H:b-gp7seu) ([raw file](https://github.com/pmem/pmemstream/blob/f893018643fd92698a853d10ed54b1ba280665be/src/region.h#L25)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would suggest to add functions: set_dirty_bit(), clear_dirty_bit and is_dirty(). 

```c
if(is_dirty(offset)) 
```

is much more readable than 

```c
if (offset & PMEMSTREAM_OFFSET_DIRTY_BIT)
```
</blockquote></details>

Ok, I'll add this in next PR


<!-- Sent from Reviewable.io -->

2022-01-12 09:47 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/60#-:-MtCflLh8U2sXxOVJkOg:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-12 09:50 UTC, merged