Introduce id_manager module
pmem/pmemstream pull request #66
Opened 2022-01-12 15:25 UTC by igchor

It can be used to assign unique ids to thread, with possibility
to reuse ids when a thread exits.

This will be handy for implementing per-thread data storage as id
can be used as an index in array.

2022-01-13 09:56 UTC, karczex reviewed
In general it may be useful, but I think, we should wait with merging it, until it would be used. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MtHqqni2yABHOgoFEfK:bxbap2l)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-14 10:17 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/id_manager.h, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN181E8HQJdMmox_IC:-MtN181F6Raec5055NHd:bx9zhe5) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L19)):*
> ```objc
> #endif
> 
> struct id {
> ```

are you using this struct anywhere?
___
*[src/id_manager.h, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN3BQoAL4JYR1YvpQ5:-MtN3BQoAL4JYR1YvpQ6:b73zjb0) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L24)):*
> ```objc
> 
> struct id_manager {
> 	/* A set (key == value) of all available ids between 0 and next_id. */
> ```

what do you mean by "all available ids"? can you please add a short comment (somewhere) on how this struct works
___
*[src/id_manager.c, line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN2CHjEodHdAnifreU:-MtN2CHjEodHdAnifreV:b-9kuowx) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L61)):*
> ```C
> 	pthread_mutex_lock(&manager->id_acquire_release_mutex);
> 
> 	uint64_t min_id = (uint64_t)-1;
> ```

perhaps make this `(uint64_t)-1` some define/const
___
*[tests/CMakeLists.txt, line 104 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN2eeF18hGyOXgZxCm:-MtN2eeF18hGyOXgZxCn:b-jstgor) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/tests/CMakeLists.txt#L104)):*
> ```CMake
> 	build_test_rc(NAME create SRC_FILES unittest/create.cpp)
> 	add_test_generic(NAME create TRACERS none)
> ```

I guess you're not rebased on the latest master...? I sorted these tests alphabetically :wink: 


<!-- Sent from Reviewable.io -->

2022-01-14 14:36 UTC, KFilipek requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/id_manager.h, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtNujUA2J-jIK8O3ig0:-MtNujUA2J-jIK8O3ig1:b-j2ztuv) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L31)):*
> ```objc
> 	uint64_t next_id;
> 
> 	/* Mutex for protecting acquiring/releasing id */
> ```

dot at the end of phrase or not



_Code quote:_
```objc
id */
```
___
*[src/id_manager.c, line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtNzoND9SRvu3tXfvjp:-MtNzoND9SRvu3tXfvjq:b-1c7ydi) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L46)):*
> ```C
> static int get_critnib_min_key(uintptr_t key, void *v, void *d)
> {
> 	uint64_t value = (uint64_t)v;
> ```

`(uint64_t)*v`?



_Code quote:_
```C
(uint64_t)v
```
___
*[src/id_manager.c, line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN2CHjEodHdAnifreU:-MtO-G8d0Huw6-maOl7G:b-ofqi0b) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make this `(uint64_t)-1` some define/const
</blockquote></details>

better approach is to include <stdint.h> and use `UINT64_MAX`
___
*[src/id_manager.c, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtO-YPh5hWoFeNFjftx:-MtO-YPh5hWoFeNFjfty:bchf214) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L64)):*
> ```C
> 	critnib_iter(manager->ids, 0, (uint64_t)-1, get_critnib_min_key, &min_id);
> 
> 	if (min_id == (uint64_t)-1) {
> ```

`UINT64_MAX`



_Code quote:_
```C
(uint64_t)-1)
```


<!-- Sent from Reviewable.io -->

2022-01-14 18:35 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/id_manager.h, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN181E8HQJdMmox_IC:-MtOogAM0QParUeC3u6K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you using this struct anywhere?
</blockquote></details>

Done.
___
*[src/id_manager.h, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN3BQoAL4JYR1YvpQ5:-MtOpB__5Cuad6WWSI5a:b-896fig) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by "all available ids"? can you please add a short comment (somewhere) on how this struct works
</blockquote></details>

Done?
___
*[src/id_manager.h, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtNujUA2J-jIK8O3ig0:-MtOpEXtCmFwC0u1uEcU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L31)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

dot at the end of phrase or not
</blockquote></details>

Done.
___
*[src/id_manager.c, line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtNzoND9SRvu3tXfvjp:-MtOpFH1Ai_OvrzSadur:b-fcv330) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L46)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`(uint64_t)*v`?
</blockquote></details>

nope, I store uint64_t directly as value in the critnib
___
*[src/id_manager.c, line 61 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN2CHjEodHdAnifreU:-MtOpV-j-q71F8bauDaZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L61)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

better approach is to include <stdint.h> and use `UINT64_MAX`
</blockquote></details>

Done.
___
*[src/id_manager.c, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtO-YPh5hWoFeNFjftx:-MtOpVFC6d3fl6Dr4pd6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.c#L64)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`UINT64_MAX`
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 104 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtN2eeF18hGyOXgZxCm:-MtOpWhGDEWTuLHinSNG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/tests/CMakeLists.txt#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you're not rebased on the latest master...? I sorted these tests alphabetically :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 15:56 UTC, lukaszstolarczuk reviewed
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 16 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/id_manager.h, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/66#-MtNujUA2J-jIK8O3ig0:-MthVQG3D8PdmXFwWNyB:b-hmva0h) ([raw file](https://github.com/pmem/pmemstream/blob/5abbe61e03e015779cdff4ba4be3b847384c1d02/src/id_manager.h#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think we keep track of these dots, sometimes they are there, sometimes they aren't :wink: I believe it's not the end of the world
___
*[src/thread_id.h, line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mth_-GN9SqgdYjb7V_R:-Mth_-GN9SqgdYjb7V_S:b-m6xq8f) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.h#L16)):*
> ```objc
> #endif
> 
> struct thread_id;
> ```

\+ short comment on this struct or header
___
*[src/thread_id.h, line 24 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mth_HJj5f3wMZrUvX5m:-Mth_HJj5f3wMZrUvX5n:b-2vcmr2) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.h#L24)):*
> ```objc
>  * Get this thread id. Value returned by this function will not change for the entire
>  * time this thread lives. Ids returned are lowest possible (starting from 0).
>  * Once thread finished, it's id can be reused by different threads.
> ```

`its id`
___
*[src/thread_id.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthawPUAykJ6WYn9vFk:-MthawPUAykJ6WYn9vFl:b3575gy) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.c#L18)):*
> ```C
> };
> 
> struct thread_id {
> ```

short comments, at least for structs, please
___
*[tests/CMakeLists.txt, line 91 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthjhr6BToi9DIF4Pq8:-Mthjhr79EKSyqIhVyTs:b-o98e14) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/CMakeLists.txt#L91)):*
> ```CMake
> build_test_ext(NAME thread_id SRC_FILES unittest/thread_id.cpp ../src/id_manager.c ../src/thread_id.c ../src/critnib/critnib.c)
> add_test_generic(NAME thread_id TRACERS none memcheck drd helgrind)
> ```

at best sort them A-Z
___
*[tests/common/unittest.hpp, line 129 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthbuEA4udkIw2ekewk:-MthbuEA4udkIw2ekewl:bt4plon) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/common/unittest.hpp#L129)):*
> ```cpp
> 
> template <typename Ctor, typename Dtor>
> auto make_instance_ctor(Ctor &&ctor, Dtor &&dtor)
> ```

I like it, but pls add a short comment :wink: or perhaps rename somehow, e.g, `make_uniqe_ptr`...?
___
*[tests/unittest/id_manager.cpp, line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthi_gFAmZb-R9RpABP:-Mthi_gG7uXO8uCe5odE:b2xfsh5) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/unittest/id_manager.cpp#L68)):*
> ```cpp
> 			/* Generate a vector of acquire/release operations. */
> 			static constexpr size_t max_acquire_release_ops = 1024;
> 			std::vector<std::pair<unsigned, unsigned>> acquire_release;
> ```

`unsigned` -> `size_t`
___
*[tests/unittest/id_manager.cpp, line 85 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthiPvvA-9bGKho3wRz:-MthiPvvA-9bGKho3wS-:bg8kmye) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/unittest/id_manager.cpp#L85)):*
> ```cpp
> 					auto id = id_manager_acquire(manager.get());
> 
> 					/* Id will either be bigger than all existsing (==
> ```

misspell



_Code quote:_
```cpp
existsing
```
___
*[tests/unittest/id_manager.cpp, line 11 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtht5QSDqSZEmYwOlMg:-Mtht5QSDqSZEmYwOlMh:b-7fv488) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/id_manager.cpp#L11)):*
> ```cpp
> #include <memory>
> #include <numeric>
> #include <variant>
> ```

you can clean this up a little, I guess...?
___
*[tests/unittest/id_manager.cpp, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthr8Mi0DyqGBlUuaLB:-Mthr8Mi0DyqGBlUuaLC:b-5yg6vj) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/id_manager.cpp#L64)):*
> ```cpp
> 			}
> 		}
> ```

to see if compaction works (the recursive case) you could add a simple test, e.g.:
1. acquire n
2. release 1...n-1
3. release n (after this next id should be 0)
___
*[tests/unittest/id_manager_multithreaded.cpp, line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthrwTYAvRZhxEqZB8H:-MthrwTYAvRZhxEqZB8I:bci4t07) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/id_manager_multithreaded.cpp#L4)):*
> ```cpp
> /* Copyright 2022, Intel Corporation */
> 
> /* id_manager.cpp -- verifies correctness of id_manager module */
> ```

pls update
___
*[tests/unittest/id_manager_multithreaded.cpp, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthsno1DDqaiSS6iMik:-Mthsno1DDqaiSS6iMil:b-1b8jk3) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/id_manager_multithreaded.cpp#L52)):*
> ```cpp
> 		std::sort(merged_ids.begin(), merged_ids.end());
> 
> 		/* The id space should be contigious. */
> ```

`contiguous`



_Code quote:_
```cpp
contigious
```
___
*[tests/unittest/thread_id.cpp, line 33 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthtKWA0cgiTpCTu_F4:-MthtKWA0cgiTpCTu_F5:b-f01nzv) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/thread_id.cpp#L33)):*
> ```cpp
> 		};
> 
> 		/* verify if thread ids are from 0..concurrency range (when all threads are alive). */
> ```

`from` -> `in`
___
*[tests/unittest/thread_id.cpp, line 46 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthtU769GnKFRkbnTYA:-MthtU778KIF7dOzngzx:b-or39jy) ([raw file](https://github.com/pmem/pmemstream/blob/e79d62b7beeed0e9418d1aac24e5f81d062a7fda/tests/unittest/thread_id.cpp#L46)):*
> ```cpp
> 					std::sort(threads_data.begin(), threads_data.end());
> 					for (size_t i = 0; i < threads_data.size(); i++) {
> 						UT_ASSERT(threads_data[i] == i);
> ```

ASSERTeq (in all places)


<!-- Sent from Reviewable.io -->

2022-01-18 16:16 UTC, KFilipek requested changes
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 16 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/thread_id.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthawPUAykJ6WYn9vFk:-Mthv5H06Qne13k3Dsy3:b-61z3zg) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.c#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

short comments, at least for structs, please
</blockquote></details>

I'd prefer to add general overview in file instead of commenting single, irrelevant structure 
___
*[tests/unittest/id_manager_multithreaded.cpp, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthwuqPBCkI1Dfpsk9C:-MthwuqQ5jx7Fhvf5r9p:bcmslsy) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L6)):*
> ```cpp
> /* id_manager.cpp -- verifies correctness of id_manager module */
> 
> #include "id_manager.h"
> ```

wrong group or rename



_Code quote:_
```cpp
#include "id_manager.h"
```
___
*[tests/unittest/id_manager_multithreaded.cpp, line 11 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthw_xW3vifXRnVFH2j:-Mthw_xW3vifXRnVFH2k:bs8nsaf) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L11)):*
> ```cpp
> #include <memory>
> #include <numeric>
> #include <variant>
> ```

also this looks like not used here



_Code snippet:_
```cpp
#include <variant>
```
___
*[tests/unittest/id_manager_multithreaded.cpp, line 21 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthxmhu2TwgxraJb7PY:-Mthxmhu2TwgxraJb7PZ:b-lh7mkn) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L21)):*
> ```cpp
> static constexpr size_t concurrency = 24;
> 
> auto make_id_manager = make_instance_ctor(id_manager_new, id_manager_destroy);
> ```

It looks interesting, could you explain this on next meeting?



_Code quote:_
```cpp
auto make_id_manager = make_instance_ctor(id_manager_new, id_manager_destroy);
```


<!-- Sent from Reviewable.io -->

2022-01-18 16:27 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 14 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/thread_id.h, line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mth_-GN9SqgdYjb7V_R:-Mthv-3v7n570gKvr9dZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.h#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ short comment on this struct or header
</blockquote></details>

Done.
___
*[src/thread_id.h, line 24 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mth_HJj5f3wMZrUvX5m:-Mthv0T-E_MWt0omHTwG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.h#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`its id`
</blockquote></details>

Done.
___
*[src/thread_id.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthawPUAykJ6WYn9vFk:-Mthv1lGE6n17B0rSYCW:bb14awr) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.c#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'd prefer to add general overview in file instead of commenting single, irrelevant structure 
</blockquote></details>

I've added comment in header file for struct (it describes what this module does) and here for thread_data and members.
___
*[tests/common/unittest.hpp, line 129 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthbuEA4udkIw2ekewk:-Mti-hC_15bnBwFr4jKt:b-69sctw) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/common/unittest.hpp#L129)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I like it, but pls add a short comment :wink: or perhaps rename somehow, e.g, `make_uniqe_ptr`...?
</blockquote></details>

you mean `make_make_unique_ptr` ? ;d I don't know how to name it better.
___
*[tests/unittest/id_manager.cpp, line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthi_gFAmZb-R9RpABP:-MthzNU90e_p8K-ssHP8:b2b4fb2) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/unittest/id_manager.cpp#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`unsigned` -> `size_t`
</blockquote></details>

Actually I made it other way around (changed type for generator).
___
*[tests/unittest/id_manager.cpp, line 85 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthiPvvA-9bGKho3wRz:-Mti-ruq2a4RrDEgYYuX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/unittest/id_manager.cpp#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell
</blockquote></details>

Done.
___
*[tests/unittest/id_manager.cpp, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthr8Mi0DyqGBlUuaLB:-Mthx2f395mjrFYHAI29:bbxnpvl) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager.cpp#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to see if compaction works (the recursive case) you could add a simple test, e.g.:
1. acquire n
2. release 1...n-1
3. release n (after this next id should be 0)
</blockquote></details>

I think this is what verify if ids are reused basically does. It acquires some number of items, then releases them (from beginning or end) and repeats. After some iterations, if acquired_ids are sorted it means that reacquistion works fine.

I don't know if we can test compaction directly - even in your idea, we could just keep all the ids in container indefinitely.
___
*[tests/unittest/id_manager_multithreaded.cpp, line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthrwTYAvRZhxEqZB8H:-Mthzus11i-I7YrGjGUy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update
</blockquote></details>

Done.
___
*[tests/unittest/id_manager_multithreaded.cpp, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthwuqPBCkI1Dfpsk9C:-MthzjI29TJZlkeOitI9:bxf5dsd) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L6)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

wrong group or rename
</blockquote></details>

Why it's wrong group? It's what we're testing so it should be on top
___
*[tests/unittest/id_manager_multithreaded.cpp, line 11 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthw_xW3vifXRnVFH2j:-Mthzh-d2pwsj1VnB8kw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L11)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

also this looks like not used here
</blockquote></details>

Done.
___
*[tests/unittest/id_manager_multithreaded.cpp, line 21 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthxmhu2TwgxraJb7PY:-Mthzwdg5HYa1Bdtnf8r:b-ohyt7s) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It looks interesting, could you explain this on next meeting?
</blockquote></details>

I've added a comment to the definition but sure I can explain in more detail.
___
*[tests/unittest/id_manager_multithreaded.cpp, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthsno1DDqaiSS6iMik:-Mti-WTa2zrm32Pj78Ko:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager_multithreaded.cpp#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`contiguous`
</blockquote></details>

Done.
___
*[tests/unittest/thread_id.cpp, line 33 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthtKWA0cgiTpCTu_F4:-MthvdUx6R5BeE2dLC7-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/thread_id.cpp#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`from` -> `in`
</blockquote></details>

Done.
___
*[tests/unittest/thread_id.cpp, line 46 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-MthtU769GnKFRkbnTYA:-Mthvj3X2NYJuIYHT4Yp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/thread_id.cpp#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ASSERTeq (in all places)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-19 13:44 UTC, lukaszstolarczuk reviewed
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/thread_id.h, line 16 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtlty9k7OAyMyj7hwyR:-Mtlty9k7OAyMyj7hwyS:b-t5fxyw) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.h#L16)):*
> ```objc
> #endif
> 
> /* Structure which holds per-thread id. It is supposed to be shared by multiple threads.
> ```

it's per thread, but it can be shared by multiple threads? I'm not sure what do you mean
___
*[src/thread_id.h, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtlu3gYDJbHuUKRsVYp:-Mtlu3gYDJbHuUKRsVYq:b-ekccse) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.h#L17)):*
> ```objc
> 
> /* Structure which holds per-thread id. It is supposed to be shared by multiple threads.
>  * Each thread can call thread_id_get() to obtain it's unique ID. */
> ```

`its` :wink: 
___
*[src/thread_id.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthawPUAykJ6WYn9vFk:-MtmUIvPAemsthU6nJbT:b7ua99k) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.c#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I've added comment in header file for struct (it describes what this module does) and here for thread_data and members.
</blockquote></details>

I asked for these 2 comments because I'm not sure what are the differences between them... Now I'm not sure if I know more :smile:

at the first glance - you have thread_data, which contains 'id' and then, just next to it, you have thread_id :wink: 
___
*[src/thread_id.c, line 20 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtlwB6v7x1N1ZpuBjV2:-MtlwB6v7x1N1ZpuBjV3:bjh423r) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.c#L20)):*
> ```C
> 
> struct thread_id {
> 	/* Key related per-thread 'thread_data' object */
> ```

related to (?)
___
*[tests/common/unittest.hpp, line 129 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthbuEA4udkIw2ekewk:-MtlxAb6EBiXLu7GgH-C:bb46725) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/common/unittest.hpp#L129)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you mean `make_make_unique_ptr` ? ;d I don't know how to name it better.
</blockquote></details>

hmm... I'm kind of confused with the `_ctor` part in the name, but I don't have a better name.

anyway, if you also don't have anything else in mind, then the comment is good enough, I believe
___
*[tests/common/unittest.hpp, line 129 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtmVH756nmae44eEz5d:-MtmVH756nmae44eEz5e:b20ptcx) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/tests/common/unittest.hpp#L129)):*
> ```cpp
> 
> /* Return function which constructs (creates unique_ptr) an instance of an object using ctor().
>  * It's main purpose is to wrap C-like interface with _new and _destroy functions in unique_ptr. */
> ```

`Its` :smile: 
___
*[tests/unittest/id_manager.cpp, line 68 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthi_gFAmZb-R9RpABP:-MtmZeymD3bwg70wYwTh:bocbktz) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/unittest/id_manager.cpp#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually I made it other way around (changed type for generator).
</blockquote></details>

sure, works both ways
___
*[tests/unittest/id_manager.cpp, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/66#-Mthr8Mi0DyqGBlUuaLB:-MtlzM102o7U0e6SFrLX:b56nl65) ([raw file](https://github.com/pmem/pmemstream/blob/dec5cc6995dae25190b95dd8a75bdba436992a1e/tests/unittest/id_manager.cpp#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this is what verify if ids are reused basically does. It acquires some number of items, then releases them (from beginning or end) and repeats. After some iterations, if acquired_ids are sorted it means that reacquistion works fine.

I don't know if we can test compaction directly - even in your idea, we could just keep all the ids in container indefinitely.
</blockquote></details>

ok, I guess then, the existing test will be enough
___
*[tests/unittest/id_manager.cpp, line 78 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtmZZJd6NWENu1zL0Az:-MtmZZJd6NWENu1zL0B-:b-xy6wak) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/tests/unittest/id_manager.cpp#L78)):*
> ```cpp
> 				auto to_release = p.second;
> 
> 				for (size_t i = 0; i < to_acquire; i++) {
> ```

you're comparing now size_t with unsigned... won't we get the warning on Coverity now? I guess you could update the above auto's with size_t's


<!-- Sent from Reviewable.io -->

2022-01-19 14:53 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: 6 of 10 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/thread_id.h, line 16 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtlty9k7OAyMyj7hwyR:-MtmfblO5krWAy7jBFht:b-vo8o35) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.h#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's per thread, but it can be shared by multiple threads? I'm not sure what do you mean
</blockquote></details>

I removed the "shared" part. In general the idea is that there should be one instance of this structure and each thread should call `thread_id_get` on the same instance to get it's own id. DO you have an idea how to exapain it better?
___
*[src/thread_id.h, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtlu3gYDJbHuUKRsVYp:-Mtmgm-DB0p-fznlwCHh:b-huj3x6) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.h#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`its` :wink: 
</blockquote></details>

Done. That must be the most common mistake on my PR :d
___
*[src/thread_id.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthawPUAykJ6WYn9vFk:-Mtmh20_CFcuPYdRcn7U:b-896fig) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/src/thread_id.c#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I asked for these 2 comments because I'm not sure what are the differences between them... Now I'm not sure if I know more :smile:

at the first glance - you have thread_data, which contains 'id' and then, just next to it, you have thread_id :wink: 
</blockquote></details>

Done?
___
*[src/thread_id.c, line 20 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtlwB6v7x1N1ZpuBjV2:-Mtmh4v877OssAZ35vmM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/src/thread_id.c#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

related to (?)
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 129 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthbuEA4udkIw2ekewk:-MtmhHyn-zuEe-OQ0xAT:b5t0xne) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/common/unittest.hpp#L129)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... I'm kind of confused with the `_ctor` part in the name, but I don't have a better name.

anyway, if you also don't have anything else in mind, then the comment is good enough, I believe
</blockquote></details>

The ctor means that this function returns a **function (constructor)** which creates an instance, e.g.:

```
auto ctor = make_instance_ctor(...):
auto instance = ctor():
```
___
*[tests/common/unittest.hpp, line 129 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtmVH756nmae44eEz5d:-MtmhHSQ-FnY-9ismIiT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/tests/common/unittest.hpp#L129)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Its` :smile: 
</blockquote></details>

Done.
___
*[tests/unittest/id_manager.cpp, line 78 at r4](https://reviewable.io/reviews/pmem/pmemstream/66#-MtmZZJd6NWENu1zL0Az:-MtmhZqPCP6yCr1iss2k:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d6da9465606e329d07024a36d7e23096f9b68992/tests/unittest/id_manager.cpp#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you're comparing now size_t with unsigned... won't we get the warning on Coverity now? I guess you could update the above auto's with size_t's
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 09:14 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/id_manager.h, line 16 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-MtsISDF66Av50fxy9wU:-Mtvt1Gn9WwvJlhi_FgS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/id_manager.h#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`assigns`
</blockquote></details>

Done.
___
*[src/id_manager.c, line 13 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-Mts8bXd3qVnCIT6NIL0:-Mtvt4eh20SwqYGuheWM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/id_manager.c#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop the ` (key == value)` part
</blockquote></details>

Done.
___
*[src/id_manager.c, line 61 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-MtsZbVQ23Edd5WqPfsj:-Mtvt7wO4C2dIats8Lh-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/id_manager.c#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe rename to be more precise `..._get_le_key(...`
</blockquote></details>

Done.
___
*[src/id_manager.c, line 69 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-MtsZgi9AGDw1ceEMo4Z:-MtvtEJk7u7VgjxRDeTc:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/id_manager.c#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and `_get_ge_key`
</blockquote></details>

Done.
___
*[src/id_manager.c, line 134 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-Mtsaiwu2csAPaDXpXrU:-MtvtGjS7hcvDN_-MQ7G:b3v1wm5) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/id_manager.c#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

won't we get an 'unused function' in release build?
</blockquote></details>

It might depend on the flags passed to the build - if we are not getting the error now I think it's OK. Alos, in future we will probably replace asserts with asserts from PDMK which solves the issue.
___
*[src/thread_id.h, line 24 at r5](https://reviewable.io/reviews/pmem/pmemstream/66#-MtsIKMEBO7XcuXPkfwN:-MtvuGXS68A6T4BnSmYd:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/17c363e25f58ba7f883cc44fc5dac1b35f5fdb60/src/thread_id.h#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Get this thread's unique id.`
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 129 at r2](https://reviewable.io/reviews/pmem/pmemstream/66#-MthbuEA4udkIw2ekewk:-MtvuAvqCobS74kzhpCn:brzfjqt) ([raw file](https://github.com/pmem/pmemstream/blob/6792cc8426cecdba0c5fb9f94fed4c37ad7f861d/tests/common/unittest.hpp#L129)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

soo, did you consider the new proposed name, like `make/get_unique_ptr_factory`...?

anyway, we can leave this name, as is :)
</blockquote></details>

tbh, I prefer this one ;d


<!-- Sent from Reviewable.io -->

2022-01-21 10:29 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MtwAmxO13wJ4Ff9nP5g:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-25 08:26 UTC, karczex commented
___
*[tests/unittest/id_manager_multithreaded.cpp, line 52 at r6](https://reviewable.io/reviews/pmem/pmemstream/66#-MuFCNpFCDYvA_6BJTF5:-MuFCNpFCDYvA_6BJTF6:b-dj01qc) ([raw file](https://github.com/pmem/pmemstream/blob/254936346c3f57a908d1b8859b869b82740b9b85/tests/unittest/id_manager_multithreaded.cpp#L52)):*
> ```cpp
> 		/* The id space should be contiguous. */
> 		for (size_t i = 1; i < merged_ids.size(); i++) {
> 			UT_ASSERT(merged_ids[i] >= merged_ids[i - 1]);
> ```

Your assert checks if it's monotonic, not contiguous. 


<!-- Sent from Reviewable.io -->

2022-01-25 09:30 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/unittest/id_manager_multithreaded.cpp, line 52 at r6](https://reviewable.io/reviews/pmem/pmemstream/66#-MuFCNpFCDYvA_6BJTF5:-MuFYgZU8T6srjmMLgEX:b-z3e6xm) ([raw file](https://github.com/pmem/pmemstream/blob/254936346c3f57a908d1b8859b869b82740b9b85/tests/unittest/id_manager_multithreaded.cpp#L52)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Your assert checks if it's monotonic, not contiguous. 
</blockquote></details>

Done. I actually wanted to check for contiguous (it's already monotonic after sort).


<!-- Sent from Reviewable.io -->

2022-01-25 11:17 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-25 13:41 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r4, 3 of 6 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MuGT62g9SQ7a3N1fFH0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-01-26 10:44 UTC, karczex requested changes
> Reviewed 1 of 10 files at r2, 2 of 7 files at r4, 2 of 6 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/unittest/id_manager.cpp, line 65 at r7](https://reviewable.io/reviews/pmem/pmemstream/66#-MuKykwuAodJDiuS6DyV:-MuKykwuAodJDiuS6DyW:b-ymbgvg) ([raw file](https://github.com/pmem/pmemstream/blob/b4f0807ed0bd01fb1fd377f13807209e990defab/tests/unittest/id_manager.cpp#L65)):*
> ```cpp
> 			static constexpr size_t max_acquire_release_ops = 1024;
> 			std::vector<std::pair<unsigned, unsigned>> acquire_release;
> 			size_t num_elements = *rc::gen::inRange<size_t>(1, max_num_id_requests);
> ```

It would be better to move it to separate arbitrary generator. It may be done as separate change, so for now ass XXX



_Code quote:_
```cpp
			std::vector<std::pair<unsigned, unsigned>> acquire_release;
			size_t num_elements = *rc::gen::inRange<size_t>(1, max_num_id_requests);
			auto gen_acq_rel = rc::gen::inRange<unsigned>(0, max_acquire_release_ops);
```
___
*[tests/unittest/thread_id.cpp, line 66 at r7](https://reviewable.io/reviews/pmem/pmemstream/66#-MuKy9gi5oHB51jSlBo6:-MuKy9gi5oHB51jSlBo7:bsgah2i) ([raw file](https://github.com/pmem/pmemstream/blob/b4f0807ed0bd01fb1fd377f13807209e990defab/tests/unittest/thread_id.cpp#L66)):*
> ```cpp
> 		}
> 
> 		/* verify that thread id is released after thread dies and can be reused. */
> ```

Please extend this test, for checking if id would be reused when thread with id in the middle ended. 
i.e. 
* spawn 10 threads. 
 * end thread with id 5
* spawn new thread 
* check if id is 5


<!-- Sent from Reviewable.io -->

2022-01-26 12:33 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/id_manager.cpp, line 65 at r7](https://reviewable.io/reviews/pmem/pmemstream/66#-MuKykwuAodJDiuS6DyV:-MuLJRVCBm_0sADNrfna:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b4f0807ed0bd01fb1fd377f13807209e990defab/tests/unittest/id_manager.cpp#L65)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It would be better to move it to separate arbitrary generator. It may be done as separate change, so for now ass XXX
</blockquote></details>

Done.
___
*[tests/unittest/thread_id.cpp, line 66 at r7](https://reviewable.io/reviews/pmem/pmemstream/66#-MuKy9gi5oHB51jSlBo6:-MuLJfR-Bz6kYpIIgXdr:bv24pv8) ([raw file](https://github.com/pmem/pmemstream/blob/b4f0807ed0bd01fb1fd377f13807209e990defab/tests/unittest/thread_id.cpp#L66)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please extend this test, for checking if id would be reused when thread with id in the middle ended. 
i.e. 
* spawn 10 threads. 
 * end thread with id 5
* spawn new thread 
* check if id is 5



</blockquote></details>

I'll do this in the separate PR - code is complicated enough to put it in some helpers header.


<!-- Sent from Reviewable.io -->

2022-01-26 14:16 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/thread_id.cpp, line 66 at r7](https://reviewable.io/reviews/pmem/pmemstream/66#-MuKy9gi5oHB51jSlBo6:-MuLjVPc1g6Z2tMCtBVM:bxwqdpn) ([raw file](https://github.com/pmem/pmemstream/blob/b4f0807ed0bd01fb1fd377f13807209e990defab/tests/unittest/thread_id.cpp#L66)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'll do this in the separate PR - code is complicated enough to put it in some helpers header.
</blockquote></details>

Actually, done here. I decided to save you from reviewing generic thread helpers ;d


<!-- Sent from Reviewable.io -->

2022-01-26 14:42 UTC, karczex commented
___
*[tests/unittest/thread_id.cpp, line 117 at r8](https://reviewable.io/reviews/pmem/pmemstream/66#-MuLpQ-W7KWkyke2WZi0:-MuLpQ-W7KWkyke2WZi1:bq1n3hv) ([raw file](https://github.com/pmem/pmemstream/blob/ca67c57f3abdbfd5c46e65d93fd17954411f81c8/tests/unittest/thread_id.cpp#L117)):*
> ```cpp
> 			stop_threads_cv.notify_all();
> 			for (size_t i = 0; i < threads.size(); i++) {
> 				if (i == thread_to_destroy_index)
> ```

if( threads[i].joinable()) {
    threads[i].join()
} 


<!-- Sent from Reviewable.io -->

2022-01-26 14:52 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MuLrxvK69Stms4_krcp:bnfp4nl)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-26 15:21 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-27 07:36 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-27 11:15 UTC, karczex reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MuQEqf02EGprx_hFG81:bg7igk9)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-27 12:15 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[src/thread_id.c, line 21 at r12](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQ1bqUCwbTJ1LyRPYE:-MuQ1bqUCwbTJ1LyRPYF:bm8h692) ([raw file](https://github.com/pmem/pmemstream/blob/5f3d72442283a2b0ea58b9b2e0eb16ade17fb0ad/src/thread_id.c#L21)):*
> ```C
> 	struct id_manager *id_manager;
> 
> 	/* Number of threads which actively hold some id + 1. Once it drops to 0,
> ```

`'id + 1'` (add '')
___
*[src/thread_id.c, line 30 at r12](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQ1StsDlsQ-8WCXgAh:-MuQ1StsDlsQ-8WCXgAi:bykfiec) ([raw file](https://github.com/pmem/pmemstream/blob/5f3d72442283a2b0ea58b9b2e0eb16ade17fb0ad/src/thread_id.c#L30)):*
> ```C
> struct thread_data {
> 	uint64_t id;
> 	struct thread_id *manager;
> ```

perhaps rename to `key_manager`
___
*[src/thread_id.c, line 36 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQCLs78b1UDiez6yac:-MuQCLs78b1UDiez6yad:br62ofi) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/src/thread_id.c#L36)):*
> ```C
> {
> 	/* Verify that id_manager is empty (it should return id == 0). */
> 	assert(id_manager_acquire(thread_id->id_manager) == 0 && id_manager_release(thread_id->id_manager, 0) == 0);
> ```

as discussed - pls consider change/removal
___
*[src/thread_id.c, line 112 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQO62EChtAFq5xGNRW:-MuQO62EChtAFq5xGNRX:bvpf3wz) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/src/thread_id.c#L112)):*
> ```C
> 		pthread_setspecific(thread_id->key, thread_data);
> 
> 		__atomic_fetch_add(&thread_id->refcount, 1, __ATOMIC_RELAXED);
> ```

shouldn't we ignore the output (for Coverity's sake)?
___
*[tests/common/thread_helpers.hpp, line 134 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQRcTo5wfw7dmnbFiK:-MuQRcTpDpH4nNkuXfoX:bqhwqcn) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/tests/common/thread_helpers.hpp#L134)):*
> ```cpp
> 
> /*
>  * This function executes 'threads_number' threads and provides
> ```

pls drop "This function"
___
*[tests/common/thread_helpers.hpp, line 134 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQRetGESvPl4RW9KMB:-MuQRetGESvPl4RW9KMC:bvf1raf) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/tests/common/thread_helpers.hpp#L134)):*
> ```cpp
> 
> /*
>  * This function executes 'threads_number' threads and provides
> ```

`executes '..' of threads`


<!-- Sent from Reviewable.io -->

2022-01-27 12:30 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/thread_id.c, line 21 at r12](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQ1bqUCwbTJ1LyRPYE:-MuQVO6v3-lyROBfflnR:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5f3d72442283a2b0ea58b9b2e0eb16ade17fb0ad/src/thread_id.c#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`'id + 1'` (add '')
</blockquote></details>

Done.
___
*[src/thread_id.c, line 36 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQCLs78b1UDiez6yac:-MuQVStO7JBV1a9iigWJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/src/thread_id.c#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed - pls consider change/removal
</blockquote></details>

Done.
___
*[src/thread_id.c, line 112 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQO62EChtAFq5xGNRW:-MuQVZWW7sRc6XdaN99R:b7bl6a5) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/src/thread_id.c#L112)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we ignore the output (for Coverity's sake)?
</blockquote></details>

I don't think coverity reports warning in such cases. It's too verbose to add suppresion in all such places anyway imo.
___
*[tests/common/thread_helpers.hpp, line 134 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQRcTo5wfw7dmnbFiK:-MuQVppYB6XS5tRXpdiO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/tests/common/thread_helpers.hpp#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop "This function"
</blockquote></details>

Done.
___
*[tests/common/thread_helpers.hpp, line 134 at r13](https://reviewable.io/reviews/pmem/pmemstream/66#-MuQRetGESvPl4RW9KMB:-MuQVtXBBac1KhVodC13:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/faccc34aabcab0e41438d2a6fb1d9768b57318b8/tests/common/thread_helpers.hpp#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`executes '..' of threads`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-27 12:37 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/66#-:-MuQXVXvEIi4unDEhLOk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-27 12:38 UTC, merged