Test public API
pmem/pmemstream pull request #67
Opened 2022-01-12 16:19 UTC by Karolina002

2022-01-13 07:49 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHORC6-GI23049G79G:-MtHORC6-GI23049G79H:brxgwz) (no related file):*
all tests have to be added for building and actual execution (right now these are not executed in any way).
Please add entries similar to "api_c/stream_from_map.c" in here:
https://github.com/pmem/pmemstream/blob/master/tests/CMakeLists.txt#L82

and run ctest to see if your new tests are executed (I believe some of them may not work, so you'll have to fix them). FYI, in our README file, there's a section on how to run our tests.

---
___
*[tests/api_c/entry_iterator.c, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHNx-g3U6o7bROguzq:-MtHNx-g3U6o7bROguzr:b4nb6nv) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L1)):*
> ```C
> #include "unittest.h"
> ```

pls add license (SPDX tag) in all files
___
*[tests/api_c/entry_iterator.c, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHOBNA3XLTGJWXLg03:-MtHOBNA3XLTGJWXLg04:bbwl90m) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L3)):*
> ```C
> #include "unittest.h"
> ```

you have here two empty lines - one is redundant (pls fix in all files)
___
*[tests/api_c/entry_iterator.c, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHPEIr5OBL3fbpW7S7:-MtHPEIr5OBL3fbpW7S8:b-wamuel) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L30)):*
> ```C
> 	pmemstream_from_map(&stream, 4096, map);
> 
>     struct pmemstream_region *region;	
> ```

whitespaces at the end of the line here should not occur :wink: - when you see e.g. `git diff` there should be red marks showing you these places
___
*[tests/api_c/region_allocate.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHP-gG-RMtzHggCEQ3:-MtHP-gH7kQOIfx80tTC:bd1652v) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_allocate.c#L11)):*
> ```C
> 
> 	struct pmemstream_region region;
> 	
> ```

FYI, you can't have a non-empty line with just whitespaces like here :wink: - please run "make cppformat"


<!-- Sent from Reviewable.io -->

2022-01-13 09:34 UTC, karczex commented
___
*[tests/api_c/entry_iterator.c, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHPEIr5OBL3fbpW7S7:-MtHmNHF8RbBHVhA89uK:b-n1wsef) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L30)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

whitespaces at the end of the line here should not occur :wink: - when you see e.g. `git diff` there should be red marks showing you these places
</blockquote></details>

When you use `make cppformat`, stuff like that would be removed


<!-- Sent from Reviewable.io -->

2022-01-13 09:51 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/api_c/region_iterator.c, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHnyghAx-fJeMvwUvk:-MtHnyghAx-fJeMvwUvl:be2zpnm) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L8)):*
> ```C
> 	struct pmemstream_region_iterator *riter;
> 
>     pmemstream_region_iterator_new(&riter, stream);
> ```

you should also check return values of all those functions (this apply to almost every API call int this PR).
___
*[tests/api_c/region_iterator.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHn8dl80_BZzA4Hcu_:-MtHn8dl80_BZzA4Hcua:bk2mwj3) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L25)):*
> ```C
> 	START();
> 
>     struct pmem2_map *map = map_open(argv[1], 10240, true);
> ```

Please try to avoid magic numbers. You may add it as const variable and use it (or define if you like)


<!-- Sent from Reviewable.io -->

2022-01-13 16:59 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHORC6-GI23049G79G:-MtJNInO3Pcewtzfe_b3:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

all tests have to be added for building and actual execution (right now these are not executed in any way).
Please add entries similar to "api_c/stream_from_map.c" in here:
https://github.com/pmem/pmemstream/blob/master/tests/CMakeLists.txt#L82

and run ctest to see if your new tests are executed (I believe some of them may not work, so you'll have to fix them). FYI, in our README file, there's a section on how to run our tests.
</blockquote></details>

Done.

---
___
*[tests/api_c/entry_iterator.c, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHNx-g3U6o7bROguzq:-MtJN4t2-_3g9UteKbcN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add license (SPDX tag) in all files
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHOBNA3XLTGJWXLg03:-MtJN6mT55dqQnww24DF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you have here two empty lines - one is redundant (pls fix in all files)
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHPEIr5OBL3fbpW7S7:-MtJN8jF3TCbTkPdrMPZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/entry_iterator.c#L30)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

When you use `make cppformat`, stuff like that would be removed
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHnyghAx-fJeMvwUvk:-MtJNFAs7MVG5tJXiEN3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L8)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

you should also check return values of all those functions (this apply to almost every API call int this PR).
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHn8dl80_BZzA4Hcu_:-MtJNFoo6-CNpGm9kwfg:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L25)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please try to avoid magic numbers. You may add it as const variable and use it (or define if you like)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-14 06:55 UTC, KFilipek requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 98 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMJxif0sb4T4J9zU1v:-MtMJxif0sb4T4J9zU1w:b-ajba4x) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/CMakeLists.txt#L98)):*
> ```CMake
> add_test_generic(NAME entry_iterator TRACERS none memcheck pmemcheck drd helgrind)
> ```

2 lines instead of one
___
*[tests/api_c/region_iterator.c, line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMM0L67veOwkZitKvL:-MtMM0L70LEjAS1XFUwb:bs1v8b5) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_iterator.c#L23)):*
> ```C
> 
> 	s = pmemstream_region_iterator_next(riter, &region);
> 	UT_ASSERT(s == 0 || s == -1);
> ```

-1 is returned on case of error, i'm not się, that we should accept every returned value, it's equal to not testing


<!-- Sent from Reviewable.io -->

2022-01-14 06:56 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/api_c/region_iterator.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHn8dl80_BZzA4Hcu_:-MtMMen23DwJA_n-Y_7X:b-v4q3kj) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L25)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still prefer const instead of define


<!-- Sent from Reviewable.io -->

2022-01-14 09:36 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex, @Karolina002, and @KFilipek)

___
*[tests/CMakeLists.txt, line 86 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMt76r9VQLIUCIFFBX:-MtMt76r9VQLIUCIFFBY:b24okr7) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/CMakeLists.txt#L86)):*
> ```CMake
> add_test_generic(NAME stream_from_map TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test(reserve_publish unittest/reserve_publish.cpp)
> ```

there shouldn't be this test here - this test is using rapidcheck and it's defined below (improper merge conflict solution, I guess)
___
*[tests/CMakeLists.txt, line 89 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMwLywAAuf2Y40gqOj:-MtMwLywAAuf2Y40gqOk:b-5bcx97) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/CMakeLists.txt#L89)):*
> ```CMake
> add_test_generic(NAME reserve_publish TRACERS none memcheck pmemcheck)
> 
> build_test(region_allocate api_c/region_allocate.c)
> ```

pls sort these new tests here alphabetically
___
*[tests/api_c/entry_iterator.c, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMuuO_4qi1-X6AgmvV:-MtMuuO_4qi1-X6AgmvW:babucgj) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/entry_iterator.c#L40)):*
> ```C
> 	struct pmem2_map *map = map_open(argv[1], 10 * SIZE, true);
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, 4 * SIZE, map);
> ```

stream and map size can be equal (only region_size should be smaller, because stream take some bytes for its metadata)
___
*[tests/api_c/region_allocate.c, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMucv96oi6cS1Q0KkX:-MtMucv96oi6cS1Q0KkY:b-6jl0wo) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_allocate.c#L7)):*
> ```C
> 
> /**
>  * region_allocate - unit test for pmemstream_region_allocate, pmemstream_region_free,
> ```

you're testing not only allocation, pls rename to e.g. just "region"/"regions" or "region_create" (which is a bit wider name than allocate, IMHO)
___
*[tests/api_c/region_iterator.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/67#-MtHn8dl80_BZzA4Hcu_:-MtMvqDk4npscqpLpn4c:b-lh732d) ([raw file](https://github.com/pmem/pmemstream/blob/502ab1011ab77c1635d6ca6d8821be3f63dec28d/tests/api_c/region_iterator.c#L25)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I still prefer const instead of define
</blockquote></details>

I think we rather use defines in our tests
___
*[tests/api_c/region_iterator.c, line 11 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMuNcl-zbsodGT7AY6:-MtMuNcl-zbsodGT7AY7:bg0w209) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_iterator.c#L11)):*
> ```C
>  */
> 
> #define SIZE 1024
> ```

size of what? pls be more precise

or even better, perhaps just use defines from unittest.h (TEST_DEFAULT_...)
___
*[tests/api_c/region_iterator.c, line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMM0L67veOwkZitKvL:-MtMvWK0-hllE-_QeGNt:b-otl71v) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_iterator.c#L23)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

-1 is returned on case of error, i'm not się, that we should accept every returned value, it's equal to not testing
</blockquote></details>

definitely, we should test separately valid and invalid paths in code


<!-- Sent from Reviewable.io -->

2022-01-17 15:06 UTC, igchor requested changes
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 4 of 6 files reviewed, 19 unresolved discussions (waiting on @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcX4FF4EJJuh5zPdLp:-MtcX4FF4EJJuh5zPdLq:bsgjsns) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L18)):*
> ```C
> 	int s;
> 
> 	s = pmemstream_entry_iterator_new(&eiter, stream, *null_region);
> ```

pmemstream_entry_iterator_new accepts region by value (not by pointer) so what are you testing here? it looks like NULL ptr dereference which is Undefined Behavior.

I would suggest preparing an invalid region and pass it like this:
```
struct pmemstream_region region = {.offset = OFFSET_INVALID};

pmemstream_entry_iterator_new(..., region);
```
and OFFSET_INVALID can be defined to be UINT64_T for example.
___
*[tests/api_c/entry_iterator.c, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYPWy7EsPe1s7J2mu:-MtcYPWy7EsPe1s7J2mv:bz0owy2) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L22)):*
> ```C
> 	UT_ASSERTeq(eiter, NULL);
> 
> 	pmemstream_entry_iterator_new(&eiter, stream, *region);
> ```

Please assert return value
___
*[tests/api_c/entry_iterator.c, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYUgX-6dyc4lAYiDc:-MtcYUgX-6dyc4lAYiDd:bl18fdo) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L24)):*
> ```C
> 	pmemstream_entry_iterator_new(&eiter, stream, *region);
> 	s = pmemstream_entry_iterator_next(eiter, null_region, &entry);
> 	UT_ASSERT(s == -1);
> ```

Why do you expect this to fail? passing NULL to pmemstream_entry_iterator_next should work fine I belive.
___
*[tests/api_c/entry_iterator.c, line 49 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYs_27p8m9derGiPh:-MtcYs_3Dt1AR-PDcm8A:braeo1u) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L49)):*
> ```C
> 	int s;
> 
> 	s = pmemstream_entry_iterator_new(&eiter, null_stream, *null_region);
> ```

As I wrote previosly - region cannot be NULL.
___
*[tests/api_c/entry_iterator.c, line 60 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZ1Tb1_hY6uA9-o2t:-MtcZ1Tb1_hY6uA9-o2u:b-35e1bs) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L60)):*
> ```C
> 	int s;
> 
> 	s = pmemstream_entry_iterator_new(&eiter, stream, *region);
> ```

I think it would be good to also have additional test where we would have first argument to pmemstream_entry_iterator_new as NULL
___
*[tests/api_c/entry_iterator.c, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZJ0YBmpeVGFSjEjL:-MtcZJ0YBmpeVGFSjEjM:b-pa134u) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L64)):*
> ```C
> 	UT_ASSERTne(eiter, NULL);
> 
> 	s = pmemstream_entry_iterator_next(eiter, region, &entry);
> ```

How about additional test with NULL as entry pointer?
___
*[tests/api_c/entry_iterator.c, line 83 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcXSSB5tPUd_EGyVDu:-MtcXSSB5tPUd_EGyVDv:b-470ld8) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L83)):*
> ```C
> 
> 	struct pmemstream_region *region;
> 	pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, region);
> ```

We should probably check return value here.
___
*[tests/api_c/entry_iterator.c, line 89 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYztJ26J2HZ1yPPmo:-MtcYztJ26J2HZ1yPPmp:b-ex0xu8) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L89)):*
> ```C
> 	null_stream_and_region_test(stream, region);
> 	valid_input_test(stream, region);
> ```

How about test which would verify if 
___
*[tests/api_c/region_create.c, line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZTbD8c1gPkvt7FbX:-MtcZTbE1UktZUFQFxmv:b-x6mltf) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L16)):*
> ```C
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_STREAM_SIZE, map);
> 	size_t null_size = NULL;
> ```

Why not just 0? NULL is usually used in context of pointers.
___
*[tests/api_c/region_create.c, line 33 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZeD8A3oiY6pPMJOE:-MtcZeD8A3oiY6pPMJOF:b73djb1) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L33)):*
> ```C
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_STREAM_SIZE, map);
> 	struct pmemstream_region null_region;
> ```

is this region initialized anywhere?


<!-- Sent from Reviewable.io -->

2022-01-17 18:58 UTC, KFilipek requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdAFWz7Cn8Ti-Ay3Z2:-MtdAFX-E63Yp2PpCe_m:b95wq9n) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L18)):*
> ```C
> 	int s;
> 
> 	s = pmemstream_entry_iterator_new(&eiter, stream, *null_region);
> ```

@igchor declaration of NULL pointer and then dereference (*null_region) is not good idea:
```cpp
s = pmemstream_entry_iterator_new(&eiter, stream, *null_region);
```

Is it working at all?



_Code quote:_
```C
struct pmemstream_region *null_region = NULL;
```
___
*[tests/api_c/entry_iterator.c, line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdHpqfABbLz94aX7rN:-MtdHpqgBhkFa9AJRplT:b-j51qcn) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L44)):*
> ```C
> {
> 	struct pmemstream_entry_iterator *eiter;
> 	struct pmemstream_entry entry;
> ```

`unused variable 'entry'`



_Code quote:_
```C
struct pmemstream_entry entry;
```
___
*[tests/api_c/entry_iterator.c, line 57 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdL5VqElT2EhKcKKpm:-MtdL5VrAJJAoXn-1g3o:b-j51qcn) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L57)):*
> ```C
> {
> 	struct pmemstream_entry_iterator *eiter;
> 	struct pmemstream_entry entry;
> ```

`unused variable 'entry'`
___
*[tests/api_c/entry_iterator.c, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdLmxFC5HCyBl8Tzmm:-MtdLmxFC5HCyBl8Tzmn:bhcw4ri) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L64)):*
> ```C
> 	UT_ASSERTne(eiter, NULL);
> 
> 	s = pmemstream_entry_iterator_next(eiter, region, &entry);
> ```

`warning: passing argument 2 of 'pmemstream_region_iterator_next' from incompatible pointer type [-Wincompatible-pointer-types]`



_Code quote:_
```C
s = pmemstream_entry_iterator_next(eiter, region, &entry);
```
___
*[tests/api_c/entry_iterator.c, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdM8ZA7sl_X7JnDr2B:-MtdM8ZA7sl_X7JnDr2C:bxvvkrf) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L87)):*
> ```C
> 	null_region_test(stream, region);
> 	null_stream_test(stream, region);
> 	null_stream_and_region_test(stream, region);
> ```

`warning: 'region' is used uninitialized in this function [-Wuninitialized]`



_Code quote:_
```C
null_stream_and_region_test(stream, region);
```
___
*[tests/api_c/region_create.c, line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZTbD8c1gPkvt7FbX:-MtdDun1BH9sniMkBdYr:b9c53bu) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why not just 0? NULL is usually used in context of pointers.
</blockquote></details>

compiler warning:



_Code snippet:_
```C
warning: initialization of 'size_t' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
```
___
*[tests/api_c/region_create.c, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdEC7qA5kuwgexfBEL:-MtdEC7qA5kuwgexfBEM:bvb9qxt) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L34)):*
> ```C
> 	pmemstream_from_map(&stream, TEST_DEFAULT_STREAM_SIZE, map);
> 	struct pmemstream_region null_region;
> 	int s;
> ```

Compilation error: conflicting types for 's'



_Code quote:_
```C
	int s;

	size_t s;
```
___
*[tests/api_c/region_create.c, line 37 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdEwnGBIL-jexosAYH:-MtdEwnGBIL-jexosAYI:bslfahs) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L37)):*
> ```C
> 
> 	size_t s;
> 	s = pmemstream_region_size(stream, null_region);
> ```

```conversion to 'size_t' {aka 'long unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]```



_Code quote:_
```C
s = pmemstream_region_size(stream, null_region);
```
___
*[tests/api_c/region_create.c, line 42 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdE_3oCh5ZWbLfpMZf:-MtdE_3p1MpbjfaWNfDu:b-skchbw) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L42)):*
> ```C
> 	struct pmemstream_region_runtime *rtm = NULL;
> 	s = pmemstream_get_region_runtime(stream, null_region, &rtm);
> 	UT_ASSERT(s == -1);
> ```

Tell me why it's not correct.



_Code quote:_
```C
UT_ASSERT(s == -1);
```
___
*[tests/api_c/region_create.c, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdKlfa6_kV3HBcNgUE:-MtdKlfa6_kV3HBcNgUF:b8ns19i) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L64)):*
> ```C
> 	UT_ASSERTne(&region, NULL);
> 
> 	size_t s;
> ```

`error: conflicting types for 's'`



_Code quote:_
```C
size_t s;
```
___
*[tests/api_c/region_iterator.c, line 21 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdGhg8-wIAo9K3TXb6:-MtdGhg8-wIAo9K3TXb7:b7yb9w2) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_iterator.c#L21)):*
> ```C
> 	UT_ASSERTne(riter, NULL);
> 
> 	s = pmemstream_region_iterator_next(riter, &null_region);
> ```

why address to pointer? `&null_region`
Compiler warning:
`warning: passing argument 2 of 'pmemstream_region_iterator_next' from incompatible pointer type [-Wincompatible-pointer-types]`



_Code quote:_
```C
s = pmemstream_region_iterator_next(riter, &null_region);
```
___
*[tests/api_c/region_iterator.c, line 67 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdMhI1-mIHJlEsELGd:-MtdMhI2DH31oZaWBhD8:bcel88m) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_iterator.c#L67)):*
> ```C
> 	struct pmemstream_region *region;
> 
> 	pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, region);
> ```

`'region' is used uninitialized in this function`



_Code quote:_
```C
pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, region);
```


<!-- Sent from Reviewable.io -->

2022-01-18 08:50 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 86 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMt76r9VQLIUCIFFBX:-MtgM7oQ3ZMTis9TtdqS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/CMakeLists.txt#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there shouldn't be this test here - this test is using rapidcheck and it's defined below (improper merge conflict solution, I guess)
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 89 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMwLywAAuf2Y40gqOj:-MtgMEorDO8rI9R3X2aH:bs7wumb) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/CMakeLists.txt#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls sort these new tests here alphabetically
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMuuO_4qi1-X6AgmvV:-MtgMfsz010rM8YdiIZI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/entry_iterator.c#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

stream and map size can be equal (only region_size should be smaller, because stream take some bytes for its metadata)
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 11 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMuNcl-zbsodGT7AY6:-MtgN8RB-8lLrWrI57zf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_iterator.c#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

size of what? pls be more precise

or even better, perhaps just use defines from unittest.h (TEST_DEFAULT_...)
</blockquote></details>

Done.
___
*[tests/api_c/region_allocate.c, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/67#-MtMucv96oi6cS1Q0KkX:-MtgNCuGCo0ohUNGFEGh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f5bd7d043ffa276dfc0178b35abe3f5df1d2a3ee/tests/api_c/region_allocate.c#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you're testing not only allocation, pls rename to e.g. just "region"/"regions" or "region_create" (which is a bit wider name than allocate, IMHO)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 09:54 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdAFWz7Cn8Ti-Ay3Z2:-MtgacFr8axRE5pTp_OB:blzy2pd) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@igchor declaration of NULL pointer and then dereference (*null_region) is not good idea:
```cpp
s = pmemstream_entry_iterator_new(&eiter, stream, *null_region);
```

Is it working at all?
</blockquote></details>

As I wrote above, this is UB. It's fine to declare this pointer (for readability) but it's not OK to dereference it.


<!-- Sent from Reviewable.io -->

2022-01-18 12:12 UTC, karczex commented
___
*[tests/api_c/entry_iterator.c, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth5bh4AQpH_KwuSWZY:-Mth5bh51bCmFxaY-2zc:burecj1) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L24)):*
> ```C
> 	pmemstream_entry_iterator_new(&eiter, stream, *region);
> 	s = pmemstream_entry_iterator_next(eiter, null_region, &entry);
> 	UT_ASSERT(s == -1);
> ```

UT_ASSERTeq


<!-- Sent from Reviewable.io -->

2022-01-18 12:13 UTC, karczex commented
___
*[tests/api_c/entry_iterator.c, line 37 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth5ieb8mgKs44_0Azy:-Mth5iec--xFtpfBdJV2:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L37)):*
> ```C
> 
> 	s = pmemstream_entry_iterator_new(&eiter, null_stream, *region);
> 	UT_ASSERT(s == -1);
> ```

.


<!-- Sent from Reviewable.io -->

2022-01-18 12:38 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 30 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth7rdrCKnnsFomALu2:-Mth7rds9XQFS6qUvG_2:b20k55j) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L16)):*
> ```C
> 	struct pmemstream_entry entry;
> 	struct pmemstream_region *null_region = NULL;
> 	int s;
> ```

this name `s` is probably taken from pmemkv, where 's' stands for 'status' :wink: 

here we rather use 'ret' as a 'returned value' - pls fix all
___
*[tests/api_c/entry_iterator.c, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth5bh4AQpH_KwuSWZY:-Mth7Q0QC0Suw4ICfiyt:b5ntg25) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

UT_ASSERTeq
</blockquote></details>

yeah, pls use it whenever possible.

UT_ASSERTeq is better than UT_ASSERT because it prints the expected and given number (return code in this case)
___
*[tests/api_c/entry_iterator.c, line 89 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYztJ26J2HZ1yPPmo:-Mth8WMjBD21KRb5Nr27:b-g31rku) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L89)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about test which would verify if 
</blockquote></details>

@igchor, I think you didn't finish this sentence :wink: or you're just keeping us in suspense :smile: 
___
*[tests/api_c/region_create.c, line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth8jhY48A4lF10rJIG:-Mth8jhY48A4lF10rJIH:blsbw9s) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L8)):*
> ```C
> /**
>  * region_create - unit test for pmemstream_region_allocate, pmemstream_region_free,
>  * 					 pmemstream_region_size, pmemstream_get_region_runtime
> ```

I believe you can't have space before tabs :wink: unfortunately, I think, you have to fix it manually (?)
___
*[tests/api_c/region_create.c, line 66 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MthA2uA8QGxVRVqHu1O:-MthA2uA8QGxVRVqHu1P:bctmx6k) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L66)):*
> ```C
> 	size_t s;
> 	s = pmemstream_region_size(stream, region);
> 	UT_ASSERTne(s, NULL);
> ```

similarily to what Igor commented above, we normally wouldn't expect non-pointer var to be equal to NULL. Here you should rather expect `s != 0` and what's more it should be `s >= size` (it's equal or bigger, because of our **aligning up** the size)
___
*[tests/api_c/region_create.c, line 91 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MthAhSz1UhXIceMmq76:-MthAhT-CqtIBFkbmYH1:b-e76kc7) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L91)):*
> ```C
> 	null_size_test(path);
> 	null_region_test(path);
> 	valid_input_test(path, TEST_DEFAULT_REGION_SIZE);
> ```

since you have this nice test parametrized with size, you can run it more than just once :wink:


<!-- Sent from Reviewable.io -->

2022-01-20 11:51 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 6 files reviewed, 30 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth7rdrCKnnsFomALu2:-MtrJ7OR5yIZKIzFiBs7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this name `s` is probably taken from pmemkv, where 's' stands for 'status' :wink: 

here we rather use 'ret' as a 'returned value' - pls fix all
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcX4FF4EJJuh5zPdLp:-MtrJ8Bs4agPncVUrx4O:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

pmemstream_entry_iterator_new accepts region by value (not by pointer) so what are you testing here? it looks like NULL ptr dereference which is Undefined Behavior.

I would suggest preparing an invalid region and pass it like this:
```
struct pmemstream_region region = {.offset = OFFSET_INVALID};

pmemstream_entry_iterator_new(..., region);
```
and OFFSET_INVALID can be defined to be UINT64_T for example.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdAFWz7Cn8Ti-Ay3Z2:-MtrJ8xm-KZq-W7YQ910:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'm okey with this declaration :)
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYPWy7EsPe1s7J2mu:-MtrJAXG9F-cvGbUVAbP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please assert return value
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYUgX-6dyc4lAYiDc:-MtrJC2YDL5vizEwqG6h:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L24)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why do you expect this to fail? passing NULL to pmemstream_entry_iterator_next should work fine I belive.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth5bh4AQpH_KwuSWZY:-MtrJCWw9PzH3ueOiq1X:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, pls use it whenever possible.

UT_ASSERTeq is better than UT_ASSERT because it prints the expected and given number (return code in this case)
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 37 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth5ieb8mgKs44_0Azy:-MtrJDXPBeXmY9kD9qhE:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L37)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdHpqfABbLz94aX7rN:-MtrJEIHBcL8a_n6HQeg:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L44)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`unused variable 'entry'`
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 49 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcYs_27p8m9derGiPh:-MtrJFB8AKfPzFZF6NwO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L49)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

dereference also cannot be done
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 57 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdL5VqElT2EhKcKKpm:-MtrJG-u8fCHFZvW1Fwl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L57)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`unused variable 'entry'`
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 60 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZ1Tb1_hY6uA9-o2t:-MtrJI7i46HzKxD7Ebqv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be good to also have additional test where we would have first argument to pmemstream_entry_iterator_new as NULL
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZJ0YBmpeVGFSjEjL:-MtrJIcG7racnZXQGk4t:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about additional test with NULL as entry pointer?
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 64 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdLmxFC5HCyBl8Tzmm:-MtrJJM8ElYKan-RE59D:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L64)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`warning: passing argument 2 of 'pmemstream_region_iterator_next' from incompatible pointer type [-Wincompatible-pointer-types]`
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 83 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcXSSB5tPUd_EGyVDu:-MtrJM1a-ESIb1MD1qA4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L83)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We should probably check return value here.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtdM8ZA7sl_X7JnDr2B:-MtrJN-85VDSz8GJQHSD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/entry_iterator.c#L87)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`warning: 'region' is used uninitialized in this function [-Wuninitialized]`
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MtcZTbD8c1gPkvt7FbX:-MtrJVqlDfoMyDIV3Wti:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L1 [...]

2022-01-20 11:51 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 6 files reviewed, 30 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/region_create.c, line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-Mth8jhY48A4lF10rJIG:-MtrJy_K3EfgNl4jBWSc:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can't have space before tabs :wink: unfortunately, I think, you have to fix it manually (?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 13:47 UTC, KFilipek requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 6 files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtrhpb41lz6FnWmLMYq:-Mtrhpb41lz6FnWmLMYr:bhaoy9n) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L45)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	ret = pmemstream_entry_iterator_new(&eiter, null_stream, region);
> ```

after some calls:
```
#0 pmemstream_offset_to_ptr (stream=0x0, offset=0) libpmemstream_internal.h:53
span_offset_to_span_ptr (stream=0x0, offset=0) span.c:14
span_get_region_runtime (stream=0x0, offset=0) span.c:106
entry_iterator_initialize (iterator=0x561d357fb2e0, stream=0x0, region=...) iterator.c:59
pmemstream_entry_iterator_new (iterator=0x7ffc61c855a0, stream=0x0, region=...) iterator.c:82
null_stream_test (stream=0x561d357fb470) entry_iterator.c:45
main (argc=2, argv=0x7ffc61c856f8) entry_iterator.c:132
```
You are finally here with `stream==null`:
```
static inline const uint8_t *pmemstream_offset_to_ptr(const struct pmemstream *stream, uint64_t offset)
{
	return (const uint8_t *)stream->data->spans + offset;
}
```
You should also add check for `stream==null` in `pmemstream_entry_iterator_new()`



_Code quote:_
```C
ret = pmemstream_entry_iterator_new(&eiter, null_stream, region);
```
___
*[tests/api_c/entry_iterator.c, line 129 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrgbWCCS1x8-9KsSjF:-MtrgbWDAJb630_TVYJy:bwramk8) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L129)):*
> ```C
> 	struct pmem2_map *map = map_open(argv[1], TEST_DEFAULT_STREAM_SIZE, true);
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_STREAM_SIZE, map);
> ```

**TEST_DEFAULT_STREAM_SIZE** - I suppose, this argument should be block_size, not stream_size



_Code quote:_
```C
pmemstream_from_map(&stream, TEST_DEFAULT_STREAM_SIZE, map);
```


<!-- Sent from Reviewable.io -->

2022-01-20 13:48 UTC, KFilipek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 6 files reviewed, 29 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtrhpb41lz6FnWmLMYq:-Mtrjdro-WN8y4ptJ3cd:b-81qit1) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L45)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

after some calls:
```
#0 pmemstream_offset_to_ptr (stream=0x0, offset=0) libpmemstream_internal.h:53
span_offset_to_span_ptr (stream=0x0, offset=0) span.c:14
span_get_region_runtime (stream=0x0, offset=0) span.c:106
entry_iterator_initialize (iterator=0x561d357fb2e0, stream=0x0, region=...) iterator.c:59
pmemstream_entry_iterator_new (iterator=0x7ffc61c855a0, stream=0x0, region=...) iterator.c:82
null_stream_test (stream=0x561d357fb470) entry_iterator.c:45
main (argc=2, argv=0x7ffc61c856f8) entry_iterator.c:132
```
You are finally here with `stream==null`:
```
static inline const uint8_t *pmemstream_offset_to_ptr(const struct pmemstream *stream, uint64_t offset)
{
	return (const uint8_t *)stream->data->spans + offset;
}
```
You should also add check for `stream==null` in `pmemstream_entry_iterator_new()`
</blockquote></details>

I mean, check = return -1 value when null_stream is passed.


<!-- Sent from Reviewable.io -->

2022-01-20 14:17 UTC, KFilipek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 6 files reviewed, 35 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 21 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrnYbM60yjU-_fnLBN:-MtrnYbM60yjU-_fnLBO:b4lrzjo) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L21)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	ret = pmemstream_entry_iterator_new(&eiter, stream, invalid_region);
> ```

This is very first sigabort you get. (span.c:12)
UINT64_MAX probably is not divisible by `sizeof(span_bytes)` and this assert fails.



_Code quote:_
```C
ret = pmemstream_entry_iterator_new(&eiter, stream, invalid_region);
```
___
*[tests/api_c/entry_iterator.c, line 45 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtrhpb41lz6FnWmLMYq:-Mtrkax-CIH0lPfbkv7J:bld32oi) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L45)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I mean, check = return -1 value when null_stream is passed.
</blockquote></details>

```cpp
	if (!iter || stream == NULL) {
		*iterator = NULL;
		return -1;
	}
```
___
*[tests/api_c/entry_iterator.c, line 56 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrmFPS4im-oXcFIzXc:-MtrmFPS4im-oXcFIzXd:b-s42b2f) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L56)):*
> ```C
> 	struct pmemstream_entry_iterator *eiter;
> 	struct pmemstream_region invalid_region = {.offset = UINT64_MAX};
> 	struct pmemstream *null_stream = NULL;
> ```

maybe: set this pointer to `0xDEAD` or something nonrandom, then we will check that pointer was set to NULL due to `pmemstream_entry_iterator_new` fail



_Code quote:_
```C
struct pmemstream *null_stream = NULL;
```
___
*[tests/api_c/entry_iterator.c, line 61 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrlZhN8o5ZfUu7heMD:-MtrlZhN8o5ZfUu7heME:b-ab1kii) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L61)):*
> ```C
> 	ret = pmemstream_entry_iterator_new(&eiter, null_stream, invalid_region);
> 	UT_ASSERTeq(ret, -1);
> 	UT_ASSERTeq(eiter, NULL);
> ```

It's ok, but you should also add logic to set `eiter` to NULL :)
But please check how libpmem2/libpmemset deal with such cases.



_Code quote:_
```C
UT_ASSERTeq(eiter, NULL);
```
___
*[tests/api_c/entry_iterator.c, line 63 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrlE6_AgPTHVe-ufsP:-MtrlE6_AgPTHVe-ufsQ:bb5iw6n) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L63)):*
> ```C
> 	UT_ASSERTeq(eiter, NULL);
> 
> 	pmemstream_region_free(stream, invalid_region);
> ```

You are freeing passed argument `stream`, but it's not used here.



_Code quote:_
```C
stream
```
___
*[tests/api_c/entry_iterator.c, line 71 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtroWe0AcWsd0xrDTuL:-MtroWe0AcWsd0xrDTuM:bdjvamz) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L71)):*
> ```C
> 	struct pmemstream_entry_iterator *eiter = NULL;
> 	struct pmemstream_region region;
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> ```

region not freed at the end



_Code quote:_
```C
ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
```
___
*[tests/api_c/entry_iterator.c, line 75 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtro___9IL0VYGUe-l8:-Mtro___9IL0VYGUe-l9:bdm5r9z) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L75)):*
> ```C
> 
> 	ret = pmemstream_entry_iterator_new(&eiter, stream, region);
> 	UT_ASSERTeq(ret, 0);
> ```

I believe this cannot be either `ret=0` and `eiter=NULL`



_Code quote:_
```C
	UT_ASSERTeq(ret, 0);
	UT_ASSERTne(eiter, NULL);
```


<!-- Sent from Reviewable.io -->

2022-01-20 14:19 UTC, KFilipek reviewed
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 5 of 6 files reviewed, 26 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-21 08:06 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 5 of 6 files reviewed, 26 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 32 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtv_2sz8Mr9JfPUz4it:-Mtv_2sz8Mr9JfPUz4iu:b-bs9faa) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L32)):*
> ```C
> 
> 	pmemstream_entry_iterator_delete(&eiter);
> 	pmemstream_region_free(stream, invalid_region);
> ```

you rather can't call free on invalid_region
___
*[tests/api_c/entry_iterator.c, line 56 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrmFPS4im-oXcFIzXc:-Mtvcs2x5mQp6i-smRCO:b-yloje9) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L56)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

maybe: set this pointer to `0xDEAD` or something nonrandom, then we will check that pointer was set to NULL due to `pmemstream_entry_iterator_new` fail
</blockquote></details>

to be honest there's nothing to check here, and this variable is rather unnecessary, you can just pass NULL to the function (we don't require to pass a variable as this param because we don't return anything). Please fix where applicable.
___
*[tests/api_c/entry_iterator.c, line 63 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrlE6_AgPTHVe-ufsP:-MtvcLSQ7e7z8W3yLYey:b-nbeiph) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L63)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You are freeing passed argument `stream`, but it's not used here.
</blockquote></details>

it's `pmemstream_region_free` function, so the stream is here alright, but (as I stated in another comment) - I'm not sure if you can free an invalid_region
___
*[tests/api_c/entry_iterator.c, line 91 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtvaMT66s0YuMHsnAjD:-MtvaMT66s0YuMHsnAjE:bvezzof) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L91)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> 	ret = pmemstream_entry_iterator_next(eiter, &region, entry);
> ```

the second parameter here is not well described in the code (nor in the docs) yet - this is an out param, where you can return a region affiliated with the (also returned) entry. You can easily pass NULL here.

Of course, we should have a separate test, where we use this properly (with an uninitialized region) and compare with the region we allocated to see if they match.
___
*[tests/api_c/region_create.c, line 66 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MthA2uA8QGxVRVqHu1O:-MtvedUL6c2Yk9KLWACw:b-16j81m) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L66)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

as I wrote previously, we can make this check more precise - `region_size >= size`
___
*[tests/api_c/region_create.c, line 46 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtveDM31KPhJFNkKeEq:-MtveDM31KPhJFNkKeEr:b-z3g8tw) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/region_create.c#L46)):*
> ```C
> 
> 	ret = pmemstream_region_free(stream, invalid_region);
> 	UT_ASSERTeq(ret, -1);
> ```

FYI, in here call of region_free with something that is not a proper region is alright - here we expect to return -1, and that's cool.


<!-- Sent from Reviewable.io -->

2022-01-21 11:11 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 5 of 6 files reviewed, 22 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 21 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrnYbM60yjU-_fnLBN:-MtwIPBB018WaFnprccM:b6rv2mi) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

This is very first sigabort you get. (span.c:12)
UINT64_MAX probably is not divisible by `sizeof(span_bytes)` and this assert fails.
</blockquote></details>

Right, you probably need to align offset to 8 bytes.


<!-- Sent from Reviewable.io -->

2022-01-24 15:43 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/entry_iterator.c, line 63 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrlE6_AgPTHVe-ufsP:-MuAllCR65Eqv4SaEic6:b-i9u27b) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's `pmemstream_region_free` function, so the stream is here alright, but (as I stated in another comment) - I'm not sure if you can free an invalid_region
</blockquote></details>

After few force-pushed commits this discussion is detached. I pointed not used stream, not region, since last revision it's resolved.


<!-- Sent from Reviewable.io -->

2022-01-30 19:27 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 2 of 8 files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 21 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrnYbM60yjU-_fnLBN:-MugRApEC-R7VKb0aZB7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L21)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, you probably need to align offset to 8 bytes.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 32 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtv_2sz8Mr9JfPUz4it:-MugREov3YoEP5QUa-cz:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you rather can't call free on invalid_region
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-31 10:48 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 4 of 8 files reviewed, 25 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/67#-MujeDa72C4WdF_tVjTw:-MujeDa72C4WdF_tVjTx:b-ym9fr5) (no related file):*
FYI, if you believe this PR is ready for review - please un-draft it - clicking "Ready for review" button on the bottom of the PR page.

---
___
*[tests/api_c/append_entry.c, line 4 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujcaYV7NO6MCYQyIzH:-MujcaYV7NO6MCYQyIzI:bpor45c) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L4)):*
> ```C
> /* Copyright 2021-2022, Intel Corporation */
> 
> #include "libpmemstream_internal.h"
> ```

wy do you need this include? if only for `span_bytes` definition, it's defined in span.h
___
*[tests/api_c/append_entry.c, line 6 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujW1IR4LZuKySDGbhz:-MujW1IR4LZuKySDGbi-:b-zbxp6j) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L6)):*
> ```C
> #include "libpmemstream_internal.h"
> #include "unittest.h"
> #include <common/util.h>
> ```

FYI, if you're including our local sources please use `""` instead of `<>`
___
*[tests/api_c/append_entry.c, line 73 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujWyXyBmhraHVwIWPQ:-MujWyXz9uLbhGfIVIZu:b-shg7l9) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L73)):*
> ```C
> {
> 	int ret;
> 	struct entry_data *data = NULL;
> ```

you don't have to create a variable and assign null, you can just use null in the _append call
___
*[tests/api_c/append_entry.c, line 84 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujaPX54IgXJWROUf02:-MujaPX54IgXJWROUf03:b-o9ctyu) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L84)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

as in prev. PR - such checks are not necessary (variable on stack will never be null)
___
*[tests/api_c/append_entry.c, line 132 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujbSWl60_puuAaK_K8:-MujbSWl60_puuAaK_K9:bk3y1x9) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L132)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	struct pmemstream_region region;
> ```

do you need this region in this function?
___
*[tests/api_c/append_entry.c, line 138 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujbpG-8DypT7Tc_ggf:-MujbpG-8DypT7Tc_ggg:bqpkn89) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L138)):*
> ```C
> 
> 	entry_data = pmemstream_entry_data(stream, entry);
> 	UT_ASSERTeq(entry_data, NULL);
> ```

I'm not sure what we expect from this test? If you want to make sure that `pmemstream_entry_data` will return NULL from the invalid entry, you should set the initial value of `*entry_data` to something else than NULL.
___
*[tests/api_c/append_entry.c, line 162 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujcG0q5deN8noP4iJ3:-MujcG0q5deN8noP4iJ4:b-8pnlpw) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L162)):*
> ```C
> 	null_entry_test(path);
> 	invalid_entry_test(path);
> ```

what about null-ed stream (first param of pmemstream_append, pmemstream_entry_data, and pmemstream_entry_length)

and, I guess, we may test also null/non-null region_runtime in _append
___
*[tests/api_c/entry_iterator.c, line 59 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujdH2jCjRfdaIY9HAm:-MujdH2jCjRfdaIY9HAn:b-4j2sop) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L59)):*
> ```C
> 	UT_ASSERTeq(eiter, NULL);
> 
> 	ret = pmemstream_entry_iterator_new(&eiter, stream, region);
> ```

why do you want to test entry_iterator_new on a proper region in `invalid_region_test`? I'd say we only want to test that `entry_iterator_new` on invalid_region will not work.
___
*[tests/api_c/entry_iterator.c, line 71 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujdlbiCF9dfqZk9hEb:-MujdlbiCF9dfqZk9hEc:b-kuoosp) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L71)):*
> ```C
> }
> 
> void null_stream_test(char *path)
> ```

you sure the name of this function is proper? I can't see null stream here
___
*[tests/api_c/entry_iterator.c, line 128 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujiiAd4cxg82JGD3NG:-MujiiAd4cxg82JGD3NH:b-ymu6ma) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L128)):*
> ```C
> }
> 
> void null_entry_test(char *path)
> ```

thanks to this test we may get rid of this comment:
https://github.com/pmem/pmemstream/blob/master/src/iterator.c#L186


<!-- Sent from Reviewable.io -->

2022-01-31 13:51 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 9 files reviewed, 25 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/append_entry.c, line 4 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujcaYV7NO6MCYQyIzH:-MukMqUVERdR9wHs3Exu:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

wy do you need this include? if only for `span_bytes` definition, it's defined in span.h
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 73 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujWyXyBmhraHVwIWPQ:-MukMzA09P_W5W0SkEG4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L73)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to create a variable and assign null, you can just use null in the _append call
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 84 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujaPX54IgXJWROUf02:-MukMyuXEcaYKxZt0HzQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as in prev. PR - such checks are not necessary (variable on stack will never be null)
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 132 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujbSWl60_puuAaK_K8:-MukN1Lr1uHafUqqVyGY:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this region in this function?
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 71 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtroWe0AcWsd0xrDTuL:-MukOjKOADt9R53WJDhR:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L71)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

region not freed at the end
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 75 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-Mtro___9IL0VYGUe-l8:-MukOm4F85jW6SqY8AC0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I believe this cannot be either `ret=0` and `eiter=NULL`
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 129 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtrgbWCCS1x8-9KsSjF:-MukOq2OAP4D3niqLL4g:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L129)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

**TEST_DEFAULT_STREAM_SIZE** - I suppose, this argument should be block_size, not stream_size
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 59 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujdH2jCjRfdaIY9HAm:-MukNHJ-6OXdNFbPnVXU:b-85j8lr) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do you want to test entry_iterator_new on a proper region in `invalid_region_test`? I'd say we only want to test that `entry_iterator_new` on invalid_region will not work.
</blockquote></details>

It is needed for the entry_iterator_next function to work properly (to pass valid eiter).
___
*[tests/api_c/entry_iterator.c, line 71 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujdlbiCF9dfqZk9hEb:-MukNnl64fc95VNYa6KI:b-eknvo9) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you sure the name of this function is proper? I can't see null stream here
</blockquote></details>

I pass NULL as a parameter to entry_iterator_new without assigning it to the variable *stream.
___
*[tests/api_c/entry_iterator.c, line 128 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujiiAd4cxg82JGD3NG:-MukOmbw95HPEqU-sXNg:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/entry_iterator.c#L128)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

thanks to this test we may get rid of this comment:
https://github.com/pmem/pmemstream/blob/master/src/iterator.c#L186
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 66 at r3](https://reviewable.io/reviews/pmem/pmemstream/67#-MthA2uA8QGxVRVqHu1O:-MukOuZgC0W2DOtQYpbs:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e208e61a18065788446b215c8f85a1026307931a/tests/api_c/region_create.c#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as I wrote previously, we can make this check more precise - `region_size >= size`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 10:40 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 4 of 9 files reviewed, 22 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/67#-MujeDa72C4WdF_tVjTw:-MuooTXzCN6its6A3wif:bpx9hax) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, if you believe this PR is ready for review - please un-draft it - clicking "Ready for review" button on the bottom of the PR page.
</blockquote></details>

I can see you marked this PR as ready, but the CI is still failing... meaning it's not ready :wink: As discussed yesterday - please make the CI green again, e.g. by commenting out the tests that are leading to pmemstream failures (perhaps add links in the comments to the newly filed issues).

---
___
*[tests/api_c/append_entry.c, line 6 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-Muor9Si-Qr4xRfdWjrs:-Muor9Si-Qr4xRfdWjrt:bxhvwvf) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L6)):*
> ```C
> #include "libpmemstream_internal.h"
> #include "unittest.h"
> #include <common/util.h>
> ```

don't you need this include for `ALIGN_*` macros?
___
*[tests/api_c/append_entry.c, line 84 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujaPX54IgXJWROUf02:-Muor4C03z4lSWjwJhRo:b57s80g) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L84)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please fix in all such places, not just this one


<!-- Sent from Reviewable.io -->

2022-02-08 11:08 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 9 files reviewed, 23 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/append_entry.c, line 51 at r7](https://reviewable.io/reviews/pmem/pmemstream/67#-MvO084q97EyavIHdSiA:-MvO084q97EyavIHdSiB:b-pzwdc8) ([raw file](https://github.com/pmem/pmemstream/blob/ae2a5e850b5faf093459f66281f498dd487d400a/tests/api_c/append_entry.c#L51)):*
> ```C
> 	int ret;
> 	struct entry_data data;
> 	data.data = UINT64_MAX;
> ```

Please try to use PTRDIFF_MAX here and in other placers to avoid overflow


<!-- Sent from Reviewable.io -->

2022-02-08 13:23 UTC, KFilipek reviewed
> Reviewed 1 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-02-14 09:08 UTC, Karolina002 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67#-:-MvrTpZa-8O_OTihfaYm:bnfp4nl)* status: 5 of 9 files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/67#-MujeDa72C4WdF_tVjTw:-MvrTrP_5TKp1p8-6oTl:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I can see you marked this PR as ready, but the CI is still failing... meaning it's not ready :wink: As discussed yesterday - please make the CI green again, e.g. by commenting out the tests that are leading to pmemstream failures (perhaps add links in the comments to the newly filed issues).
</blockquote></details>

Done.

---
___
*[tests/api_c/append_entry.c, line 6 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-Muor9Si-Qr4xRfdWjrs:-MvOr_qkDQ_3Mi7gmYLP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't you need this include for `ALIGN_*` macros?
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 84 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujaPX54IgXJWROUf02:-MvOrfgPCmHrj1RGqEBh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please fix in all such places, not just this one
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 91 at r4](https://reviewable.io/reviews/pmem/pmemstream/67#-MtvaMT66s0YuMHsnAjD:-MvrUCzWExzCp37rmZ5U:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bae8485301649639fb8b3230e7496afcde01573c/tests/api_c/entry_iterator.c#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the second parameter here is not well described in the code (nor in the docs) yet - this is an out param, where you can return a region affiliated with the (also returned) entry. You can easily pass NULL here.

Of course, we should have a separate test, where we use this properly (with an uninitialized region) and compare with the region we allocated to see if they match.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 14:41 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 3 of 9 files reviewed, 22 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/append_entry.c, line 6 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-Muor9Si-Qr4xRfdWjrs:-MwgA6PI4KSHnoKN6KrY:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done, `ALIGN_*` macros are defined in `common/util.h`, so it should be included here
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 138 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujbpG-8DypT7Tc_ggf:-MwgAA9k6hEAMSZ7QISM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

bump
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 6 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-Mvs9WkXBiMNspGUXpTQ:-MwgACxX9ggyZi-ZHj2o:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

same here, you have to include common/util (pls fix whenever applicable; where you use `ALIGN_*`)
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 61 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsBAHz7jbbVlFFBioX:-Mw12oF3-STwIRfd-n6_:bsdsi54) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

The second param given here is an output param, so passing here `invalid_region` does not make any difference.

The below check works only because we have no entries in the stream, so it returns `-1`.
</blockquote></details>

I'm aware of that. In valid_input_test the return value is also expected to be -1.
___
*[tests/api_c/entry_iterator.c, line 94 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsCRD2E3KBEQ0QOZ60:-MwgAFUe3iEe1LSNAVZR:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L94)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why not just pass null below - I believe this var is redundant
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 113 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsCvZi7xLqhcNPkRei:-MwgAHZ79ylzoqe3m8Uu:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe this test does not verify much. We pass here a proper variable (with some value; equal to null in our case). This function, though, gets `struct pmemstream_entry_iterator **iterator` as a first param, so we're actually missing some check/assert within the `pmemstream_entry_iterator_new` function, that the "iterator" is given (let's try to pass here just `NULL` (instead of `&eiter`) and you'll see an error).
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 47 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsFisQ0WZCs1ucwO7X:-MwgAJk79Iwj9O4mMBVU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_create.c#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this `zero_size` variable? :wink: 
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 62 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsHgpv5tDAgl66PoAQ:-MwgAKSNAJBElvUueu7D:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_create.c#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls mark this line with a comment "XXX: to be verified, we should not get a proper size here"
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 48 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsLHOs0YKbjsoAhCDM:-MwgALkV45nxlD2CUm7_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_iterator.c#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls assign NULL here
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 57 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsMxF42i8PQJ27SZ8r:-MwgAOoJANqZck1rw-_g:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_iterator.c#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

similar situation to entry_iter_next - the second param is just an output param, so it doesn't matter what we'll pass there.
The check here passes, only because region_iter_next has nothing to return (there are no regions).

what we could actually check here is if the variable's value didn't change
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 67 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsNbo4Bh2bYpsQIJcq:-MwgAO1FBUbJso9jv7Kv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_iterator.c#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this variable?
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 83 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsQJI20maJoaBSXFxt:-MwgAQM621NBL-UQJXvF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/reserve_and_publish.c#L83)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls rename this var to "invalid_region" (similarly to other tests)
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 141 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsPq6m0Rbba0JZyA3E:-MwgARP69S01wcpdyXwf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/reserve_and_publish.c#L141)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's the difference between this test and the `null_data_test`? Shouldn't you also try to publish some real data (non-null) with size 0?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 15:55 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 6 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @Karolina002)

___
*[tests/api_c/append_entry.c, line 162 at r5](https://reviewable.io/reviews/pmem/pmemstream/67#-MujcG0q5deN8noP4iJ3:-MwgNfW44KI0XPqLo2JD:b-7sks9o) ([raw file](https://github.com/pmem/pmemstream/blob/418b80864d97180ced574bca70a0e5fd68618c81/tests/api_c/append_entry.c#L162)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about null-ed stream (first param of pmemstream_append, pmemstream_entry_data, and pmemstream_entry_length)

and, I guess, we may test also null/non-null region_runtime in _append
</blockquote></details>

bump?
___
*[tests/api_c/entry_iterator.c, line 61 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsBAHz7jbbVlFFBioX:-MwgR9bf4m7-cnZz4K3R:b-oa218x) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L61)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I'm aware of that. In valid_input_test the return value is also expected to be -1.
</blockquote></details>

similarly to region_iter_next we may at least check if the `invalid_region` value didn't change after this call
___
*[tests/api_c/region_iterator.c, line 57 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsMxF42i8PQJ27SZ8r:-MwgPVs26QCEODm8njA4:bgc8t96) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_iterator.c#L57)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I believe it'd be better to assign this `ALIGN_DOWN(UINT64_MAX, sizeof(span_bytes))` into some const (within this function) and use it twice
___
*[tests/api_c/reserve_and_publish.c, line 156 at r11](https://reviewable.io/reviews/pmem/pmemstream/67#-MwgQCRi-NyQZy5785yj:-MwgQCRi-NyQZy5785yk:b-rl7gm7) ([raw file](https://github.com/pmem/pmemstream/blob/bdf483029d729dbdff091defd2417efca1269814/tests/api_c/reserve_and_publish.c#L156)):*
> ```C
> 	int ret;
> 	void *data_address = NULL;
> 	struct entry_data data;
> ```

do you need this var?


<!-- Sent from Reviewable.io -->

2022-02-24 16:25 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @Karolina002)



<!-- Sent from Reviewable.io -->

2022-02-28 21:45 UTC, Karolina002 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 61 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsBAHz7jbbVlFFBioX:-Mx1HlIU1dMozCbLEquZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/entry_iterator.c#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

similarly to region_iter_next we may at least check if the `invalid_region` value didn't change after this call
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 57 at r8](https://reviewable.io/reviews/pmem/pmemstream/67#-MvsMxF42i8PQJ27SZ8r:-Mx1HpTyD-LlwNQ9WRIj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfa41e43126270226a39e0bc518b9cbcc6b8ac7e/tests/api_c/region_iterator.c#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it'd be better to assign this `ALIGN_DOWN(UINT64_MAX, sizeof(span_bytes))` into some const (within this function) and use it twice
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 156 at r11](https://reviewable.io/reviews/pmem/pmemstream/67#-MwgQCRi-NyQZy5785yj:-Mx1HuNB3euvPurYT0S8:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bdf483029d729dbdff091defd2417efca1269814/tests/api_c/reserve_and_publish.c#L156)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this var?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 18:31 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67#-:-MxAteCB6UfNlyCse8xw:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-03-02 18:31 UTC, lukaszstolarczuk approved these changes

2022-03-02 20:37 UTC, Karolina002 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67#-:-MxBLSfS9B_ebHXwxZ-s:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-03-03 15:59 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r9, 2 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67#-:-MxE-DDo5WxLlqAUlRlp:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-03-03 16:12 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r9, 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/67#-:-MxFYNFqD916fAohyGhQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)



<!-- Sent from Reviewable.io -->

2022-03-03 16:12 UTC, merged