span_create_entry fixes
pmem/pmemstream pull request #69
Opened 2022-01-14 09:56 UTC by lukaszstolarczuk

The most relevant fix, imho, is proper usage of `persist_size` in span_create_entry

2022-01-14 10:44 UTC, igchor reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/span.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNAotT5ydjUUz1M3Le:-MtNAotU2dOS5_3mQ5tV:b-enbtva) ([raw file](https://github.com/pmem/pmemstream/blob/a0e2934f1ddc1cb0efef32b0d76ee73e6c6f3eb8/src/span.c#L50)):*
> ```C
> 
> 	if (persist_size != 0) {
> 		stream->persist(span, SPAN_ENTRY_METADATA_SIZE);
> ```

Do we have pmemcheck enabled for reserve publish and append tests? I think this should have been found by tests/


<!-- Sent from Reviewable.io -->

2022-01-14 13:50 UTC, KFilipek requested changes
> Reviewed 4 of 4 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNi-LE6z8lhH-ZSiGK):*
@karczex send guidelines how to write correct commit messages.
Short desc is splitted with description part.



_Code quote:_
```
- 1a2a4d1: fix usage of persist_size in span_create_entry

  and enable pmemcheck in append test.
```
___
*[-- commits, line 7 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNiR841hG_zvfxZYN-):*
It should be combined with commit introduced in r2 and message rewritten.



_Code quote:_
```
New commits in r3 on 1/14/2022 at 11:58 AM:
- e389e9a: get rid of redundant 'data' argument in span_create_entry
```
___
*[-- commits, line 9 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNiatu-DTABE1CBvJ3):*
First of all, it's not a "code cleanup", also this enigmatic title exists many times around our repositories, no mention about descriptions added, updating license in different commit than editing.
Please, remove last commit and create separate PR for this change, just one cherry-pick and squash 1&2 commit with one description.



_Code quote:_
```
New commits in r4 on 1/14/2022 at 11:58 AM:
- 0a97a39: minor code cleanup
```
___
*[src/span.h, line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNk4hC9dRc8LXl-xz4:-MtNk4hC9dRc8LXl-xz5:bjl4jvm) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.h#L2)):*
> ```objc
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021-2022, Intel Corporation */
> ```

Date updated after editing



_Code quote:_
```objc
2021-2022
```
___
*[src/span.c, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkh_xAyBltaqjYpgh:-MtNkh_xAyBltaqjYpgi:b1ili2s) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L17)):*
> ```C
> }
> 
> /* Creates span with type = empty, at given offset.
> ```

Just simply: Creates empty span at given offset



_Code quote:_
```C
Creates span with type = empty, at given offset.
```
___
*[src/span.c, line 18 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkUGTEAc-Ck0rqqRS:-MtNkUGTEAc-Ck0rqqRT:b-vj82ts) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L18)):*
> ```C
> 
> /* Creates span with type = empty, at given offset.
>  * It sets empty's type and size, and zero out the whole span.
> ```

`zeroes`?



_Code quote:_
```C
zero
```
___
*[src/span.c, line 31 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkliZ17aKcN2YdHNG:-MtNkli_5Uuh7F2WXgdx:b-7es8qp) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L31)):*
> ```C
> }
> 
> /* Creates span with type = entry, at given offset.
> ```

Just simply: Creates entry span at given offset
___
*[src/span.c, line 57 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNknbO0xC3XUDsEHWs:-MtNknbO0xC3XUDsEHWt:be4opkl) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L57)):*
> ```C
> }
> 
> /* Creates span with type = region, at given offset.
> ```

Just simply: Creates region span at given offset


<!-- Sent from Reviewable.io -->

2022-01-18 13:20 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: all files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/span.c, line 36 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MthKjodDcBgt7KkHgqO:-MthKjodDcBgt7KkHgqP:ba17mts) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L36)):*
> ```C
>  * If any data is requested to be flushed, it's followed by a drain.
>  */
> void span_create_entry(struct pmemstream *stream, uint64_t offset, size_t data_size, size_t popcount, int flags)
> ```

Actually, after looking at this for some time I think I would prefer to split this function into two:

`span_create_entry_no_flush_data`
and
`span_create_entry`

and get rid of the flags parameter. It would make bugs like this with persist_size easier to spot. And we don't use the NO_FLUSH flag anywhere anyway.


<!-- Sent from Reviewable.io -->

2022-01-21 13:53 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNi-LE6z8lhH-ZSiGK):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@karczex send guidelines how to write correct commit messages.
Short desc is splitted with description part.
</blockquote></details>

it was split, not sure what do you mean...?
___
*[-- commits, line 7 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNiR841hG_zvfxZYN-):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It should be combined with commit introduced in r2 and message rewritten.
</blockquote></details>

that's totally different change, not sure why you'd like to combine these two...?
___
*[-- commits, line 9 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNiatu-DTABE1CBvJ3):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

First of all, it's not a "code cleanup", also this enigmatic title exists many times around our repositories, no mention about descriptions added, updating license in different commit than editing.
Please, remove last commit and create separate PR for this change, just one cherry-pick and squash 1&2 commit with one description.
</blockquote></details>

IMHO, all these changes are related to span_create_empty, so they can stay in one PR. Anyway, the commit msg changes, I agree, it wasn't too informative :wink: 
___
*[src/span.h, line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNk4hC9dRc8LXl-xz4:-Mtwcq_0CT-zxNzm486I:by7q8uw) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.h#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Date updated after editing
</blockquote></details>

I'm not sure what do you mean...?
___
*[src/span.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNAotT5ydjUUz1M3Le:-Mtwd-gf-hWxkTakkNvL:by5frq1) ([raw file](https://github.com/pmem/pmemstream/blob/a0e2934f1ddc1cb0efef32b0d76ee73e6c6f3eb8/src/span.c#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do we have pmemcheck enabled for reserve publish and append tests? I think this should have been found by tests/
</blockquote></details>

I finally split the reserve_publish, just for pmemcheck run, and now it spots the issue... so I guess multiple (RC?) tests in one file mess with the cleaning up something and impacts our integrity check.
___
*[src/span.c, line 17 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkh_xAyBltaqjYpgh:-MtwfzSA00aRSCnD50zy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Just simply: Creates empty span at given offset
</blockquote></details>

Done.
___
*[src/span.c, line 18 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkUGTEAc-Ck0rqqRS:-MtwfzhsD40lzS-09I0i:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`zeroes`?
</blockquote></details>

Done.
___
*[src/span.c, line 31 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNkliZ17aKcN2YdHNG:-MtwgJF33MYnf835UEHS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L31)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Just simply: Creates entry span at given offset
</blockquote></details>

Done.
___
*[src/span.c, line 36 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MthKjodDcBgt7KkHgqO:-MtwiiA-CZWWSLHVa56n:bkn8fwh) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually, after looking at this for some time I think I would prefer to split this function into two:

`span_create_entry_no_flush_data`
and
`span_create_entry`

and get rid of the flags parameter. It would make bugs like this with persist_size easier to spot. And we don't use the NO_FLUSH flag anywhere anyway.
</blockquote></details>

I like it, done. I was thinking how we could test the third case, but this approach is much better - just get rid of it :wink: 

Please let me know what you think of leaving flags in `pmemstream_internal_publish`
___
*[src/span.c, line 57 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MtNknbO0xC3XUDsEHWs:-MtwgJxx-c3GYTyIawYi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L57)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Just simply: Creates region span at given offset
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 15:43 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/span.c, line 36 at r4](https://reviewable.io/reviews/pmem/pmemstream/69#-MthKjodDcBgt7KkHgqO:-MtxIcqUEQLUOEhjk2mt:bba2h23) ([raw file](https://github.com/pmem/pmemstream/blob/0a97a3949ee85b26677416479bab4f08a51063f8/src/span.c#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if we actually need pmemstream_internal_publish now ;d

I think it could be more readable to just call appropriate span_entry_create function in append and publish
</blockquote></details>

agreed, done.


<!-- Sent from Reviewable.io -->

2022-01-21 15:48 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69#-:-MtxJqzA9KOTf4CTAlKc:bnfp4nl)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-24 14:27 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream_internal.h, line 19 at r9](https://reviewable.io/reviews/pmem/pmemstream/69#-MuBU1-d-eClTneNm01a:-MuBU1-d-eClTneNm01b:b-amco8h) ([raw file](https://github.com/pmem/pmemstream/blob/e4fede30f15380fdc990a5346825831d87148128/src/libpmemstream_internal.h#L19)):*
> ```objc
> 
> #define PMEMSTREAM_PUBLISH_PERSIST (0)
> #define PMEMSTREAM_PUBLISH_NOFLUSH_DATA (1)
> ```

Is it used anywhere now?


<!-- Sent from Reviewable.io -->

2022-01-24 14:40 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/69)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/libpmemstream_internal.h, line 19 at r9](https://reviewable.io/reviews/pmem/pmemstream/69#-MuBU1-d-eClTneNm01a:-MuBWwOF9GB18FqvHIFO:blhpwr3) ([raw file](https://github.com/pmem/pmemstream/blob/e4fede30f15380fdc990a5346825831d87148128/src/libpmemstream_internal.h#L19)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is it used anywhere now?
</blockquote></details>

naah, of course, I forgot to remove these. Done.


<!-- Sent from Reviewable.io -->

2022-01-24 18:21 UTC, merged