Basic append benchmark
pmem/pmemstream pull request #83
Opened 2022-01-19 09:58 UTC by karczex

2022-01-19 12:23 UTC, igchor requested changes
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @igchor and @karczex)

___
*[benchmarks/measure.hpp, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmEfm-8U2qxLh6MRvu:-MtmEfm-8U2qxLh6MRvv:b-s2xlhx) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L12)):*
> ```cpp
> {
> template <typename TimeUnit, typename F>
> static typename TimeUnit::rep measure(F &&func)
> ```

if function is a template then `static` is not necessary I belive, if it's not (e.g. generate_data) then it should be `static inline`
___
*[benchmarks/measure.hpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFEV-1h8A0Q9Rnm5J:-MtmFEV-1h8A0Q9Rnm5K:b-187wex) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L40)):*
> ```cpp
> 		return std::mt19937_64(seed);
> 	}();
> 	std::vector<uint8_t> ret;
> ```

if you generate size_t values, shouldn't this vector be of `size_t` also? Right now, you loose some of the data generated by generator.
___
*[benchmarks/measure.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmF5FzBhmS6eQ-Ewrs:-MtmF5FzBhmS6eQ-Ewrt:bgn1eck) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L43)):*
> ```cpp
> 	ret.reserve(count);
> 	for (size_t i = 0; i < count; ++i) {
> 		/* only even keys will be insterted */
> ```

why only even keys? 
___
*[benchmarks/measure.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFrRwDMhDK78EsDZf:-MtmFrRwDMhDK78EsDZg:b-pdjhpc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L52)):*
> ```cpp
> 
> template <typename T>
> T min(std::vector<T> values)
> ```

`const std::vector<T> &values`
___
*[benchmarks/measure.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFuO754WUxzSQ-CWP:-MtmFuO754WUxzSQ-CWQ:b-pdjhpc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L58)):*
> ```cpp
> 
> template <typename T>
> T max(std::vector<T> values)
> ```

`const std::vector<T> &values`
___
*[benchmarks/measure.hpp, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFw0B9PmV8kiY5hwB:-MtmFw0B9PmV8kiY5hwC:b-pdjhpc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L64)):*
> ```cpp
> 
> template <typename T>
> float mean(std::vector<T> values)
> ```

`const std::vector<T> &values`
___
*[benchmarks/measure.hpp, line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFz-269TXrHMaJlEn:-MtmFz-269TXrHMaJlEo:b-pdjhpc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L70)):*
> ```cpp
> 
> template <typename T>
> float std_dev(std::vector<T> values)
> ```

`const std::vector<T> &values`
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmGcT-203DgO8SjNux:-MtmGcT-203DgO8SjNuy:b8q9pzl) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
> ```cpp
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(config.iterations, [&] {
> 		for (auto it = data.begin(); it != data.end(); std::advance(it, config.element_size)) {
> 			pmemstream_append(stream.get(), region, NULL, &it, config.element_size, NULL);
> ```

Right now, we are clearing region in first append. I would suggest measuring (and printing) time of first append separately to get a better view of latency.
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmHF17CL4Qnl_3QSSG:-MtmHF17CL4Qnl_3QSSH:b-6utbz1) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
> ```cpp
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(config.iterations, [&] {
> 		for (auto it = data.begin(); it != data.end(); std::advance(it, config.element_size)) {
> 			pmemstream_append(stream.get(), region, NULL, &it, config.element_size, NULL);
> ```

It would be better to test performance with non-null `region_runtime` : before the loop, call pmemstream_get_region_runtime and pass it's return value to all append calls. It will have better performance (no lookup in internal data structure).

In general we could run benchmarks using both approaches to see what's the difference but that's for future probably.


<!-- Sent from Reviewable.io -->

2022-01-19 13:13 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 5 of 7 files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[benchmarks/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmOa0y7C6i5V9BuavL:-MtmOa0z9C7eztJwl7Nk:b-g50ha0) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L12)):*
> ```CMake
> 
> include_directories(.)
> include_directories(${PMEMSTREAM_INCLUDE_DIRS} .)
> ```

this entry is doubled
___
*[benchmarks/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmOuYa3XjSTMcYkX5C:-MtmOuYa3XjSTMcYkX5D:bnsx81f) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L12)):*
> ```CMake
> 
> include_directories(.)
> include_directories(${PMEMSTREAM_INCLUDE_DIRS} .)
> ```

since you're including `../tests/` I guess you should add `..` here as well
___
*[benchmarks/CMakeLists.txt, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS_RjDT-R9eUFXR_5:-MtmS_RjDT-R9eUFXR_6:b7u9kwe) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L37)):*
> ```CMake
> # ----------------------------------------------------------------- #
> 
> add_benchmark(pmemstream_append append/main.cpp)
> ```

perhaps drop `pmemstream_` from the name?
___
*[benchmarks/append/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS6snD2mKQTbuIjX1:-MtmS6snD2mKQTbuIjX2:b7u9kwe) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/CMakeLists.txt#L5)):*
> ```CMake
> 
> cmake_minimum_required(VERSION 3.3)
> project(benchmark-pmemstream_append)
> ```

perhaps drop `pmemstream_` from the name?
___
*[benchmarks/append/main.cpp, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmPs1917d9uFXDOZCD:-MtmPs1917d9uFXDOZCE:b-ep0bxm) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L11)):*
> ```cpp
> #include <vector>
> 
> #include "../tests/common/unittest.hpp"
> ```

you could drop the `../` part and mark it as XXX (if/when we add the `make_pmemstream` function to public, this can be removed, I guess)
___
*[benchmarks/append/main.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmPdk52zww0eAsUNgJ:-MtmPdk52zww0eAsUNgK:bjdbn2a) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L83)):*
> ```cpp
> 			"\n\t--element_count [count] Number of elements inserted into stream" +
> 			"\n\t--element_size [size] Number of bytes of each element inserted into stream" +
> 			"\n\t--iterations [iterations] Number of iterations. More iterations gives more robust statistical data, but takes more time";
> ```

this line is pretty long? wasn't it broken by `make cppformat`?
___
*[benchmarks/append/main.cpp, line 95 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmSEUU98KWIVBhiOJ6:-MtmSEUU98KWIVBhiOJ7:b-ncm4vm) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L95)):*
> ```cpp
> 	out << "region_size: " << cfg.region_size << ", ";
> 	out << "element_count: " << cfg.element_count << ", ";
> 	out << "ement_size: " << cfg.element_size << ", ";
> ```

misspell (ement_size)
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmHF17CL4Qnl_3QSSG:-MtmIzR74ouM9rWk6gXf:bgkv7xx) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It would be better to test performance with non-null `region_runtime` : before the loop, call pmemstream_get_region_runtime and pass it's return value to all append calls. It will have better performance (no lookup in internal data structure).

In general we could run benchmarks using both approaches to see what's the difference but that's for future probably.
</blockquote></details>

yeah, good idea, we could add this in the future using config setting
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmGcT-203DgO8SjNux:-MtmJ7YA2bPtamjYcnS4:b-unnuso) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right now, we are clearing region in first append. I would suggest measuring (and printing) time of first append separately to get a better view of latency.
</blockquote></details>

in general (perhaps mark it XXX for now) we could add the ramp-up part with no measurements (also could be configurable)
___
*[benchmarks/append/main.cpp, line 140 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmJHUG75oLJhc8M5Y-:-MtmJHUG75oLJhc8M5Y0:bthw60b) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L140)):*
> ```cpp
> 	std::cout << "\tmax: " << max << "ns" << std::endl;
> 	std::cout << "\tmin: " << min << "ns" << std::endl;
> 	std::cout << "\tstdandard deviation " << std_dev << "ns" << std::endl;
> ```

1. misspell (stdandard)
2. `deviation: "` (add missing colon)
___
*[utils/docker/prepare-for-build.sh, line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmJYm6BMOQ9xVxoaD1:-MtmJYm6BMOQ9xVxoaD2:b5r3k7a) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/utils/docker/prepare-for-build.sh#L14)):*
> ```Shell
> 
> INSTALL_DIR=/tmp/pmemstream
> STANDALONE_TEST_DIR=/tmp/build_example
> ```

then you can change `/build_example` into, e.g., `/build_dir` (?)


<!-- Sent from Reviewable.io -->

2022-01-19 13:16 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 5 of 7 files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmT_Nc3CI2-BRZt05k:-MtmT_Nc3CI2-BRZt05l:bm5e6ou) (no related file):*
I guess you could ignore `benchmarks` dir in `codecov.yml`

---


<!-- Sent from Reviewable.io -->

2022-01-19 15:48 UTC, KFilipek reviewed
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmPdk52zww0eAsUNgJ:-Mtn-B7D6qpm1VVbezR8:b-45a7mc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L83)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this line is pretty long? wasn't it broken by `make cppformat`?
</blockquote></details>

I suppose that cppformat don't break lines of text.



_Code quote:_
```cpp
			"\n\t--iterations [iterations] Number of iterations. More iterations gives more robust statistical data, but takes more time";
```
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmGcT-203DgO8SjNux:-Mtn03hz3lD7CjAPC3jH:bl611pj) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in general (perhaps mark it XXX for now) we could add the ramp-up part with no measurements (also could be configurable)
</blockquote></details>

Or skip some values with lowest/highest deviation.


<!-- Sent from Reviewable.io -->

2022-01-20 14:48 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 0 of 10 files reviewed, 19 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmT_Nc3CI2-BRZt05k:-Mtrx2KD1Us0085nzwIt:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you could ignore `benchmarks` dir in `codecov.yml`
</blockquote></details>

Done.

---
___
*[benchmarks/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmOa0y7C6i5V9BuavL:-MtrXcD1Cj2LZzsCvo8C:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this entry is doubled
</blockquote></details>

Done.
___
*[benchmarks/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmOuYa3XjSTMcYkX5C:-MtrQmMP1nOyuELekM2L:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you're including `../tests/` I guess you should add `..` here as well
</blockquote></details>

Done.
___
*[benchmarks/CMakeLists.txt, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS_RjDT-R9eUFXR_5:-MtqyIIrBKxS8OOyJjdw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/CMakeLists.txt#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps drop `pmemstream_` from the name?
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmEfm-8U2qxLh6MRvu:-MtqycwPDxGI6Y7gODJI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

if function is a template then `static` is not necessary I belive, if it's not (e.g. generate_data) then it should be `static inline`
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFEV-1h8A0Q9Rnm5J:-Mtrwr81-eujpBi5P4x-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

if you generate size_t values, shouldn't this vector be of `size_t` also? Right now, you loose some of the data generated by generator.
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmF5FzBhmS6eQ-Ewrs:-MtqzRIY2hQf3NSWvsVe:brx52n9) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L43)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why only even keys? 
</blockquote></details>

copy-paste error. Comment removed
___
*[benchmarks/measure.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFrRwDMhDK78EsDZf:-MtrQtIxBd45K29esxkn:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<T> &values`
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFuO754WUxzSQ-CWP:-MtqzhTK7wRNPxWz4-gP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<T> &values`
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFw0B9PmV8kiY5hwB:-Mtqzh9A0rQCEa98DJRR:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<T> &values`
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFz-269TXrHMaJlEn:-MtqzgonDhTIPJj5MT9D:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::vector<T> &values`
</blockquote></details>

Done.
___
*[benchmarks/append/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS6snD2mKQTbuIjX1:-MtqzrSm5EQhFA7qa3b_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/CMakeLists.txt#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps drop `pmemstream_` from the name?
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmPs1917d9uFXDOZCD:-MtrQdBu3NJ3we4dq8hv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could drop the `../` part and mark it as XXX (if/when we add the `make_pmemstream` function to public, this can be removed, I guess)
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmPdk52zww0eAsUNgJ:-Mtr-WWb8eJ9HAj9PPJZ:bgt3ufc) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L83)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I suppose that cppformat don't break lines of text.
</blockquote></details>

It wasn't broken by `make cppformat`. Done
___
*[benchmarks/append/main.cpp, line 95 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmSEUU98KWIVBhiOJ6:-Mtr-iCbDFeK9cWihZmB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L95)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell (ement_size)
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmHF17CL4Qnl_3QSSG:-MtrXL3uAAJc421IGrEW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, good idea, we could add this in the future using config setting
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 127 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmGcT-203DgO8SjNux:-MtrxDRo8Q73MgciU8L_:b-bbx05j) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/main.cpp#L127)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Or skip some values with lowest/highest deviation.
</blockquote></details>

marked as XXX
___
*[benchmarks [...]

2022-01-20 15:29 UTC, KFilipek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: all files reviewed, 20 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[-- commits, line 1 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts5qaGAhzmJ3LVu09J):*
Drop @igchor commits. They are also merged in master



_Code quote:_
```
New commits in r2 on 1/20/2022 at 3:35 PM by Igor Chorążewicz:

- 974807c: Extend reserve_publish test

  Add testcase for not calling pmemstream_publish.

- 44b13a3: Add missing #include<iostream> to thread_helpers.hpp

  It's needed by handle_exceptions.
```


<!-- Sent from Reviewable.io -->

2022-01-20 15:33 UTC, lukaszstolarczuk reviewed
> Reviewed 7 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 8 of 10 files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts1VQx3ReGmK1qbdmF):*
bad rebase? :wink: 
___
*[benchmarks/append/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS6snD2mKQTbuIjX1:-Mts2H5CC08gTAn0geVr:bw3i9vi) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/CMakeLists.txt#L5)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done in project name?
___
*[benchmarks/append/main.cpp, line 91 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts3l7G0ks06lv78Dkr:-Mts3l7G0ks06lv78Dks:b215ikw) ([raw file](https://github.com/pmem/pmemstream/blob/e4d478d39528222c82ddf7dac1473b3805f4f442/benchmarks/append/main.cpp#L91)):*
> ```cpp
> 			"\n\t--iterations [iterations] Number of iterations. " +
> 			"More iterations gives more robust statistical data, but takes more time" +
> 			"\n\t--null_region_runtime indicates if region runtime would be passed to append" +
> ```

if we set this param then "null" will be passed, so the description here should be rather like:
`--null_region_runtime indicates if **null** region runtime would be passed to append`


<!-- Sent from Reviewable.io -->

2022-01-20 15:36 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor and @karczex)



<!-- Sent from Reviewable.io -->

2022-01-20 15:37 UTC, KFilipek approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor and @karczex)



<!-- Sent from Reviewable.io -->

2022-01-20 15:41 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 8 of 10 files reviewed, 11 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 1 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts5qaGAhzmJ3LVu09J):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Drop @igchor commits. They are also merged in master
</blockquote></details>

Done.
___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts1VQx3ReGmK1qbdmF):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

bad rebase? :wink: 
</blockquote></details>

unfortunately 
___
*[benchmarks/append/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmS6snD2mKQTbuIjX1:-Mts7TJ-5wi51N8vHTf_:buf54yl) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/append/CMakeLists.txt#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done in project name?
</blockquote></details>

good catch. Done.
___
*[benchmarks/append/main.cpp, line 91 at r4](https://reviewable.io/reviews/pmem/pmemstream/83#-Mts3l7G0ks06lv78Dkr:-Mts8X38BC_rrOwZ2wSY:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e4d478d39528222c82ddf7dac1473b3805f4f442/benchmarks/append/main.cpp#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if we set this param then "null" will be passed, so the description here should be rather like:
`--null_region_runtime indicates if **null** region runtime would be passed to append`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 15:45 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83#-:-Mts9OL76k4o1-H0cGfA:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-20 16:04 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83#-:-MtsDwi51w1LQO2-Oe1i:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[benchmarks/measure.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFrRwDMhDK78EsDZf:-MtsD1KQ6y89kEBqLCfa:b-ymw6yi) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L52)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not const?
___
*[benchmarks/measure.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFuO754WUxzSQ-CWP:-MtsD3nF-lP-UqUJX5-8:b-ymw6yi) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L58)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not const?
___
*[benchmarks/measure.hpp, line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFw0B9PmV8kiY5hwB:-MtsD6oI67GJRs-QYtND:b-ymw6yi) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L64)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not const?
___
*[benchmarks/measure.hpp, line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFz-269TXrHMaJlEn:-MtsDj_I79ozVRNc-AzM:b-pl2qai) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L70)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>


why not const?
___
*[benchmarks/measure.hpp, line 35 at r6](https://reviewable.io/reviews/pmem/pmemstream/83#-MtsCaGK817nbcV2BAjT:-MtsCaGLAXDWPu92wG9-:b-ey5kh2) ([raw file](https://github.com/pmem/pmemstream/blob/c971cd5b0395a1f54035ec4285d384d6e98b23de/benchmarks/measure.hpp#L35)):*
> ```cpp
> }
> 
> auto generate_data(size_t count)
> ```

please add static inline to those non-template function (this one and other ones)
___
*[benchmarks/measure.hpp, line 47 at r6](https://reviewable.io/reviews/pmem/pmemstream/83#-MtsCmKZEL-HdJWJMhOZ:-MtsCmK_3kg_RXJd7xAP:b-ku6q8d) ([raw file](https://github.com/pmem/pmemstream/blob/c971cd5b0395a1f54035ec4285d384d6e98b23de/benchmarks/measure.hpp#L47)):*
> ```cpp
> 	for (size_t i = 0; i < count / gen_size; ++i) {
> 		auto entry = generator();
> 		uint8_t *entry_slices = reinterpret_cast<uint8_t *>(&entry);
> ```

why not just store `std::mt19937_64::result_type` in the vector?


<!-- Sent from Reviewable.io -->

2022-01-20 16:33 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-01-20 16:33 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/83)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[benchmarks/measure.hpp, line 70 at r1](https://reviewable.io/reviews/pmem/pmemstream/83#-MtmFz-269TXrHMaJlEn:-MtsI7Y2--tQpI8eu_be:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/588791e8643caaf908615bd8bd44fc86809bb359/benchmarks/measure.hpp#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not const?
</blockquote></details>

Done.
___
*[benchmarks/measure.hpp, line 47 at r6](https://reviewable.io/reviews/pmem/pmemstream/83#-MtsCmKZEL-HdJWJMhOZ:-MtsGCD86wWL59-Icfnc:b6kj3rb) ([raw file](https://github.com/pmem/pmemstream/blob/c971cd5b0395a1f54035ec4285d384d6e98b23de/benchmarks/measure.hpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not just store `std::mt19937_64::result_type` in the vector?
</blockquote></details>

basically `result_type` is 8 byte. I want to have  uint8_t granularity to be not constrained in element size in benchmark. 
Do you have better idea how to efficiently convert `std::vector<uint64_t>` of length `n` into std::vector<uint8_t> of length `8*n`?  


<!-- Sent from Reviewable.io -->

2022-01-20 17:04 UTC, merged