Optimize data generation in benchmark
pmem/pmemstream pull request #85
Opened 2022-01-21 09:44 UTC by karczex

This way is simpler and faster. Also usage of such generated data seems
to have less confusing syntax.

2022-01-21 09:58 UTC, igchor requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[benchmarks/measure.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw2S485ajVayiBF1qU:-Mtw2S485ajVayiBF1qV:bx5m6b) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/measure.hpp#L34)):*
> ```cpp
> }
> 
> /* Generate vector<uint64_t> which contains byte_count rounded up to 64 bytes */
> ```

64 bits
___
*[benchmarks/append/main.cpp, line 148 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw3M0YAjHBz5p-T4ap:-Mtw3M0YAjHBz5p-T4aq:bl46w8) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L148)):*
> ```cpp
> 	/* XXX: Add initialization phase whith separate measurement */
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(config.iterations, [&] {
> 		for (size_t i = 0; i < data.size(); i += config.element_size) {
> ```

If config.element_size is in bytes then data.size() * sizeof(uint64_t)?
___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw2xa6CKTU3TjKhZ6K:-Mtw2xa6CKTU3TjKhZ6L:b-ex5w77) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L149)):*
> ```cpp
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(config.iterations, [&] {
> 		for (size_t i = 0; i < data.size(); i += config.element_size) {
> 			pmemstream_append(stream.get(), region, region_runtime_ptr, data.data() + i,
> ```

since `data.data()` is `uint64_t*`, then for example, `dat.data() + 10` will return pointer to 8th uint64_t (80th byte).
If config.element_size is in bytes and I think what you need here is:
```
auto data = reinterpret_cast<char*>(data.data());
...
pmemstream_append(..., data, ...)
```


<!-- Sent from Reviewable.io -->

2022-01-21 10:02 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw2xa6CKTU3TjKhZ6K:-Mtw4NuG5Fl5TQqTdIbC:bpgzu11) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L149)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

since `data.data()` is `uint64_t*`, then for example, `dat.data() + 10` will return pointer to 8th uint64_t (80th byte).
If config.element_size is in bytes and I think what you need here is:
```
auto data = reinterpret_cast<char*>(data.data());
...
pmemstream_append(..., data, ...)
```
</blockquote></details>

correction: pointer to 10th uint64_t (80th bytes).


<!-- Sent from Reviewable.io -->

2022-01-21 10:14 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw75f-DtAPvD0SjKK2:-Mtw75f-DtAPvD0SjKK3:bw7vnpe) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L149)):*
> ```cpp
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(config.iterations, [&] {
> 		for (size_t i = 0; i < data.size(); i += config.element_size) {
> 			pmemstream_append(stream.get(), region, region_runtime_ptr, data.data() + i,
> ```

Could you maybe try to run this benchmark on CI with some basic configuration under USAN/UBSAN? - I think such kind of errors should be caught by some tests/sanitizers.


<!-- Sent from Reviewable.io -->

2022-01-21 11:02 UTC, KFilipek requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

___
*[benchmarks/measure.hpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-MtwFzOk06c9rOh8Loae:-MtwFzOm5sGGBKxEWreq:b-li22iw) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/measure.hpp#L37)):*
> ```cpp
> static inline std::vector<uint64_t> generate_data(size_t bytes_count)
> {
> 	size_t count = bytes_count / 8 + (bytes_count % 8 != 0);
> ```

For fun:
`((bytes_count >> 3) | (bytes_count & 1))`

Also you have bug (I think): `bytes_count % 8 != 0)`, maybe: `bytes_count % 2 != 0)` if you need to implement simple division by 8.



_Code quote:_
```cpp
bytes_count / 8 + (bytes_count % 8 != 0);
```


<!-- Sent from Reviewable.io -->

2022-01-21 12:38 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[benchmarks/measure.hpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-MtwFzOk06c9rOh8Loae:-Mtwbnks65z5j6IKl0kz:b2gjup2) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/measure.hpp#L37)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

For fun:
`((bytes_count >> 3) | (bytes_count & 1))`

Also you have bug (I think): `bytes_count % 8 != 0)`, maybe: `bytes_count % 2 != 0)` if you need to implement simple division by 8.
</blockquote></details>

Your code does not give the same result and the existing code is OK.

The most efficient way would probably be:
`(bytes_count + sizeof(uint64_t) - 1) / sizeof(uint64_t)`

But it doesn't really matter, the existing code is probably more readable.


<!-- Sent from Reviewable.io -->

2022-01-24 10:49 UTC, KFilipek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85#-:-MuAh7Yd9lYHfGGAJEtC:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-01-24 11:07 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85#-:-MuAlC9WAvaBwxlKmgfg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2022-01-24 11:12 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[benchmarks/measure.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw2S485ajVayiBF1qU:-MtwSrcY2jbE-QDG4hYT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/measure.hpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

64 bits
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 148 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw3M0YAjHBz5p-T4ap:-MtwTPYRAKDxFgcvvL27:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L148)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If config.element_size is in bytes then data.size() * sizeof(uint64_t)?
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw2xa6CKTU3TjKhZ6K:-MtwTzpY7gUbPP9eZhfj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L149)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

correction: pointer to 10th uint64_t (80th bytes).
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/85#-Mtw75f-DtAPvD0SjKK2:-MuAmI15AP2QfXXSprSq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fa6835df4f3680be648157a2d84974d6fca4b1a8/benchmarks/append/main.cpp#L149)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you maybe try to run this benchmark on CI with some basic configuration under USAN/UBSAN? - I think such kind of errors should be caught by some tests/sanitizers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-24 11:17 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/85#-:-MuAnXqd9mTr_KrB5hqM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-01-24 11:18 UTC, merged