Add pmemlog for benchmark compilation
pmem/pmemstream pull request #90
Opened 2022-01-25 17:58 UTC by KFilipek

TODO:

- [ ] extract `make_pmemstream()` change to another commit

2022-01-26 08:36 UTC, igchor requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 3 of 4 files reviewed, 17 unresolved discussions (waiting on @KFilipek)

___
*[benchmarks/CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTO8JB1X2O-NgIM-Y:-MuKTO8K4dr4a2jtsB_d:b-uva2vb) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/CMakeLists.txt#L13)):*
> ```CMake
> include_directories(${PMEMSTREAM_INCLUDE_DIRS} ${PMEMSTREAM_ROOT_DIR}/tests/common .)
> link_directories(${PMEMSTREAM_LIBRARY_DIRS})
> pkg_check_modules(LIBPMEMLOG REQUIRED libpmemlog)
> ```

find_package()?
___
*[benchmarks/append/main.cpp, line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTWoj1F-zAZbQxDOr:-MuKTWoj1F-zAZbQxDOs:b-7md22b) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L23)):*
> ```cpp
> class Config {
>  private:
> 	static const std::set<std::string> engine_names;
> ```

why not constexpr like long_options?
___
*[benchmarks/append/main.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTd9a0xPFQ43eCrmS:-MuKTd9a0xPFQ43eCrmT:b-bjs90h) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L57)):*
> ```cpp
> 				case 'e':
> 					engine = std::string(optarg);
> 					if (engine_names.find(engine) == engine_names.end()) {
> ```

can we move this to separate function?
___
*[benchmarks/append/main.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTpE14qBEUFKkX8k1:-MuKTpE14qBEUFKkX8k2:b13il3o) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L71)):*
> ```cpp
> 					break;
> 				case 'x':
> 					log_size = std::stoull(optarg);
> ```

maybe just 'size'?  so that it's applicable to both stream and log?
___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKU0ET8g3wXxP9w0Pi:-MuKU0ET8g3wXxP9w0Pj:b-k3y764) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L149)):*
> ```cpp
> }
> 
> class IWorkload {
> ```

please keep naming convention: snake_case
___
*[benchmarks/append/main.cpp, line 161 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKUCHtBxIAcPZHaY-h:-MuKUCHtBxIAcPZHaY-i:bnovs5n) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L161)):*
> ```cpp
> 		std::cout << "input generation time: " << input_generation_time << "s" << std::endl;
> 	}
> 	uint8_t *data_chunks;
> ```

Having one member depend on another is a bit dangerous - you might forget to change data_chunks after changing data. Maybe make `data` private and create a function to return `uint8_t*` instead?
___
*[benchmarks/append/main.cpp, line 165 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKUNAfEEsyD2nDqhyg:-MuKUNAfEEsyD2nDqhyh:bjxk5g4) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L165)):*
> ```cpp
> };
> 
> class PmemlogWorkload : public IWorkload {
> ```

snake_case
___
*[benchmarks/append/main.cpp, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW4_E-MA6BniGw1x7:-MuKW4_F8yvMD3lV3jmC:b-e2a48c) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L168)):*
> ```cpp
>  private:
> 	Config config;
> 	PMEMlogpool *plp;
> ```

why not unique_ptr?  now you have a leak.
___
*[benchmarks/append/main.cpp, line 177 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKV_qwAaGW7DUf7PBH:-MuKV_qwAaGW7DUf7PBI:bfn9l30) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L177)):*
> ```cpp
> 	virtual void perform() override
> 	{
> 		for (auto it = data.begin(); it != data.end(); std::advance(it, config.element_size)) {
> ```

data.begin() is uin64_t* which means that advance(it, 1) will move by 8 bytes. Instead of data.begin() you want to use data_chunks.

This should be implement the same way as pmemstrem_append below (which is correct).
___
*[benchmarks/append/main.cpp, line 178 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVobQ-C7YCqThTMFk:-MuKVobQ-C7YCqThTMFl:bwsyx3u) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L178)):*
> ```cpp
> 	{
> 		for (auto it = data.begin(); it != data.end(); std::advance(it, config.element_size)) {
> 			if (pmemlog_append(plp, &it, config.element_size) < 0) {
> ```

Same comment as in Pawel's PR: &it isuint64_t** (pointer to iterator), you want pointer to actual data here.
___
*[benchmarks/append/main.cpp, line 187 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVHOw9iid9lHUZYHZ:-MuKVHOw9iid9lHUZYH_:bd2tqw) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L187)):*
> ```cpp
> 	{
> 		auto path = config.path.c_str();
> 		plp = pmemlog_create(path, config.log_size, 0666);
> ```

make `mode` a const perhaps?
___
*[benchmarks/append/main.cpp, line 192 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVMf51AeaQidIz3q6:-MuKVMf51AeaQidIz3q7:b-whea23) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L192)):*
> ```cpp
> 		if (plp == NULL) {
> 			perror(path);
> 			// maybe throw?
> ```

yeah, that would be better
___
*[benchmarks/append/main.cpp, line 201 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW2lZ5QhI63nP8BXn:-MuKW2lZ5QhI63nP8BXo:bjxk5g4) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L201)):*
> ```cpp
> };
> 
> class PmemstreamWorkload : public IWorkload {
> ```

snake_case
___
*[benchmarks/append/main.cpp, line 213 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW98PEsZTBsTwCuQX:-MuKW98Q5W9xvg-2R3Ky:bppd3pe) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L213)):*
> ```cpp
> 	{
> 		stream = make_pmemstream(config.path.c_str(), config.block_size, config.log_size);
> 		pstream = stream.get();
> ```

Keeping pstream* directly is not the best idea - what if you reset the unique_ptr? I would just keep `stream` and call get() every time.
___
*[benchmarks/append/main.cpp, line 219 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKWNHE4w9Zic5RwziS:-MuKWNHE4w9Zic5RwziT:b-k6t3fm) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L219)):*
> ```cpp
> 	{
> 		if (pmemstream_region_allocate(stream.get(), config.region_size, &region)) {
> 			return -1;
> ```

throw?
___
*[benchmarks/append/main.cpp, line 223 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKWO44DwYM25m_chSp:-MuKWO44DwYM25m_chSq:b-k6t3fm) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L223)):*
> ```cpp
> 		if (!config.null_region_runtime &&
> 		    pmemstream_get_region_runtime(stream.get(), region, &region_runtime_ptr)) {
> 			return -2;
> ```

throw?
___
*[benchmarks/append/main.cpp, line 234 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKWgWlC5NU7RuCoGtY:-MuKWgWlC5NU7RuCoGtZ:bxuvuu9) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L234)):*
> ```cpp
> 	void perform() override
> 	{
> 		for (size_t i = 0; i < data.size() * sizeof(uint64_t); i += config.element_size) {
> ```

some return value checking here?
___
*[benchmarks/append/main.cpp, line 256 at r1](https://reviewable.i [...]

2022-01-26 13:17 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 3 of 4 files reviewed, 19 unresolved discussions (waiting on @KFilipek)

___
*[benchmarks/append/main.cpp, line 134 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuL0tw971m8FUKimuVT:-MuL0tw971m8FUKimuVU:b-izpz16) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L134)):*
> ```cpp
> std::string Config::app_name;
> constexpr option Config::long_options[];
> const std::set<std::string> Config::engine_names = std::initializer_list<std::string>{"pmemlog", "pmemstream"};
> ```

The way, the long_options is done is more readable. 
___
*[benchmarks/append/main.cpp, line 159 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuL4VU20wOECXFmeXds:-MuL4VU20wOECXFmeXdt:bh4u328) ([raw file](https://github.com/pmem/pmemstream/blob/98b670a4c70b05cd32f27276ec205b831952ec3e/benchmarks/append/main.cpp#L159)):*
> ```cpp
> 	auto std_dev = benchmark::std_dev(results) / config.element_count;
> 
> 	std::cout << "pmemstream_append measurement:" << std::endl;
> ```

std::cout << wokload->engine << measurement << std::endl;


<!-- Sent from Reviewable.io -->

2022-01-26 14:30 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 3 of 4 files reviewed, 25 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[benchmarks/CMakeLists.txt, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLiRi7EFA7j4tiAqnI:-MuLiRi7EFA7j4tiAqnJ:b-u5vkws) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/CMakeLists.txt#L20)):*
> ```CMake
> 	add_executable(benchmark-${name} ${srcs})
> 	add_dependencies(benchmarks benchmark-${name})
> 	target_link_libraries(benchmark-${name} ${LIBPMEM2_LIBRARIES} ${LIBPMEMLOG_LIBRARIES} pmemstream)
> ```

Do we always want to require log? Whenever benchmarks are turned on, this library is our dependency (this also affects our tests, because we've enabled append as a test in ctest).

We can either:
1. add log as our dependency (in the INSTALL.md),
2. add separate CMake option for turning on pmemlog benchmark,
3. or, I don't know, enable pmemlog only in some additional, extra CMake file for standalone compilation (with pmemlog).
___
*[benchmarks/append/CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLjPyH67c8askguuOe:-MuLjPyH67c8askguuOf:b11kdv2) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/CMakeLists.txt#L13)):*
> ```CMake
> include_directories(${LIBPMEMSTREAM_INCLUDE_DIRS} ../../tests/common . ..)
> link_directories(${LIBPMEMSTREAM_LIBRARY_DIRS})
> ```

what about include and link dirs (I guess it won't work if you have pmemlog installed in a custom path)
___
*[benchmarks/append/main.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLi579CPpCXf7ghmXd:-MuLi579CPpCXf7ghmXe:b-dop4dv) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L41)):*
> ```cpp
> 	std::string engine = "pmemstream";
> 	std::string path;
> 	size_t log_size = PMEMLOG_MIN_POOL;
> ```

I believe we should use whatever the value of these 2 consts is bigger (pmemlog_min_pool vs test_default_stream_size; these values can change in time :wink: )
___
*[benchmarks/append/main.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTpE14qBEUFKkX8k1:-MuLl6be5M2Q09fdnmtG:bcu08g9) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe just 'size'?  so that it's applicable to both stream and log?
</blockquote></details>

I guess log_size is cool, if you have only 'size' it won't be understandable at the first glance, what size is that, I guess.

we might, perhaps, call this `file_size`...?
___
*[benchmarks/append/main.cpp, line 111 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLhtpDDkjySpOD9-5J:-MuLhtpDDkjySpOD9-5K:b-elu8cx) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L111)):*
> ```cpp
> 		std::vector<std::string> new_line = {"", ""};
> 		std::vector<std::vector<std::string>> options = {
> 			{"Usage: " + app_name + " [OPTION]...\n" + "Pmemstream benchmark for append.", ""},
> ```

as Pawel's comment below - not necessarily "pmemstream"
___
*[benchmarks/append/main.cpp, line 113 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLmDIPDc2FxyO-yOiy:-MuLmDIPDc2FxyO-yOiz:b1hbl64) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L113)):*
> ```cpp
> 			{"Usage: " + app_name + " [OPTION]...\n" + "Pmemstream benchmark for append.", ""},
> 			new_line,
> 			{"--engine [name]", "engine name, possible values: pmemstream pmemlog"},
> ```

we have these 2 names hardcoded here... so maybe instead of evaluating `possible_engines` above, you'll do the same there...?
___
*[benchmarks/append/main.cpp, line 116 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLm1mJ32zhcQD6Qjon:-MuLm1mJ32zhcQD6Qjoo:bpn8m5v) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L116)):*
> ```cpp
> 			{"--path [path]", "path to file"},
> 			{"--log_size [size]", "log size"},
> 			{"--element_count [count]", "number of elements inserted into stream"},
> ```

`into stream` :wink: (here and below)
___
*[benchmarks/append/main.cpp, line 138 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLhwO-EwCVBKFL7TaQ:-MuLhwO-EwCVBKFL7TaR:b-elu8cx) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L138)):*
> ```cpp
> std::ostream &operator<<(std::ostream &out, Config const &cfg)
> {
> 	out << "Pmemstream Benchmark, path: " << cfg.path << ", ";
> ```

as Pawel's comment below - not necessarily "pmemstream"


<!-- Sent from Reviewable.io -->

2022-01-26 14:32 UTC, karczex commented
___
*[benchmarks/append/main.cpp, line 134 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuL0tw971m8FUKimuVT:-MuLmotV8UVKC0TOXTnU:byzt9ip) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L134)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

The way, the long_options is done is more readable. 
</blockquote></details>

you may something like: 
```
struct holder {
	static constexpr std::string_view my_list[] = {"foo", "bar"};
	bool contain(std::string_view word) {
		
		auto f = std::find(my_list, my_list + sizeof(my_list), word);
		if(f != my_list + sizeof(my_list)) {
			return true;
		}
		return false;
	}
};
```


<!-- Sent from Reviewable.io -->

2022-01-26 15:55 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 2 of 5 files reviewed, 23 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTWoj1F-zAZbQxDOr:-MuL4k-y9qXRysi0zliT:b3lvfbh) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not constexpr like long_options?
</blockquote></details>

"std::set is not literal because has a non-trivial destructor"
also don't have any constexpr constructor:
https://en.cppreference.com/w/cpp/container/set/set
___
*[benchmarks/append/main.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLi579CPpCXf7ghmXd:-MuLyO6q31f_t1dBbc6X:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe we should use whatever the value of these 2 consts is bigger (pmemlog_min_pool vs test_default_stream_size; these values can change in time :wink: )
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKTpE14qBEUFKkX8k1:-MuLCI9w62xGrA-eowAg:b8g21jk) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L71)):*
> maybe just 'size'?  so that it's applicable to both stream and log?
I changed from `stream_size` to be more generic, pmemstream and pmemlog are logging structure, but no problem.
@lukaszstolarczuk `file_size` has similar problem, it refers to "file", but pool can be also device. 
Changed to generic `size`.
___
*[benchmarks/append/main.cpp, line 111 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLhtpDDkjySpOD9-5J:-MuLz9AVDnZCc3HxWJOy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as Pawel's comment below - not necessarily "pmemstream"
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 116 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLm1mJ32zhcQD6Qjon:-MuM1lizA8M5MELnKtWe:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L116)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`into stream` :wink: (here and below)
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 134 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuL0tw971m8FUKimuVT:-MuLZDV27BVPpZQ0Bfrr:b5hjyhg) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L134)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

you may something like: 
```
struct holder {
	static constexpr std::string_view my_list[] = {"foo", "bar"};
	bool contain(std::string_view word) {
		
		auto f = std::find(my_list, my_list + sizeof(my_list), word);
		if(f != my_list + sizeof(my_list)) {
			return true;
		}
		return false;
	}
};
```
</blockquote></details>

std::set have not constexpr constructor :D
Changed to std::array. Worth to notice that std::find is constexpr since C++20, so... it will be executed in runtime I think
___
*[benchmarks/append/main.cpp, line 138 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLhwO-EwCVBKFL7TaQ:-MuLtu2w6CY2QfY8VFaO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as Pawel's comment below - not necessarily "pmemstream"
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 149 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKU0ET8g3wXxP9w0Pi:-MuM2S6Z3SBGTzEygGI5:bb3cq4u) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L149)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please keep naming convention: snake_case
</blockquote></details>

Done. Applied also to function `prepareData()`
___
*[benchmarks/append/main.cpp, line 165 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKUNAfEEsyD2nDqhyg:-MuM2aYy6e5m8iWTZGUH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L165)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

snake_case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 16:01 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 2 of 5 files reviewed, 22 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 51 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM5o--Ce2ZhFvh_fXK:-MuM5o--Ce2ZhFvh_fXL:bt4fasa) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L51)):*
> ```cpp
> 	{
> 		engine = engine_name;
> 		if (std::find(engine_names.begin(), engine_names.end(), engine) == engine_names.end()) {
> ```

shouldn't this be before the assignment?
___
*[benchmarks/append/main.cpp, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM5uf6B_RkDJq1e5pj:-MuM5uf79dwISMwmLpg0:b-o340e7) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L67)):*
> ```cpp
> 	std::string engine = "pmemstream";
> 	std::string path;
> 	size_t size = (PMEMLOG_MIN_POOL > TEST_DEFAULT_STREAM_SIZE ? PMEMLOG_MIN_POOL : TEST_DEFAULT_STREAM_SIZE);
> ```

nit: probably easier to use std::max
___
*[benchmarks/append/main.cpp, line 192 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM6Wmn4y9UiFoTHb2t:-MuM6Wmn4y9UiFoTHb2u:b-2flkoy) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L192)):*
> ```cpp
> 		for (auto it = data.begin(); it != data.end(); std::advance(it, cfg.element_size)) {
> 			if (pmemlog_append(plp, &it, cfg.element_size) < 0) {
> 				throw std::runtime_error("Error while appending new entry!");
> ```

you could use some error code here (I guess pmemlog exposes some)


<!-- Sent from Reviewable.io -->

2022-01-26 17:28 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 2 of 5 files reviewed, 16 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 159 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuL4VU20wOECXFmeXds:-MuMIc3zDHcI5QyWqcaG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/98b670a4c70b05cd32f27276ec205b831952ec3e/benchmarks/append/main.cpp#L159)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

std::cout << wokload->engine << measurement << std::endl;
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW4_E-MA6BniGw1x7:-MuMNvKR304T_nXI1TDN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L168)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not unique_ptr?  now you have a leak.
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 177 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKV_qwAaGW7DUf7PBH:-MuM5ugv5D1WQzSyXTij:bl5jud4) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

data.begin() is uin64_t* which means that advance(it, 1) will move by 8 bytes. Instead of data.begin() you want to use data_chunks.

This should be implement the same way as pmemstrem_append below (which is correct).
</blockquote></details>

Done. Copied from pmemstream
___
*[benchmarks/append/main.cpp, line 178 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVobQ-C7YCqThTMFk:-MuM5v1C9fc091BCP2r3:bl5jud4) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L178)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Same comment as in Pawel's PR: &it isuint64_t** (pointer to iterator), you want pointer to actual data here.
</blockquote></details>

Done. Copied from pmemstream
___
*[benchmarks/append/main.cpp, line 187 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVHOw9iid9lHUZYHZ:-MuMMGjZB7GkeSsteRxG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L187)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

make `mode` a const perhaps?
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 192 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKVMf51AeaQidIz3q6:-MuMMHzg7ifqqi9PnZwu:b-gb7eiv) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L192)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

yeah, that would be better
</blockquote></details>

Roger that.
___
*[benchmarks/append/main.cpp, line 201 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW2lZ5QhI63nP8BXn:-MuM77OR8LKJz_xSF5aI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L201)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

snake_case
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 213 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW98PEsZTBsTwCuQX:-MuM78eq2C_b8xODy-xx:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L213)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Keeping pstream* directly is not the best idea - what if you reset the unique_ptr? I would just keep `stream` and call get() every time.
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 234 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKWgWlC5NU7RuCoGtY:-MuM7LFI3AikQEq5sGjB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L234)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

some return value checking here?
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 51 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM5o--Ce2ZhFvh_fXK:-MuMQE2z2YsA3kvDqp-R:b-81la7d) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L51)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't this be before the assignment?
</blockquote></details>

Right
___
*[benchmarks/append/main.cpp, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM5uf6B_RkDJq1e5pj:-MuMPsYN3A_ChpKcMeL4:bmxevfc) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: probably easier to use std::max
</blockquote></details>

You are my C++ superhero.
___
*[benchmarks/append/main.cpp, line 192 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM6Wmn4y9UiFoTHb2t:-MuMNrLE1xUegiYuq0uL:b-yciw3m) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L192)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you could use some error code here (I guess pmemlog exposes some)
</blockquote></details>

Sets errno, I changed it


<!-- Sent from Reviewable.io -->

2022-01-27 07:58 UTC, karczex reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 3 of 5 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-01-27 08:15 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[CMakeLists.txt, line 31 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuP_vzI2sWcxQY5P1X1:-MuP_vzJAEXslmvfhMJ6:b-3cgqbc) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/CMakeLists.txt#L31)):*
> ```CMake
> set(CMAKE_C_STANDARD ${C_STANDARD})
> 
> set(CXX_STANDARD 14 CACHE STRING "C++ language standard")
> ```

why do we need this?

if only for benchmarks, then perhaps put it in the benchmark's CMakeLists
___
*[benchmarks/append/main.cpp, line 137 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuPXjlt7FT13NsK0q-O:-MuPXjlu9SC9jwFQgdFN:b-4m7th5) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/benchmarks/append/main.cpp#L137)):*
> ```cpp
> 			{"pmemstream related options:", ""},
> 			{"--block_size [size]", "block size"},
> 			{"--region_size [size]", "region size"},
> ```

some of these options apply only for pmemstream engine :wink: perhaps mark this somehow...? or we can add readme/howto later on, with proper explanation/examples (you can mark this as XXX for now)


<!-- Sent from Reviewable.io -->

2022-01-27 08:28 UTC, karczex commented
___
*[CMakeLists.txt, line 31 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuP_vzI2sWcxQY5P1X1:-MuPcf2N9_jw7nxnXDVf:bapllr4) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/CMakeLists.txt#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need this?

if only for benchmarks, then perhaps put it in the benchmark's CMakeLists
</blockquote></details>

Anyway, it should be C++17


<!-- Sent from Reviewable.io -->

2022-01-27 09:07 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90#-:-MuPm1lF2s8cUM3KSOr0:bnfp4nl)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 31 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuP_vzI2sWcxQY5P1X1:-MuPmFZlEM3IuUoPxUXm:b-v64lca) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/CMakeLists.txt#L31)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Anyway, it should be C++17
</blockquote></details>

We have this for tests already (with C++17), just move it to the main CMakeLists
___
*[benchmarks/append/main.cpp, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuKW4_E-MA6BniGw1x7:-MuPm8Se0cmCbwXfgmiO:b8tlnbs) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/append/main.cpp#L168)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done I think?
___
*[benchmarks/append/main.cpp, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/90#-MuM5uf6B_RkDJq1e5pj:-MuPlWVR15kZnymoY8p3:b-ve3yvb) ([raw file](https://github.com/pmem/pmemstream/blob/57bb310a5f444766a06163f25c98e14243bfadf3/benchmarks/append/main.cpp#L67)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You are my C++ superhero.
</blockquote></details>

:smile: 


<!-- Sent from Reviewable.io -->

2022-01-27 11:25 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/append/main.cpp, line 291 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuQH6Js43AXhTh3vD5_:-MuQH6Js43AXhTh3vD5a:b-6vurx6) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/benchmarks/append/main.cpp#L291)):*
> ```cpp
> 	/* XXX: Add initialization phase whith separate measurement */
> 	auto results = benchmark::measure<std::chrono::nanoseconds>(
> 		cfg.iterations, [interface = workload.get()] { interface->perform(); });
> ```

interface? not workload?


<!-- Sent from Reviewable.io -->

2022-01-28 13:01 UTC, karczex approved these changes
As it's now partially my change, obviously <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  
:)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90#-:-MuVlZa02p-WkqFF-lvT:b-196dkr)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-28 13:16 UTC, karczex commented
___
*[benchmarks/CMakeLists.txt, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/90#-MuLiRi7EFA7j4tiAqnI:-MuVovXiEAC2_wQOzfKU:byidxvc) ([raw file](https://github.com/pmem/pmemstream/blob/07d140a7f8560a0c80123870bfe5e6eddb3b184f/benchmarks/CMakeLists.txt#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Do we always want to require log? Whenever benchmarks are turned on, this library is our dependency (this also affects our tests, because we've enabled append as a test in ctest).

We can either:
1. add log as our dependency (in the INSTALL.md),
2. add separate CMake option for turning on pmemlog benchmark,
3. or, I don't know, enable pmemlog only in some additional, extra CMake file for standalone compilation (with pmemlog).
</blockquote></details>

It's dependency in tests only if benchmarks are enabled (disabled by default)


<!-- Sent from Reviewable.io -->

2022-01-28 13:36 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 291 at r3](https://reviewable.io/reviews/pmem/pmemstream/90#-MuQH6Js43AXhTh3vD5_:-MuVpHk251x29nhlOpVL:b38tzd6) ([raw file](https://github.com/pmem/pmemstream/blob/c89ead78c71b962da061b329da8752902d6fc4af/benchmarks/append/main.cpp#L291)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

interface? not workload?
</blockquote></details>

I would do some refactor here in another PR


<!-- Sent from Reviewable.io -->

2022-01-28 13:44 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r1, 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek)

___
*[-- commits, line 10 at r6](https://reviewable.io/reviews/pmem/pmemstream/90#-MuVu8KXBvXntliOkpRK):*
default default :stuck_out_tongue_winking_eye: 
___
*[-- commits, line 13 at r6](https://reviewable.io/reviews/pmem/pmemstream/90#-MuVuFN2CHCZvvdp7LJD):*
that's rather the part of the first commit, this is where we require the log library
___
*[INSTALL.md, line 31 at r6](https://reviewable.io/reviews/pmem/pmemstream/90#-MuVu_rV-v1p1riko294:-MuVu_rV-v1p1riko295:bfklwvz) ([raw file](https://github.com/pmem/pmemstream/blob/2148d7a13541cccee3b62f1e09441b7c1372420c/INSTALL.md#L31)):*
> ```Markdown
> 	* [**perl**](https://www.perl.org/) - for whitespace checker script
> 	* [**clang format**](https://clang.llvm.org/docs/ClangFormat.html) - to format and check coding style, version **9.0** is required
> * Used for **benchmarks**
> ```

benchmarks:
___
*[benchmarks/append/main.cpp, line 69 at r6](https://reviewable.io/reviews/pmem/pmemstream/90#-MuVuon29F-dL8uVWPMW:-MuVuon29F-dL8uVWPMX:b-ubtmjk) ([raw file](https://github.com/pmem/pmemstream/blob/2148d7a13541cccee3b62f1e09441b7c1372420c/benchmarks/append/main.cpp#L69)):*
> ```cpp
> 	std::string engine = "pmemstream";
> 	std::string path;
> 	size_t size = std::max(PMEMLOG_MIN_POOL, TEST_DEFAULT_STREAM_SIZE * 10);
> ```

hmm this `size` is used as a "minimal required size" in `set_size` function. Now it may be misleading in some usages (user wants to pass only a few small elements and it will be required to have "huge" pmemstream).


<!-- Sent from Reviewable.io -->

2022-01-28 13:51 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[-- commits, line 13 at r6](https://reviewable.io/reviews/pmem/pmemstream/90#-MuVuFN2CHCZvvdp7LJD):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's rather the part of the first commit, this is where we require the log library
</blockquote></details>

I would rather not :)


<!-- Sent from Reviewable.io -->

2022-01-28 14:03 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/90#-:-MuVzlMz9_aB80f8tRJ7:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2022-01-28 14:03 UTC, merged